### ISSUE TITLE
Retry step 00_deploy-done

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1003]
https://sentry.io/canonical-pj/conjure-up/issues/297191165/

```
Exception: Failure in step 00_deploy-done
  File "conjureup/controllers/deploystatus/gui.py", line 13, in _wait_for_applications
    await common.wait_for_applications(app.ui.set_footer)
  File "conjureup/controllers/deploystatus/common.py", line 22, in wait_for_applications
    msg_cb)
  File "conjureup/utils.py", line 172, in run_step
    raise Exception("Failure in step {}".format(step.filename))

Exception: Failure in step 00_deploy-done
```

**Comment by battlemidget** [comment]
@johnsca still seeing a bunch of these from the results of juju-wait, i think at the very least we need to capture `juju status --format yaml` and maybe prioritize having libjuju do the things we rely on `juju wait` to do. thoughts?

**Comment by johnsca** [comment]
We either need to get https://bugs.launchpad.net/juju-wait/+bug/1680963 resolved to make `juju-wait` allow for Juju to retry failed hooks once or twice, or we can replace `juju-wait` with (or pre-wait with) something using libjuju that we have more control over.
