### ISSUE TITLE
Move steps view before deploy status

### ISSUE THREAD

**Issue by tvansteenburgh** [conjure-up/conjure-up#1009]
Change order.
Store step results.

**Comment by johnsca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move Steps view before Deploy](https://trello.com/c/n8vfimEl/6-move-steps-view-before-deploy)

**Comment by battlemidget** [comment]
https://github.com/conjure-up/conjure-up/commit/8088792caedc8905d470e9aa691df435b890943e
