### ISSUE TITLE
error occurs when run the installer non-interactively (headless mode)  in MacOS

### ISSUE THREAD

**Issue by xsren** [conjure-up/conjure-up#1018]
Hi! I run conjure-up on MacOS 10.12.5.

install it by Homebrew
```
brew install conjure-up
```
run the installer non-interactively (headless mode)
```
conjure-up canonical-kubernetes localhost
```
but error happens 
![image](https://user-images.githubusercontent.com/4971925/27673749-f3e656b4-5cd4-11e7-885e-7777d953dc14.png)

this is the cache.
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1111036/conjure-up.tar.gz)

Any idea?

**Comment by battlemidget** [comment]
Localhost is not supported on macOS at this time (macOS doesn't have LXD). We are still investigating other alternatives to make this work. We've also got another bug opened on this same issue, going to close this one as a dupe. #1016
