### ISSUE TITLE
update bundled lxd to handle things like reboots

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1020]
stgraber has made several improvements to the snap version of lxd which allows handling of containers better during crashes, snap refreshes, and snap removals. Need to port this work over to our bundle lxd scripts.

Also test against lxd 2.15

https://github.com/lxc/lxd-pkg-ubuntu/tree/snappy-16

@johnsca @tvansteenburgh I'd like to include this in the next planning sprint

**Comment by pigopl** [comment]
Great :-)

**Comment by battlemidget** [comment]
Addressed in `edge` channel
