### ISSUE TITLE
How to get conjure-up with packaged LXD to use lxdbr0

### ISSUE THREAD

**Issue by caleblloyd** [conjure-up/conjure-up#1023]
## Report

Now that conjure-up packages it's own LXD, it also defaults `eth0` on everything to it's own LXD network, `conjureup1`

I want to put conjure-up back on `lxdbr0` so that it can talk to the rest of my normal LXD containers that are on `lxdbr0`

Could you please provide guidance on how to accomplish this, I cannot find anything about it in the documentation

## Please provide the output of the following commands

```
caleb@rog:~$ which juju
/snap/bin/juju
caleb@rog:~$ which conjure-up
/snap/bin/conjure-up
caleb@rog:~$ which conjure-up.lxd
/snap/bin/conjure-up.lxd
caleb@rog:~$ juju version
2.2.1-zesty-amd64
caleb@rog:~$ conjure-up --version
conjure-up 2.2.2
caleb@rog:~$ conjure-up.lxd --version
2.14
caleb@rog:~$ conjure-up.lxc config show
config:
  core.https_address: '[::]:49847'
caleb@rog:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

**Comment by battlemidget** [comment]
Hey Caleb,

You should be able to do something like:

```
$ conjure-up.lxc network detach-profile conjureup1 default
$ conjure-up.lxc network attach-profile lxdbr0 default eth0
```

So any newly created containers would inherit the lxdbr0 bridge. There is possibly a bug floating around somewhere with this so please feel free to let us know through this bug so we can get it sorted.

**Comment by caleblloyd** [comment]
I tried that, but every time I run `conjure-up`, it changes `eth0` back to `conjureup1`

Should `conjure-up` add a config item for `eth0` network so that when it checks the default profile and repairs it, it adds the proper bridge?

**Comment by battlemidget** [comment]
Thanks, will get this addressed in next dev cycle (of course PR's always welcomed, the heart of the lxdsetup code is in `conjureup/controllers/lxdsetup/common.py`)

**Comment by caleblloyd** [comment]
Thanks for the pointer to the code.  As a workaround for now, I've patched my system's snap and changed this line to `lxdbr0`:

https://github.com/conjure-up/conjure-up/blob/6aef984676847987f246edbe7e42647dac30af96/conjureup/controllers/lxdsetup/common.py#L164

Looking forward to this fix so it's not so hacky - patching a snap is a bit of a pain.  I used [this SO post](https://unix.stackexchange.com/a/80312/153971) for some help with commands to unsquash / squash the snap

**Comment by battlemidget** [comment]
@caleblloyd glad you have a workaround for now, i've got it on the next milestone and will make sure it's approved to be fixed.

**Comment by battlemidget** [comment]
Addressed in our `edge` snap, you will now be able to select the network bridge to use with your deployment
