### ISSUE TITLE
Exception: Failure in step 00_deploy-done

### ISSUE THREAD

**Issue by jamesbeedy** [conjure-up/conjure-up#1025]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which conjure-up.juju
/snap/bin/conjure-up.juju

which conjure-up
/snap/bin/conjure-up

which conjure-up.lxd
/snap/bin/conjure-up.lxd

conjure-up.juju version
2.2.1-xenial-amd64

conjure-up --version
conjure-up 2.2.2

conjure-up.lxd --version
2.14

conjure-up.lxc config show
config:
  core.https_address: '[::]:49161'

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1115903/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.
```
$ sosreport

sosreport (version 3.4)

no valid plugins were enabled
```

## What Spell was Selected?
openstack-lxd
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?

## Commands ran
```$ conjure-up```
Please outline what commands were run to install and execute conjure-up:

## Additional Information
http://paste.ubuntu.com/24990085/

**Comment by jamesbeedy** [comment]
Possibly this is because I only added 1 unit each of ceph-osd and ceph ....

blowing it all away (including `snap remove conjure-up; snap install conjure-up --classic`), and re-running `conjure-up` this time using the default 3 units of ceph-osd and ceph gives a different traceback on 00_deploy-done http://paste.ubuntu.com/24990450/

**Comment by battlemidget** [comment]
hmm, @johnsca any idea? looks like a sentry issue

**Comment by battlemidget** [comment]
This has been addressed in our `edge` snap
