### ISSUE TITLE
unable to parse snap versions like 2.25~14.04

### ISSUE THREAD

**Issue by debayan-ch** [conjure-up/conjure-up#1027]
## Report

The following message is seen on the conjure-up UI while deploying kubernetes-core.
**You must be on a snapd version of 2.25 or newer. Please run `sudo apt update && sudo apt dist-upgrade**
However, I am already running a newer version of snapd - so this is an erroneous message.
**Version: 2.25~14.04**

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
No
- [ ] Is conjure-up running inside a virtual machine?
Yes
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
Yes - it is reproducible

## Please provide the output of the following commands

```
which juju
**$ which juju
/snap/bin/juju**
which conjure-up
**$ which conjure-up
/snap/bin/conjure-up**
which conjure-up.lxd
**$ which conjure-up.lxd
/snap/bin/conjure-up.lxd**
juju version
**$ juju version
2.3-alpha1-trusty-amd64**
conjure-up --version
**$ conjure-up --version
conjure-up 2.3-alpha1**
conjure-up.lxd --version
**$ conjure-up.lxd --version
2.14**
conjure-up.lxc config show
**$ conjure-up.lxc config show
LXD socket not found; is LXD installed and running?**
cat /etc/lsb-release
**$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"**

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1138965/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes-core

## What provider (aws, maas, localhost, etc)?
**Localhost**

### MAAS Users
Which version of MAAS?

## Commands ran
**sudo apt-get install snapd
sudo groupadd lxd && sudo usermod -a -G lxd $USER
sudo reboot
sudo snap install conjure-up --classic

sudo apt update && sudo apt dist-upgrade
conjure-up kubernetes-core

sudo snap refresh conjure-up --edge
conjure-up kubernetes-core**

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
I realize they documentation hasn't been regenerated since I updated it last but only Xenial is supported at this time. @evilnick can we get the conjure-up docs regenerated?
