### ISSUE TITLE
Unrecoverable error when application has an empty readme

### ISSUE THREAD

**Issue by wwwtyro** [conjure-up/conjure-up#1034]
See http://paste.ubuntu.com/25082615/ and https://github.com/conjure-up/conjure-up/blob/master/conjureup/ui/views/applicationlist.py#L182

conjure-up displays an error and bails at this point.

**Comment by battlemidget** [comment]
Is this on --edge as well?

**Comment by wwwtyro** [comment]
This is the upstream spell with a modified bundle (one app had an empty readme)

**Comment by battlemidget** [comment]
there were some fixes in the edge snap though for invalid markup

**Comment by wwwtyro** [comment]
Ah okay, if this is already fixed, I'll close it.
