### ISSUE TITLE
application list view: no way to tell if charms are out of date

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#104]
If a bundle/spell has pinned charm revnos and they become out of date, we won't know.
It might be worth showing this to the user, if only as a one-time warning somewhere that "this spell has pinned versions of charms that are older than the currently available versions on the charm store, please contact your spell author if you think this is a bug" or something

**Comment by mikemccracken** [comment]
I noticed this while testing readmes - my branch of bundle-observable-kubernetes has an etcd charm source of cs:~containers/trusty/etcd-2, which has a README with a TODO in the first paragraph

**Comment by battlemidget** [comment]
:+1:

**Comment by mikemccracken** [comment]
This doesn't help the user fix the problem. We should focus on making sure the spells stay up to date.
