### ISSUE TITLE
VSphere: Query API to gather network switches, ext network, datasources

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1047]
Enhancement to give conjure-up ability to query vsphere api to get a list of virtual switches, external networks, datasources and present those to the user during credentials view. This will also need to be set via juju bootstrap-config so that the options persist to the bootstrap.

**Comment by battlemidget** [comment]
@tvansteenburgh @johnsca

**Comment by tvansteenburgh** [comment]
1. Include client to query vsphere
2. Add screen that lists network switch, external network, and data sources
3. Take selections from #2 and pass through to bootstrap
