### ISSUE TITLE
Failed to create LXD conjureup1 network bridge: error: Failed to run: dnsmasq - Address already in use

### ISSUE THREAD

**Issue by afterbangx** [conjure-up/conjure-up#1064]
## Report

This issue was reported once before but has since been closed. I'm guessing because the user didn't respond or provide the info needed. 

I just installed Ubuntu 16.04.2 this morning. I wanted to play around with OpenStack so I watched the video and followed the directions on [this page](https://www.ubuntu.com/download/cloud/conjure-up?_ga=2.211042325.1488519469.1501375723-608273075.1501375723). The install is failing every time with this error. I'm not sure where to go from here. Is there a workaround? I see there was a PR (#952) that was recently merged and released in `2.2.1`. It appears to be a related problem. Let me know if you need any additional info.

![image](https://user-images.githubusercontent.com/12399066/28750385-a88258ca-74ae-11e7-96ec-eca315fcde5e.png)

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems.
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? Yes.

## Please provide the output of the following commands

```
which juju 
/usr/bin/juju

which conjure-up 
/snap/bin/conjure-up

which conjure-up.lxd 
/snap/bin/conjure-up.lxd

juju version 
2.0.2-xenial-amd64

conjure-up --version 
conjure-up 2.2.2 and 2.3-alpha1

conjure-up.lxd --version 
2.14

conjure-up.lxc config show 
config:
  core.https_address: '[::]:60359'

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1185423/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

[tmp_lfhmqp2.txt](https://github.com/conjure-up/conjure-up/files/1185425/tmp_lfhmqp2.txt)

## What Spell was Selected?
OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
`sudo snap install conjure-up --classic`
`conjure-up`

`sudo snap refresh conjure-up --edge`
`conjure-up`

**Comment by battlemidget** [comment]
if you do a `ps -ef|grep dnsmasq` and if you see anything referencing `conjureup1` then try killing that process. We are making some changes in the coming weeks to help with this issue.

**Comment by afterbangx** [comment]
Tried this and didn't see anything referencing `conjureup1`. I did try installing 16.04 in a VM yesterday and got a little farther. Ultimately it failed but it was a completely different issue than this one. I'll stay tuned for the updates and try again in a few weeks, Thanks.

**Comment by battlemidget** [comment]
Addressed in `edge` channel
