### ISSUE TITLE
Insufficient peer units to bootstrap cluster(require 3). How to solve this error? Is it Hardware related or what?

### ISSUE THREAD

**Issue by adityatajne94** [conjure-up/conjure-up#1067]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
which conjure-up
which conjure-up.lxd
juju version
conjure-up --version
conjure-up.lxd --version
conjure-up.lxc config show
cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
Please make sure to fill out everything we asked for so that we can properly debug this.

**Comment by adityatajne94** [comment]
Error is solved automatically. It requires time to download other peers thats why it gives error. But now there is no error but installation stuck at some unit is ready and some are still waiting for machine.
So please suggest the exact configuration of a machine?
that means how much RAM, CPU, HDD it require to fully install

**Comment by adityatajne94** [comment]
![virtualbox_ubuntu 16 04_02_08_2017_10_20_46](https://user-images.githubusercontent.com/29370998/28858205-97898b7c-776c-11e7-8888-f20008529722.png)

**Comment by adityatajne94** [comment]
Is conjure-up running inside a virtual machine? -> yes
Is this problem reproducible with sudo snap refresh conjure-up --edge? -> yes
which juju -> /snap/bin/juju
which conjure-up-> /snap/bin/conjure-up
which conjure-up.lxd->  /snap/bin/conjure-up.lxd
juju version -> 2.3-alpha1-xenial-amd64
conjure-up --version -> 2.3-apha1
conjure-up.lxd --version -> 2.14
conjure-up.lxc config show -> core.https_address: '[::]:54731'
cat /etc/lsb-release -> DISTRIB_ID=Ubuntu
                                     [8/2/2017 10:49 AM] Sanjivani Jalkote: 
                                    DISTRIB_RELEASE=16.04
[8/2/2017 10:49 AM] Sanjivani Jalkote: 
DISTRIB_CODENAME=xenial

**Comment by adityatajne94** [comment]
cat /etc/lsb-release->
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS

**Comment by battlemidget** [comment]
https://docs.ubuntu.com/conjure-up/en/#hardware-requirements is the requirements to running conjure-up
