### ISSUE TITLE
LXC Shows nothing after fresh install and 1 instance running

### ISSUE THREAD

**Issue by mattwhi** [conjure-up/conjure-up#1074]
After a fresh install of Ubuntu Openstack on Single node, everything installed successfully, I launched an instance, applied a floating IP but cannot access the instance externally.

I ran $ lxc list - this is the result
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju /snap/bin/juju
which conjure-up /snap/bin/conjure-up
which conjure-up.lxd /snap/bin/conjure-up.lxd
juju version 2.2.1-xenial-amd64
conjure-up --version conjure-up 2.2.2
conjure-up.lxd --version 2.14
conjure-up.lxc config showconfig:
  core.https_address: '[::]:55970'
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?

## What provider (aws, maas, localhost, etc)?

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**Comment by battlemidget** [comment]
This will be addressed this week

**Comment by battlemidget** [comment]
Addressed in `edge` channel
