### ISSUE TITLE
Unable to bootstrap (Cloud type: maas)

### ISSUE THREAD

**Issue by sophatvathana** [conjure-up/conjure-up#1076]
## Please provide the output of the following commands

```
which juju = /usr/bin/juju
which conjure-up = /snap/bin/conjure-up
which conjure-up.lxd = /snap/bin/conjure-up.lxd
juju version = 2.2.2-zesty-amd64
conjure-up --version
conjure-up.lxd --version = 2.14
conjure-up.lxc config show = config: {}
cat /etc/lsb-release =
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=17.04
    DISTRIB_CODENAME=zesty
    DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1202369/conjure-up.tar.gz)

Follow this tutorial:
https://www.ubuntu.com/download/cloud/autopilot

Thanks in advanced.

**Comment by battlemidget** [comment]
Autopilot is being phased out, this bug does not apply any longer
