### ISSUE TITLE
error in ubuntu 16.04 while installing the openstack using conjure-up parameter

### ISSUE THREAD

**Issue by ammadyousaf8888** [conjure-up/conjure-up#1077]
error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connection refused

i apply the following commands on ubuntu 16.04

sudo snap install conjure-up --classic
conjure-up

but when i select the option in the conjure-up interface it is giving the above error

thank you

**Comment by battlemidget** [comment]
Addressed in `edge` channel
