### ISSUE TITLE
Error on macOS trying to deploy using local controller with MAAS

### ISSUE THREAD

**Issue by andyshinn** [conjure-up/conjure-up#1083]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine? *I'm not sure what is being asked here. I am running `conjure-up` on my Mac but provisioning using MAAS that is running inside a VirtualBox VM.*
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? *I'm running on a Mac and not sure this applies.*

## Please provide the output of the following commands

```
which juju: */usr/local/bin/juju*
which conjure-up: */usr/local/bin/conjure-up*
which conjure-up.lxd: *conjure-up.lxd not found*
juju version: *2.2.2-sierra-amd64*
conjure-up --version: *conjure-up 2.2-beta2*
conjure-up.lxd --version: *zsh: command not found: conjure-up.lxd*
conjure-up.lxc config show: *zsh: command not found: conjure-up.lxc*
cat /etc/lsb-release: *cat: /etc/lsb-release: No such file or directory*
```

[Tarball of **~/.cache/conjure-up** attached](https://github.com/conjure-up/conjure-up/files/1206937/conjure-up.tar.gz). Sosreport not available on Mac.

## What Spell was Selected?
`canonical-kubernetes` or `kubernetes-core`.

## What provider (aws, maas, localhost, etc)?
I'm doing a self-hosted Juju controller on local VM which is supposed to get deployed via MAAS.

### MAAS Users
Which version of MAAS? 2.2.0 installed on Ubuntu 16.04 (using `apt install maas`). I am next going to try upgrading to 2.2.2. But I'm not convinced it is a MAAS issue yet.

## Commands ran

Please outline what commands were run to install and execute conjure-up:

I first started with 2.1.5 using `brew install conjure-up` and then tried 2.2-beta2 by upgrading with `brew upgrade conjure-up --devel`. I am just running `conjure-up` and then following the prompts to do Kubernetes Core or the Canonical Kubernetes deployed via my own controller and then choose MAAS and enter my MAAS IP and API key. I then just do the deploy to do the defaults (I have 8 nodes available which seems like enough) and it eventually errors out on the deploy while it is still bootstrapping Juju.

## Additional Information

The MAAS setup probably isn't very typical. I am using a VirtualBox host-only network with a pfSense firewall (for doing NAT for internet) also deployed in the host-only network. MAAS still handles the DHCP but the pfSense is the gateway.

I'm not quite sure if the Juju controller is getting deployed fully. But during the Juju bootstrapping it errors out with: https://gist.github.com/andyshinn/5dc9c84cf4ed3b04f2a2c69acafcfc9d. Normal MAAS node deployments seem to work fine (I tested deploying a regular Ubuntu 16.04 node). I can also SSH to the Juju bootstrap node (I added some process output to the gist).

Is this a possible bug or am I missing something?

**Comment by battlemidget** [comment]
Are you able to start maas nodes without having to manually power the vm's on/off? Are all the nodes in a 'Ready' state?

**Comment by andyshinn** [comment]
> Are you able to start maas nodes without having to manually power the vm's on/off?
Not yet. Trying to get this working via `virsh` but no luck yet. I am just manually powering them on when I see them transition state in MAAS.
> Are all the nodes in a 'Ready' state?
Yep, they have all been commissioned using my manual power method. I've also provisioned a plain Ubuntu host to test that it works as desired by just manual power.

**Comment by battlemidget** [comment]
I think you're going to have a tough time getting a deployment done since during the initial cloud-init for each node they have to be rebooted and that's tough to tell when to do that manually.

**Comment by andyshinn** [comment]
I didn't see this in the menus. But is there a way that I could bootstrap the Juju node manually and select it in the menus? It seems to only have options for deploying a new one on MAAS or using JaaS with a cloud (AWS, Azure, etc). I'm just thinking for troubleshooting sake I want to just try re-using the Juju node that it is bootstrapping and try and catch the problem instead of going through the entire MAAS provision process again.

**Comment by andyshinn** [comment]
Something interesting I just noticed. The Juju node lists multiple controllers:

```
$ juju controllers          
Use --refresh flag with this command to see the latest information.

Controller            Model                           User                 Access     Cloud/Region  Models  Machines    HA  Version
conjure-up-maas-4d9   conjure-canonical-kubern-123    admin                superuser  maas               2         1  none  2.2.2  
conjure-up-maas-9db*  conjure-up-kubernetes-core-802  admin                superuser  maas               2         1  none  2.2.2  
jaas                  -                               andyshinn2@external  (unknown)                     -         -     -  2.2.2  
```

These look like controllers I was probably previously trying in `conjure-up`. Is there a possibility of confusion here if there are unavailable controllers? Is there a proper way to clean these up (maybe just removing my `~/.cache` folder?

**Comment by battlemidget** [comment]
Does `juju kill-controller conjure-up-maas-4d9` clear that up for that controller?

**Comment by andyshinn** [comment]
Yea, that helps. OK cool, so based on the `conjure-up` positional arguments it looks like I can just specify the Juju controller somehow. But I'm not sure which `cloud` it is supposed to be paired with. The `localhost` option fails:

```
$ conjure-up kubernetes-core localhost conjure-up-maas-9db
[info] Summoning kubernetes-core to localhost
[info] Using controller 'conjure-up-maas-9db'
[info] Creating new model named 'conjure-up-kubernetes-core-286', please wait.
Traceback (most recent call last):
  File "/usr/local/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2b2', 'console_scripts', 'conjure-up')()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/app.py", line 350, in main
    _start()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/app.py", line 143, in _start
    controllers.use('clouds').render()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/clouds/tui.py", line 54, in render
    self.finish()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/clouds/tui.py", line 37, in finish
    allow_exists=True)
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/juju.py", line 773, in add_model
    "Unable to create model: {}".format(sh.stderr.decode('utf8')))
Exception: Unable to create model: ERROR "localhost" is neither a cloud supported by this controller,
nor a region in the controller's default cloud "maas".
The clouds/regions supported by this controller are:

Cloud  Regions
maas   
```

Is there a way I can just specify it on the `conjure-up` CLI?

**Comment by battlemidget** [comment]
Yea on macOS localhost doesn't exist as it uses LXD. Your options are basically anything else beside localhost. So you could do `conjure-up kubernetes-core aws k8s-controller k8s-model` if you wish

**Comment by andyshinn** [comment]
Ah, OK so that gets me back to the original error:

```
$ conjure-up kubernetes-core google conjure-up-maas-9ba conjure-up-kubernetes-core-eff
[info] Summoning kubernetes-core to google
[info] Using controller 'conjure-up-maas-9ba'
[info] Creating new model named 'conjure-up-kubernetes-core-eff', please wait.
Traceback (most recent call last):
  File "/usr/local/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2b2', 'console_scripts', 'conjure-up')()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/app.py", line 350, in main
    _start()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/app.py", line 143, in _start
    controllers.use('clouds').render()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/clouds/tui.py", line 54, in render
    self.finish()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/clouds/tui.py", line 38, in finish
    return controllers.use('deploy').render()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/deploy/tui.py", line 82, in render
    self.do_pre_deploy()
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/controllers/deploy/tui.py", line 30, in do_pre_deploy
    app.current_model)['provider-type']
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/juju.py", line 123, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/usr/local/Cellar/conjure-up/2.2-beta2/libexec/lib/python3.6/site-packages/conjureup/juju.py", line 756, in get_model
    "Unable to find model: {}".format(name))
LookupError: Unable to find model: conjure-up-kubernetes-core-eff
```

The model does appear to exist:

```
$ juju models
Controller: conjure-up-maas-9ba

Model                            Cloud/Region  Status     Machines  Cores  Access  Last connection
conjure-up-kubernetes-core-eff*  maas          available         0      -  admin   59 seconds ago
controller                       maas          available         1      1  admin   just now
```

I'll do some more debugging.

**Comment by battlemidget** [comment]
Ok, so you can re-use conjure-up-maas-9ba b/c that controller is tied to MAAS  and not GCE. You would need to use different a different unique controller name if you want to use a different provider

**Comment by andyshinn** [comment]
I think I've figured out where the issue is happening at least. It seems to be at https://github.com/conjure-up/conjure-up/blob/master/conjureup/juju.py#L760. In the `m` array the model `name` in my case is `admin/conjure-up-kubernetes-core-eff`. But the `name` it compares to is just `conjure-up-kubernetes-core-eff`.

The `name` appears to come from `get_models` method which uses `juju list-models --format yaml` to grab the names. The `name` is incorrect but the `short-name` is... I wonder if this was meant to be `short-name`?

**Comment by andyshinn** [comment]
So, I just hacked it to be `m['short-name']` instead of `m['name']` and it is actually working now! It is deploying the nodes in MAAS. I'm not quite sure why the naming has `admin/` prepended, but it is actually moving along again.

**Comment by battlemidget** [comment]
interesting, we'll need to dig in this a bit more, @johnsca

**Comment by battlemidget** [comment]
@johnsca pointed me to:

https://bugs.launchpad.net/juju/+bug/1693581 and https://github.com/juju/juju/pull/7436

**Comment by johnsca** [comment]
Looks like this was changed in juju/juju#7436 and we probably should use `short-name`.

**Comment by battlemidget** [comment]
@andyshinn are you comfortable posting a PR for your change? We'd like to review it and get it merged in

**Comment by andyshinn** [comment]
Good finds. It does look like whatever `name` was has changed to `short-name` in Juju 2.2+. But with a change in PR, wouldn't that mean that newer `conjure-up` would only work with Juju 2.2+?

If we are fine with that I'm happy to open the PR.

**Comment by battlemidget** [comment]
@andyshinn Yea, totally fine with newer conjure-up supporting 2.2+

**Comment by andyshinn** [comment]
Cool, thanks! I didn't open the PR as I actually couldn't verify my fix because I broke my MAAS setup right after discovering the fix. I'll test this soon and open another issue if it is still a problem.

**Comment by battlemidget** [comment]
Thanks! It should be in a build by tonight

**Comment by battlemidget** [comment]
Yea i need to find time to update that forumlae
