### ISSUE TITLE
Error bootstrapping controller: ['ERROR unknown cloud "vsphere", please try "juju update-clouds"']

### ISSUE THREAD

**Issue by brettdh** [conjure-up/conjure-up#1097]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems **No**
- [x] Is conjure-up running inside a virtual machine? **No**
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? **N/A; running on macOS**

## Please provide the output of the following commands

Note: omitting details specific to the Linux client, since I'm running conjure-up on macOS.
```
$ which juju
/usr/local/bin/juju
$ which conjure-up
/usr/local/bin/conjure-up
$ juju version
2.2.2-sierra-amd64
$ conjure-up --version
conjure-up 2.2.2
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1219186/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## What Spell was Selected?

canonical-kubernetes

## What provider (aws, maas, localhost, etc)?

vsphere

## Commands ran

```
$ conjure-up canonical-kubernetes
```

## Additional Information

Running on macOS Sierra, 10.12.5

**Comment by brettdh** [comment]
FWIW, I did try `juju update-clouds` but it didn't add anything. Juju seems to have saved my vSphere credential, though, since it's visible in `juju list-credentials --show-secrets` (though the `vsphere`cloud doesn't appear at all without the `--show-secrets`).

**Comment by battlemidget** [comment]
@brettdh thanks for testing on macOS! I'll take a look asap

**Comment by battlemidget** [comment]
@brettdh Can you try with `--HEAD` and see if the problem persists?

**Comment by brettdh** [comment]
Well this seems bad. 🤔 
```
➜ brew upgrade conjure-up --HEAD
<snip>
➜ conjure-up --version
conjure-up 2.3-alpha1

➜ conjure-up  canonical-kubernetes

  !! Unable to connect to Redis. !!
```

**Comment by battlemidget** [comment]
hmm, does redis not start automatically when it's installed on macOS?

**Comment by brettdh** [comment]
¯\_(ツ)_/¯

I can tell you it's not running on my laptop, anyway.

**Comment by battlemidget** [comment]
https://github.com/conjure-up/conjure-up/issues/1039

**Comment by battlemidget** [comment]
Is this still an issue? If so, please re-open this bug and we'll do some more digging.
