### ISSUE TITLE
Openstack NovaLXD stuck at Bootstrapping Juju controller

### ISSUE THREAD

**Issue by mangonerd** [conjure-up/conjure-up#1098]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems **No**
- [x] Is conjure-up running inside a virtual machine? **No**
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? **Don't know. Running --classic **

## Please provide the output of the following commands

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which conjure-up.lxd
/snap/bin/conjure-up.lxd
$ juju version
2.2.1-zesty-amd64
$ conjure-up --version
conjure-up 2.2.2
$ conjure-up.lxd --version
2.14
$ conjure-up.lxc config show
config:
  core.https_address: '[::]:39857'
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"


```

##Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1226090/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

[Dropbox link](https://www.dropbox.com/s/0ggb7ukya2hxgxy/sosreport-MirzaPrangon.001-20170816011919.tar.xz?dl=0) Could not attach here.

## What Spell was Selected?
Openstack NovaLXD
## What provider (aws, maas, localhost, etc)?
Localhost
### MAAS Users
Which version of MAAS?
NA
## Commands ran
snap install conjure-up --classic
conjure-up

## Additional Information
I live in a developing country and electricity is not always online here. The machine was shut down during installation 4 times for power outage. This is the 5th time. Each time there was a juju controller which i could not remove with destroy-controller. It showed some error about not able to connect to API. I used kill-controller to remove the controller, then ran conjure-up each time.

Now the installation is stuck in the state seen in the image for about 3 hours.
![2017-08-16-013826_1366x768_scrot](https://user-images.githubusercontent.com/29655919/29332962-c4fa2cb2-8223-11e7-9ec7-e4982edbfc41.png)

**Comment by mangonerd** [comment]
I am running LUBUNTU if it helps. Any known issue with LUBUNTU?

**Comment by mangonerd** [comment]
This problem persists on fresh install of lubuntu 16.04 and ubuntu 16.04. Same problem. 

Last line of conure-up log ` [DEBUG] conjure-up/openstack-novalxd - events.py:55 - Awaiting RelationsAdded:nova-cloud-controller at /snap/conjure-up/549/usr/lib/python3.6/asyncio/events.py:127 in task wait at conjureup/events.py:95`
Last line of juju ` - copying image for juju/xenial/amd64 from https://cloud-images.ubuntu.com/daily/: rootfs: 100% (18.72kB/s)`

After that its just stuck like this. My partition has about 130GB free. Is this problem for disk space?

**Comment by battlemidget** [comment]
That should be enough space, in another terminal could you provide output of `juju status --format yaml|pastebinit`

**Comment by mangonerd** [comment]
`juju status` says "no API address."
`$ juju status --format yaml | pastebinit
ERROR no API addresses
You are trying to send an empty document, exiting.`

I manually imported image into lxc, following [this](https://bryanquigley.com/howto/jujus-localhost-lxd-now-works-with-offline-images), now bootstrapping is stuck at "Attempting to connect to ******". Tried bootstrapping manually by `juju bootstrap localhost test01`. This also stuck at "Attempting to connect to ...."

![2017-08-21-024243_1366x768_scrot](https://user-images.githubusercontent.com/29655919/29498290-7011edac-861a-11e7-85cb-2777b4637af0.png)

**Comment by battlemidget** [comment]
what does `conjure-up.lxc list show`

**Comment by mangonerd** [comment]
```
$ conjure-up.lxc list
+---------------+---------+----------------------+------+------------+-----------+
|     NAME      |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+----------------------+------+------------+-----------+
| juju-6ce797-0 | RUNNING | 10.190.154.31 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
```
This

**Comment by mangonerd** [comment]
I see that network interface of the container is `eth0`. Shouldn't it be 'lxdbr0`?

Anyway i could access internet from my manually created container - 

```
$ conjure-up.lxc launch juju/xenial/amd64 test003
Creating test003
Starting test003
mirza@cloudpc:~$ conjure-up.lxc list
+---------------+---------+----------------------+------+------------+-----------+
|     NAME      |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+----------------------+------+------------+-----------+
| juju-6ce797-0 | RUNNING | 10.190.154.31 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
| test003       | RUNNING | 10.190.154.82 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+----------------------+------+------------+-----------+
mirza@cloudpc:~$ conjure-up.lxc exec test003 -- ping www.google.com -c 5
PING www.google.com (172.217.27.228) 56(84) bytes of data.
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=1 ttl=50 time=89.7 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=2 ttl=50 time=89.3 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=3 ttl=50 time=90.3 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=4 ttl=50 time=89.8 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=5 ttl=50 time=90.0 ms

--- www.google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 89.363/89.877/90.354/0.501 ms
```

**Comment by pragon** [comment]
Maybe try to use JUJU directly, and see how it goes.

**Comment by mangonerd** [comment]
Well i reisntalled lubuntu. Same problem, hangs at "Attempting to connect to 10.168.198.95:22"
![2017-08-23-225304_1366x768_scrot](https://user-images.githubusercontent.com/29655919/29628017-f59d9d8a-8855-11e7-89ae-e4fedeeee1c3.png)

The bootstrap created container can connect to internet. 
```
$ conjure-up.lxc exec juju-0ee57b-0 -- ping www.google.com -c 5
PING www.google.com (172.217.27.228) 56(84) bytes of data.
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=2 ttl=50 time=90.3 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=3 ttl=50 time=90.6 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=4 ttl=50 time=90.9 ms
64 bytes from kul09s01-in-f4.1e100.net (172.217.27.228): icmp_seq=5 ttl=50 time=90.6 ms

--- www.google.com ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4025ms
rtt min/avg/max/mdev = 90.312/90.637/90.967/0.380 ms
```
I can ping the bootstrap created container from terminal too
```
$ ping 10.168.198.95 -c 4
PING 10.168.198.95 (10.168.198.95) 56(84) bytes of data.
64 bytes from 10.168.198.95: icmp_seq=1 ttl=64 time=0.048 ms
64 bytes from 10.168.198.95: icmp_seq=2 ttl=64 time=0.052 ms
64 bytes from 10.168.198.95: icmp_seq=3 ttl=64 time=0.043 ms
64 bytes from 10.168.198.95: icmp_seq=4 ttl=64 time=0.054 ms

--- 10.168.198.95 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3058ms
rtt min/avg/max/mdev = 0.043/0.049/0.054/0.006 ms
```
 
After seeing [this bug](https://bugs.launchpad.net/ubuntu/+source/juju-core/+bug/1644566), tried `ls -l /home/ubuntu/.ssh`, bootstrap have installed ssh.
```
$ conjure-up.lxc exec juju-0ee57b-0 -- ls -l /home/ubuntu/.ssh
total 4
-rw------- 1 ubuntu ubuntu 402 Aug 23 16:28 authorized_keys
```

**Comment by mangonerd** [comment]
After stuck there for 1:15 hour, it started deplyoing. Only change from previous tries is that i used the ***root.tar.gz file instead of ***root.tar.xz file from ubuntu-cloud image.

Still, the problem remains that juju could not even start bootstrapping. As it was stuck at copying image 100%, i had to manually add the image to lxc.

**Comment by battlemidget** [comment]
Yea it's hard to say, can you attach a new tarball of `~/.cache/conjure-up`

**Comment by mangonerd** [comment]
Here is a new tarball of `~/.cache/conjure-up`
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1246568/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
ok nothing in there that would indicate why, can you run `juju status --format yaml|pastebinit` and paste the link here

**Comment by mangonerd** [comment]
`juju status --format yaml|pastebinit`
http://paste.ubuntu.com/25378430/

**Comment by mangonerd** [comment]
I am using mirror.dhakacom.com mirror server of bangladesh. Can it be any issue with this mirror?

**Comment by battlemidget** [comment]
it's possible, it just seems like it's taking you a long time to download anything

**Comment by mangonerd** [comment]
Installation fails with "Failure in step 00_deploy-done"
![2017-08-24-033543_1366x768_scrot](https://user-images.githubusercontent.com/29655919/29639716-8a4f7ddc-887d-11e7-82a2-a2ec49f426f1.png)

Tarball of `~/.cache/conjure-up`
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1247121/conjure-up.tar.gz)

`juju status --format yaml|pastebinit` - http://paste.ubuntu.com/25378930/

**Comment by battlemidget** [comment]
there are --apt-proxy and --apt-https-proxy

**Comment by mangonerd** [comment]
I can not conjure-down.
![2017-08-24-105718_1366x768_scrot](https://user-images.githubusercontent.com/29655919/29650189-093d1bda-88bb-11e7-9152-ca8665b96c88.png)

How do i remove conjure-up uncompleted installation? So that i don't have to install os.

**Comment by battlemidget** [comment]
You can do `juju controllers` and then `juju kill-controller -y <controller name>`

**Comment by battlemidget** [comment]
Addressed in `edge` channel
