### ISSUE TITLE
conjure-up failed to initiate containers: Error : ERROR juju.provisioner provisioner_task.go:707 cannot start instance for machine "0/lxd/2": failed to bridge devices: bridge activaction error: bridge activation failed: Killed old client process

### ISSUE THREAD

**Issue by vbijumon** [conjure-up/conjure-up#1128]
i was trying to conjure-up and getting t he below error.

Error from machine 0 :
Location:

/var/log/juju$ sudo cat machine-0.log

2017-08-31 14:31:36 WARNING juju.provisioner provisioner_task.go:739 failed to start instance (failed to bridge devices: bridge activaction error: bridge activation failed: Killed old client process
2017-08-31 14:31:49 WARNING juju.provisioner provisioner_task.go:739 failed to start instance (failed to bridge devices: bridge activaction error: bridge activation failed: Killed old client process
2017-08-31 14:32:01 ERROR juju.provisioner provisioner_task.go:707 cannot start instance for machine "0/lxd/2": failed to bridge devices: bridge activaction error: bridge activation failed: Killed old client process

juju status error:

0/lxd/3 down pending xenial failed to bridge devices: bridge activaction error: bridge activation failed: Killed old client process
Internet Systems Consortium DHCP Client 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/ens2f0/0c:c4:7a:19:69:5c
Sending on LPF/ens2f0/0c:c4:7a:19:69:5c
Sending on Socket/fallback
DHCPRELEASE on ens2f0 to 10.205.76.4 port 67 (xid=0xcf0222c)
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted
Bringing up bridged interfaces failed, see system logs and /etc/network/interfaces.new
Internet Systems Consortium DHCP Client 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/ens2f0/0c:c4:7a:19:69:5c
Sending on LPF/ens2f0/0c:c4:7a:19:69:5c
Sending on Socket/fallback
DHCPDISCOVER on ens2f0 to 255.255.255.255 port 67 interval 3 (xid=0xddb8be72)
DHCPREQUEST of 10.205.76.6 on ens2f0 to 255.255.255.255 port 67 (xid=0x72beb8dd)
DHCPOFFER of 10.205.76.6 from 10.205.76.4
DHCPACK of 10.205.76.6 from 10.205.76.4
bound to 10.205.76.6 -- renewal in 286 seconds.
RTNETLINK answers: Operation not permitted
RTNETLINK answers: Operation not permitted

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
No
- [ ] Is conjure-up running inside a virtual machine?

NO

- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
lxc config show
lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by vbijumon** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1267636/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
Are you attempting ot deploy landscape on to maas?

**Comment by vbijumon** [comment]
yes i am trying to deploy landscape from MAAS

**Comment by battlemidget** [comment]
This error is network related which leads me to believe it's a misconfiguration on your maas server. Also FYI the landscape spell is being deprecated as Autopilot is being phased out. You'll want to use our `openstack-base` spell as an alternative

**Comment by vbijumon** [comment]
Thank you...i will do recheck my maas network configuration and come back for any help...

i had the working openstack lab setup which i deployed using landscape...due to some hardware issue i replaced one server and tried to redeploy the openstack from landscape ...the same issue(lxd not starting : bridge activation error) i faced during the deployment  of openstack from landscape...so i desided to rebuild my entire lab...and now it is failing at landscape itself 😱...

**Comment by vbijumon** [comment]
as per my understanding ... before starting the lxd machines on machine 0... it will create bridge (in my case it is br-ens2f0)in machine 0 and remove the dhcp ip from physical interface ens2f0 and assign the same to bridge br-ens2f0 to activate the bridge...but while checking ifconfig on machine 0 ...both bridge and the physical interface showing the same ip....not sure whether it is creating any problem... 😱

**Comment by vbijumon** [comment]
i have checked from maas and i could able to auto power on/off all the nodes from Maas...

**Comment by vbijumon** [comment]
related to network settings in maas...i have two nic one is public and another one is private...public nic in fabri 4 and private nic in fabric 6... both are in same space-1...in maas both subnet vlan is untaged...

**Comment by vbijumon** [comment]
any idea ...where i am doing wrong....

**Comment by vbijumon** [comment]
also have added 2 node to maas... one us gor juju other is for autopilot.. both are physical machines..and having 2 nic... one is connected to public vlan and other nic is connected to a private vlan in a l3 switch....

**Comment by battlemidget** [comment]
You'll want to obtain support for this via askubuntu.com, currently there is no bug to report here related to conjure-up.

**Comment by vbijumon** [comment]
sure thank you...also do we have any suggestions related to network architecture with 3 physical machines (Maas, juju, autopilot) with 2 nic.......

**Comment by battlemidget** [comment]
Again we're phasing out Autopilot so I would suggest looking into our OpenStack base solutions
