### ISSUE TITLE
The Canonical Distribution (kube on Ubuntu) cannot find apiserver config file

### ISSUE THREAD

**Issue by chientt** [conjure-up/conjure-up#1130]
It seems not an issue, sorry for that, but this is the first time I work with Canonical dist, so How I can configure some parameter for kube-apiserver such as: admission-control, secure-port, it is very different with some other distribution using /etc/kubernetes/config or /etc/kubernetes/apiserver

**Comment by tvansteenburgh** [comment]
We have a [PR submitted](https://github.com/kubernetes/kubernetes/pull/47912) that will let you modify apiserver args via charm config. In the meantime, you can do it using the `snap set` command (see https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Kubernetes-Snaps:-The-Quick-Version)

**Comment by battlemidget** [comment]
Closing this out, @chientt please follow the linked PR above for when it gets merged upstream and also signup to https://lists.ubuntu.com/mailman/listinfo/juju to be notified when an updated CDK is released with this capability.
