### ISSUE TITLE
Can't Access Services Outside Cluster Network (LXD installation)

### ISSUE THREAD

**Issue by lghinet** [conjure-up/conjure-up#1144]
hello,
i dont know if its the right area , but I am having the same problem like 

https://stackoverflow.com/questions/45304692/cant-access-services-outside-cluster-network-lxd-installation
or 

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/410

is there any documentation on how to do this right, 
thank you

**Comment by battlemidget** [comment]
The bug you filed https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/410 is the right place for this. I've been told there is a blog post coming very soon on how to accomplish this. Please follow the above bug to be notified when that documentation becomes available.

Thanks!

**Comment by lghinet** [comment]
ok , thanks, but until then, can you point me to some workarounds ?

**Comment by battlemidget** [comment]
The blog post would be the workaround, maybe @tvansteenburgh can post a tldr here until then?
