### ISSUE TITLE
Deploy Kubernetes localhost (lxd) hang on 00_deploy-done

### ISSUE THREAD

**Issue by matinalro** [conjure-up/conjure-up#1155]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [ yes] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju  = /snap/bin/juju
juju version = 2.2.2-yakkety-amd64

which conjure-up = /snap/bin/conjure-up 
conjure-up --version = conjure-up 2.3.0 

which lxc = /snap/bin/lxc
lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
lxc version = 2.17

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1312451/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
The resulting output file can be attached to this issue.

[sosreport.zip](https://github.com/conjure-up/conjure-up/files/1312493/sosreport.zip)

## What Spell was Selected?
Kubernetes Canonical

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
N/A
## Commands ran

Please outline what commands were run to install and execute conjure-up:
After I have installed a fresh new Ubuntu 16.04 I run:

```
$ sudo apt install snapd
$ sudo snap install lxd
$ sudo snap install conjure-up --classic 
$ sudo usermod -aG lxd username
$ sudo lxd init (dir, ipv4-auto, ipv6-none)
$ conjure-up kubernetes 
```

## Additional Information

It hangup on  00_deploy-done.  I tried to use lxd from apt packet manager instead snap but conjure didn't recognize it (localhost controller was gray out and asked me to install lxd with sudo snap install lxd && lxd init)

**Comment by battlemidget** [comment]
The agents never got out of allocating state, one thing to note (which has been addressed in upcoming 2.3.1) is that you should run:

```
/snap/bin/lxd init
```

Since you have both lxd from apt and snap lxd installed the PATH will always search for the apt installed LXD. Until `/snap/bin` can be added to Ubuntu's default $PATH we've updated our conjure-up documentation to explicitly call to `/snap/bin/lx{d,c}`

**Comment by matinalro** [comment]
Yes, I did run /snap/bin/lxd init 

Withouth running /snap/bin/lxd init will not even let you choose localhost. /snap/bin/lxd = 2.17  and the apt package is 2.0.1

I want to note that I have run conjure-up and lxd directly on metal host. However if I follow this tutorial which supose to run conjure nested inside other lxc container, the deployment works fine. Why is that ? This is what suppose to run, nested ?

Thank you

**Comment by blackolo** [comment]
I have same/similar issue when conjure-up would stop on 00_deploy_done. My setup in VM works well when I tried to do it on my dedicated server it would hang on that step.

One interesting thing was that juju status would show Missing source '/dev/null' for disk 'aadisable', i tried to investigating it on my own but after few days came up empty handed.

hope someone here would be able to help

conjure-up 2.3.1
lxc 2.18

`user@wintermute:~$ juju status
Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-9f2  conjure-up-localhost-e68  localhost/localhost  2.2.3    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                         waiting    0/1  easyrsa                jujucharms   15  ubuntu
etcd                            waiting    0/3  etcd                   jujucharms   48  ubuntu
flannel                         waiting      0  flannel                jujucharms   26  ubuntu
kubeapi-load-balancer           waiting    0/1  kubeapi-load-balancer  jujucharms   25  ubuntu  exposed
kubernetes-master               waiting    0/1  kubernetes-master      jujucharms   47  ubuntu
kubernetes-worker               waiting    0/3  kubernetes-worker      jujucharms   52  ubuntu  exposed

Unit                     Workload  Agent       Machine  Public address  Ports  Message
easyrsa/0                waiting   allocating  1                               waiting for machine
etcd/0                   waiting   allocating  2                               waiting for machine
etcd/1                   waiting   allocating  3                               waiting for machine
etcd/2                   waiting   allocating  4                               waiting for machine
kubeapi-load-balancer/0  waiting   allocating  0                               waiting for machine
kubernetes-master/0      waiting   allocating  5                               waiting for machine
kubernetes-worker/0      waiting   allocating  9                               waiting for machine
kubernetes-worker/1      waiting   allocating  10                              waiting for machine
kubernetes-worker/2      waiting   allocating  11                              waiting for machine

Machine  State  DNS  Inst id  Series  AZ  Message
0        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
1        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
2        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
3        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
4        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable1'
5        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
6        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
7        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
8        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable1'
9        down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
10       down        pending  xenial      Missing source '/dev/null' for disk 'aadisable1'
11       down        pending  xenial      Missing source '/dev/null' for disk 'aadisable'
`

`lxc profile show juju-$(juju switch | awk -F/ '{print $2}')
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /dev/null
    type: disk
  aadisable1:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
`

thanks in advance
