### ISSUE TITLE
Error running conjure-up (openstack novalxd) on a clean install of Ubuntu Server 17.04

### ISSUE THREAD

**Issue by davparker** [conjure-up/conjure-up#1160]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems no
- [ ] Is conjure-up running inside a virtual machine?  No
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? Yes

## Please provide the output of the following commands

```
david@ubuntu01:~$ which juju
/snap/bin/juju
david@ubuntu01:~$ juju version
2.3-alpha1-zesty-amd64
david@ubuntu01:~$
david@ubuntu01:~$ which conjure-up
/snap/bin/conjure-up
david@ubuntu01:~$ conjure-up --version
conjure-up 2.4-alpha1
david@ubuntu01:~$
david@ubuntu01:~$ which lxc
/usr/bin/lxc
david@ubuntu01:~$ lxc config show
config: {}
david@ubuntu01:~$ lxc version
2.12
david@ubuntu01:~$
david@ubuntu01:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"

```

Please attach tarball of **~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1316659/conjure-up.tar.gz)
[sosreport-dparker.na-20170920001536.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/1316665/sosreport-dparker.na-20170920001536.tar.xz.zip)

**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
openstack with NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
sudo snap install conjure-up --classic
conjure-up

## Additional Information
This was a clean install of Ubuntu Server 17.04
conjure-up intially reported that lxd was not installed when it is part of a fresh install of Ubuntu  Server 17.04. What's more, I had ran 'sudo lxd init' prior to running conjure-up.
I then ran ' sudo snap install lxd && lxd init' as the message instructed but then get the error.
===================================================================
Oops, there was a problem with your install:
Reason:
Could not locate any network or storage devices to continue. Please make sure you have at least 1 network bridge and 1 storage pool: see 'lxc network list' and 'lxc storage list'

Review log messages at ~/.cache/conjure-up/conjure-up.log. If appropriate, please submit a bug here: https://github.com/conjure-up/conjure-up/issues/new
===================================================================
I've reinstalled Ubuntu Server 17.04 and went through all the steps again, but the result is the same error.

david@ubuntu01:~$ lxc network list
+--------+----------+---------+---------+
|  NAME  |   TYPE   | MANAGED | USED BY |
+--------+----------+---------+---------+
| eno1   | physical | NO      | 0       |
+--------+----------+---------+---------+
| lxdbr0 | bridge   | YES     | 0       |
+--------+----------+---------+---------+
| wlp1s0 | physical | NO      | 0       |
+--------+----------+---------+---------+
david@ubuntu01:~$ lxc storage list
+--------+--------+-------------------------------+---------+
|  NAME  | DRIVER |            SOURCE             | USED BY |
+--------+--------+-------------------------------+---------+
| vmpool | zfs    | /var/lib/lxd/disks/vmpool.img | 1       |
+--------+--------+-------------------------------+---------+

**Comment by battlemidget** [comment]
I suspect that lxdbr0 has ipv6 enabled, can you verify with:

```
/snap/bin/lxc network show lxdbr0
```

**Comment by davparker** [comment]
My thought was conjure-up wasn't tested with Ubuntu Server 17.x so I reloaded with Ubuntu Server 16.04.3, went through all the steps again but got exactly the same error. When I ran lxd init I indicated not to use IPv6.
david@ubuntu01:~$ /snap/bin/lxc network show lxdbr0
config: {}
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: false

Sorry, should have waited. It is just very frustrating coming off multiple clean installs of a server, thinking I'm following setup instructions carefully, but it doesn't matter. Different OS exactly the same result. Is it that there are multiple versions or libraries for lxc/lxd installed? The one that comes installed by default, and the one installed via snap?  Or does the snap install upgrade the existing?

**Comment by davparker** [comment]
Yeah, my fears were correct apparently. See...
https://stgraber.org/2016/10/17/lxd-snap-available/
If this is true, it deserves a footnote at the very least. I'm going to start over, from scratch, back to Ubuntu Server 17.x. Then try to clean up a fresh install of these what I guess are now orphaned packages. Man, Ubuntu still has a long ways to go...

**Comment by battlemidget** [comment]
@davparker Totally understand your frustration. I'm currently updating the official documentation to be more clear in this regard. Ubuntu is also in a time period where snaps are becoming production ready and are transitioning to be some of the default packages on the system (lxd being a prime example). What this means is soon into the future there won't be 2 seperate installs of the same thing and this confusion will go away.

**Comment by adiroiban** [comment]
Another issue I found, is that I had to run this

```
newgrp lxd
usermod -G lxd MY_USER_RUNNING_CONJURE
```

conjure was instructing me to add lxd via snap, and I did all that, but unless I have created that group, it was not working.

**Comment by davparker** [comment]
Thanks, I appreciate it. It has been a while since I used Ubuntu/lxd/Docker. I think I'll go over some of the docs and processes I've done in the past before I take another crack at OpenStack with conjure-up.

**Comment by keanesf** [comment]
I ran this command to resolve the issues on ubuntu 16.04

/snap/bin/lxc network set lxdbr0 ipv6.address none ipv6.nat false

**Comment by slobastev** [comment]
To make `conjure-up` working I had to remove lxd

`sudo apt-get remove lxd lxd-client`

then, install it using snap

`sudo snap install lxd`

after installation was completed I run 

`lxd init`

to install bridge adapter and storage pool.

the command `/snap/bin/lxc network show lxdbr0` showed that ipv6 was enabled. So, I had to run separately 

`/snap/bin/lxc network set lxdbr0 ipv6.address none`
`/snap/bin/lxc network set lxdbr0 ipv6.nat false`
