### ISSUE TITLE
juju.py bootstrap fn uses incorrect parameter --model-default instead of --model-defaults

### ISSUE THREAD

**Issue by dsanders1234** [conjure-up/conjure-up#1164]
I believe that juju.py bootstrap function passes --model-default rather than --model-defaults to juju command.  This causes conjure-up to basically ignore settings during deploy (such as canonical-kubernetes vsphere 'primary-network' and 'datastore' settings).

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
lxc config show
lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
Where did you see `model-defaults` described? Looking at the juju help output it is supposed to be `model-default`

```
Usage: juju bootstrap [options] [<cloud name>[/region] [<controller name>]]

Summary:
Initializes a cloud environment.

Options:
-B, --no-browser-login  (= false)
    Do not use web browser for authentication
--agent-version (= "")
    Version of tools to use for Juju agents
--auto-upgrade  (= false)
    Upgrade to the latest patch release tools on first bootstrap
--bootstrap-constraints (= "")
    Specify bootstrap machine constraints
--bootstrap-series (= "")
    Specify the series of the bootstrap machine
--build-agent  (= false)
    Build local version of agent binary before bootstrapping
--clouds  (= false)
    Print the available clouds which can be used to bootstrap a Juju environment
--config  (= )
    Specify a controller configuration file, or one or more configuration
    options
    (--config config.yaml [--config key=value ...])
--constraints (= "")
    Set model constraints
--credential (= "")
    Credentials to use when bootstrapping
-d, --default-model (= "default")
    Name of the default hosted model for the controller
--keep-broken  (= false)
    Do not destroy the model if bootstrap fails
--metadata-source (= "")
    Local path to use as tools and/or metadata source
--model-default  (= ) <--- HERE
    Specify a configuration file, or one or more configuration
    options to be set for all models, unless otherwise specified
    (--config config.yaml [--config key=value ...])
--no-gui  (= false)
    Do not install the Juju GUI in the controller when bootstrapping
--no-switch  (= false)
    Do not switch to the newly created controller
--regions (= "")
    Print the available regions for the specified cloud
--to (= "")
    Placement directive indicating an instance to bootstrap
```

**Comment by dsanders1234** [comment]
https://jujucharms.com/docs/2.2/models-config

**Comment by battlemidget** [comment]
This is after a bootstrap takes place though, so that wouldn't apply here since we set it during bootstrap. @johnsca correct me if I'm wrong here

**Comment by dsanders1234** [comment]
Try to conjure-up canonical kubernetes against a vsphere that has several networks and datastores to choose from.  Select a non-default primary network and datastore and you will notice that it ignores these settings.  The resulting VMs will be on their defaults.  The workaround for us was to set the model defaults to what we want prior to running conjure-up.

**Comment by battlemidget** [comment]
Ok will take a look today

**Comment by johnsca** [comment]
The `juju model-defaults` command is used to show the defaults that were set when the controller was bootstrapped with `juju bootstrap --model-default <filename>`.  See [cmd/juju/commands/bootstrap.go line 189](https://github.com/juju/juju/blob/develop/cmd/juju/commands/bootstrap.go#L189).  You can then override those defaults using `juju model-config` on a per-model basis.

It sounds like you're re-using an existing controller, and I see that while we pass the correct `--model-default` option to the `juju bootstrap` command, we don't seem to set any config on the model if an existing controller is used.  This means the network settings would only be honored on the initial bootstrap.

We should update `conjureup.juju.add_model` (or maybe `conjureup.controllers.bootstrap.common.BaseBootstrapController.do_add_model`) to use the `app.provider.model_defaults` data to set the per-model config.

**Comment by dsanders1234** [comment]
Yes, you are correct in that we bootstrapped the controller beforehand following the juju docs on setting up for vsphere.  This may have been because we were initially having trouble using conjure-up directly and thought that we were required to do that first.

**Comment by battlemidget** [comment]
Ok cool, we'll get this sorted

**Comment by dsanders1234** [comment]
Scrubbing everything and doing conjure-up directly puts the VMs on both the network that we select AND the first one in the list of networks.  All VMs also have the same IP address.  We get this output in the logs:

2017-09-22 12:59:45,758 [DEBUG] conjure-up/canonical-kubernetes - events.py:53 - Received DeploymentComplete at conjureup/controllers/deploy/common.py:59 in task _wait_for_applications at conjureup/controllers/deploy/gui.py:90
2017-09-22 12:59:45,758 [INFO] conjure-up/canonical-kubernetes - common.py:61 - Waiting for deployment to settle.
2017-09-22 13:01:25,722 [WARNING] conjure-up/canonical-kubernetes - websocket: connection.py:254 - RPC: Connection closed, reconnecting
2017-09-22 13:01:25,722 [INFO] conjure-up/canonical-kubernetes - websockets.protocol: protocol.py:638 - Failing the WebSocket connection: 1011

**Comment by battlemidget** [comment]
Ok I'll try to reproduce this afternoon, thanks for taking the time to try this out

**Comment by dsanders1234** [comment]
Any updates on these issues?

**Comment by johnsca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Model config (i.e., vsphere network selection) doesn't get applied to new models on existing controllers](https://trello.com/c/wxY7F1NC/95-model-config-ie-vsphere-network-selection-doesnt-get-applied-to-new-models-on-existing-controllers)

**Comment by johnsca** [comment]
@dsanders1234 @battlemidget wasn't able to get to it before he left for vacation, so I've put it on the board for myself to work on this week.

I'm not sure about your other reply, though; when you allow conjure-up to bootstrap the controller, what does the model config end up having for the network selection?

**Comment by jstano** [comment]
Here is the output of the model-config command.

Thanks,

Jeff
[model-config.txt](https://github.com/conjure-up/conjure-up/files/1354364/model-config.txt)

**Comment by dsanders1234** [comment]
We didn't choose an external network in conjure-up UI, but it appears to assign one anyway?

**Comment by johnsca** [comment]
@dsanders1234 I fixed both issues in the linked PR, but I'm not 100% certain it will fix the issue you encountered and I wasn't able to reproduce it.  It would be great if you could test from the PR.  You can either use `make dev; source conjure-dev/bin/activate; conjure-up` or you can build the snap from the PR with `snapcraft` and then install it with `snap install --dangerous ./<snap-file>` (I don't recall the exact name of the snap that is built).

**Comment by johnsca** [comment]
Otherwise, I'll try to get the PR reviewed and into the edge snap.

**Comment by johnsca** [comment]
That change is now in the edge channel of the conjure-up snap.  Please test to see if it resolves all of the issues.
