### ISSUE TITLE
Conjure-up install NOVA KVM Neutron-gateway hook failed

### ISSUE THREAD

**Issue by brotherchris** [conjure-up/conjure-up#1173]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
Don't see it, but the neutron-gateway is mentioned. Doc says maybe a bridge problem. Shouldn't I be able to use the default setting?
- [ ] Is conjure-up running inside a virtual machine?
No
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
Working on this now.

## Please provide the output of the following commands

```
which juju /snap/bin/juju
juju version 2.3-alpha1-xenial-amd64


which conjure-up /snap/bin/conjure-up

conjure-up --version  conjure-up 2.4-alpha1


which lxc /usr/bin/lxc

lxc config show

Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init
To start your first container, try: lxc launch ubuntu:16.04

config: {}
lxc version 2.0.10



cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1337058/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport


sosreport (version 3.4)

no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Conjure-up
## What provider (aws, maas, localhost, etc)?
MAAS
### MAAS Users
Which version of MAAS?

## Commands ran

conjure-up
Selected NOVA KVM install
## Additional Information
I have tried the NOVA KVM install a couple of time now. Neutron-gateway always gets set to hook failed config changed. When I try to resolve it is says missing relations, messaging network-service. Then it falls back to hook failed. 
![missing](https://user-images.githubusercontent.com/19783552/30912931-fa6ed482-a353-11e7-9ef8-f0ebd2383ecf.PNG)
![faild](https://user-images.githubusercontent.com/19783552/30912937-05ed75a2-a354-11e7-9b3c-103684ab8d2d.PNG)

**Comment by brotherchris** [comment]
Same error from conjure-up --edge on neutron-gateway. A few other charms didn't get as far as they did in stable.

**Comment by brotherchris** [comment]
MAAS version: 2.2.2 (6099-g8751f91-0ubuntu1~16.04.1)

**Comment by fenris** [comment]
any update or status on this matter ? im still having the same issue now .. thanks

**Comment by fenris** [comment]
use solution for issue #728 ?

**Comment by miguelcostaUI** [comment]
Have you found a solution for this issue? I'm having the same problem..

Setting "net.ifnames=0" in maas kernel parameters does not fix it.

**Comment by NDgunner** [comment]
having the same issue
