### ISSUE TITLE
Error creating Model for Openstack-novalxd

### ISSUE THREAD

**Issue by pgupta408** [conjure-up/conjure-up#1175]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju  --- /usr/bin/juju
juju version --- 2.2.3-xenial-amd64

which conjure-up --- /snap/bin/conjure-up

conjure-up --version  -------   conjure-up 2.3.1

which lxc   --- /usr/bin/lxc

lxc config show 
ubuntu@mobilestack:~$ lxc config show
config:
  core.https_address: '[::]'
  storage.zfs_pool_name: lxd



lxc version  -- 2.0..10

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:
ubuntu@mobilestack:~$ sosreport

sosreport (version 3.4)

no valid plugins were enabled

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
openstack-novalxd

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
conjure-up openstack-novalxd

## Additional Information ------  Log file information:

2017-10-01 22:47:09,781 [DEBUG] conjure-up/openstack-novalxd - events.py:53 - Setting Error at conjureup/events.py:147
2017-10-01 22:47:09,788 [ERROR] conjure-up/openstack-novalxd - events.py:159 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py:16> exception=Exception('Unable to create model: ERROR opening API connection: try was stopped\n',)>
Traceback (most recent call last):
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 20, in run
    await self.do_add_model()
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/controllers/bootstrap/common.py", line 33, in do_add_model
    app.provider.credential)
  File "/snap/conjure-up/745/lib/python3.6/site-packages/conjureup/juju.py", line 817, in add_model
    "Unable to create model: {}".format(stderr.decode('utf8')))
Exception: Unable to create model: ERROR opening API connection: try was stopped

2017-10-01 22:47:09,796 [DEBUG] conjure-up/openstack-novalxd - __init__.py:21 - Showing dialog for exception: Unable to create model: ERROR opening API connection: try was stopped

**Comment by kowalczykb** [comment]
Hey pgupta408
Is conjure-up running inside a virtual machine?

**Comment by pgupta408** [comment]
Nope. Not for the error posted on GitHub. 

 

I had separately tried to install conjure-up in VM and that failed for different reasons.

 

 

Thanks

-Praveen

**Comment by guylil** [comment]
I have the exact same problem 

Trying  **Kubernetes-core** on **localhost**
I am running on VM


` File "/snap/conjure-up/815/lib/python3.6/site-packages/conjureup/juju.py", line 807, in add_model
"Unable to create model: {}".format(stderr.decode('utf8')))
Exception: Unable to create model: ERROR opening API connection: try was stopped

... [DEBUG] conjure-up/kubernetes-core - __init__.py:21 - Showing dialog for exception: Unable to create model: ERROR opening API connection: try was stopped  `

**Comment by bmullan** [comment]
I have the exact same problem.

$ sudo snap install conjure-up --classic
$ conjure-up

then I try to install openstack w novalxd and it eventually fails with:

> Oops, there was a problem with your install:
> ───────────────────────────────────────────────────────                                                                                                                                                                      
> Reason:
>   Unable to create model: ERROR opening API connection: try was stopped
> 
> Review log messages at ~/.cache/conjure-up/conjure-up.log If appropriate, 
> please submit a bug here: https://github.com/conjure-up/conjure-up/issues/new

I am using Ubuntu 17.10

**Comment by battlemidget** [comment]
Is it possible to get a tar of `~/.cache/conjure-up` so we can take a look?

**Comment by battlemidget** [comment]
Also output of:

```
snap version
snap list
lxc version
uname -a
```

Also is everyone running this in a VM where the problem is seen? Currently, I can not reproduce this on 17.10 bare metal.

**Comment by bmullan** [comment]
In my attempts to use Conjure-Up I am on an *Ubuntu 17.10* desktop system (*NOT
a VM*), 32GB ram, 1TB SSD, i7 cpu:

*$ uname -a*

pc1 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64
x86_64 x86_64 GNU/Linux

*$ snap version*
snap    2.29.3
snapd   2.29.3
series  16
ubuntu  17.10
kernel  4.13.0-17-generic

*$ snap list*
Name  Version    Rev   Developer  Notes
core  16-2.29.3  3440  canonical  core

*I am following the instructions in the cojure-up.io <http://cojure-up.io>
Manual:*

https://docs.ubuntu.com/conjure-up/2.4.0/en/

*$ /snap/bin/lxd --version*
2.20

*$ /snap/bin/lxc version*
2.20

*$ /snap/bin/lxd init --auto*
LXD has been successfully configured.

*$ /snap/bin/lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true
ipv6.address=none ipv6.nat=false*
Network lxdbr0 created

*$ sudo snap install conjure-up --classic*
conjure-up 2.4.1-20171121.0211 from 'canonical' installed

*$ conjure-up*

<then I make the relevant selections>
I see the conjure-up openstack-novalxd 131x52 screen
waiting
               Juju Model is initializing.  Please wait

               Creating Juju Model.

Nothing else appears on that screen until after approx 18 minutes  I get:











*> Oops, there was a problem with your install:>  >
────────────────────────────────────────────────────────────────────────────
>  > Reason:> Unable to create model: ERROR opening API connection: try was
stopped> > > Review log messages at ~/.cache/conjure-up/conjure-up.log > If
appropriate, please submit a bug here:>
https://github.com/conjure-up/conjure-up/issues/new
<https://github.com/conjure-up/conjure-up/issues/new>  *


The contents of  *.cache/conjure-up* is attached.


Brian

**Comment by battlemidget** [comment]
Attachment doesn't work via email, you'll need to attach it in github

**Comment by bmullan** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1502715/conjure-up.tar.gz)

**Comment by bmullan** [comment]
just added .tar.gz to the Github issue for this...
