### ISSUE TITLE
conjure-down of localhost lxd openstack fails with AttributeError: 'NoneType' object has no attribute 'controller'

### ISSUE THREAD

**Issue by dougparrish** [conjure-up/conjure-up#1182]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [X] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [yes] Is this problem reproducible AFTER `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3-beta1-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.4-alpha1

which lxc
/usr/bin/lxc

lxc config show
config:
  core.https_address: '[::]'

lxc version
2.18

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up-cache.tar.gz](https://github.com/conjure-up/conjure-up/files/1361118/conjure-up-cache.tar.gz)

```

## Sosreport

Please attach a sosreport: 

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?
Openstack-NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
N/A

## Commands ran
After successful conjure-up deployment of Openstack, conjure-down on either controller model or default model fails with same error

Please outline what commands were run to install and execute conjure-up:

## Additional Information

**Comment by andyshinn** [comment]
I have this as well with my MAAS cloud so it may not be entirely related to LXD.
