### ISSUE TITLE
lxd not found (Ubuntu 16.04 vm)

### ISSUE THREAD

**Issue by zthompson2350** [conjure-up/conjure-up#1190]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [NO] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [YES] Is conjure-up running inside a virtual machine?
- [YES] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju (/snap/bin/juju)
juju version (2.2.3-xenial-amd64)

which conjure-up (/snap/bin/conjure-up)
conjure-up --version (conjure-up 2.3.1)

which lxc (/snap/bin/lxc)
lxc config show [as normal user: (you are not a member of the lxd group...) As root: (config: {})]
lxc version (2.18)

cat /etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=Xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.03 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

This command doesn't work. I get an error message saying --same-order cannot be done with -c

## Sosreport

Please attach a sosreport:

You don't support this filetype.

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes (canonical distribution of kubernetes) + Deis Workflow and Helm Components

## What provider (aws, maas, localhost, etc)?
I want to do localhost

### MAAS Users
Which version of MAAS?
N/A but possibly may use this as I noticed it was available if I didn't add in the Components. I'd really prefer to use localhost though.

## Commands ran

This is a log of the commands I issue that lead up to this problem. Note: Nothing else has been done on this virtual machine. Also, the vm has been given 2GB RAM and 25 GB of HDD Space, as per normal download recommendations.

>
> AS SUPER USER:
>
> INSTALL DOCKER:
> apt-get update
> apt-get install apt-transport-https ca-certificates curl software-properties-common
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
> apt-key fingerprint 0EBFCD88
> add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
> apt-get update
> apt-get install docker-ce
> docker run hello-world (verify it worked properly)
> 
> INSTALL KUBERNETES:
> snap install conjure-up --classic
> (REBOOT)
> snap install lxd
> /snap/bin/lxd init --auto
> /snap/bin/lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false
> (BECOME NORMAL USER, CONJURE-UP WILL NOT WORK AS ROOT)
> conjure-up kubernetes
>

**Comment by groundzero2010** [comment]
I'm having the same issue with exact same criteria

**Comment by battlemidget** [comment]
Does `/snap/bin/lxd` exists?

**Comment by battlemidget** [comment]
and are you using bash?

**Comment by zthompson2350** [comment]
Yes, and yes.

**Comment by battlemidget** [comment]
Ok, so snapd installs the proper profile in /etc/profile.d that adds `/snap/bin` do your `$PATH`, my guess is snapd was never previously installed and now that it is you need to log out of all your user sessions and log back in so the new PATH can be read.

From there `which lxd` should point to /snap/bin/lxd (assuming you apt-get remove lxd from the deb archive)

**Comment by aolsux** [comment]
I am having the same (or very similar issue) on a very similar setup:
```
Ubuntu 17.04 as VMWare guest system
lxc version: 2.19
lxc config: {} 
which lx*: /snap/bin/lx*
```
Its almost a clean system, just as above, i have installed docker in advance.

**Comment by aolsux** [comment]
Update: I had a look at my conjure-up.log file and found the following:
```2017-10-24 06:08:54,928 [DEBUG] conjure-up/kubernetes-core - provider.py:371 - LXD query cmd: lxc query --wait -X GET /1.0```
in fact running ` lxc query --wait -X GET /1.0` gives a permission denied error.
I then added myself to the lxd user group (`usermod -a -G lxd <myusername>`)
then i rellogged with `sudo login -f <myusername>` 
now it seems to work.

**Comment by battlemidget** [comment]
Can you attach a tarball of ~/.cache/conjure-up?

**Comment by rahul606** [comment]
I am trying to install OpenStack cloud on Ubuntu 16.04 LTS desktop via conjure-up but facing this error:

> LXD not found, please install lxd and gives me some commands : sudo snap install lxd /snap/bin/lxd init --auto /snap/bin/lxc network create lxdbr1 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false .

Tried everything still having the problem.

**Comment by battlemidget** [comment]
Are you part of the lxd group?

**Comment by mickdelaney** [comment]
aolsux comment worked for me too.

i'm on ubuntu 17.10 desktop as a vmware guest, 
a clean install.

**Comment by battlemidget** [comment]
@aolsux can you attach a tarball of ~/.cache/conjure-up, that should include an *.err file of your pre_deploy failure (or just attaching those *.err and *.out files in the steps/ directory would be enough too)
