### ISSUE TITLE
No environmental variables for unattended canonical-kubernetes localhost install onto bare-metal

### ISSUE THREAD

**Issue by naisanza** [conjure-up/conjure-up#1191]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
admin@k8smaster-conjure:~$ which juju
/snap/bin/juju

admin@k8smaster-conjure:~$ juju version
2.2.3-xenial-amd64

admin@k8smaster-conjure:~$ which conjure-up
/snap/bin/conjure-up

admin@k8smaster-conjure:~$ conjure-up --version
conjure-up 2.3.1

admin@k8smaster-conjure:~$ which lxc
/snap/bin/lxc

admin@k8smaster-conjure:~$ lxc config show
config: {}

admin@k8smaster-conjure:~$ lxc version
2.18

admin@k8smaster-conjure:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1392803/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:
[sosreport-k8smaster-conjure.1191-20171017181645.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/1392812/sosreport-k8smaster-conjure.1191-20171017181645.tar.xz.zip)

The resulting output file can be attached to this issue.
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1392801/conjure-up.tar.gz)

## What Spell was Selected?
`canonical-kubernetes`

## What provider (aws, maas, localhost, etc)?
`localhost`

### MAAS Users
Which version of MAAS?
`n/a
`
## Commands ran

Please outline what commands were run to install and execute conjure-up:

I used this ansible playbook https://github.com/TheShellLand/antsable/blob/master/playbooks/k8s_master_conjure-up.yml

## Additional Information

```bash
admin@k8smaster-conjure:~$ conjure-up --show-env canonical-kubernetes localhost
Available environment variables: 

+-----+---------+--+
| ENV | DEFAULT |  |
+-----+---------+--+
+-----+---------+--+

See https://docs.ubuntu.com/conjure-up/en/usage#customising-headless-mode for
more information on using these variables to further customize your deployment.
```

**Comment by battlemidget** [comment]
This is a regression and we'll get it addressed, thanks for the bug
