### ISSUE TITLE
OpenStack NovaLXD using old version of LXD inside the controller node

### ISSUE THREAD

**Issue by RevoluPowered** [conjure-up/conjure-up#1194]
[no] Is conjure-up running inside a virtual machine?
[yes] Is this problem reproducible AFTER sudo snap refresh conjure-up --edge?

**System info:**
Debian 9 Strech.

**Installed using:**
sudo apt install snapd
sudo snap install lxd
sudo snap install conjure-up --classic --edge
conjure-up

host system lxd/lxc version: 2.18.
controller lxd/lxc verison: 2.10.

Can you please look into this? It's causing the following warning when logging into the controller:
The configuration file contains legacy configuration keys.
Please update your configuration file!

Apparently according to this issue it should go away on reboot, but if you're using a older version of lxd maybe the cause of the issue persisting is the old version installed?

https://github.com/lxc/lxd/issues/3845

If you need any logfiles or anything give me a message here

Kind Regards
Gordon

**Comment by battlemidget** [comment]
This has been addressed with the switch to xenial-pike
