### ISSUE TITLE
conjure-up Unable to bootstrap (cloud type: maas)

### ISSUE THREAD

**Issue by miguelgusils** [conjure-up/conjure-up#1196]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.3-beta2-xenial-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.4-alpha1
which lxc
/usr/bin/lxc
lxc config show
Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init
To start your first container, try: lxc launch ubuntu:16.04

Connection refused; is LXD running?
lxc version
2.0.10
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1408696/conjure-up.tar.gz)

```

## Sosreport
sosreport

sosreport (version 3.4)

no valid plugins were enabled

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?
MAAS version: 2.2.2 (6099-g8751f91-0ubuntu1~16.04.1)
## Commands ran
conjure-up --debug
Please outline what commands were run to install and execute conjure-up:

## Additional Information
here are the resources i'm working with 
<img width="814" alt="screen shot 2017-10-23 at 4 31 11 pm" src="https://user-images.githubusercontent.com/8731076/31911782-cba16b30-b80f-11e7-927b-2a9ca03e4999.png">

**Comment by battlemidget** [comment]
```
Creating Juju controller "conjure-up-maas-797" on maas
Looking for packaged Juju agent version 2.3-beta2 for amd64
No packaged binary found, preparing local Juju agent binary
Launching controller instance(s) on maas...
ERROR failed to bootstrap model: cannot start bootstrap instance: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Error: Conflict Error</title>
  </head>
  <body>
    <h2>
      Conflict error. Try your request again, as it will most likely succeed.
    </h2>
  </body>
</html>
```

Looks like MAAS can't start instances, do these nodes respond to MAAS power on/off capabilities or are you manually powering them on/off?

**Comment by miguelgusils** [comment]
Thanks for the reply..
The nodes do start / stop via maas. However you made me think about the networking 
I changed the non-pxe network settings to auto-assign and it gets further! but fails creating the neutron-gateway
I’ve tried auto-assigned and static? any ideas?

**Comment by battlemidget** [comment]
Make sure you've setup neutron options correctly https://docs.ubuntu.com/conjure-up/2.2.0/en/troubleshoot#openstack
