### ISSUE TITLE
unable to bootstrap (cloud type: ec2) review log messages at ~/.cache/conjure-up/conjure-up.log If appropriate, plese submit a bug here

### ISSUE THREAD

**Issue by krishnna-parihar** [conjure-up/conjure-up#1198]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
lxc config show
lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by iramsey85** [comment]
juju version
2.0.2-xenial-amd64

conjure-up --version
conjure-up 2.3.1

lxc config show
config:
  storage.zfs_pool_name: lxd

lxc version
2.0.10

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

sosreport output:
sosreport (version 3.4)

no valid plugins were enabled

Spell selected: AWS

commands run
conjure-up
followed steps to install Canonical Distro Kubernetes in AWS


[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1427702/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
This is the error you are getting:

```
ERROR You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe. (OptInRequired)
```

This isn't an issue with conjure-up it seems

**Comment by iramsey85** [comment]
hmmm, I just created this AWS account, so thats odd.  thank you for your help.
