### ISSUE TITLE
Conjure-up cannot detect the local installed lxd

### ISSUE THREAD

**Issue by Teeina** [conjure-up/conjure-up#1200]
juju version
2.2.3-xenial-amd64

conjure-up --version
conjure-up 2.3.1

lxc config show
storage.zfs_pool_name:zfslxd
lxc version
2.0.10
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1423909/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:
sosreport (version 3.4)
no valid plugins are enabled

The resulting output file can be attached to this issue.

## What Spell was Selected?
Openstack with Novalxd

## Commands ran
sudo snap install lxd
sudo snap install conjure-up --classic
Please outline what commands were run to install and execute conjure-up:
conjure-up
## Additional Information

I've install lxd using snap. However, when i was direct to the page to configure the openstack on localhost, it shows that cannot find LXD ,pls install with .... commands. How to solve this problem? Can anyone here help?

**Comment by battlemidget** [comment]
Yep we're looking into it
