### ISSUE TITLE
Failure in step  - step-01_get-kubectl

### ISSUE THREAD

**Issue by sha-net** [conjure-up/conjure-up#1201]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju - /usr/local/bin/juju
juju version - 2.2.4-sierra-amd64

which conjure-up - /usr/local/bin/conjure-up
conjure-up --version - conjure-up 2.3.1

which lxc
lxc config show - -bash: lxc: command not found
lxc version

cat /etc/lsb-release
[conjure-up-mac-bug.zip](https://github.com/conjure-up/conjure-up/files/1424541/conjure-up-mac-bug.zip)


```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
None of the data requested has been attached

**Comment by sha-net** [comment]
[conjure-up-mac-bug.zip](https://github.com/conjure-up/conjure-up/files/1424890/conjure-up-mac-bug.zip)
