### ISSUE TITLE
auto bug submission

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#1207]
Have conjure-up collect the necessary data and optionally auto submit to github for debugging errors.

**Comment by magick93** [comment]
@battlemidget - what kind of help do you need for this?

**Comment by battlemidget** [comment]
Hey @magick93 , thanks for reaching out! Basically whenever an exception occurs we want to provide the user with a screen that will allow them to submit a bug via apport. We'd also like to submit that report with things like juju-crashdump and/or sosreport, and a tarball of ~/.cache/conjure-up.

If you're interested in helping me and @johnsca could sync up on a hangout or irc to discuss the specifics.

Thanks again
