### ISSUE TITLE
local user unable to run zfs commands

### ISSUE THREAD

**Issue by naisanza** [conjure-up/conjure-up#1225]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine? No, I've decided to run it for production
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
admin@k8smaster:~$ which juju
/snap/bin/juju

admin@k8smaster:~$ juju version
2.2.3-xenial-amd64

admin@k8smaster:~$ which conjure-up
/snap/bin/conjure-up

admin@k8smaster:~$ conjure-up --version
conjure-up 2.3.1

admin@k8smaster:~$ which lxc
/snap/bin/lxc

admin@k8smaster:~$ lxc config show
config: {}

admin@k8smaster:~$ lxc version
2.18

admin@k8smaster-conjure:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1460542/conjure-up.tar.gz)

## Sosreport
[sosreport-ej.2017-20171110031254.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/1460559/sosreport-ej.2017-20171110031254.tar.xz.zip)

## What Spell was Selected?
`conjure-up kubernetes`

## What provider (aws, maas, localhost, etc)?
`localhost`
### MAAS Users
Which version of MAAS?

## Commands ran
```
conjure-up
```
Please outline what commands were run to install and execute conjure-up:

## Additional Information
I'm using zfs as the location for conjure-up to store everything its creating for portability and ease of recovery.

However, zfs utils require admin privileges by default to run, and conjure-up does not allow you to run as root or with sudo.

**Comment by battlemidget** [comment]
We do have support for actions that require sudo but it's explicit for steps. Could you outline what commands you need to run (or conjure-up to run) so we can see about providing a way for you to enter your sudo password within the ui?

**Comment by naisanza** [comment]
@battlemidget When provisioning the services, it fails, and the logs show that it wasn't able to create the necessary zfs datasets and mount them, because zfs commands require elevated privileges.

`/snap/bin/lxd init` was configured to use an exiting zfs dataset. `conjure-up` could allow to be run with sudo, and take into account to use the user-level account for anything non-root related.
