### ISSUE TITLE
Replace charmhelpers with kv

### ISSUE THREAD

**Issue by johnsca** [conjure-up/conjure-up#1231]
The only thing in charmhelpers we use is the unitdata, making it an unnecessarily heavy-weight dependency.  The [kv](https://pypi.python.org/pypi/kv/) library does what we need and only what we need, so we should switch to that instead.

**Comment by battlemidget** [comment]
https://trello.com/c/98p07unO/143-replace-charm-helpers-with-kv-package-for-state-persistence

**Comment by johnsca** [comment]
Also, charmhelpers doesn't support OS X at all, so this is definitely required.
