### ISSUE TITLE
Remove problems And VPN problem

### ISSUE THREAD

**Issue by TaChao** [conjure-up/conjure-up#1240]
1. How to remove settings and hosts when use ctrl+c to stop program install.Useing conjure-down  without any indication of the problem.
2. When useing openvpn the program will not execute

**Comment by battlemidget** [comment]
> How to remove settings and hosts when use ctrl+c to stop program install.Useing conjure-down without any indication of the problem.

See:

```
juju help controllers
juju help models
```

> When useing openvpn the program will not execute

Not sure I understand your problem with openvpn.
