### ISSUE TITLE
Feature Request: support custom model config

### ISSUE THREAD

**Issue by jamesbeedy** [conjure-up/conjure-up#1241]
## Report
Need ability to configure the VPC prior to the model being created, possibly it would be useful to have the capability to support custom model config in general.

This would be one step in the right direction towards #591 too.

**Comment by jryberg** [comment]
Hi,

I have the exact same issue. I'm having several VPC for different purposes and I need to be able to install everything in a VPC that are NOT default. It would be nice to define vpc-id in a config or pass it as an argument

**Comment by johnsca** [comment]
Current thinking to handle this is a command-line flag to pass in a YAML file containing model config.  If any given config items become used frequently, we can add explicit UI to the interactive mode for those.

Another option would be to add a button to the Spell Config or Application Config screens that takes you to a generic Model Config screen that lets you enter arbitrary model config (perhaps with drop-downs or auto-completes for known config keys).  That would be more work up front, and we'd probably still need to support a CLI arg for headless, but it would be a better experience for interactive users.  Maybe do it in two phases?

**Comment by jryberg** [comment]
Yes, add more "simple" first step using command-line flag and then do UI interactive things if needed.

**Comment by battlemidget** [comment]
This can be done with conjurefile, see https://docs.conjure-up.io/devel/en/conjurefile (search model-config)

It's in edge atm but will be pushing to stable today.
