### ISSUE TITLE
 issue with  kubernetes installation with conjure-up (ubuntu 17.04)

### ISSUE THREAD

**Issue by quantumc3** [conjure-up/conjure-up#1257]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information
Unable to bootstrap (cloud type: ec2)                           
                                                                        
        Review log messages at ~/.cache/conjure-up/conjure-up.log If    
        appropriate, please submit a bug here:                          
        https://github.com/conjure-up/conjure-up/issues/new

**Comment by manuelbcd** [comment]
Hi, working with an Ubuntu 17.04 guest running into a Windows10 host machine.

Output of suggested commands:
```
root@ubuntu:/home/thecult# which juju
root@ubuntu:/home/thecult# juju version
juju: command not found
root@ubuntu:/home/thecult# 
root@ubuntu:/home/thecult# which conjure-up
root@ubuntu:/home/thecult# conjure-up --version
The program 'conjure-up' is currently not installed. You can install it by typing:
apt install conjure-up
root@ubuntu:/home/thecult# 
root@ubuntu:/home/thecult# which lxc
/usr/bin/lxc
root@ubuntu:/home/thecult# /snap/bin/lxc config show
bash: /snap/bin/lxc: No such file or directory
root@ubuntu:/home/thecult# /snap/bin/lxc version
bash: /snap/bin/lxc: No such file or directory
root@ubuntu:/home/thecult# 
root@ubuntu:/home/thecult# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

When I try to generate the attachment (tar cvzf conjure-up.tar.gz ~/.cache/conjure-up)
```
root@ubuntu:/home/thecult# tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
tar: Removing leading `/' from member names
tar: /root/.cache/conjure-up: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

I cannot install conjure-up nor juju.  Any idea?
Thank you

**Comment by battlemidget** [comment]
What's the error when you do `sudo snap install conjure-up --classic`
