### ISSUE TITLE
conjure-up not released as an i686 (32-bit) snap

### ISSUE THREAD

**Issue by matthewpaulthomas** [conjure-up/conjure-up#1263]
On a 32-bit Ubuntu installation:
```
 😌 16:43:15@~> sudo snap install conjure-up --classic
error: snap "conjure-up" not found
 😠 16:43:20@~> snap info conjure-up
argument: "conjure-up"
warning:  not a valid snap
error: no valid snaps given
```

[Discovered while investigating [conjure-up.io#23](https://github.com/canonical-websites/conjure-up.io/issues/23).]

**Comment by battlemidget** [comment]
It's not really a matter of conjure-up not supporting 32bit but the additional packages like kubectl having to match the same architecture
