### ISSUE TITLE
Deploy getting stuck on setting relations

### ISSUE THREAD

**Issue by johnsca** [conjure-up/conjure-up#1264]
Happening intermittently in CI and I think users are seeing this as well.  The deployment gets to adding the relations and then hangs, but the relations do get added and the model comes up.  From CI logs, the controller is sending the deltas for the relations and the watcher task should be notifying the observer created by `Model.add_relation()` but that never seems to get back to unblock the `Model.add_relation()` call.

**Comment by johnsca** [comment]
This has been tracked down to being caused by juju/python-libjuju#191

**Comment by johnsca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [race condition in add_relations](https://trello.com/c/lgv1yteg/151-race-condition-in-addrelations)

**Comment by battlemidget** [comment]
Fixed in master using libjuju 0.7.0
