### ISSUE TITLE
Openstack Autopilot with Landscape

### ISSUE THREAD

**Issue by 51319** [conjure-up/conjure-up#1266]
Is there currently a way to install Ubuntu Openstack with Landscape?

We tested the installation with the two images (16.04.3, 17.10).
We have followed the installation instructions from the following links.

1. https://www.ubuntu.com/download/cloud/build-openstack

we start conjure-up (sudo snap install conjure-up --classic)
Landscape is not displayed under other

2. https://insights.ubuntu.com/2014/11/06/putting-your-openstack-on-autopilot/

**sudo add-apt-repository ppa:cloud-installer/stable**

> Cannot add PPA: 'ppa:~cloud-installer/ubuntu/stable'.
> The team named '~cloud-installer' has no PPA named 'ubuntu/stable'
> Please choose from the following available PPAs:
> * 'simplestreams-testing': Simplestreams Changes Testing

**sudo apt install openstack**

> Package openstack can not be found

can someone help me with this?
The MAAS server is installed and is working. The OpenStack installation with Landscape does not work.

**Comment by battlemidget** [comment]
Autopilot ( OpenStack with Landscape ) is no longer available. Please follow the installation instructions from https://conjure-up.io (`sudo snap install conjure-up --classic`).

There are 2 options available to you for OpenStack, however, neither of these use Landscape currently.

Thanks
