### ISSUE TITLE
Application constraints are ignored

### ISSUE THREAD

**Issue by johnsca** [conjure-up/conjure-up#1272]
Because machines are created prior to deploying the applications (rather than just sending the bundle through for Juju to handle), any constraints on the applications (rather than on the machines) are ignored.

**Comment by token47** [comment]
Yes, just ran into this tight now. I'm trying to deploy Openstack with NovaKVM using machines from a MAAS lab. I have 7 machines tagged metal and some other tagged virtual (and not tagged metal). I want the deploy to get only baremetal machines but it picks both types, randomly.

What I am doing is passing "tags=metal" on all major applications (in this case, nova-compute *3 and neutron-gateway *1), all the other ones are subordinates and can't (don't need to) have the constraint. This is done inside the configuration for each application on the last screen before deploy. I could not find any place to pass tags specific for machine deploying.

The tags get ignored and any machine is picked. I even put "tags=nonsense" there and nothing happened, it picked any 4 machines and happily continued.

I suspect those constraints are not being used at all when deploying machines.

Versions tested:

conjure-up  2.6.4-20181213.2312  1039  stable    canonical✓  classic
juju        2.4.7                6012  stable    canonical✓  classic
MAAS version: 2.3.5 (6511-gf466fdb-0ubuntu1~16.04.1)
