### ISSUE TITLE
Stuck on LXD Configuration Screen

### ISSUE THREAD

**Issue by RobLach** [conjure-up/conjure-up#1275]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [NO ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [NO] Is conjure-up running inside a virtual machine?
- [YES] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju

> /snap/bin/juju

juju version

> 2.2.6-xenial-amd64

which conjure-up

> /snap/bin/conjure-up

conjure-up --version

> conjure-up 2.4.2

which lxc

> /snap/bin/lxc

/snap/bin/lxc config show

> config: {}

/snap/bin/lxc version

> 2.20

cat /etc/lsb-release

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> DISTRIB_CODENAME=xenial
> DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1565549/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

[sosreport-RLACH.whatever-20171217050142.tar.gz](https://github.com/conjure-up/conjure-up/files/1566097/sosreport-RLACH.whatever-20171217050142.tar.gz)

## What Spell was Selected?`

> Canonical Distribution of Kubernetes

## What provider (aws, maas, localhost, etc)?

> Localhost

### MAAS Users
Which version of MAAS?

> N/A

## Commands ran

> sudo snap install conjure-up
> conjure-up

## Additional Information

Tried to install Canonical distro of kubernetes through conjure-up
Reached LXD configuration screen
No matter what I select I cannot move past that screen
Tried pressing enter, moved around with the arrow keys, walked the keyboard except 'q'
tried different storage pool / network bridge configurations 

Stuck here:
<img width="1433" alt="screen shot 2017-12-17 at 04 54 13" src="https://user-images.githubusercontent.com/879610/34078790-e1e62320-e2e6-11e7-87ed-55b1ca33d659.png">

**Comment by battlemidget** [comment]
@RobLach did you try <tab>?

**Comment by RobLach** [comment]
Your prompt is a bit ambiguous but
> ?

Yes

> [space]

Yes

In fact I've walked the entire keyboard with modifiers while avoiding obvious pitfalls (ctrl-z, ctrl-c, etc)

**Comment by RobLach** [comment]
That worked! Feel a bit foolish but it's good. Massive thanks.

**Comment by battlemidget** [comment]
@RobLach np! We are currently reworking the keyboard navigation to be more consistent tab for header, body, footer and arrow keys for input switching. This should be done shortly and we'll have documentation along with it.
