### ISSUE TITLE
                   Unable to bootstrap (cloud type: maas)                                                                                                                     

### ISSUE THREAD

**Issue by peymanfarahani** [conjure-up/conjure-up#1286]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.2.6-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.4.2

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
config: {}
l
/snap/bin/lxc version
2.0.11

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1585596/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport

sosreport (version 3.4)

no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What provider (aws, maas, localhost, etc)?
MAAS
### MAAS Users
yooz
Which version of MAAS?

please help me

**Comment by wroersma** [comment]
I'm also having the same issues and can't seem to figure it out. Am I missing something in the docs?

**Comment by battlemidget** [comment]
It's giving an invalid api key:

```
Error bootstrapping controller: ['ERROR Authorization Error: Invalid API key.']
```

Are you using the correct api key from MAAS?

**Comment by wroersma** [comment]
I'm getting a different issue I will get in the rocket chat and hit you guys up there. I'm now using a different box because I can't read and Intel AMT wasn't supported :) but I'm having storage issues with IPMI 2.0 with a supermicro server getting MAAS to see the storage. So when I figure out if the issue is between the keyboard and mouse I'll let you know in chat. Thanks for the response!
