### ISSUE TITLE
Final screen is easy to quit

### ISSUE THREAD

**Issue by hyperbolic2346** [conjure-up/conjure-up#1293]
It is quite easy to exit the final screen before the deployment is completed.

![easy_quit](https://user-images.githubusercontent.com/3506308/34732191-7e330d3a-f532-11e7-823f-a9f91b406c52.png)

It would be nice to have a confirmation before exiting if post-deploy steps are still running.

**Comment by kwmonroe** [comment]
related to #1291

**Comment by battlemidget** [comment]
@kwmonroe wins im closing this as a duplicate
