### ISSUE TITLE
addon steps dont seem to be executing

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#1295]
I'm working on moving logging and metric steps to addons for cdk:

https://github.com/kwmonroe/spells/tree/feature/cdk-log-metric-addons/canonical-kubernetes/addons

Using that repo as my `--spells-dir` and conjure-up snap from beta:

```
tracking:    beta
installed:   2.5.1-20180106.0201 (919) 91MB classic
refreshed:   2018-01-05 20:45:25 -0600 CST
```

I select CDK, and then *all* the addons.  It doesn't seem like the `./addons/*/steps/*/*` bits are being processed.  I don't see any UI to prompt for input like this:

https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/addons/deis/steps/01_install-workflow/metadata.yaml#L7

Nor is my deployment configured per `after-deploy` like this:

https://github.com/kwmonroe/spells/blob/feature/cdk-log-metric-addons/canonical-kubernetes/addons/graylog/steps/01_install-graylog/after-deploy

When I run through a deployment with my spells repo, the final CDK screen doesn't mention helm, prometheus, deis, or graylog at all, further making me think perhaps the `setResult` bits in `after-deploy` aren't running:

![screen shot 2018-01-10 at 1 57 11 pm](https://user-images.githubusercontent.com/4576822/34798105-5c4cf2b4-f620-11e7-8b7b-b64cf3c1a4aa.png)

**Comment by kwmonroe** [comment]
logs from my ```--cache-dir```:

[cdk-addon-logs.tar.gz](https://github.com/conjure-up/conjure-up/files/1620606/cdk-addon-logs.tar.gz)

I can see the addons were selected:

```
$ cat /tmp/test/conjure-up.log | grep -i addon
2018-01-10 15:16:05,892 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Addon Selected: deis 
2018-01-10 15:16:05,893 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Addon Selected: graylog 
2018-01-10 15:16:05,900 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Addon Selected: helm 
2018-01-10 15:16:05,904 [DEBUG] conjure-up/canonical-kubernetes - telemetry.py:31 - Addon Selected: prometheus 
```

But none of the addon steps showed any signs of life.  I expected to be prompted somewhere for the `additional-input` from the addon metadata as well as post deployment config from `after-deploy`.

**Comment by shrajfr12** [comment]
I am also encountering this issue on mac. I install it via brew. When will the latest commit make it to the release ? Thanks

**Comment by kwmonroe** [comment]
@shrajfr12 i'm not sure exactly which version fixed this, but addons are executing as expected for me on macos with:

```
$ brew info conjure-up
conjure-up: stable 2.5.2 (bottled)
```

**Comment by shrajfr12** [comment]
Yes, I can confirm it started working for me with 2.5.2 on macos  and ubuntu as well approximately couple of weeks back. Thanks @kwmonroe.
