### ISSUE TITLE
Unable to bootstrap (cloud type: localhost)

### ISSUE THREAD

**Issue by arekpawel3** [conjure-up/conjure-up#1299]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems **I can't find this problem**
- [ ] Is conjure-up running inside a virtual machine? **I don't know, how can I check this**
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? **Problem isn't reproducible after this command**

## Please provide the output of the following commands

```
which juju
juju version **2.3.1-xenial-amd64**

which conjure-up
conjure-up --version **conjure-up 2.5.2
**

which lxc
/snap/bin/lxc config show **config: {}
**
/snap/bin/lxc version **2.21
**

cat /etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

Please attach tarball of **~/.cache/conjure-up**:

``` I don't know, how can I do it
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```I don't know, how can I do it

## Sosreport

Please attach a sosreport: what should I do??

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected?
 OpenStack with NovaLXD
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?
I don't know
## Commands ran

Please outline what commands were run to install and execute conjure-up:

sudo snap install conjure-up --classic
conjure-up


## Additional Information
Error:
Oops, there was a problem with your install:  
                                                                              
                                                                              
      Reason:                                                             
        Unable to bootstrap (cloud type: localhost)                     
                                                                        
         Review log messages at                                         
        /home/arek/.cache/conjure-up/conjure-up.log If appropriate,     
        please submit a bug here:                                       
        https://github.com/conjure-up/conjure-up/issues/new

**Comment by johnsca** [comment]
It's difficult to diagnose this issue without the log files, which would contain the error message from the failed bootstrap.  At a minimum, can you provide the contents of `~/.cache/conjure-up/canonical-kubernetes/*-bootstrap.err`
