### ISSUE TITLE
Unable to read add-on selection screen on small windows

### ISSUE THREAD

**Issue by hyperbolic2346** [conjure-up/conjure-up#1305]
If you have a smaller window than the add-on selection screen you can not read the information on the bottom of the screen. This prevents reading the description of Prometheus in this screenshot:

![image](https://user-images.githubusercontent.com/3506308/34991928-5aa9f7e0-fa99-11e7-881c-9d04a53dafca.png)

**Comment by battlemidget** [comment]
I'm not sure what we can do about this except add a ton of padding at the bottom of the addons list

**Comment by johnsca** [comment]
I think the scrolling support I added in #1290 should make this better.  @battlemidget Can you update edge, please?

**Comment by battlemidget** [comment]
It's updated, give that a try and let us know

**Comment by hyperbolic2346** [comment]
Works great, thanks!
