### ISSUE TITLE
Update Juju to 2.3.2

### ISSUE THREAD

**Issue by neclimdul** [conjure-up/conjure-up#1307]
## Report
Juju version is 2.3.1 but yesterday 2.3.2 was released which has a bug fix for datacenters with `-` in the name that I need. Tested on --edge.

```
+ which juju
/snap/bin/juju
+ juju version
2.3.1-artful-amd64
+ which conjure-up
/snap/bin/conjure-up
+ conjure-up --version
conjure-up 2.5.3-rc1
+ which lxc
/snap/bin/lxc
+ /snap/bin/lxc config show
config: {}
+ /snap/bin/lxc version
2.21
+ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```

Note: I know its fast :) just wanted to get it on the radar and so I could track it. Thanks!

**Comment by battlemidget** [comment]
Thanks, will get this pushed out ASAP

**Comment by neclimdul** [comment]
Any idea when this might land. Been watching snap --edge and it updated today but this hasn't made its way in yet.
https://bugs.launchpad.net/juju/+bug/1738993 makes conjure-up unusable to me until this gets in.

**Comment by battlemidget** [comment]
Sorry, that got overlooked somehow, fixed it here https://github.com/conjure-up/conjure-up/commit/39e5a76beb248f20f98d9ceb708ff66349b846e9

Builds are happening now: https://code.launchpad.net/~conjure-up/+snap/conjure-up

Once those are done do a snap refresh from --edge and should be good to go.

**Comment by neclimdul** [comment]
Thanks so much!

**Comment by battlemidget** [comment]
@neclimdul it's in the snap store now, can you give it a go and let me know how things turn out?

**Comment by neclimdul** [comment]
juju looks like the right version locally and machines are starting up! Think that did it, thanks again!
