### ISSUE TITLE
conjure-up doesn't work on a freshly installed ubuntu server system unless apt update && apt upgrade actions are performed

### ISSUE THREAD

**Issue by dshcherb** [conjure-up/conjure-up#1332]
While it might be easy to solve for a long-time Ubuntu user, newcomers who merely download an ubuntu ISO and install conjure-up without running apt update face the following issue:

1. Download an image from http://releases.ubuntu.com/16.04.3/ubuntu-16.04.3-server-amd64.iso;
2. Install it in a virtual machine or on physical hardware;
3. Do not run apt update after installation;
4. sudo snap install conjure-up --classic
5. sudo snap install lxd (optional)
6. sudo lxd init (optional)
7. conjure-up (fails at juju version detection)

ubuntu@maas-2:~$ conjure-up                                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                           
  File "/snap/conjure-up/924/bin/conjure-up", line 11, in <module>                                                                                                                                           
    load_entry_point('conjure-up==2.5.2', 'console_scripts', 'conjure-up')()                                                                                                                                 
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/app.py", line 253, in main                                                                                                                
    utils.juju_version(),                                                                                                                                                                                    
  File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/utils.py", line 272, in juju_version                                                                                                      
    raise Exception("Could not determine Juju version.")                                                                                                                                                     
Exception: Could not determine Juju version.      

See https://asciinema.org/a/2V2mbfunjQMejab2zpJbnPFxb (01:36)

The issue is resolved after `apt update && apt upgrade`.

Could this be fixed or documented for the sake of people who try it out for the first time and fail?

**Comment by battlemidget** [comment]
Odd that it fails there and that `apt upgrade` fixes it, since `juju` is packaged inside the conjure-up snap for first time users. Does `/snap/bin/juju` exists?

**Comment by dshcherb** [comment]
Yes, see the asciinema at 01:36. Or the output below. Also: snapd version is 2.25 in non-daily ISOs and it is not included at all into daily cloud-images https://bugs.launchpad.net/cloud-images/+bug/1750187

```
ubuntu@maas-2:~$ snap list
No snaps are installed yet. Try "snap install hello-world".
ubuntu@maas-2:~$ apt policy snapd
snapd:
  Installed: 2.25
  Candidate: 2.29.4.2
  Version table:
     2.29.4.2 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
 *** 2.25 100
        100 /var/lib/dpkg/status
     2.0.2 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
ubuntu@maas-2:~$ which juju
ubuntu@maas-2:~$ sudo snap install conjure-up --classic
[sudo] password for ubuntu:
2018-02-18T05:33:21-05:00 INFO cannot auto connect core:core-support-plug to core:core-support: (slot auto-connection), existing connection state "core:core-support-plug core:core-support" in the way
conjure-up 2.5.2-20180113.1501 from 'canonical' installed
ubuntu@maas-2:~$ which juju
/snap/bin/juju
ubuntu@maas-2:~$ juju --version
Since Juju 2 is being run for the first time, downloading latest cloud information.
Fetching latest public cloud list...
Updated your list of public clouds with 4 cloud regions deleted:

    deleted cloud region:
        - google/europe-west2
        - google/europe-west3
        - google/southamerica-east1
        - google/us-east4
2.3.1-xenial-amd64
```

**Comment by dshcherb** [comment]
@battlemidget 

And here's a recording of a successful installation with apt upgrade, deb lxd/lxd-client removal + installation from a snap and finally running conjure-up.

https://asciinema.org/a/lxWY3hbzFz59csj7XJiSGjQFm

**Comment by battlemidget** [comment]
Keep an eye on https://github.com/canonical-docs/conjure-up-docs/pull/30 for the fix to this bug.
