### ISSUE TITLE
TypeError on configapps

### ISSUE THREAD

**Issue by johnsca** [conjure-up/conjure-up#1345]
[From Sentry](https://sentry.io/canonical-pj/conjure-up/issues/474098620/):

```
TypeError: __init__() missing 1 required positional argument: 'back_cb'
  File "conjureup/controllers/showsteps/gui.py", line 35, in show_steps
    return self.finish()
  File "conjureup/controllers/showsteps/gui.py", line 52, in finish
    return controllers.use('configapps').render()
  File "conjureup/controllers/configapps/gui.py", line 65, in render
    self.back)
```

**Comment by johnsca** [comment]
The Sentry report claims it's from 2.5.5, but the line numbers in the stack trace don't match up with the code: https://github.com/conjure-up/conjure-up/blob/2.5.5/conjureup/controllers/configapps/gui.py#L65

I don't understand how this error happened.

**Comment by battlemidget** [comment]
I'm doing a bunch of work in configapps (and views) is this from my local testing?

**Comment by johnsca** [comment]
Yep, that seems to be the case.  Please disable Sentry reporting for dev machines.  ;)
