### ISSUE TITLE
"Architect" kubernetes-worker unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by ktsakalozos** [conjure-up/conjure-up#1365]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
# which juju
/snap/bin/juju
# which juju
/snap/bin/juju
# juju version
2.3.4-xenial-amd64
# which conjure-up
/snap/bin/conjure-up
# conjure-up --version
conjure-up 2.5.5
# which lxc
/snap/bin/lxc
#/snap/bin/lxc config show
config:
  core.https_address: '[::]'
# /snap/bin/lxc version
2.21
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

## Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1815561/conjure-up.tar.gz)

## What Spell was Selected?
kubernetes-core

## What provider (aws, maas, localhost, etc)?
aws

## Commands ran
Please outline what commands were run to install and execute conjure-up:

To install: sudo snap refresh conjure-up --edge
To execute: conjure-up --channel=edge

## Additional Information
TypeError: unsupported operand type(s) for /: 'str' and 'int'
When selecting to "Architect" kubernetes-worker

**Comment by johnsca** [comment]
Closed by #1366
