### ISSUE TITLE
No available deployment options Openstack(even cannot deploy localhost)

### ISSUE THREAD

**Issue by zetelight** [conjure-up/conjure-up#1382]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
As I know, no.
- [ ] Is conjure-up running inside a virtual machine?
No. It runs on a real machine with refresh 
installed Ubuntu 16.04 LTS Desktop
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
I tried but it threw some new issues. It would say: "No such file or directory: '/snap/conjure-up/981/spells/ghost/metadata.yaml'
## Please provide the output of the following commands

```
which juju: /snap/bin/juju
juju version: 2.3.3-xenial-amd64

which conjure-up: /snap/bin/conjure-up
conjure-up --version: conjure-up 2.5.5

which lxc: /snap/bin/lxc
/snap/bin/lxc config show: config: {}
/snap/bin/lxc version: 2.21

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1846208/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
sosreport (version 3.5)

no valid plugins were enabled

The resulting output file can be attached to this issue.

## What Spell was Selected?
No idea about what it is. I am totally new for Openstack/Conjure-up

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
No idea about this.

## Commands ran

Please outline what commands were run to install and execute conjure-up:
sudo apt-get update; sudo apt-get upgrade -y; sudo snap install lxd; sudo snap install conjure-up --classic; /snap/bin/lxd init --auto; /snap/bin/lxc network create lxbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false
conjure-up openstack

## Additional Information
I tried to use Openstack with conjure-up so I visited this site: https://www.ubuntu.com/download/cloud/try-openstack Then I followed the instructions of User: bogdan from this site: https://askubuntu.com/questions/955728/conjure-up-unable-to-deploy-openstack-cloud-on-lxd-configuration-ubuntu-16-04l
I also described my issue at there: 
https://askubuntu.com/questions/1018972/no-deployment-options-conjure-up-ubuntu-16-04lts

Overall, my issue is that I cannot see any available deployment options for Openstack. Please help! Any suggestions will be appreciated! Thank you!

**Comment by ToniIltanen** [comment]
You should create an lxd storage for openstack to use, if you are using the OpenStack with NovaLXD spell. run lxd init, and follow the directions and use defaults, but do not use the ipv6, so disable it when the lxd init asks for it. Also, install zfs before running lxd init.

**Comment by ToniIltanen** [comment]
you can follow the tutorial on https://www.youtube.com/watch?v=il3cGo8KG3I

**Comment by zetelight** [comment]
Thank you! After using the mixed solutions from @Trinh and @bogdan, it finally worked.
