### ISSUE TITLE
cannot change profile for the next exec call: No such file or directory

### ISSUE THREAD

**Issue by tvansteenburgh** [conjure-up/conjure-up#1392]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.5-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.6

snap info conjure-up
name:      conjure-up
summary:   Package runtime for conjure-up spells
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
license:   unknown
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
commands:
  - conjure-up.conjure-down
  - conjure-up
  - conjure-up.juju
  - conjure-up.juju-wait
snap-id:   ijQR4HjYlTAmIjELJm5XCpNAqbDZWJ3h
tracking:  edge
refreshed: 2018-04-03T14:28:58-04:00
installed:   2.5.6-20180403.1804 (984) 105MB classic
channels:                              
  stable:    2.5.6-20180404.1904 (986) 105MB classic
  candidate: 2.5.6-20180404.1904 (986) 105MB classic
  beta:      2.5.6-20180404.1904 (986) 105MB classic
  edge:      2.5.6-20180404.1904 (986) 105MB classic

which lxc
/snap/bin/lxc

/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1877676/conjure-up.tar.gz

## What Spell was Selected?
kubernetes-core

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
N/A

## Commands ran
```
conjure-up kubernetes-core localhost local --channel edge --bundle-add frag.yaml
[info] Summoning kubernetes-core to localhost
[info] Creating Juju model conjure-kubernetes-core-411...
[info] Juju model created.
[info] Running Kubernetes Core step: 00_process-providertype before-deploy.
[info] Deploying Applications.
[info] Waiting for deployment to settle.
[error] Some applications failed to start successfully.
[warning] Shutting down
```
```
cat frag.yaml 
services:
  kubernetes-master:
    options:
      channel: 1.10/edge
  kubernetes-worker:
    options:
      channel: 1.10/edge
```

## Additional Information
conjure-up aborts with '[error] Some applications failed to start successfully.' fairly quickly, but the deployment goes on to succeed. The relevant snip from conjure-up.log is at http://paste.ubuntu.com/p/DrS2QGKbcf/ (line 54)

**Comment by johnsca** [comment]
This is [an issue with snapd](https://bugs.launchpad.net/snappy/+bug/1687079) that is apparently related to custom kernels.  At least one person [was able to fix it](https://itsfoss.com/fix-snap-error/) by switching (in their case, downgrading) their kernel.  It also seems that there are [some built-in workarounds](https://github.com/snapcore/snapd/pull/2815) for known cases where it will fail (by forcing devmode confinement).

I would recommend commenting on the snapd issue with details about your kernel.

I'm a little surprised that you were able to get this far in the deployment process, since it seems like it should affect any snap on your system and I would swear there would have been at least one snap call before that point.  Perhaps invoking a couple different snaps (juju, lxd, juju-wait) manually on your system and see if only some of them fail.  It may be that it affects snaps differently based on when they were built and juju-wait needs a rebuild.

**Comment by dudalev** [comment]
I'm hit by a similar issue, but only after rebooting the host machine (i.e. straight after conjuring it works fine) and only inside lxd containers. updating snap inside them didn't help. it looks something like this:
`
ubuntu@juju-9cf1fd-1:~$ sudo snap list
Name        Version    Rev   Tracking  Developer       Notes
core        16-2.32.8  4650  beta      canonical       core
etcd        3.2.9      153   3.2       tvansteenburgh  -
speed-test  1.8.0      21    stable    bartaz          -
ubuntu@juju-9cf1fd-1:~$ speed-test

      Ping ⠼
  Download
    Upload
^Cubuntu@juju-9cf1fd-1:~/snap/bin/etcd.etcdctl --version
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1
ubuntu@juju-9cf1fd-1:~$ uname -a
Linux juju-9cf1fd-1 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@juju-9cf1fd-1:~$ sudo apparmor_status
apparmor module is loaded.
101 profiles are loaded.
58 profiles are in enforce mode.
`
