### ISSUE TITLE
Update website - http://webchat.freenode.net/

### ISSUE THREAD

**Issue by magick93** [conjure-up/conjure-up#1411]
Hello

Your website says:

```
Join the Rocketchat channel if you’re having problems with getting conjure-up running.

Go to ubuntu.rocketchat
```

But when logging into ubuntu.rocketchat there is a message that the room is now in read-only mode, and instead to use http://webchat.freenode.net/

**Comment by battlemidget** [comment]
Yea sorry about that, I think something has happened with the deployment of the conjure-up.io website. It should say to connect via IRC.

**Comment by battlemidget** [comment]
Site updated
