### ISSUE TITLE
 Waiting for kube-system pods to start

### ISSUE THREAD

**Issue by magick93** [conjure-up/conjure-up#1412]
## Report
![screenshot from 2018-04-21 01-07-00](https://user-images.githubusercontent.com/2173213/39052717-11656e18-4501-11e8-9ae2-66cbf5855ca9.png)

- [NO] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [NO] Is conjure-up running inside a virtual machine?
- [NO] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version
2.3.3-artful-amd64

which lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

```
$ juju status
Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-abd  conjure-up-localhost-559  localhost/localhost  2.3.3    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms   40  ubuntu  
etcd                   3.2.9    active       3  etcd                   jujucharms   80  ubuntu  
flannel                0.9.1    active       2  flannel                jujucharms   56  ubuntu  
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   58  ubuntu  exposed
kubernetes-master      1.10.0   waiting      1  kubernetes-master      jujucharms  104  ubuntu  
kubernetes-worker      1.10.0   active       1  kubernetes-worker      jujucharms  118  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   0        10.44.87.80                     Certificate Authority connected.
etcd/0*                   active    idle   1        10.44.87.87     2379/tcp        Healthy with 3 known peers
etcd/1                    active    idle   2        10.44.87.205    2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   3        10.44.87.38     2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   4        10.44.87.174    443/tcp         Loadbalancer ready.
kubernetes-master/0*      waiting   idle   5        10.44.87.2      6443/tcp        Waiting for kube-system pods to start
  flannel/0*              active    idle            10.44.87.2                      Flannel subnet 10.1.70.1/24
kubernetes-worker/0*      active    idle   6        10.44.87.162    80/tcp,443/tcp  Kubernetes worker running.
  flannel/1               active    idle            10.44.87.162                    Flannel subnet 10.1.88.1/24

Machine  State    DNS           Inst id        Series  AZ  Message
0        started  10.44.87.80   juju-d5c4fd-0  xenial      Running
1        started  10.44.87.87   juju-d5c4fd-1  xenial      Running
2        started  10.44.87.205  juju-d5c4fd-2  xenial      Running
3        started  10.44.87.38   juju-d5c4fd-3  xenial      Running
4        started  10.44.87.174  juju-d5c4fd-4  xenial      Running
5        started  10.44.87.2    juju-d5c4fd-5  xenial      Running
6        started  10.44.87.162  juju-d5c4fd-6  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular      
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      
etcd:cluster                         etcd:cluster                         etcd              peer         
etcd:db                              flannel:etcd                         etcd              regular      
etcd:db                              kubernetes-master:etcd               etcd              regular      
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate  
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate  

```

**Comment by Cynerva** [comment]
This is a common symptom with a wide variety of causes. Could you run cdk-field-agent and attach the resulting archive so we can see which pods are failing to start and why? https://github.com/juju-solutions/cdk-field-agent

**Comment by Cynerva** [comment]
Ah, scratch that, I see now that you're running the canonical-kubernetes-nvidia spell on lxd/localhost. That almost certainly isn't going to work since the spell currently has AWS-specific constraints, and LXD brings its own set of challenges for working with GPU hardware that we haven't had a chance to work through.

Best we can do for now is update the canonical-kubernetes-nvidia spell to blacklist non-AWS clouds, I think.

**Comment by magick93** [comment]
> the spell currently has AWS-specific constraints

I have removed the ` instance-type=p2.xlarge `. Are there any other AWS specific constraints?

> LXD brings its own set of challenges for working with GPU hardware
Ok. This is interesting. 

Thanks

**Comment by udhaya10** [comment]
Same problem exist for _canonical-kubernetes_ ( no GPU )

Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-289  conjure-up-localhost-276  localhost/localhost  2.3.7    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
apache2                         unknown      1  apache2                jujucharms   24  ubuntu  exposed
easyrsa                3.0.1    active       1  easyrsa                jujucharms   40  ubuntu
elasticsearch                   active       1  elasticsearch          jujucharms   27  ubuntu
etcd                   3.2.9    active       1  etcd                   jujucharms   80  ubuntu
filebeat               5.6.9    active       2  filebeat               jujucharms    9  ubuntu
flannel                0.9.1    active       2  flannel                jujucharms   56  ubuntu
grafana                         active       1  grafana                jujucharms   11  ubuntu  exposed
graylog                2.3.1-1  active       1  graylog                jujucharms   15  ubuntu
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   58  ubuntu  exposed
kubernetes-master      1.10.2   waiting      1  kubernetes-master      jujucharms  104  ubuntu
kubernetes-worker      1.10.2   active       1  kubernetes-worker      jujucharms  118  ubuntu  exposed
mongodb                         unknown      1  mongodb                jujucharms   47  ubuntu
prometheus                      active       1  prometheus             jujucharms    6  ubuntu
telegraf                        active       2  telegraf               jujucharms   13  ubuntu

Unit                      Workload  Agent  Machine  Public address  Ports                                    Message
apache2/0*                unknown   idle   0        10.86.26.80
easyrsa/0*                active    idle   1        10.86.26.243                                             Certificate Authority connected.
elasticsearch/0*          active    idle   2        10.86.26.159    9200/tcp                                 Ready
etcd/0*                   active    idle   3        10.86.26.113    2379/tcp                                 Healthy with 1 known peer
grafana/0*                active    idle   4        10.86.26.15     3000/tcp                                 Started grafana-server
graylog/0*                active    idle   5        10.86.26.253    5044/tcp                                 Ready with: filebeat, elasticsearch, mongodb
kubeapi-load-balancer/0*  active    idle   6        10.86.26.7      443/tcp                                  Loadbalancer ready.
kubernetes-master/0*      waiting   idle   7        10.86.26.104    6443/tcp                                 Waiting for kube-system pods to start
  filebeat/0*             active    idle            10.86.26.104                                             Filebeat ready.
  flannel/0*              active    idle            10.86.26.104                                             Flannel subnet 10.1.11.1/24
  telegraf/0*             active    idle            10.86.26.104    9103/tcp                                 Monitoring kubernetes-master/0
kubernetes-worker/0*      active    idle   8        10.86.26.220    80/tcp,443/tcp                           Kubernetes worker running.
  filebeat/1              active    idle            10.86.26.220                                             Filebeat ready.
  flannel/1               active    idle            10.86.26.220                                             Flannel subnet 10.1.60.1/24
  telegraf/1              active    idle            10.86.26.220    9103/tcp                                 Monitoring kubernetes-worker/0
mongodb/0*                unknown   idle   9        10.86.26.166    27017/tcp,27019/tcp,27021/tcp,28017/tcp
prometheus/0*             active    idle   10       10.86.26.25     9090/tcp,12321/tcp                       Ready

Machine  State    DNS           Inst id         Series  AZ  Message
0        started  10.86.26.80   juju-352297-0   xenial      Running
1        started  10.86.26.243  juju-352297-1   xenial      Running
2        started  10.86.26.159  juju-352297-2   xenial      Running
3        started  10.86.26.113  juju-352297-3   xenial      Running
4        started  10.86.26.15   juju-352297-4   xenial      Running
5        started  10.86.26.253  juju-352297-5   xenial      Running
6        started  10.86.26.7    juju-352297-6   xenial      Running
7        started  10.86.26.104  juju-352297-7   xenial      Running
8        started  10.86.26.220  juju-352297-8   xenial      Running
9        started  10.86.26.166  juju-352297-9   xenial      Running
10       started  10.86.26.25   juju-352297-10  xenial      Running

Relation provider                    Requirer                             Interface            Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates     regular
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates     regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates     regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates     regular
elasticsearch:client                 graylog:elasticsearch                elasticsearch        regular
elasticsearch:peer                   elasticsearch:peer                   http                 peer
etcd:cluster                         etcd:cluster                         etcd                 peer
etcd:db                              flannel:etcd                         etcd                 regular
etcd:db                              kubernetes-master:etcd               etcd                 regular
graylog:beats                        filebeat:logstash                    elastic-beats        regular
graylog:website                      apache2:reverseproxy                 http                 regular
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address       regular
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http                 regular

**Comment by battlemidget** [comment]
dup of https://github.com/conjure-up/conjure-up/issues/1430
