### ISSUE TITLE
NTP not supported in containers: please configure on host

### ISSUE THREAD

**Issue by Manhim** [conjure-up/conjure-up#1417]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.7-bionic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.6

which lxc
/usr/bin/lxc

/usr/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1945124/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sosreport (version 3.5)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?

localhost

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```
sudo apt update && sudo apt dist-upgrade
sudo apt install ntp
sudo apt install zfsutils-linux
lxd init
  "none" at ipv6
  everything else is default
sudo snap install conjure-up --classic --edge
conjure-up
  OpenStack with NovaLXD
  localhost
```

## Additional Information

It says the `NTP not supported in containers: please configure on host` message on both `ntp/0` and `ntp/1`, `conjure-up` hangs indefinitely because the status is `blocked` on both. If I quit `conjure-up`, the installation seems to work. Although I haven't had a lot of time to put it to the test so far.

The reason that I install `ntp` on the host machine is because I've had this issue previously. So I reinstalled Ubuntu 18.04 with a fresh daily and retried. I've looked at the spell and it seems to simply block as soon as it is being ran from a container, and I don't really know how to fix this issue.

**Comment by battlemidget** [comment]
Ill talk to the Openstack guys to see if they have an idea
