### ISSUE TITLE
kubernetes-master/0* waits forever - Waiting for kube-system pods to start 

### ISSUE THREAD

**Issue by einKunze** [conjure-up/conjure-up#1425]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems

no

- [ ] Is conjure-up running inside a virtual machine?

no

- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

yes

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.7-xenial-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.6

which lxc
/snap/bin/lxc

/snap/bin/lxc config show
config:
  core.https_address: '[::]:8443'

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1964910/conjure-up.tar.gz)

## What Spell was Selected?

Canonical Distribution of Kubernetes

## What provider (aws, maas, localhost, etc)?

localhost

## Commands ran

conjure-up canonical-kubernetes

Please outline what commands were run to install and execute conjure-up:

snap install conjure-up

## Additional Information

The kube master waits forever with the message: _Waiting for kube-system pods to start_

```
juju status
Model                         Controller                Cloud/Region         Version  SLA
conjure-canonical-kubern-d12  conjure-up-localhost-72e  localhost/localhost  2.3.7    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                jujucharms   40  ubuntu  
etcd                   3.2.9    active       3  etcd                   jujucharms   80  ubuntu  
flannel                0.9.1    active       4  flannel                jujucharms   56  ubuntu  
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   58  ubuntu  exposed
kubernetes-master      1.10.0   waiting      1  kubernetes-master      jujucharms  104  ubuntu  
kubernetes-worker      1.10.0   active       3  kubernetes-worker      jujucharms  118  ubuntu  exposed

Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   0        10.139.12.18                    Certificate Authority connected.
etcd/0                    active    idle   1        10.139.12.184   2379/tcp        Healthy with 3 known peers
etcd/1*                   active    idle   2        10.139.12.166   2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   3        10.139.12.46    2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   4        10.139.12.47    443/tcp         Loadbalancer ready.
kubernetes-master/0*      waiting   idle   5        10.139.12.3     6443/tcp        Waiting for kube-system pods to start
  flannel/0*              active    idle            10.139.12.3                     Flannel subnet 10.1.13.1/24
kubernetes-worker/0*      active    idle   6        10.139.12.10    80/tcp,443/tcp  Kubernetes worker running.
  flannel/1               active    idle            10.139.12.10                    Flannel subnet 10.1.47.1/24
kubernetes-worker/1       active    idle   7        10.139.12.187   80/tcp,443/tcp  Kubernetes worker running.
  flannel/3               active    idle            10.139.12.187                   Flannel subnet 10.1.43.1/24
kubernetes-worker/2       active    idle   8        10.139.12.61    80/tcp,443/tcp  Kubernetes worker running.
  flannel/2               active    idle            10.139.12.61                    Flannel subnet 10.1.61.1/24

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.139.12.18   juju-b11bb2-0  xenial      Running
1        started  10.139.12.184  juju-b11bb2-1  xenial      Running
2        started  10.139.12.166  juju-b11bb2-2  xenial      Running
3        started  10.139.12.46   juju-b11bb2-3  xenial      Running
4        started  10.139.12.47   juju-b11bb2-4  xenial      Running
5        started  10.139.12.3    juju-b11bb2-5  xenial      Running
6        started  10.139.12.10   juju-b11bb2-6  xenial      Running
7        started  10.139.12.187  juju-b11bb2-7  xenial      Running
8        started  10.139.12.61   juju-b11bb2-8  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular      
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      
etcd:cluster                         etcd:cluster                         etcd              peer         
etcd:db                              flannel:etcd                         etcd              regular      
etcd:db                              kubernetes-master:etcd               etcd              regular      
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate  
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate 
```

Please let me know if you need any additional information.

**Comment by tony-haibo-zhu** [comment]
But is there something for walking around this ?

**Comment by ZuSe** [comment]
I can confirm the same problem with my deployment on Ubuntu 18.04

> ~$ which juju
> /snap/bin/juju

> juju version
> 2.4.0-bionic-amd64

```
lxc version
Client version: 3.0.1
Server version: 3.0.1
```

> juju status
> Model                        Controller                Cloud/Region         Version  SLA          Timestamp
> conjure-kubernetes-core-c55  conjure-up-localhost-0e7  localhost/localhost  2.4.0    unsupported  11:12:54+02:00
> 
> App                Version        Status   Scale  Charm              Store       Rev  OS      Notes
> canal              0.10.0/2.6.10  active       2  canal              jujucharms   45  ubuntu  
> easyrsa            3.0.1          active       1  easyrsa            jujucharms   50  ubuntu  
> etcd               3.2.9          active       1  etcd               jujucharms   96  ubuntu  
> kubernetes-e2e     1.11.1         active       1  kubernetes-e2e     jujucharms   75  ubuntu  
> kubernetes-master  1.11.1         waiting      1  kubernetes-master  jujucharms  122  ubuntu  exposed
> kubernetes-worker  1.11.1         active       1  kubernetes-worker  jujucharms  138  ubuntu  exposed
> 
> Unit                  Workload  Agent  Machine  Public address                         Ports           Message
> easyrsa/0*            active    idle   0/lxd/0  10.0.169.71                                            Certificate Authority connected.
> etcd/0*               active    idle   0        2a02:8106:22e:cf00:216:3eff:fe63:4679  2379/tcp        Healthy with 1 known peer
> kubernetes-e2e/0*     active    idle   2        2a02:8106:22e:cf00:216:3eff:fe4d:45d6                  Ready to test.
> kubernetes-master/0*  waiting   idle   0        2a02:8106:22e:cf00:216:3eff:fe63:4679  6443/tcp        Waiting for kube-system pods to start
>   canal/0*            active    idle            2a02:8106:22e:cf00:216:3eff:fe63:4679                  Flannel subnet 10.1.50.1/24
> kubernetes-worker/0*  active    idle   1        2a02:8106:22e:cf00:216:3eff:fe96:a1f6  80/tcp,443/tcp  Kubernetes worker running.
>   canal/1             active    idle            2a02:8106:22e:cf00:216:3eff:fe96:a1f6                  Flannel subnet 10.1.73.1/24
> 
> Entity  Meter status  Message
> model   amber         user verification pending  
> 
> Machine  State    DNS                                    Inst id              Series  AZ  Message
> 0        started  2a02:8106:22e:cf00:216:3eff:fe63:4679  juju-e1230a-0        xenial      Running
> 0/lxd/0  started  10.0.169.71                            juju-e1230a-0-lxd-0  xenial      Container started
> 1        started  2a02:8106:22e:cf00:216:3eff:fe96:a1f6  juju-e1230a-1        xenial      Running
> 2        started  2a02:8106:22e:cf00:216:3eff:fe4d:45d6  juju-e1230a-2        xenial      Running

I tried to deploy kubernetes-core (not the Canonical distribution)

Hopefully this information helps to find the source of the problem

**Comment by battlemidget** [comment]
https://docs.conjure-up.io/stable/en/spellbooks/kubernetes#limitations

**Comment by ZuSe** [comment]
I tried that and used dir instead, still the same problem.

**Comment by battlemidget** [comment]
Make sure `lxc storage list` shows the dir in use. conjure-up (juju underneath) may still be referencing the incorrect storage.

**Comment by babarzahoor** [comment]
juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" kubernetes-worker proxy-extra-args="proxy-mode=userspace" fixed issue for me .
