### ISSUE TITLE
Doesn't support OpenStack Queens on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by chanjarster** [conjure-up/conjure-up#1428]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.3.3-bionic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.5.6

which lxc
/usr/bin/lxc

/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?

localhost

### MAAS Users

Which version of MAAS?

Doesn't use MAAS

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```conjure-up```

## Additional Information

conjure-up only supports OpenStack Pike on Ubuntu 16.04 LTS:

<img width="1355" alt="wx20180510-130319 2x" src="https://user-images.githubusercontent.com/612413/39853082-a6e2edc0-5452-11e8-935c-6464e106f2c0.png">

But:

1. this [page][1] says 18.04 LTS supports OpenStack Queens.
1. [OpenStack Juju charm][2] also says it deploys OpenStack Queens.
1. this [page][3] shows that 18.04 LTS will support OpenStack Queens until 2023.

[1]: https://insights.ubuntu.com/2018/04/27/whats-new-in-ubuntu-18-04-and-openstack-queens?_ga=2.23014075.1006626274.1525927688-1163436623.1522733529
[2]: https://jujucharms.com/openstack-base/
[3]: https://www.ubuntu.com/info/release-end-of-life

**Comment by blhende** [comment]
Anyone find a resolution to this- it appears 18.04 deploys the 16.04 version of conjure up.
Also, the "Architect" option is missing in the next step- can't modify the type of services deployed. 

![screenshot from 2018-07-10 08-11-48](https://user-images.githubusercontent.com/8172511/42509137-04000d58-8419-11e8-9069-28b8712f0045.png)

**Comment by clayscode** [comment]
Any updates on this? Was trying to deploy Openstack using conjure-up earlier today and ran into the same issue. Would be pretty frustrating if I have to just erase everything and install Ubuntu 16.04

**Comment by battlemidget** [comment]
We deploy Queens as seen in this spell bundle https://github.com/conjure-up/spells/blob/master/openstack-novalxd/bundle.yaml

We just need to update the description
