### ISSUE TITLE
Conjure-up fails while "Juju Model is initializing"

### ISSUE THREAD

**Issue by navandres** [conjure-up/conjure-up#1429]
## Report
I was almost able to go through, but the Master kubernetes stayed there waiting and I had to stop it.
Then I uninstall everything and reinstall everything again following the guides below, but now it never even go through the initialization.

It always fail with the following message:
[Errno 110] Connect call failed ('10.35.150.155', 17070)

## Please provide the output of the following commands
/snap/bin/juju
2.3.3-xenial-amd64
/snap/bin/conjure-up
conjure-up 2.5.6
/snap/bin/lxc
config: {}
Client version: 3.0.0
Server version: 3.0.0
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Canonical Distribution of Kubernetes

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran
sudo snap install lxd
sudo usermod -a -G lxd $USER
newgrp lxd
lxc network create lxdbr0 ipv4.address=auto ipv4.nat=true ipv6.address=none ipv6.nat=false
sudo snap install conjure-up --classic
conjure-up

Please outline what commands were run to install and execute conjure-up:

## Additional Information
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1992952/conjure-up.tar.gz)

**Comment by navandres** [comment]
Folks! I found the problem. There was a wrong IP in juju's controllers yaml configuration file and that was stopping the whole process of bootstraping and initializing.

Thanks for you time anyways!!

**Comment by dimthe** [comment]
care to explain where this yaml is please?

**Comment by battlemidget** [comment]
It's in `~/.local/share/juju/controllers.yaml`

**Comment by dimthe** [comment]
mine is failing with this error

TimeoutError(110, "Connect call failed ('10.188.65.18', 17070)")

and this endpoint is in the controllers.yaml 

to what ip would this need to be changed to ? based on what ?
