### ISSUE TITLE
Unable to bootstrap (cloud type: maas)

### ISSUE THREAD

**Issue by jasonrgann** [conjure-up/conjure-up#1433]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
linq3@maas:~$ which juju
/snap/bin/juju

linq3@maas:~$ which conjure-up
/snap/bin/conjure-up

linq3@maas:~$ which lxc
/snap/bin/lxc
sudo /snap/bin/lxc config show
config: {}
linq3@maas:~$ sudo /snap/bin/lxc version
Client version: 3.0.0
Server version: 3.0.0
linq3@maas:~$ /snap/bin/lxc version
Client version: 3.0.0
Server version: unreachable

linq3@maas:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2010651/conjure-up.tar.gz)


## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport

[sosreport-jgann.1-20180516160707.tar.zip](https://github.com/conjure-up/conjure-up/files/2010725/sosreport-jgann.1-20180516160707.tar.zip)

```

The resulting output file can be attached to this issue.


## What Spell was Selected?
conjure-up

## What provider (aws, maas, localhost, etc)?
maas

### MAAS Users
linq3

Which version of MAAS?
MAAS version: 2.4.0~beta2 (6865-gec43e47e6-0ubuntu1)

## Commands ran
conjure-up

Please outline what commands were run to install and execute conjure-up:
https://www.ubuntu.com/download/cloud/build-openstack
sudo snap install conjure-up --classic
conjure-up

## Additional Information
Seems like this is supposed to be easy but I have been fighting this for weeks... Help...

**Comment by jasonrgann** [comment]
Hello,

I just gave it a shot and I get the same error...  see attache d picture. I know this is not for MAAS help.. Where can I get help for MAAS? conjure-up is supposed to make this easy. Even though this is not directly related to conjure-up it will still impact the product if people can't use it.  Would love to get this working....


![maas 2018-05-17_12-01-03](https://user-images.githubusercontent.com/39348682/40189341-32ec06ea-59ca-11e8-99ee-d27a02eec4f6.jpg)

Thanks,

JRG

**Comment by battlemidget** [comment]
For maas help, https://askubuntu.com/questions/tagged/maas and http://webchat.freenode.net/?channels=maas
