### ISSUE TITLE
Can we use conjure-up for NovaLXD or NovaKVM without internet ?

### ISSUE THREAD

**Issue by Sideris35** [conjure-up/conjure-up#1446]
Hi,

I must install an openstack architecture without internet on ubuntu 16.04 with conjure-up.
I try conjure up NovaLXD on bare-metal with internet and it's works !

But juju use charms from internet and conjure deploy spell
NovaLXD or NovaKVM can be deploy without internet?

Thanks 
Best regards

**Comment by battlemidget** [comment]
Not at this time.
