### ISSUE TITLE
Service Resource's External LB endpoint not working

### ISSUE THREAD

**Issue by publiccloudeng** [conjure-up/conjure-up#1468]
## Report
Hi,
When I try to deploy my app (using DockerHub) and expose it externally via a service resource, the service spins up giving me an external endpoint, however, the LB link doesn't work.
Would anyone know what the issue is in this case?

Commands run:
`$ kubectl run hello-world--image=index.docker.io/xxx/hello-world --port 8080`
`$ kubectl expose deployment hello-world --type=LoadBalancer --port 80 --target-port 8080`

URGENT:
Further, is there a way for me to use an older version of conjure-up? I need a solution to this asap if possible.
Thanks

## Please provide the output of the following commands

```
which juju
juju version
2.3.8-xenial-amd64

which conjure-up
conjure-up --version
conjure-up 2.5.8

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes-core

## What provider (aws, maas, localhost, etc)?
aws

**Comment by battlemidget** [comment]
@johnsca @Cynerva any idea on this? This is 2.5.8 using aws charm

**Comment by battlemidget** [comment]
@publiccloudeng Also, can you run https://github.com/juju-solutions/cdk-field-agent and attach that to this issue?

**Comment by johnsca** [comment]
You said that you get a LB link in the External Address field, so it sounds like it's working from the perspective of conjure-up and kubernetes.  If the link that AWS is giving to Kubernetes doesn't work for you, I can only imagine that it has something to do with the AWS account settings, but I've never encountered that before.  Can you give more info on the link that is generated (perhaps redact the IP address portion) and the error you see when trying to visit it?

Regrading installing an old version of conjure-up, the snap store really isn't designed to allow installing old versions, and even if you could, it would auto-update soon after anyway.  If you really need to get a specific version, you could build the snap yourself from a specific revision of the conjure-up repo and the snapcraft snap (`snapcraft cleanbuild` from within the conjure-up repo), but you'll also need to pin the spells repo reference (by modifying the `snap/snapcraft.yaml` file) to a revision that works with that version.  Once built, you would install it with `snap install --dangerous --classic ./<filename.snap>`.  All in all, it is not really recommended.
