### ISSUE TITLE
Error setting up microk8s on Azure

### ISSUE THREAD

**Issue by rotev** [conjure-up/conjure-up#1478]
## Report

I tried to setup a single machine Kubernetes on Azure using conjure-up and received the following error message:

```
'BundleApplicationFragment' object has no attribute 'fragment'
```

What did work was to set up a big cluster using the "Canonical Distribution of Kubernetes" spell, and to set up a 2 machine cluster with the "Kubernetes Core" spell.

I'm using MacOS, not on a virtual machine. I couldn't find any instructions to set up conjure-up edge on mac.

## Please provide the output of the following commands

```
➜  which juju
/usr/local/bin/juju
➜  juju version
2.3.8-highsierra-amd64
➜  which conjure-up
/usr/local/bin/conjure-up
➜  conjure-up --version
conjure-up 2.5.7
➜  which lxc
lxc not found
➜  cat /etc/lsb-release
cat: /etc/lsb-release: No such file or directory
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2130847/conjure-up.tar.gz)

## What Spell was Selected?
microk8s

## What provider (aws, maas, localhost, etc)?
Azure

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```
conjure-up kubernetes
```

<img width="1271" alt="screenshot 2018-06-24 16 28 49" src="https://user-images.githubusercontent.com/562267/41820053-d41c59ec-77cb-11e8-882a-c73f880953ec.png">
<img width="1276" alt="screenshot 2018-06-24 16 29 05" src="https://user-images.githubusercontent.com/562267/41820054-d435bb6c-77cb-11e8-8d22-c032dbf6ad51.png">
<img width="1279" alt="screenshot 2018-06-24 16 29 19" src="https://user-images.githubusercontent.com/562267/41820055-d44d2892-77cb-11e8-9494-568e3eac6520.png">
<img width="1275" alt="screenshot 2018-06-24 16 29 27" src="https://user-images.githubusercontent.com/562267/41820056-d4761b3a-77cb-11e8-974a-63a411c66089.png">

**Comment by battlemidget** [comment]
This is expecting a juju bundle where snap microk8s is not available on macos
