### ISSUE TITLE
Unable to find a storage pool for LXD

### ISSUE THREAD

**Issue by hnviradiya** [conjure-up/conjure-up#1483]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ No ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ No ] Is conjure-up running inside a virtual machine?
- [ No ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
2.3.8-bionic-amd64

which conjure-up
conjure-up 2.5.7

which lxc
config: {}
Client version: 3.0.1
Server version: 3.0.1

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2146148/conjure-up.tar.gz)

```
tar: Removing leading `/' from member names
/home/krishna/.cache/conjure-up/
/home/krishna/.cache/conjure-up/.state.db
/home/krishna/.cache/conjure-up/openstack-novalxd/
/home/krishna/.cache/conjure-up/openstack-novalxd/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/tests/
/home/krishna/.cache/conjure-up/openstack-novalxd/tests/verify
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/01_glance/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/01_glance/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/01_glance/glance.sh
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/01_glance/after-deploy
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/novarc
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/02_keypair/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/02_keypair/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/02_keypair/after-deploy
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/02_keypair/keypair.sh
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/00_process-providertype/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/00_process-providertype/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/00_process-providertype/before-deploy
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/neutron.sh
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/neutron-tenant-net
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/neutron-ext-net
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/03_neutron/after-deploy
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/04_horizon/
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/04_horizon/metadata.yaml
/home/krishna/.cache/conjure-up/openstack-novalxd/steps/04_horizon/after-deploy
/home/krishna/.cache/conjure-up/openstack-novalxd/bundle.yaml
/home/krishna/.cache/conjure-up/conjure-up.log
```

## Sosreport

Please attach a sosreport:

```
sosreport (version 3.5)

no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What Spell was Selected?

OpenStack with NovaLXD

## What provider (aws, maas, localhost, etc)?

localhost

### MAAS Users
Which version of MAAS?

## Commands ran

sudo snap install conjure-up --classic
conjure-up

## Additional Information

tried with beta version and edge version.

in edge version, it gave me this error on selection of spell -> 'set' object does not support indexing (So this might be another issue to solve)

this error comes when i select localhost.

lxc storage list
```
+---------+-------------+--------+------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |               SOURCE               | USED BY |
+---------+-------------+--------+------------------------------------+---------+
| default |             z| dir    | /var/lib/lxd/storage-pools/default | 1       |
+---------+-------------+--------+------------------------------------+---------+
```

**Comment by battlemidget** [comment]
The tarball is empty, can you try to reupload

**Comment by hnviradiya** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2146193/conjure-up.tar.gz)

**Comment by hnviradiya** [comment]
My bad. i had created. **sudo lxd init** instead of **sudo /snap/bin/lxd init**

**Comment by sreeve29** [comment]
I have the same/similar issue.
Is conjure-up not supported on a VM?
I get this error when selecting "localhost" for "Where would you like to deplay":

_**Unable to find a storage pool for LXD.**_

I already ran 'lxd init'.  What lxd commands should I run to show that it is (or isn't) configured properly?

sreeve@u18server:~$ conjure-up
sreeve@u18server:~$ lxd --version
3.0.1
sreeve@u18server:~$ conjure-up --version
conjure-up 2.6.1
sreeve@u18server:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Any help is greatly appreciated.

**Comment by battlemidget** [comment]
https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd
