### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by ilovezfs** [conjure-up/conjure-up#1484]
We're working on the Python 3.7 PR for Homebrew and it looks like conjure-up is broken because `async` became a keyword but there's a conflicting conjureup.async module. There are also some issues with the dependencies (specifically juju needs a newer pyyaml and websockets).

CC @battlemidget 

It would be great if Python 3.7 support could be added ASAP here as this is blocking the 3.7 upgrade for everyone unless we're willing to break conjure-up.

**Comment by battlemidget** [comment]
Hey, I'll get working on this right away

Thanks for the heads up

**Comment by battlemidget** [comment]
cc @johnsca

**Comment by ilovezfs** [comment]
Thanks very much @battlemidget!

**Comment by ilovezfs** [comment]
@battlemidget btw in case it helps,

https://files.pythonhosted.org/packages/bd/da/0a49c1a31c60634b93fd1376b3b7966c4f81f2da8263f389cad5b6bbd6e8/PyYAML-4.2b1.tar.gz

is a python 3.7 friendly version until an actual 4.2 release is out (possibly today).

**Comment by battlemidget** [comment]
Just a quick update, we've updated the code to not rely on the user supplied async module. We are now going through getting testing to work on 3.7 via travis. As you mentioned we are updating libjuju to pull in a later websockets and also using the beta release of pyyaml.

Soon as I can get travis passing I'll spin a new release.

Thanks for your patience!
Adam

**Comment by ilovezfs** [comment]
Awesome! Thanks for the hard work @battlemidget

**Comment by battlemidget** [comment]
Working on getting https://github.com/juju/python-libjuju/pull/251 passing, then on to conjure-up testing.

**Comment by battlemidget** [comment]
Issues with paramiko and websockets:

websockets: https://github.com/aaugustin/websockets/issues/431

**Comment by ilovezfs** [comment]
@battlemidget yes, if you can open a PR for the new version that would be great. Then I can just add it as a revision bump to https://github.com/Homebrew/homebrew-core/pull/29490
