### ISSUE TITLE
Error when running conjure-up and choosing Openstack with NovaKVM : 'set' object does not support indexing                          

### ISSUE THREAD

**Issue by csj1** [conjure-up/conjure-up#1487]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems - No
- [ ] Is conjure-up running inside a virtual machine? - No. Ubuntu desktop
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? yes

## Please provide the output of the following commands

``

which juju
juju version - Juju version: 2.3.8-bionic-amd64

which conjure-up
conjure-up --version -  2.5.8

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version - Client version: 3.2
Server version: 3.2

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

Please attach tarball of **~/.cache/conjure-up**:

[conjure-up.log](https://github.com/conjure-up/conjure-up/files/2152601/conjure-up.log)

tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2152602/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport


sosreport


The resulting output file can be attached to this issue.
```
sosreport (version 3.5)

no valid plugins were enabled

## What Spell was Selected?
Openstack with NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by davidrobertson** [comment]
Also happens with NovaLXD for a local dev install.  Tried both --classic and --edge.  Tried on several machines of varying hardware and horsepower.  'conjure-up' fails 100% of the time.

Instructions at https://www.ubuntu.com/download/cloud/try-openstack are useless, as 'lxc init' by default enables ipv6 on the bridge interface.

**Comment by battlemidget** [comment]
> Also happens with NovaLXD for a local dev install. Tried both --classic and --edge. Tried on several machines of varying hardware and horsepower. 'conjure-up' fails 100% of the time.
> 
> Instructions at ubuntu.com/download/cloud/try-openstack are useless, as 'lxc init' by default enables ipv6 on the bridge interface.

Yep, we need to get those docs updated to match https://docs.conjure-up.io/devel/en/#users-of-lxd
