### ISSUE TITLE
conjure-up kubernetes-core hangs on master Waiting for kube-system pods to start

### ISSUE THREAD

**Issue by cshowers** [conjure-up/conjure-up#1499]
I am having issues getting conjure up to work for kubernestes-core.   In the conjure-up stats screen I never get pasts kubernetes master and worker-nodes.  The Following status is displayed
   ⌛   kubernetes-master/0                                waiting                                                 
                    Waiting for kube-system pods to start                                                                    
              ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
              ⌛   kubernetes-worker/0                                waiting                                                 
                    Waiting for kubelet to start.        
********************                    
When I run juju status I get:
                     Controller                Cloud/Region         Version  SLA          Timestamp
conjure-kubernetes-core-574  conjure-up-localhost-0fb  localhost/localhost  2.4.0    unsupported  23:08:04-04:00

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            jujucharms   50  ubuntu  
etcd               3.2.9    active       1  etcd               jujucharms   96  ubuntu  
flannel            0.10.0   waiting      2  flannel            jujucharms   66  ubuntu  
kubernetes-master  1.11.1   waiting      1  kubernetes-master  jujucharms  122  ubuntu  exposed
kubernetes-worker  1.11.1   waiting      1  kubernetes-worker  jujucharms  138  ubuntu  exposed

Unit                  Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*            active    idle   0/lxd/0  10.0.22.78                      Certificate Authority connected.
etcd/0*               active    idle   0        10.106.19.246   2379/tcp        Errored with 0 known peers
kubernetes-master/0*  waiting   idle   0        10.106.19.246   6443/tcp        Waiting to retry addon deployment
  flannel/0*          waiting   idle            10.106.19.246                   Waiting for Flannel
kubernetes-worker/0*  waiting   idle   1        10.106.19.211   80/tcp,443/tcp  Waiting for kubelet to start.
  flannel/1           waiting   idle            10.106.19.211                   Waiting for Flannel

Entity  Meter status  Message
model   amber         user verification pending  

Machine  State    DNS            Inst id              Series  AZ  Message
0        started  10.106.19.246  juju-65b53a-0        xenial      Running
0/lxd/0  started  10.0.22.78     juju-65b53a-0-lxd-0  xenial      Container started
1        started  10.106.19.211  juju-65b53a-1        xenial      Running
******************************************
I ssh into master and check logs.  I see the following repeated many times.  Not sure if this is why.
2018-07-24 02:36:19 DEBUG collect-metrics The connection to the server localhost:8080 was refused - did you specify the right host or port?
********************
System commands run
which juju:
/snap/bin/juju

juju version:
2.4.0-bionic-amd64

which conjure-up:
/snap/bin/conjure-up

conjure-up --version:
conjure-up 2.6.0

which lxc:
/usr/bin/lxc

/snap/bin/lxc config show:
config:
  core.https_address: '[::]'

/snap/bin/lxc version:
Client version: 3.0.1
Server version: 3.0.1
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2221840/conjure-up.tar.gz)

cat /etc/lsb-release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.


## What Spell was Selected? kubernetes-core

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran
sudo apt update
sudo snap install conjure-up --classic
sudo usermod -a -G lxd $(whoami)
conjure-up kubernetes-core

## Additional Information

**Comment by cshowers** [comment]
Can someone help here please.  I found a similar bug raised [https://github.com/conjure-up/conjure-up/issues/1134](url) and it seemed to stem from the below error in logs, the fix was to configure flannel to use a different CIDR
`Get https://gcr.io/v1/_ping: dial tcp: i/o timeout
`

I ran the collect.py script and I don't have the above error at all.   I attached my results.  I do see the following error on file unit-kubernetes-master-0.log when I ssh onto master.  I can't tell if this is cause
`2018-07-26 02:04:44 DEBUG etcd-relation-changed Traceback (most recent call last):
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/snap/cdk-addons/427/apply", line 150, in <module>
2018-07-26 02:04:44 DEBUG etcd-relation-changed     main()
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/snap/cdk-addons/427/apply", line 13, in main
2018-07-26 02:04:44 DEBUG etcd-relation-changed     if render_templates():
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/snap/cdk-addons/427/apply", line 21, in render_templates
2018-07-26 02:04:44 DEBUG etcd-relation-changed     node_count = get_node_count()
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/snap/cdk-addons/427/apply", line 134, in get_node_count
2018-07-26 02:04:44 DEBUG etcd-relation-changed     output = kubectl("get", "nodes", "-o", "name")
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/snap/cdk-addons/427/apply", line 130, in kubectl
2018-07-26 02:04:44 DEBUG etcd-relation-changed     return subprocess.check_output(cmd)
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-07-26 02:04:44 DEBUG etcd-relation-changed     **kwargs).stdout
2018-07-26 02:04:44 DEBUG etcd-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2018-07-26 02:04:44 DEBUG etcd-relation-changed     output=stdout, stderr=stderr)
2018-07-26 02:04:44 DEBUG etcd-relation-changed subprocess.CalledProcessError: Command '['/snap/cdk-addons/427/kubectl', 'get', 'nodes', '-o', 'name']' returned non-zero exit status 1
`
[results-2018-07-25-22-27-22.tar.gz](https://github.com/conjure-up/conjure-up/files/2230271/results-2018-07-25-22-27-22.tar.gz)

**Comment by battlemidget** [comment]
https://docs.conjure-up.io/stable/en/spellbooks/kubernetes#limitations
