### ISSUE TITLE
Openstack with NovaKVM: how to deploy without Ceph

### ISSUE THREAD

**Issue by Sidiox** [conjure-up/conjure-up#1501]
## Report

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ x] Is conjure-up running inside a virtual machine? Yes, but the juju controller is on bare metal, and the maas resources are other bare metal servers
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```

juju version
2.4.0-bionic

conjure-up --version
2.6.0

cat /etc/lsb-release
Ubuntu 18.04.1 LTS
```

## What Spell was Selected?

Openstack with NovaKVM

## What provider (aws, maas, localhost, etc)?
maas
### MAAS Users
MAAS 2.0.4-beta2

## Commands ran

conjure-up

## Additional Information
In the current version of conjure up with the Openstack on NovaKVM spell I cannot figure out how to deploy with only Cinder and without the Ceph backend. If I leave the units field empty for the ceph related charms, the deployment fails because "invalid literal for int() with base 10: ''", ie it is trying to parse the empty unit number. Is there a setting in the advanced options for any of the charms I'm missing or does the spell currently does not support deployment without Ceph (in the GUI)?

**Comment by ainiml** [comment]
I'm trying to deploy Openstack NovaLXD without Ceph, and getting this error too

`invalid literal for int() with base 10: ''`
