### ISSUE TITLE
Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done

### ISSUE THREAD

**Issue by kandadeepak** [conjure-up/conjure-up#1509]
- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
Yes looks similar,but with lower canonical version.

- [x] Is conjure-up running inside a virtual machine?
Yes

- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
Yes

dee@lulu:~$ which juju
/snap/bin/juju

dee@lulu:~$ juju version
2.4.1-bionic-amd64

dee@lulu:~$ which conjure-up
/snap/bin/conjure-up

dee@lulu:~$ conjure-up --version
conjure-up 2.6.1

dee@lulu:~$ which lxc
/snap/bin/lxc

dee@lulu:~$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
  core.trust_password: true

dee@lulu:~$ /snap/bin/lxc version
Client version: 3.4
Server version: 3.4

dee@lulu:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:
https://www.dropbox.com/s/nm6z7v19ydxivmz/conjure-up.tar.gz?dl=0


## Sosreport

Please attach a sosreport:

```
dee@lulu:~$ sudo apt install sosreport
Reading package lists... Done
Building dependency tree
Reading state information... Done
sosreport is already the newest version (3.5-1ubuntu3.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
dee@lulu:~$ sosreport

sosreport (version 3.5)

no valid plugins were enabled

The resulting output file can be attached to this issue.

## What Spell was Selected?
canonical kubernetes
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?
NA
## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information
4th attempt with fresh installation.

**Comment by kandadeepak** [comment]
Commands ran 
sudo apt remove lxd lxd-client
sudo snap install lxd
sudo snap install conjure-up --classic --edge
/snap/bin/lxd init
conjure-up kubernetes

**Comment by battlemidget** [comment]
What did you pick for your lxd storage type and did you disable ipv6 as stated in our documentation?

**Comment by kandadeepak** [comment]
in lxd I've choosen zfs and ipv6 in disable both OS and container.

**Comment by battlemidget** [comment]
You'll need to use the storage 'dir' type instead of zfs for now

**Comment by kandadeepak** [comment]
@battlemidget that worked,but the blogs it says zfs.

https://tutorials.ubuntu.com/tutorial/install-kubernetes-with-conjure-up#0
