### ISSUE TITLE
Conjure up fails with Exception: Could not determine Juju version

### ISSUE THREAD

**Issue by msLinuxNinja** [conjure-up/conjure-up#1514]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [Y] Is conjure-up running inside a virtual machine? -> VirtualBox Ubuntu 18.04
- [Y] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
/snap/conjure-up/1022/bin/wrappers/juju: line 20: /snap/conjure-up/1022/bin/juju: No such file or directory

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.1

which lxc
/snap/bin/lxc

/snap/bin/lxc config show

config:
  core.https_address: '[::]:8443'

/snap/bin/lxc version

Client version: 3.5
Server version: 3.5

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes

## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS? N/A

## Commands ran
juju version
Please outline what commands were run to install and execute conjure-up:
snap install conjure-up --classic

## Additional Information

Fresh installation of conjure-up through snap, when trying to summon a spell it fails fails with:

panzer@ubnt:~$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/1022/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.6.1', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/conjureup/app.py", line 290, in main
    utils.juju_version(),
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/conjureup/utils.py", line 269, in juju_version
    raise Exception("Could not determine Juju version.")
Exception: Could not determine Juju version.

juju version shows:

panzer@ubnt:~$ juju version
/snap/conjure-up/1022/bin/wrappers/juju: line 20: /snap/conjure-up/1022/bin/juju: No such file or directory

**Comment by msLinuxNinja** [comment]
[1514-cache_sosreport.zip](https://github.com/conjure-up/conjure-up/files/2408091/1514-cache_sosreport.zip)

**Comment by battlemidget** [comment]
Sorry about that, seems the build is missing juju. You can get around this for now with

```
sudo snap install juju --classic
```

**Comment by msLinuxNinja** [comment]
Thanks a lot! Didn't think of installing juju separately :) that did the trick.

**Comment by Wiklem** [comment]
> Sorry about that, seems the build is missing juju. You can get around this for now with
> 
> ```
> sudo snap install juju --classic
> ```

I tried that, but then got
` Reason:
                   list index out of range

                    Review log messages at /home/user/.cache/conjure-up/conjure-up.log If appropriate, please submit a bug here:
                   https://github.com/conjure-up/conjure-up/issues/new
`

And from the log:

` conjure-up/kubernetes-core - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1022/l$
Traceback (most recent call last):
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 19, in run
    await self.do_add_model()
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 24, in do_add_model
    if await juju.model_available():
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/conjureup/juju.py", line 154, in model_available
    await controller.connect(app.provider.controller)
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/juju/controller.py", line 100, in connect
    await self._connector.connect_controller(controller_name, **kwargs)
  File "/snap/conjure-up/1022/lib/python3.6/site-packages/juju/client/connector.py", line 90, in connect_controller
    endpoint = controller['api-endpoints'][0]
IndexError: list index out of range
`

**Comment by battlemidget** [comment]
New version is in snapstore which should resolve this.

Thanks for reporting!
