### ISSUE TITLE
"lxc list" is not showing containers list of bootstraped juju controller and its deployed machines

### ISSUE THREAD

**Issue by usama2490** [conjure-up/conjure-up#1517]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by usama2490** [comment]
usama@usama-HP-EliteBook-8470p:~$ juju bootstrap
Clouds
aws
aws-china
aws-gov
azure
azure-china
cloudsigma
google
joyent
localhost
oracle
rackspace

Select a cloud [localhost]: localhost

Enter a name for the Controller [localhost-localhost]: lxd-test

Creating Juju controller "lxd-test" on localhost/localhost
Looking for packaged Juju agent version 2.4.3 for amd64
No packaged binary found, preparing local Juju agent binary
To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md
Launching controller instance(s) on localhost/localhost...
 - juju-8543d4-0 (arch=amd64)          
Installing Juju agent on bootstrap instance
Unable to fetch Juju GUI info: error fetching simplestreams metadata: invalid URL "https://streams.canonical.com/juju/gui/streams/v1/index.sjson" not found
Waiting for address
Attempting to connect to 10.39.183.3:22
Connected to 10.39.183.3
Running machine configuration script...
Bootstrap agent now started
Contacting Juju controller at 10.39.183.3 to verify accessibility...
Bootstrap complete, "lxd-test" controller now available
Controller machines are in the "controller" model
Initial model "default" added


usama@usama-HP-EliteBook-8470p:~$ lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+

**Comment by ssks3092** [comment]
I am trying to bootstrap juju but not able to do so .
ubuntu# sg lxd -c "juju bootstrap --bootstrap-series=xenial localhost osm"
Getting below Error:-

No packaged binary found, preparing local Juju agent binary
To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md
Launching controller instance(s) on localhost/localhost...
 - juju-7f1e52-0 (arch=amd64)
Installing Juju agent on bootstrap instance
Unable to fetch Juju GUI info: error fetching simplestreams metadata: invalid URL "https://streams.canonical.com/juju/gui/streams/v1/index.sjson" not found
Waiting for address

ERROR failed to bootstrap model: waited for 20m0s without getting any addresses
ERROR No controllers registered.

Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".


### Mon Sep 23 14:58:06 IST 2019 juju_createcontroller: FATAL error: Juju installation failed
BACKTRACE:
### FATAL /usr/share/osm-devops/jenkins/common/logging 39
### juju_createcontroller /usr/share/osm-devops/installers/full_install_osm.sh 643
### install_lightweight /usr/share/osm-devops/installers/full_install_osm.sh 1014
### main /usr/share/osm-devops/installers/full_install_osm.sh 1387


Please let me know what i have to do to bootstrap juju successfully.
