### ISSUE TITLE
Conjure-up cannot add relation for Kubernetes add-ons

### ISSUE THREAD

**Issue by Coolfeather2** [conjure-up/conjure-up#1524]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.4.4-xenial-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.1

which lxc
/usr/bin/lxc
/snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
/snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2459618/conjure-up.tar.gz)
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport

sosreport (version 3.5)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Canonical distribution of kubernetes
--Graylog
--Helm
--kubeflow
--Prometheus

## What provider (aws, maas, localhost, etc)?
vSphere

### MAAS Users
Which version of MAAS?
-
## Commands ran
conjure-up

Please outline what commands were run to install and execute conjure-up:
sudo snap install conjure-up --classic

## Additional Information
'cannot add relation "filebeat:beats-host kubernetes-master:juju-info": principal and subordinate applications\' series must match',

**Comment by itsbentheboy** [comment]
Also having this same issue. 

Error Message: 
'cannot add relation "filebeat:beats-host kubernetes-master:juju-info": principal and subordinate applications' series must match'

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ N] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ N] Is conjure-up running inside a virtual machine?
Running on latest ubuntu 18.04 server, fresh install, fully updated. 
- [ Y] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
user@kubernetes:~$ which juju
/snap/bin/juju

user@kubernetes:~$ juju version
2.4.3-bionic-amd64

user@kubernetes:~$ which conjure-up
/snap/bin/conjure-up

user@kubernetes:~$ conjure-up --version
conjure-up 2.6.1

user@kubernetes:~$ which lxc
/usr/bin/lxc

user@kubernetes:~$ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
(LXD installed via apt, not snap)

user@kubernetes:~$ lxc config show
config:
  core.https_address: '[::]'

user@kubernetes:~$ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
(LXD installed via apt, not snap)

user@kubernetes:~$ lxc version
Client version: 3.0.1
Server version: 3.0.1

user@kubernetes:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

## What Spell was Selected?
conjure-up kubernetes
--Graylog
--Helm
--Prometheus
--Rancher 2.0(beta)

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
N/A

## Commands ran

Please outline what commands were run to install and execute conjure-up:

sudo snap install conjure-up --classic
lxd init (default settings, no IPv6 on Bridge)
lxd backend: zfs (existing mirror, freshly created after install)
reboot
conjure-up kubernetes (spell info above)

## Additional Information
Using LXD storage on simple ZFS 2 disk mirror for storage.
