### ISSUE TITLE
any new developments about this issue in Ubunutu 18.04?

### ISSUE THREAD

**Issue by sephad** [conjure-up/conjure-up#1528]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version

which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
What?

**Comment by sephad** [comment]
Hi Adam,
 I was getting the error below"error: Unable to connect to the source LXD: Get http://unix.socket/1.0: dial uni                                                                             x /var/lib/lxd/unix.socket: connect: no such file or directory"
I uninstalled 'lxd' using snap and then installed it again with 'apt' and all was ok.
Thanks
Kind Regards
Philip Serwanga (Phil)

"The value of a college education is not the learning of many facts but the training of the mind to think" Albert Einstein --n Phil acknowledges
"Success is Valuable only if you share it"
"Success isn't about how much money you make, it's about the difference you make in people's lives." Michelle Obama.
& Phil acknowledges
"Don't be in such a hurry to condemn a person because he doesn't do what you do, or think as you think. There was a time when you didn't know what you know today" Malcolm X
http://www.youtube.com/watch?v=zxRDc-z6EcQhttps://www.youtube.com/watch?v=B6fA35Ved-Y

 

    On Wednesday, October 17, 2018, 3:37:23 PM GMT+2, Adam Stokes <notifications@github.com> wrote:  
 
 
What?
