### ISSUE TITLE
Working installation procedure for local kubernetes-core on Ubuntu 16.04

### ISSUE THREAD

**Issue by spjz** [conjure-up/conjure-up#1529]
Documentation is a mess, and the software is very dependent on specific stable versions.

- [Ubuntu 16.04 LTS Server](https://www.ubuntu.com/kubernetes)
  - Known issues with 18.04 LTS
  - Best to start with a clean installation, defaults, no software presets
  - `$ sudo apt update; sudo apt upgrade`

- Snap packages
  - Do not use `apt` packages, use `snap`!
    - `$ sudo snap install conjure-up --classic`
    - `$ sudo snap install lxd`
  - `$ which lxd`, `$ which lxc` MUST resolve to snap binary!
    - Reboot after `$ sudo apt remove --purge` `lxd/lxc` packages if not.

- [LXD](https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd)
  - Check user in group `lxd`, add and logout if not: `$ groups`, `$ usermod -a -G $USER lxd`
  - `$ lxd init`
    - use defaults
    - create storage pool: `dir`
    - create network bridge with `ipv4` only

- Python
  - [Known](https://github.com/conjure-up/spells/issues/202) issue requires manual installation of `sudo apt install python3-pip` and `pip3 install pyyaml`

- [Conjure-Up](https://conjure-up.io/)
  - `$ conjure-up kubernetes-core`
    - Use defaults

Now wait, and pray. If it fails, check above steps again and reboot. Try again. `conjure-down` will fail, just `conjure-up` again over same controller.

**Comment by battlemidget** [comment]
Are you saying these https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd are a mess? If so, PR's welcomed against the docs to get them updated.

**Comment by spjz** [comment]
That particular document is actually the most useful I had found!

Users' troubles seem to come from unexpected presets and missing dependencies, which are reasonably expected to be accommodated by an automated deployment utility.
