### ISSUE TITLE
Openstack NovaKVM Dashboard cannot login with the given credential

### ISSUE THREAD

**Issue by sunnywty** [conjure-up/conjure-up#1534]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.4.3-xenial-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.1


which lxc
/usr/bin/lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
Please check with the latest deploy:
[https://drive.google.com/file/d/1ngYP9_w5hT44PtrKOOh7IPK6HtWTTeYZ/view?usp=sharing](https://drive.google.com/file/d/1ngYP9_w5hT44PtrKOOh7IPK6HtWTTeYZ/view?usp=sharing)
## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
NovaKVM
### MAAS Users
Which version of MAAS?
2.3.5
## Commands ran

Please outline what commands were run to install and execute conjure-up:
conjure-up --bootstrap-to roboconolddell
## Additional Information
My deployment have fully done according to conjure-up and juju status:
[Screenshot of JUJU Status](https://drive.google.com/open?id=138B00Pskmud9BEWAOSvOz1uby3q4fAHv)
However, with the following credential, I still cannot login:
[https://drive.google.com/open?id=1SNdnKIzWeQke3ZIu8-alIqGYSsxZmuqI](https://drive.google.com/open?id=1SNdnKIzWeQke3ZIu8-alIqGYSsxZmuqI)
Anything can I do to reset the password or get me in?

**Comment by rdwild** [comment]
source openrc
env
and then look for the password (it will be a random string of text).  It took be a bit to figure out that the password being provided as the default was not the right password.

**Comment by sunnywty** [comment]
Finally I have solved the problem by creating another user with the admin token.
