### ISSUE TITLE
Conjure-Up with Openstack spell never started neutron.  All other OpenStack components did work.

### ISSUE THREAD

**Issue by sreeve29** [conjure-up/conjure-up#1535]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ No] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [No ] Is conjure-up running inside a virtual machine?
- [Yes, makes no difference ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version

which conjure-up
conjure-up --version


**sreeve@u16:~$ which juju
/snap/bin/juju
sreeve@u16:~$ juju version
2.4.3-xenial-amd64
sreeve@u16:~$ which conjure-up
/snap/bin/conjure-up
sreeve@u16:~$ conjure-up --version
conjure-up 2.6.1**




which lxc
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release


**sreeve@u16:~$ which lxc
/snap/bin/lxc
sreeve@u16:~$ lxc config show
config:
  core.https_address: '[::]'
sreeve@u16:~$ lxc version
Client version: 3.6
Server version: 3.6
sreeve@u16:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"**



```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
openstack

## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2539456/conjure-up.tar.gz)

Devstack is on the left just for comparison.  Ubuntu/Conjure-Up/Openstack is on the right.
There is no Network tab:

![pic3](https://user-images.githubusercontent.com/6954302/47868768-7678ba80-dddb-11e8-84c0-9ccb7fffe116.png)

![pic2](https://user-images.githubusercontent.com/6954302/47868777-7c6e9b80-dddb-11e8-8800-bbd80846afa4.png)

![pic1](https://user-images.githubusercontent.com/6954302/47868783-809ab900-dddb-11e8-85fb-8aef42d1c250.png)

**Comment by hmlanigan** [comment]
I hit this as well, luckily i noticed while units were settling and did a remove-machine 11, remove-unit neutron-api/0 and add-unit neutron-api before things settled.  The conjure-up steps worked fine and everything configured.
