### ISSUE TITLE
can't deploy instance in conjure'd openstack-novalxd cloud

### ISSUE THREAD

**Issue by hmlanigan** [conjure-up/conjure-up#1536]
Juju bootstrap of the deploy openstack failed to start an instance.  Then tried openstack server create... failed again to create an instance.

Both instances failed with:
 "Permission denied - Can't open /dev/null"

Logs:
http://people.canonical.com/~heather/nova-compute.log
https://pastebin.canonical.com/p/QVV5qV7gkq/
http://people.canonical.com/~heather/lxd.tar.gz

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [no] Is conjure-up running inside a virtual machine?
- [yes ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? edge and stable are the same, tracking stable: 2.6.1-20181018.1610

## Please provide the output of the following commands

```
which juju
  /snap/bin/juju
juju version
  2.4.4-cosmic-amd64

which conjure-up
  /snap/bin/conjure-up
conjure-up --version
  conjure-up 2.6.1

which lxc
  /snap/bin/lxc
/snap/bin/lxc config show
  config:
  core.https_address: '[::]'
/snap/bin/lxc version
  Client version: 3.6
  Server version: 3.6

cat /etc/lsb-release
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=18.10
  DISTRIB_CODENAME=cosmic
  DISTRIB_DESCRIPTION="Ubuntu 18.10"
```

Please attach tarball of **~/.cache/conjure-up**:

http://people.canonical.com/~heather/conjure-up.tar.gz

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
openstack-novalxd

## What provider (aws, maas, localhost, etc)?
localhost

## Commands ran

juju bootstrap localhost conjure-up
conjure-up

## Additional Information

**Comment by hmlanigan** [comment]
I may have hit this issue: https://github.com/lxc/lxd/issues/4950#issuecomment-414159711.
unit nova-compute/0 is running a 4.18 kernel with liblxc 3.01.  I didn't see a 3.0.2 for xenial/liblxc available.

After running 'sudo lxc profile set default security.privileged true' on nova-compute/0, I was able to successfully run: 'sudo lxc launch ubuntu', where before I could not.  However openstack command to start an instance still fails the same way.  Is there a different profile it's using?

**Comment by battlemidget** [comment]
Shouldnt be, this is how the profile is being set:

https://github.com/conjure-up/spells/blob/master/openstack-novalxd/steps/00_process-providertype/before-deploy

**Comment by hmlanigan** [comment]
Does anything in conjure-up or openstack charms change the profiles on the nova-compute/0 unit, for the openstack instances to be deployed with?

**Comment by battlemidget** [comment]
Not that I know of from the conjure-up side

**Comment by hmlanigan** [comment]
I hit this with juju as well: https://bugs.launchpad.net/juju/+bug/1802151, which is now marked won't fix due to unsupported kernel/lxc combo.

The issue is caused by starting from a Cosmic host and using Xenial lxd containers.  The Xenial containers pick up the 4.18 kernel, but the version of lxc is 2.0.11 for Xenial.  To use the 4.18 kernel, you need lxc 3.0.2+ or a fix to systemd which isn't planned for back port.

If the openstack-novalxd bundle is used in the spell is updated to use Bionic, this issue shouldn't occur.  Bionic uses a lxc 3.0.2.

**Comment by battlemidget** [comment]
@ryan-beisner @ChrisMacNaughton any objection to bumping this to bionic?

**Comment by ChrisMacNaughton** [comment]
@battlemidget generally speaking, no problem with it, but it will need validation :)
