### ISSUE TITLE
Conjure-Up Openstack install fails if you use Ubuntu 18.04 Minimal Install OS

### ISSUE THREAD

**Issue by bmullan** [conjure-up/conjure-up#1538]
## Report

Simple report and I have replicated this 4 times so I'm pretty confident in this.

I created a 110GB VM using Virt-Manager.
I allocated 16GB of Ram and 4 CPU core.
Disk is a dedicated 500GB SSD 

**_I installed Ubuntu 18.04 Desktop Minimal Desktop_** onto that VM

[I then followed the instructions here](https://www.ubuntu.com/openstack/install#workstation-deployment).

The installation gets to the point where all of the services are green except for one of the CEPH OSD 0 (or CEPH OSD 1 (I don't have that written down) and  one Neutron service which continue to spin for hours till I kill it.

Over a 2 day period I retried this several times and always the same result... it never finishes even after 4 hours.

I was puzzled because I've done this before and it **always** succeeded.   Then it dawned on me that my that in my previous Conjure-Up installations  I **did not use the Ubuntu "minimal" install but did a full Ubuntu Desktop install**  (note is was the same .ISO file.

I retried one more time and this time in a VM I did a full Ubuntu 18.04 Desktop install and Conjure-Up succeeded in installing OpenStack and the completion took about 60 minutes.

_So I am opening this issue just to let you know that apparently there is something Conjure-Up doesn't like with the Ubuntu Desktop Minimal install_.

Brian

**Comment by battlemidget** [comment]
Thanks Brian we'll take a look

**Comment by bmullan** [comment]
other than a "we'll take a look" response in November there was never any response... so I'll just close this.
