### ISSUE TITLE
conjure-up does not detect my manual cloud

### ISSUE THREAD

**Issue by dimthe** [conjure-up/conjure-up#1539]
## Please provide the output of the following commands

```
dimtheo@juju:~$ which juju
/snap/bin/juju
dimtheo@juju:~$ juju version
2.4.5-bionic-amd64
dimtheo@juju:~$
which conjure-up
conjure-up --version

dimtheo@juju:~$ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
dimtheo@juju:~$ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
dimtheo@juju:~$ which lxc
/usr/bin/lxc
dimtheo@juju:~$

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2559992/conjure-up.tar.gz)

```

## What provider (aws, maas, localhost, etc)?
manual

Hello
I am on ubuntu 18.04. bionic

i have created a manual cloud via juju add cloud and juju shows it fine

dimtheo@juju:~$ juju clouds | grep auvious
auvious 0 manual

when i enter conjure-up and i select it i get the below error

Unable to find cloud for manual, you can double check that cloud exists by running `juju clouds`. Please see `juju help clouds` for more information

what could be wrong ? thanks

**Comment by dimthe** [comment]
logs from journalctl are here

https://pastebin.com/JqxMcrsz

**Comment by ktsakalozos** [comment]
Hi @dimthe ,

Since you get this:
```
dimtheo@juju:~$ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
dimtheo@juju:~$ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
```
You will need to remove the lxc/lxd binaries you have and get the latest lxd from snap:
```
sudo apt-get purge lxc*
sudo apt-get purge lxd*
sudo snap install lxd
```

Then do a: `lxd init` and select dir for storage and do not enable ipv6.

**Comment by ktsakalozos** [comment]
A safer approach is to ` snap install lxd` and then `lxd.migrate` to move from the apt instalation to snaps.

**Comment by dimthe** [comment]
yea i had figured these out but i forgot to close this issue
