### ISSUE TITLE
connection refused error

### ISSUE THREAD

**Issue by rifaterdemsahin** [conjure-up/conjure-up#1542]
during the installation process i have restarted after creating the lxd and the network

I am still getting this
administrator@DevOps-Ubunti:~$ sudo snap install conjure-up --classic
error: cannot install "conjure-up": Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp:
       lookup api.snapcraft.io on [::1]:53: read udp [::1]:47619->[::1]:53: read: connection
       refused

**Comment by battlemidget** [comment]
Issue with snap store, please visit https://forum.snapcraft.io/ for more help

**Comment by chipaca** [comment]
A DNS lookup failure is _probably_ not an "issue with snap store", but with local DNS.
