### ISSUE TITLE
Conjure-Up k8s core install fails on flannel setup with error: hook failed: "install"

### ISSUE THREAD

**Issue by gstyle** [conjure-up/conjure-up#1545]
Hey friends, 

I'm having a problem getting conjure-up to install successfully via localhost. I've done this at least a dozen times and every time it fails on the flannel install. Both worker nodes give up because flannel fails and the subnet won't start. At that point conjure-up errors out and quits.

I'll start with the report inline:
- [ ] Is conjure-up running inside a virtual machine? Yes, this is running on my VMware 6.0 ESXi production environment.
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? Yes
which juju /snap/bin/juju
juju version 2.4.3-bionic-amd64
which conjure-up /snap/bin/conjure-up
conjure-up --version conjure-up 2.6.1
which lxc /snap/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'
/snap/bin/lxc version -Client version: 3.7, Server version: 3.7
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
Please attach tarball of **~/.cache/conjure-up**:
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
## Sosreport
Please attach a sosreport:
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.
## What Spell was Selected? conjure-up kubernetes-core
## What provider (aws, maas, localhost, etc)? localhost
### MAAS Users - Which version of MAAS? NA
## Commands ran
Please outline what commands were run to install and execute conjure-up:
conjure-up kubernetes-core 

## Additional Information
Here's the order of events:
This is a fresh install of ubuntu server 18.01 lts. I've installed conjure-up as part of the ubuntu package OOB.  Trying to deploy a localhost cloud via lxd. I followed the instructions in the video here https://www.ubuntu.com/kubernetes/install (minus the cloud setup) since I am doing localhost I followed the lxd setup instructions here https://docs.conjure-up.io/stable/en/user-manual#users-of-lxd and got that working successfully. I did the migrate to the snap version of lxd, setup the storage pool with ZFS and disabled ip6 on the network bridge. I can successfully deploy and destroy containers. At this point, I ran conjure-up kubernetes-core. I'd like to do the full stack but I haven't gotten the install to work yet so at this point I'm just trying to get the core running. I can do a juju status which shows flanel failed error: hook failed: "install". I gave canal a try instead of flanel thinking that would work but that made the install sit for 4+ hours with canal status: Container runtime not available and the master sitting at: Waiting for CNI plugins to become available.

I appreciate any help you can give me.
Thanks!



[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2634909/conjure-up.tar.gz)
[sosreport-alb-k8s01-20181130200211.tar.gz](https://github.com/conjure-up/conjure-up/files/2634924/sosreport-alb-k8s01-20181130200211.tar.gz)

**Comment by battlemidget** [comment]
@Cynerva @hyperbolic2346 any idea? Could it be the new resources? I haven't pushed anything to stable

**Comment by Cynerva** [comment]
This is almost certainly the same issue as https://github.com/conjure-up/conjure-up/issues/1546 and https://github.com/juju-solutions/charm-flannel/issues/52. Should be fixed now - can you try again and let us know if it's still not working?

**Comment by seffyroff** [comment]
I updated my snap to edge: 2.6.1-20181204.0012 (1033) 109MB classic
And deployed CDK, it fails on Flannel in the same way.
[results-2018-12-04-01-06-13.tar.gz](https://github.com/conjure-up/conjure-up/files/2641930/results-2018-12-04-01-06-13.tar.gz)

**Comment by gstyle** [comment]
It failed in the same way again. Version 2.6.1-20181204.0012. I tried both edge and candidate releases.

**Comment by battlemidget** [comment]
Yea we're looking into it

**Comment by gstyle** [comment]
Unfortunately that didn't work. Still got the same error. I upgraded flannel and re-ran conjure-up. Was there a manual way you got it to work to download/install kubernetes? I just installed the new snap packages.

juju upgrade-charm flannel
Added charm "cs:~containers/flannel-340" to the model.
conjure-up kubernetes-core

**Comment by seffyroff** [comment]
The deploy for me has progressed beyond installing Flannel - currently my deploy looks like this:
https://i.imgur.com/UXIStuo.png

It seems like one worker is failing to install Docker (or another part of the container runtime deps) and I think that's what's holding everything else up.

**Comment by iatrou** [comment]
@gstyle Here are the steps:
```
git clone https://github.com/conjure-up/spells.git
wget https://api.jujucharms.com/charmstore/v5/canonical-kubernetes/archive/bundle.yaml -O spells/canonical-kubernetes/bundle.yaml
sed -ri 's/series: bionic/series: xenial/g' spells/canonical-kubernetes/bundle.yaml
sed -ri 's/flannel-339/flannel-340/g' spells/canonical-kubernetes/bundle.yaml
conjure-up spells/canonical-kubernetes
```

**Comment by aparamon** [comment]
Confirm that modifying for "flannel-340" works for me!

**Comment by Cynerva** [comment]
I've updated the stable bundles to point to flannel revision 340. Quick test of `conjure-up kubernetes-core` looks good now but I'm still in the process of testing other bundles. If anyone hits the issue again, please let us know.

**Comment by gstyle** [comment]
@iatrou Thanks a lot for the code! I followed those exact steps and it worked. Flannel came up and built subnets. My kube system pods are still waiting to start but I think for the purpose of this bug its fixed. I still did not get "conjure-up kubernetes-core" to work. It failed with hook failed "leader-setting-changed." However, it could possibly be fixed since it appears he just updated the bundles. Thanks guys.

**Comment by battlemidget** [comment]
Can you all test conjure-up now? Should be resolved

**Comment by gstyle** [comment]
@battlemidget I just retested for you and I can confirm this is fixed and working. Flannel works and installs properly if you simply run "conjure-up kubernetes-core."

My install is hanging on "waiting for kubelets to start" but as far as flannel goes its solid. My answer may lie in #1134 so I am still working on it. Thanks for getting me to the next step. :)
