### ISSUE TITLE
 exception: 'BundleApplicationFragment' object has no attribute 'fragment'

### ISSUE THREAD

**Issue by mapdegree** [conjure-up/conjure-up#1549]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
juju version
2.4.3-bionic-amd64

which conjure-up
conjure-up --version
conjure-up 2.6.1

 
/snap/bin/lxc config show
/snap/bin/lxc version

cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by mapdegree** [comment]
Attachment
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2645810/conjure-up.tar.gz)

**Comment by mapdegree** [comment]
It fails when calico is selected.
Next to this, it fails, if region eu-west-2 is selected. Unfortunately too many issues with the tool.

**Comment by strainovic** [comment]
I can confirm that it fails when calico is selected.

Any workaround?

**Comment by tvansteenburgh** [comment]
Unfortunately the only workaround I know at the moment is to choose Flannel instead. We're looking into this and will hopefully have it fixed soon.
