### ISSUE TITLE
Not able to create an Image, Ubuntu 18.04 Juju OpenStack Config and Installation on LXD

### ISSUE THREAD

**Issue by arturgvieira** [conjure-up/conjure-up#1551]
Information:
`/snap/bin/juju`
`2.4.3-bionic-amd64`
`/snap/bin/conjure-up`
`conjure-up 2.6.1`
`/snap/bin/lxc`
```
config:
  core.https_address: '[::]'
```
`/snap/bin/lxc version`
```
Client version: 3.7
Server version: 3.7
```
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

## What Spell was Selected?
`openstack-lxd`
## What provider (aws, maas, localhost, etc)?
`localhost`
### MAAS Users
Which version of MAAS?
None

## Commands ran

`conjure-up`

Please outline what commands were run to install and execute conjure-up:

`sudo snap install conjure-up --classic`

I cant make a new image, It is hanging on Saving the 12MB Cirros Test Image
![screenshot from 2018-12-07 08-55-48](https://user-images.githubusercontent.com/7041980/49661455-f0651a80-f9fd-11e8-99cd-230f7eb46924.png)
Fresh install of 18.04

**Comment by arturgvieira** [comment]
I think that it's because, of the storage type... I forgot to specify `dir` in the init. This has been the worst install experience, for me. Ubuntu's tutorial saved me.
https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up#1

**Comment by battlemidget** [comment]
Also reading our conjure-up docs would've saved you the hassle.
