### ISSUE TITLE
[Errno 110] Connect call failed ('10.X.X.X', 17070)

### ISSUE THREAD

**Issue by tywkeene** [conjure-up/conjure-up#1559]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
+ which juju
/snap/bin/juju
+ juju version
2.4.3-bionic-amd64
+ which conjure-up
/snap/bin/conjure-up
+ conjure-up --version
conjure-up 2.6.3
+ which lxc
/snap/bin/lxc
+ /snap/bin/lxc config show
config: {}
+ /snap/bin/lxc version
Client version: 3.7
Server version: 3.7
+ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up

```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2677816/conjure-up.tar.gz)
## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

Kubernetes Core

## What provider (aws, maas, localhost, etc)?

Localhost

### MAAS Users
Which version of MAAS?

N/A

## Commands ran

Please outline what commands were run to install and execute conjure-up:

```
$ sudo snap install lxd
$ /snap/bin/lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: no
Do you want to configure a new storage pool? (yes/no) [default=yes]: yes
Name of the new storage pool [default=default]: default
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]: dir
Would you like to connect to a MAAS server? (yes/no) [default=no]: no
Would you like to create a new local network bridge? (yes/no) [default=yes]: yes
What should the new bridge be called? [default=lxdbr0]: lxdbr0
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: auto
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like LXD to be available over the network? (yes/no) [default=no]: no 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] yes
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: no 

$ sudo snap install --classic conjure-up
$ conjure-up kubernetes
```

## Additional Information

Previously ran into error as described in issues  #1556 and then #961 after downloading the fixed revision Conjure-up 2.6.3 (rev 1038), and now I am running into this error

**Comment by qiumin98** [comment]
I encounter the same problem. in addition to above similar problem the IP address appeared to be the IP left in previous try.  "sudo snap remove lxd/conjure-up"; rm -rf .cache and ./snap did not remove the old IP.  ls /snap show lxd and conjure-up were gone.  not sure where the old IP was stored.

**Comment by qiumin98** [comment]
found the problem:
mqiu@ubu-pc:~$ cat .local/share/juju/controllers.yaml 
controllers:
  conjure-up-localhost-cd7:
    uuid: e8d0b088-a714-4399-83ae-b5be8ca485b1
    api-endpoints: ['10.27.84.72:17070']
    ca-cert: |
      -----BEGIN CERTIFICATE-----
      MIIDrDCCApSgAwIBAgIUXd7CzlDfiqwp4YVmmgECa5ZoSLYwDQYJKoZIhvcNAQEL
      BQAwbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
      Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkNDYzYWQxMzItNTc2Zi00MDc3
      LTgxNWItMTZjYTJhNzUyNjFiMB4XDTE5MDQwNzAyNDgyMloXDTI5MDQxNDAyNDgy
      MlowbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
      Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkNDYzYWQxMzItNTc2Zi00MDc3
      LTgxNWItMTZjYTJhNzUyNjFiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAshIkzZ9+NepW4s91F5PNREaFIEnTf4rAk5bzgum5p2PGyX0CF5ed9RJ+2H+A
      p7qU6sFJGqzPHGXOw3oe2HiMwk/gA8sNhmd4ahwe0rIYtHz4JPybG0nsH/j9EKKH
      5PHyUTfBgGR+mjwTUDZaSkDrWwY90pNKYa3XWsFgFZgTExvOJR0SX6ZuUXXWgVE9
      gCJWwbfazfLjOLLGtC535/g0afZJlwO1Hg8s9nXfRS1Y/vB2Um6d04IJ22F844/N
      Yv/M2KP+dQdYsFV90Ha61xqnO0RigKHXzNHCLsl51g5pGMBulTUuM7Ter9d5vXVf
      QP8h/CzrGqeV9RfrAaDnxhxA7wIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
      VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfYeN2Qh0QsMUdopGD0uwBv1UkW8wDQYJ
      KoZIhvcNAQELBQADggEBAH1tLTPxB4RMYcbCwxhTjVb70VSp8BuUljD0e8sRO9ft
      oz18UCi+Qt5+lB0oSG0a10AEaTe/krWBD6I55VyyJ3KtsrvLX/E8IqKsRgX2r4Qt
      Btesu11o5rZQRMKg+JWZSAbNp8pm8vMGsaXijHUxKnB1T+KV3pU/oMgTHigIMjUJ
      yTVHOmSIHBBKKd+ReUVMXOP2uJxNyQPGGIKVFXA/HmAXpIXRXK7diGi37GyYDsPE
      RZjZnWzzUJJDFWcxSav0XFAlYwrZdSNiAfVLmDUpQ0ZQmolrrdEuGO5VjNVAHBFD
      b9FYh5df/9tfd9+1MGrwhviqeaphuehCN2sNQ1yaFno=
      -----END CERTIFICATE-----
    cloud: localhost
    region: localhost
    agent-version: 2.5.0
    controller-machine-count: 1
    active-controller-machine-count: 0
    machine-count: 1
current-controller: conjure-up-localhost-cd7
