### ISSUE TITLE
subordinate application must be deployed without units

### ISSUE THREAD

**Issue by reyou** [conjure-up/conjure-up#1561]
## Report

- [x] Is conjure-up running inside a virtual machine?

## Please provide the output of the following commands

```
which juju
# /snap/bin/juju
juju version
# 2.4.3-xenial-amd64
which conjure-up
# /snap/bin/conjure-up
conjure-up --version
# conjure-up 2.6.3
which lxc
# /snap/bin/lxc
/snap/bin/lxc config show
## config:
##   core.https_address: '[::]'
/snap/bin/lxc version
# Client version: 3.7
# Server version: 3.7
cat /etc/lsb-release
# DISTRIB_ID=Ubuntu
# DISTRIB_RELEASE=16.04
# DISTRIB_CODENAME=xenial
# DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
https://pastebin.com/9LA75Hjz

## What provider (aws, maas, localhost, etc)?
localhost

## Commands ran
```
$ conjure-up kubernetes
```
## Additional Information

I was trying to install kubernetes-core, and faced this issue.
Here is screen shot:

![](https://i.imgur.com/Pb2KxSO.png)

##### Logs
Attached.
[conjure-up.log](https://github.com/conjure-up/conjure-up/files/2678378/conjure-up.log)

**Comment by johnsca** [comment]
2.6.4 was released yesterday evening to fix this.  Please do a `snap refresh conjure-up` and try again.

**Comment by reyou** [comment]
Will do, thanks!

**Comment by reyou** [comment]
`$ sudo snap refresh conjure-up`
snap "conjure-up" has no updates available

any idea on this?

@johnsca

**Comment by reyou** [comment]
Sorry it got updated actually, my bad 💯
