### ISSUE TITLE
kubernetes-core bootstrap (localhost) hangs on "Waiting for deployment to settle."

### ISSUE THREAD

**Issue by gzambon** [conjure-up/conjure-up#1565]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [**NO**] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [**NO**] Is conjure-up running inside a virtual machine?
- [**YES**] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

juju version
2.4.3-cosmic-amd64

which conjure-up
/snap/bin/conjure-up

conjure-up --version
conjure-up 2.6.4

which lxc
/snap/bin/lxc

/snap/bin/lxc config show
config:
  core.https_address: '[::]'

/snap/bin/lxc version
Client version: 3.8
Server version: 3.8

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
```

Please attach tarball of **~/.cache/conjure-up**:
```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2700897/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes-core

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
N/A

## Commands ran
lxc network set lxdbr0 ipv6.nat false
lxc network set lxdbr0 ipv6.address none
conjure-up

Please outline what commands were run to install and execute conjure-up:
sudo snap install lxd
sudo /snap/bin/lxd init
sudo snap install conjure-up --classic --edge
## Additional Information
I`ve downloaded the cdk-field-agend from https://raw.githubusercontent.com/juju-solutions/cdk-field-agent/master/collect.py and run it with the following output: [results-2018-12-20-21-33-43.tar.gz](https://github.com/conjure-up/conjure-up/files/2700978/results-2018-12-20-21-33-43.tar.gz)

The hardware is a MacPro (early 2008) 2xE5462 @ 2.80GHz (4 cores/6mb cache), 32GB RAM and 400GB SSD

Screenshot: 
<img width="1427" alt="screen shot 2018-12-20 at 21 19 08" src="https://user-images.githubusercontent.com/3682161/50316245-fdbde280-049c-11e9-9173-9f2acb3187df.png">

**Comment by johnsca** [comment]
The `auto` value for the `docker_runtime` config option is [known](https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/707) to be problematic on LXD.  We're working on improving that, but in the meantime, an easier workaround is to change that option to `apt` via the Configure Spell screen on both Kubernetes Master and Kubernetes Worker.  This will be improved when that fix lands, but in the meantime this should be easier than removing the GPU.

**Comment by gzambon** [comment]
Hi **Johnsca**, thanks for your time and the reply. Indeed it looks much easier than removing the GPU! I am closing it as it is known and also there is a better workaround! Best regards from Brazil!
