### ISSUE TITLE
Error in conjure-up: Some applications failed to start successfully

### ISSUE THREAD

**Issue by Klemen-t** [conjure-up/conjure-up#1568]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [X] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [X] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.4.3-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.4

which lxc
/snap/bin/lxd
/snap/bin/lxc config show
config: {}
/snap/bin/lxc version
Client version: 3.8
Server version: 3.8

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2732388/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
sosreport is attached inside conjure-up.tar.gz :)

## What Spell was Selected?
OpenStack with NovaLXD
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?
No MAAS installed
## Commands ran

From de beggining, a fresh Ubuntu 18.04.1 LTS Server. I've followed official tutorial from https://www.ubuntu.com/openstack/install#workstation-deployment:
```
ping 8.8.8.8 //It works
sudo snap install lxd
sudo lxd.migrate -yes //I have deleted old .deb lxd version
reboot
sudo lxd init //All by default except questions about IPv6 (answered as none) and space of loop device (answered as 2GB). 
sudo snap install conjure-up --classic 
```

Once conjure-up executed, I've chosen OpenStack with NovaLXD, localhost, network bridge and storage pool by default (the same tha I've created before with lxd init), and I've chosen all the applications by default (ceph-mon, ceph-osd, ceph-radosgw... all by default). 

## Additional Information
I've tried so many times this configuration, using VirtualBox and using a fresh install, and also using --edge version of conjure-up. I've also tried with a Bare Metal Ubuntu 18.10 Desktop (I've created lxd group and I've attached my user to sthis group).
Maybe I have some misconception about what I have to do...

**Comment by Klemen-t** [comment]
It was a hardware problem: I was using a virtual machine with 10GB of disk space and 1GB of RAM. 
Now I use 40 Gb of hard disk, 4 GB of RAM and 3 CPU cores.

The probem now is: **Status code not 101: 503**. Some help please?

I undestand that there is no problem with hardware... maybe something about network?

**Comment by johnsca** [comment]
That error message sounds like a websocket error connecting to the Juju controller.

I would recommend using `lxc list` to see if there is a `juju-` prefixed instance (the controller) and what state it's in.  If it's `running`, then maybe connecting to it and checking the logs under `/var/log/juju` and possibly the status of the juju services (I can recall their names off the top of my head, something like `juju-machine-agent` and / or `juju-controller`; but you can find them with `systemctl list-unit-files *juju*`) to figure out why the controller failed.

Additional assistance debugging the controller can be found on IRC on #juju on Freenode, or on Discourse at https://discourse.jujucharms.com/

**Comment by Klemen-t** [comment]
Thanks johnsca. 
For now I'm not able to finish the configuration. 
Now I'm near the finish line, but the deploymen freezes. I have no error log.
Error 101:503 has benn solved giving more storage space (I gave 2GB, now 20GB and I get no error).

But I'm still at the same point... Will update asap.
