### ISSUE TITLE
Failed to apply container template

### ISSUE THREAD

**Issue by Jasdevi21** [conjure-up/conjure-up#1588]
## Report

I am doing tests within a single machine with localhost novalxd and at the moment of running the openstack services it stays in waiting for machine and in the report of juju status the message appears:

Create container from image: Failed to apply container template: Failed to set apply_template volatile key: failed to write backup file: write /var/snap/lxd/common/lxd/containers/juju-7c09bc-6/backup.yaml: no space left on device

```
which juju
juju version

2.3.7-xenial-amd64

which conjure-up
conjure-up --version

conjure-up 2.6.6

which lxc
/snap/bin/lxc config show
core.https_address: '[: :]'
/snap/bin/lxc version
Client version: 3.10
Server version: 3.10
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

localhost

sudo apt install sosreport
sosreport

sosreport (version 3.6)

no valid plugins were enabled

Which version of MAAS?
no

conjure-up openstack
choose novalxd
Please outline what commands were run to install and execute conjure-up:
sudo snap install conjure-up --classic
sudo snap refresh conjure-up --classic --edge

**Comment by battlemidget** [comment]
`Failed to set apply_template volatile key: failed to write backup file: write /var/snap/lxd/common/lxd/containers/juju-7c09bc-6/backup.yaml: no space left on device`

You are out of storage space
