### ISSUE TITLE
conjure-up installation for OpenStack with NovaKVM does not show localhost cloud option as available

### ISSUE THREAD

**Issue by mrbatwood** [conjure-up/conjure-up#1590]
## Report

Thank you very much to everyone who can give me some input regarding this problem that I've found.  I really look forward to working with OpenStack, but am daunted by the hand installation tools that I've found.  This Workstation install with conjure-up sounds perfect!  Unfortunately it doesn't install as shown in the video I watched:  https://www.ubuntu.com/openstack/install#workstation-deployment

Here is the requested debugging information:
- [NO] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [NO] Is conjure-up running inside a virtual machine?
- [?] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
I ran this command and the problem still appears

## Please provide the output of the following commands

sol@sored2:~$ which juju
/snap/bin/juju
sol@sored2:~$ juju version
2.5.0-xenial-amd64
sol@sored2:~$ which conjure-up
/snap/bin/conjure-up
sol@sored2:~$ conjure-up --version
conjure-up 2.6.6
sol@sored2:~$ 
sol@sored2:~$ which lxc
/snap/bin/lxc
sol@sored2:~$ /snap/bin/lxc config show
config: {}
sol@sored2:~$ /snap/bin/lxc version
Client version: 3.10
Server version: 3.10
sol@sored2:~$ 
sol@sored2:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/2938305/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
Not sure about this one;  here's what happened when I ran this command:
sol@sored2:~$ sosreport

sosreport (version 3.6)

no valid plugins were enabled

## What Spell was Selected?
OpenStack with NovaKVM

## What provider (aws, maas, localhost, etc)?
localhost is the one that was not available

## Commands ran
Just conjure-up ...

## Additional Information
I followed all of the steps listed on the page  below.  I spent a lot of time validating the configuration of lxd and lxc -- and can't see anything that should prevent the localhost option from being available.

    https://www.ubuntu.com/openstack/install#workstation-deployment

Here's the screen I see in conjure-up:
<img width="939" alt="conjure-up without localhost" src="https://user-images.githubusercontent.com/48292888/53914382-591a5e00-4012-11e9-9489-11db0ddeb83e.png">

**Comment by mrbatwood** [comment]
Sorry!  I didn't mean to submit this one yet!  Filling in the rest of the information now ...

**Comment by mrbatwood** [comment]
Just checking;  did I do anything wrong with this form or is there just no feedback? ;^)

**Comment by quartzeye** [comment]
Just tried to install Openstack with NovaKVM and this effect still exists.  MAAS is the only active option in the spell.  I too want to install a single server install of Openstack with NovaKVM using conjure-up per the Ubuntu tutorial.

https://tutorials.ubuntu.com/tutorial/install-openstack-with-conjure-up#0

**Comment by primesoftnz** [comment]
Still present in my install

**Comment by ainiml** [comment]
Issue exists in `conjure-up 2.6.8` as well
