### ISSUE TITLE
KeyError('charm',)

### ISSUE THREAD

**Issue by Coolfeather2** [conjure-up/conjure-up#1600]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
ubuntu@nathan-ubuntu:~$ which juju
/snap/bin/juju
ubuntu@nathan-ubuntu:~$ juju version
2.6.2-bionic-amd64
ubuntu@nathan-ubuntu:~$
ubuntu@nathan-ubuntu:~$ which conjure-up
/snap/bin/conjure-up
ubuntu@nathan-ubuntu:~$ conjure-up --version
conjure-up 2.6.7
ubuntu@nathan-ubuntu:~$
ubuntu@nathan-ubuntu:~$ which lxc
/usr/bin/lxc
ubuntu@nathan-ubuntu:~$ /snap/bin/lxc config show
-bash: /snap/bin/lxc: No such file or directory
ubuntu@nathan-ubuntu:~$ /snap/bin/lxc version
-bash: /snap/bin/lxc: No such file or directory
ubuntu@nathan-ubuntu:~$
ubuntu@nathan-ubuntu:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
ubuntu@nathan-ubuntu:~$

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3185605/conjure-up.tar.gz)

```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
sosreport (version 3.6)

no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Canonical Kubernetes
## What provider (aws, maas, localhost, etc)?
vSphere
### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
```
sudo snap install conjure-up --classic
conjure-up
```

## Additional Information
Configured no add-ons

**Comment by blinkeye** [comment]
I can confirm the error. I conjured-up with the debug flag:
```
conjure-up kubernetes-core --debug
```
please see the zipped ~/.cache/conjure-up: [conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3194901/conjure-up.tar.gz)

**NOTE**: this used to work a couple of month ago.

**Workaround**: 

The setup/deployment of the juju-controller works, so I installed a more recent juju with:
```
sudo snap install juju --classic
```
which installs juju v2.6.2

NOTE: the conjure-up snap uses an older juju version:

```
$ conjure-up.juju --version
2.5.0-bionic-amd64
```

and continued with snap juju v2.6.2:
```
juju deploy kubernetes-core
```
successfully.

**Comment by battlemidget** [comment]
Will get this upgraded

**Comment by gildas** [comment]
Just to make sure. How long should we wait? I tried today and chose "Charned Distribution of Kubernetes" and it still fails the same way.
Even after doing a `sudo snap install juju --classic`.

**Comment by blinkeye** [comment]
After it fails, did you continue the installation with (in your case):
```
juju deploy canonical-kubernetes
```

**Comment by gildas** [comment]
> After it fails, did you continue the installation with (in your case):
> 
> ```
> juju deploy canonical-kubernetes
> ```

No. Let me try that again.

**Comment by gildas** [comment]
After it fails, running `juju deploy canonical-kubernetes` worked. No need to install juju, as it was already on 2.6.2.
So, is it a conjure-up UI glitch only?

**Comment by blinkeye** [comment]
From what you wrote above:

> Just to make sure. How long should we wait? ...
> Even after doing a `sudo snap install juju --classic`.

you installed a snap juju version v2.6.2 - which is newer than the one that comes bundled with conjure-up. And that's exactly what @battlemidget fixed with: 888e1e1

**Comment by battlemidget** [comment]
I need to bump up libjuju to 0.11.5 as well. I'll do that in the next hour

**Comment by gildas** [comment]
I can re-run the test if you need. Just give me a howler.

**Comment by battlemidget** [comment]
Just pushed it to the builders, should be available in the next 30 minutes or so

**Comment by gildas** [comment]
Thanks, that part is working now.

Now, `conjure-up kubernetes` fails later with the error:
```
hostname 'X.Y.Z.O' doesn't match either of 'juju-apiserver', 'juju-mongodb', 'localhost'
```
But this is another issue, IMO. I will search and maybe open another issue.

**Comment by battlemidget** [comment]
Yeah I noticed this late last night as well. Will need to dig into it some more

**Comment by gildas** [comment]
Oh ok. So, at least I am not going nuts....

I will use kubeadm in the mean time as I need a k8s cluster, right  now.
Will spin up a VM from time to time to check if this is getting there.

**Comment by battlemidget** [comment]
@gildas I would try https://microk8s.io before going with kubeadm

**Comment by blinkeye** [comment]
> @gildas I would try https://microk8s.io before going with kubeadm

I think by cluster he means a multi-node k8s cluster, not a single node cluster. @gildas: if I'm mistaken and you only need a single node k8s cluster I second @battlemidget recommendation, it's a joy to use! NOTE: in channel >=v1.14.1  dockerd was replaced with containerd, see [this link](https://itnext.io/containerd-on-a-more-secure-microk8s-c2c97ac0268f) for more information.

**Comment by gildas** [comment]
Thanks. I already use microk8s. And I agree it is joy to install and use.
But for it's for dev and test. You cannot use it in production.
And certainly not in multi-nodes, which, as @blinkeye guessed, I want to do.

**Comment by battlemidget** [comment]
snap version is updated, feel free to give it another go

**Comment by battlemidget** [comment]
This should be resolved now, feel free to reopen if not

Thanks
