### ISSUE TITLE
Openstack spell fails trying to deploy applications, cannot unmarshall string

### ISSUE THREAD

**Issue by HeroesLament** [conjure-up/conjure-up#1605]
json: cannot unmarshal string into Go struct field ApplicationDeploy.devices of type devices.Constraints

                        Review log messages at /home/netdepot/.cache/conjure-up/conjure-up.log If appropriate, please submit a bug here: https://github.com/conjure-up/conjure-up/issues/new

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems - Not that I can find.
- [ ] Is conjure-up running inside a virtual machine? - No, bare metal install through MAAS. 
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? - Yes.

## Please provide the output of the following commands

```
which juju - /snap/bin/juju

juju version - 2.6.2-bionic-amd64

which conjure-up - /snap/bin/conjure-up

conjure-up --version - conjure-up 2.6.8

which lxc - /snap/bin/lxc
/snap/bin/lxc config show - If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:18.04

config: {}

/snap/bin/lxc version - Client version: 3.13
Server version: 3.13

cat /etc/lsb-release - DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

```

Please attach tarball of **~/.cache/conjure-up**: tar: Removing leading `/' from member names
tar: /root/.cache/conjure-up: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS? - MAAS version: 2.4.2 (7034-g2f5deb8b8-0ubuntu1)

## Commands ran - 

Please outline what commands were run to install and execute conjure-up: snap install conjure-up --classic

## Additional Information
None at this time :'(
[sosreport-hou1-12322.na-20190531152556.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/3241423/sosreport-hou1-12322.na-20190531152556.tar.xz.zip)

**Comment by dni** [comment]
got the same error, did you find anything?

**Comment by JohnnyElvis** [comment]
same here with juju 2.6.3-bionic-amd64, conjure-up conjure-up 2.6.8 and maas 2.4.2
