### ISSUE TITLE
juju.provider.common bootstrap.go:576 connection attempt for 10.8.8.206 failed: *** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by javaJake** [conjure-up/conjure-up#1609]
## Description
When debugging conjure-up's inability to start up OpenStack on LXD, I came across this debug command and gave it a try:
`juju bootstrap localhost lxd-test --debug`

This ultimately fails with the following message printed repeatedly:
```
juju.provider.common bootstrap.go:576 connection attempt for 10.8.8.206 failed: *** stack smashing detected ***: <unknown> terminated
```

If I remove conjure-up and install juju (all through snap) then I do not see this error. I think the bundled juju may not be built correctly.

## Report

- [X] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems (no)
- [X] Is conjure-up running inside a virtual machine? (no)
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`? (yes)

## Please provide the output of the following commands

```
$ which juju
/snap/bin/juju
$ juju version
2.6.2-disco-amd64

$ which conjure-up
/snap/bin/conjure-up
$ conjure-up --version
conjure-up 2.6.8

$ which lxc
/snap/bin/lxc
$ /snap/bin/lxc config show
config:
  core.https_address: '[::]'
$ /snap/bin/lxc version
Client version: 3.14
Server version: 3.14

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

## What Spell was Selected?
I was trying OpenStack on LXD.

## What provider (aws, maas, localhost, etc)?
localhost

**Comment by javaJake** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3335474/conjure-up.tar.gz)

**Comment by javaJake** [comment]
sosreport just prints:

```
sosreport (version 3.6)

no valid plugins were enabled
```

**Comment by battlemidget** [comment]
It's possible but we include the same snap that upstream builds https://github.com/conjure-up/conjure-up/blob/master/snap/snapcraft.yaml#L39

I'll need to see what else may be going on

**Comment by anastasiamac** [comment]
launchpad bug reference https://bugs.launchpad.net/conjure-up/+bug/1834491. Thank you @battlemidget \o/
