### ISSUE TITLE
conjure-up kubernetes instalation breaks up (ubuntu server 18.04)

### ISSUE THREAD

**Issue by ultimomaximus** [conjure-up/conjure-up#1613]
## Description
Installation is running on Ubuntu Server 18.04 (with 8 Cores CPU, 32GB RAM and 250GB HD)
It started with **_conjure-up kubernetes_** and Kubernetes Core was selected.
After a while _**juju status**_ showed error at App _**containerd**_. Message is _**hook failed: "install"**_
In the generated reports from _collect.py_ I found following error:
ERROR unit.containerd/0.juju-log Unable to find implementation for relation: provides of sdn-plugin 

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.6.5-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.8

which lxc
/usr/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'
/snap/bin/lxc version
Client version: 3.14
Server version: 3.14

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

[results-2019-07-09-21-20-43.tar.gz](https://github.com/conjure-up/conjure-up/files/3374763/results-2019-07-09-21-20-43.tar.gz)

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran
Please outline what commands were run to install and execute conjure-up:
conjure-up kubernetes

## Additional Information
ERROR unit.containerd/0.juju-log Unable to find implementation for relation: provides of sdn-plugin

--
THX

**Comment by jschulthess** [comment]
Same effect here when deploying current kubernetes-core-815 with juju.
