### ISSUE TITLE
Grafana error causes conjure-up to quit (hook failed: "install")

### ISSUE THREAD

**Issue by mechadoll7** [conjure-up/conjure-up#1615]
- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [X] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

```
## Please provide the output of the following commands
which juju
/snap/bin/juju
juju version
2.6.5-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.8

which lxc
/usr/bin/lxc
/usr/bin/lxc config show
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:18.04
config: {}
/usr/bin/lxc version
Client version: 3.0.3
Server version: 3.0.3

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
sosreport (version 3.6)
no valid plugins were enabled

```

The resulting output file can be attached to this issue.

## What Spell was Selected?
Charmed Distribution of Kubernetes

## What provider (aws, maas, localhost, etc)?
VSphere

### MAAS Users
Which version of MAAS?

## Commands ran
conjure-up

Please outline what commands were run to install and execute conjure-up:
conjure-up was available for a quick installation during the initial server set-up

## Additional Information
When I run conjure-up to install the charmed distro of k8s, errors with Grafana cause the conjure-up process to quit. 
```
DEBUG:root:grafana/0 workload status is error since 2019-07-14 13:47:20Z
ERROR:root:grafana/0 failed: workload status is error
2019-07-14 13:47:25,541 [DEBUG] conjure-up/charmed-kubernetes - events.py:52 - Setting Error at conjureup/events.py:149
2019-07-14 13:47:25,543 [ERROR] conjure-up/charmed-kubernetes - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
    await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
    await juju.wait_for_deployment()
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
    "Some applications failed to start successfully.")
```

When doing `juju status`, I see: hook failed: "install". I can't seem to easily find any more detail. I'm also having problems with Filebeat in one of the workers, but I'm omitting that from the issue to avoid confusion.

I'm selecting Graylog, Helm, Kubeflow, and Prometheus when doing the installation. The only place I've deviated from the default configuration is to create 5 workers with 16GB of memory.

Please let me know if you need any more info. 

Any help is much appreciated. Thanks ahead of time.
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3389999/conjure-up.tar.gz)

**Comment by shawnweeks** [comment]
I'm seeing the exact same error on a Maas Install as well. No LXD involved these are installs to managed KVMs.

**Comment by shawnweeks** [comment]
Just found out the issue, the repo for Grafana has [changed](https://grafana.com/blog/2019/01/05/moving-to-packages.grafana.com/). The charm is no longer correct for grafana because it's still trying to use the old repo location.

**Comment by mimpy** [comment]
can somebody fix the charm?

**Comment by mimpy** [comment]
I know how to change it where is the repo for the grafana charm?

**Comment by timClicks** [comment]
@mimpy The upstream repo is hosted in Launchpad. Here's the tracking bug: https://bugs.launchpad.net/grafana-charm/+bug/1844733

**Comment by kwmonroe** [comment]
The outdated grafana charm has been fixed in https://github.com/conjure-up/spells/pull/255
