### ISSUE TITLE
Openstack-Nova with LXD installation with conjure-up fails with neutron-gateway config error, ubuntu 18.04

### ISSUE THREAD

**Issue by camille-rodriguez** [conjure-up/conjure-up#1618]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ no ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ no ] Is conjure-up running inside a virtual machine?
- [ yes ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.6.5-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.8

which lxc
/snap/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'
/snap/bin/lxc version
Client version: 3.15
Server version: 3.15


cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
openstack-nova with lxd

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?

## Commands ran
Please outline what commands were run to install and execute conjure-up:
sudo apt update
sudo apt upgrade
(setup of lxd following the tutorial users of lxd)
sudo snap install conjure-up --classic
conjure-up
(selected openstack-nova on lxd, localhost)

## Additional Information
This bug seems similar to these closed issues: #1475 and  #1173 

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3443109/conjure-up.tar.gz)

[sosreport-node-caloric-20190729154957.tar.gz](https://github.com/conjure-up/conjure-up/files/3443351/sosreport-node-caloric-20190729154957.tar.gz)

Upon installation of openstack -nova with lxd with conjure-up, setup failed due to  applications failing to start. Partial log from conjure-up.log:

> 2019-07-26 19:31:20,020 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting DeploymentComplete at conjureup/controllers/juju/deploy/common.py:37
2019-07-26 19:31:20,022 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Received DeploymentComplete at conjureup/controllers/juju/deploy/common.py:41 in task _wait_for_applications at conjureup/controllers/juju/deploy/gui.py:82
2019-07-26 19:31:20,023 [INFO] conjure-up/openstack-novalxd - common.py:47 - Waiting for deployment to settle.
2019-07-26 20:24:47,774 [ERROR] conjure-up/openstack-novalxd - juju.py:744 - DEBUG:root:ceph-mon/2 workload status is maintenance since 2019-07-26 20:02:49Z
DEBUG:root:ceph-osd/0 workload status is blocked since 2019-07-26 19:54:08Z
DEBUG:root:ceph-osd/1 workload status is blocked since 2019-07-26 19:55:17Z
DEBUG:root:ceph-osd/2 workload status is blocked since 2019-07-26 19:55:17Z
DEBUG:root:ceph-radosgw/0 workload status is waiting since 2019-07-26 20:10:35Z
DEBUG:root:glance/0 workload status is waiting since 2019-07-26 20:24:12Z
DEBUG:root:keystone/0 workload status is waiting since 2019-07-26 20:21:15Z
DEBUG:root:neutron-api/0 workload status is maintenance since 2019-07-26 20:24:21Z
DEBUG:root:neutron-gateway/0 workload status is error since 2019-07-26 20:24:42Z
ERROR:root:neutron-gateway/0 failed: workload status is error
2019-07-26 20:24:47,778 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2019-07-26 20:24:47,780 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<DeployController._wait_for_applications() done, defined at /snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py:81> exception=DeploymentFailure('Some applications failed to start successfully.',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/gui.py", line 82, in _wait_for_applications
	await common.wait_for_applications(view.set_footer)
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/controllers/juju/deploy/common.py", line 50, in wait_for_applications
	await juju.wait_for_deployment()
  File "/snap/conjure-up/1055/lib/python3.6/site-packages/conjureup/juju.py", line 746, in wait_for_deployment
	"Some applications failed to start successfully.")
conjureup.errors.DeploymentFailure: Some applications failed to start successfully.

Most units start successfully except neutron-gateway. Error with message "hook failed:'config-changed' ". See image below:

![image](https://user-images.githubusercontent.com/42066843/62066884-71c52380-b200-11e9-843a-7383e6fa6976.png)

From juju debug-log --level ERROR --replay:
![image](https://user-images.githubusercontent.com/42066843/62066918-81dd0300-b200-11e9-94d8-60401430e356.png)

Also found message in error log:
Can\'t connect to MySQL server on \'10.221.58.7
\' (timed out)") (Background on this error at: http://sqlalche.me/e/e3q8)\n\n' 

Digging into neutron-gateway, I logged into the host machine for this unit. 
![image](https://user-images.githubusercontent.com/42066843/62066961-9c16e100-b200-11e9-8b6d-34215720c860.png)
![image](https://user-images.githubusercontent.com/42066843/62066972-a042fe80-b200-11e9-8eca-a8f6f6cec6b9.png)
![image](https://user-images.githubusercontent.com/42066843/62066977-a46f1c00-b200-11e9-9e99-51906537333c.png)
It looks like there is a mismatch between the OpenVSwitch bridge and the interfaces on the machine. There is an error message  "could not open network device eno2 (No such device)" for the bridge, and there is no eno2 interface to be found in the network config.

**Comment by camille-rodriguez** [comment]
It also looks like a similar issue was hit by the openstack charm team for lxd, I'm wondering if it could be of any help https://bugs.launchpad.net/charm-lxd/+bug/1635659 .

**Comment by camille-rodriguez** [comment]
If conjure-up cannot determine on its own which network interface to use for neutron-gateway, I think there should be an interactive prompt asking the user to select one.

**Comment by fuhsjr00** [comment]
It doesn't appear that anyone is actively working on conjure-up bugs. I would really like an answer to this one.

**Comment by joaopinto** [comment]
I have the exact same problem. Does anyone know a solution or workaround?

**Comment by fuhsjr00** [comment]
If you're looking to get a test system working, I've found that conjure-up with OpenStackKVM on a _6_ node virtual MAAS cluster will work. This means figuring out how to use MAAS, but it was easier than trying to sort out all the things that were wrong with the Workstation deployment.

You'll need 2 NICs and 2 storage drives per PXE-booted node with the default conjure-up configuration.

**Comment by tonyevolutionstar** [comment]
can anyone tell me why openstack doesn't create a instance?
