### ISSUE TITLE
Containerd error on Kubernetes Core spell

### ISSUE THREAD

**Issue by keanesf** [conjure-up/conjure-up#1619]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
**which juju**

/snap/bin/juju

**juju version**

2.6.5-bionic-amd64

**which conjure-up**

/snap/bin/conjure-up

**conjure-up --version**

conjure-up 2.6.8

**which lxc**

/snap/bin/lxc

**/snap/bin/lxc config show**

config:
  core.https_address: '[::]'

**/snap/bin/lxc version**

Client version: 3.15
Server version: 3.15

**cat /etc/lsb-release**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"


```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

kubernetes-core

## What provider (aws, maas, localhost, etc)?

localhost

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

unit-containerd-0: 21:24:06 DEBUG unit.containerd/0.install modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.15.0-55-generic/modules.dep.bin'
unit-containerd-0: 21:24:06 DEBUG unit.containerd/0.install modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.15.0-55-generic
unit-containerd-0: 21:24:07 ERROR unit.containerd/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-containerd-0/charm/reactive/containerd.py", line 262, in enable_br_netfilter_module
    modprobe('br_netfilter', persist=True)
  File "/var/lib/juju/agents/unit-containerd-0/.venv/lib/python3.6/site-packages/charmhelpers/core/kernel.py", line 48, in modprobe
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['modprobe', 'br_netfilter']' returned non-zero exit status 1.

**Comment by wilkmar** [comment]
I can confirm the same problem. Running exactly the same juju, lxc, conjure-up versions on 18.04.
Taking look at the containerd charm:
`$ tail -n 7 reactive/containerd.py
@when_not('containerd.br_netfilter.enabled')
def enable_br_netfilter_module():
    # Fixes https://github.com/kubernetes/kubernetes/issues/21613
    modprobe('br_netfilter', persist=True)
    set_state('containerd.br_netfilter.enabled')`

It uses modprobe. Is it a valid approach when running in LXC container, since all modules should be provided from the host kernel?

**Comment by ian7** [comment]
I can confirm the same issue here :(
