### ISSUE TITLE
Install of kubernetes-core to localhost hanging on "waiting for 6 kube-system pods to start"

### ISSUE THREAD

**Issue by tquid** [conjure-up/conjure-up#1620]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
juju version
2.6.5-bionic-amd64

which conjure-up
/snap/bin/conjure-up
conjure-up --version
conjure-up 2.6.8

which lxc
/snap/bin/lxc
/snap/bin/lxc config show
config:
  core.https_address: '[::]'
  core.trust_password: true
/snap/bin/lxc version
Client version: 3.16
Server version: 3.16

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3527227/conjure-up.tar.gz)
```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
sosreport (version 3.6)

no valid plugins were enabled
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
kubernetes-core
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:
```
sudo snap install conjure-up
conjure-up kubernetes-core
```
## Additional Information
`
juju debug-log` shows repeatedly:
```
unit-kubernetes-worker-0: 13:35:19 DEBUG unit.kubernetes-worker/0.kube-control-relation-changed Error from server (NotFound): nodes "juju-bcf186-1" not found
unit-kubernetes-worker-0: 13:35:19 INFO unit.kubernetes-worker/0.juju-log kube-control:2: Failed to apply label juju-application=kubernetes-worker. Will retry.
```

**Comment by snooksy** [comment]
I have this same problem. I've followed all the steps to make sure IPv6 is disabled. I've confirmed the lxc bridge configuration. I've set Kubernetes to install to a 'dir' storage which is sitting on a new nvme drive. I've tried running it with "sudo snap refresh conjure-up --edge". Both Juju and Conjure-up are failing for me. Both for Charmed Kubernetes and Kubernetes Core. Same issue each time. I'm running bionic latest version with all updates.

**Comment by jschulthess** [comment]
Having the same issues as snooksy. Using 'dir' for storage. Version kubernetes-core-815 fails with said waiting state.
Deployed an older version via juju, cs:bundle/canonical-kubernetes-124, and that works (took forever to start the 10 lxc containers but everything came up).

**Comment by snooksy** [comment]
Please see my other post #1625 where I’ve published a solution.
