### ISSUE TITLE
Install of kubernetes-core  / charmed-kubernetes to localhost 'dir' hanging on Kubernetes-master/0 "waiting for 6 kube-system pods to start"

### ISSUE THREAD

**Issue by snooksy** [conjure-up/conjure-up#1625]
## Report

Please help me, I've spent two days trying to get Kubernetes up on my server.
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/3548385/conjure-up.tar.gz)

- [NO] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [NO] Is conjure-up running inside a virtual machine?
- [YES] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
/snap/bin/conjure-up
conjure-up 2.6.8

/snap/bin/lxc
/snap/bin/lxc config show

config:
  core.https_address: '[::]'

/snap/bin/lxc list
+---------------+---------+-----------------------+------+------------+-----------+
|     NAME      |  STATE  |         IPV4          | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+-----------------------+------+------------+-----------+
| juju-c8ceae-0 | RUNNING | 10.101.64.126 (eth0)  |      | PERSISTENT | 0         |
+---------------+---------+-----------------------+------+------------+-----------+
| juju-d6f29b-0 | RUNNING | 10.115.86.1 (lxdbr0)  |      | PERSISTENT | 0         |
|               |         | 10.101.64.4 (eth0)    |      |            |           |
|               |         | 10.1.56.0 (flannel.1) |      |            |           |
+---------------+---------+-----------------------+------+------------+-----------+
| juju-d6f29b-1 | RUNNING | 10.101.64.43 (eth0)   |      | PERSISTENT | 0         |
|               |         | 10.1.89.0 (flannel.1) |      |            |           |
+---------------+---------+-----------------------+------+------------+-----------+

/snap/bin/lxc profile list
+----------------------------------+---------+
|               NAME               | USED BY |
+----------------------------------+---------+
| default                          | 3       |
+----------------------------------+---------+
| juju-conjure-kubernetes-core-d70 | 2       |
+----------------------------------+---------+
| juju-controller                  | 1       |
+----------------------------------+---------+

 /snap/bin/lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: nvme1
    type: disk
name: default
used_by:
- /1.0/containers/juju-c8ceae-0
- /1.0/containers/juju-d6f29b-0
- /1.0/containers/juju-d6f29b-1

lxc storage list
+------------+-------------+--------+------------------------------------------------+---------+
|    NAME    | DESCRIPTION | DRIVER |                     SOURCE                     | USED BY |
+------------+-------------+--------+------------------------------------------------+---------+
| default    |             | dir    | /var/snap/lxd/common/lxd/storage-pools/default | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-btrfs |             | btrfs  | /var/snap/lxd/common/lxd/disks/juju-btrfs.img  | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
| juju-zfs   |             | zfs    | /var/snap/lxd/common/lxd/disks/juju-zfs.img    | 0       |
+------------+-------------+--------+------------------------------------------------+---------+
| nvme1      |             | dir    | /mnt/nvme                                      | 4       |
+------------+-------------+--------+------------------------------------------------+---------+

/snap/bin/lxc network show lxdbr0
config:
  ipv4.address: 10.101.64.1/24
  ipv4.nat: "true"
  ipv6.address: none
  ipv6.nat: "false"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/juju-c8ceae-0
- /1.0/containers/juju-d6f29b-0
- /1.0/containers/juju-d6f29b-1
managed: true
status: Created
locations:
- none

/snap/bin/lxc version

Client version: 3.16
Server version: 3.16

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

## Sosreport

no valid plugins were enabled


## What Spell was Selected?

kubernetes-core

## What provider (aws, maas, localhost, etc)?

localhost - dir /mnt/nvme1

### MAAS Users
Which version of MAAS?
N/A

## Commands ran

sudo snap refresh conjure-up --classic --edge
conjure-up

## Additional Information

I have this same problem as other users. I've followed all the steps to make sure IPv6 is disabled. I've confirmed the lxc bridge configuration. I've set Kubernetes to install to a 'dir' storage which is sitting on a new nvme drive. I've tried running it with "sudo snap refresh conjure-up --edge". Both Juju and Conjure-up are failing for me. Both for Charmed Kubernetes and Kubernetes Core. Same issue each time. I'm running bionic latest version with all updates. juju-btrfs and juju-zfs lxc storage are being set up by conjure-up.I've removed them before starting new install with conjure-up.

As a point of interest this server is running a separate ZFS pool however I had troubles previously installed charmed k to the ZFS pool so I got a 2TB nvme. 

Logs attached

**Comment by snooksy** [comment]
I've juju ssh'ed into the Kubernetes-master/0 which doesn't come up. 

There is an error in the syslog:

Aug 27 09:48:43 juju-d6f29b-0 kube-apiserver.daemon[13683]: error: error creating self-signed certificates: mkdir /var/run/kubernetes: permission denied
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: snap.kube-apiserver.daemon.service: Main process exited, code=exited, status=1/FAILURE
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: snap.kube-apiserver.daemon.service: Failed with result 'exit-code'.
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: snap.kube-apiserver.daemon.service: Service hold-off time over, scheduling restart.
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: snap.kube-apiserver.daemon.service: Scheduled restart job, restart counter is at 1.
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: Stopped Service for snap application kube-apiserver.daemon.
Aug 27 09:48:43 juju-d6f29b-0 systemd[1]: Started Service for snap application kube-apiserver.daemon.
Aug 27 09:48:43 juju-d6f29b-0 kube-apiserver.daemon[14942]: Error: error creating self-signed certificates: mkdir /var/run/kubernetes: permission denied
Aug 27 09:48:43 juju-d6f29b-0 kernel: [ 1809.372687] kauditd_printk_skb: 19 callbacks suppressed
Aug 27 09:48:43 juju-d6f29b-0 kernel: [ 1809.372688] audit: type=1400 audit(1566899323.923:261): apparmor="DENIED" operation="mkdir" profile="snap.kube-apiserver.daemon" name="/run/kubernetes/" pid=7277 comm="kube-apiserver" requested_mask="c" denied_mask="c" fsuid=0 $

**Comment by snooksy** [comment]
I'm surprised to see the above error for the certificates because this issue was supposed to be fixed. 

juju debug log says:

unit-kubernetes-worker-0: 23:30:42 DEBUG unit.kubernetes-worker/0.update-status Error from server (NotFound): nodes "juju-d6f29b-1" not found
unit-kubernetes-worker-0: 23:30:42 INFO unit.kubernetes-worker/0.juju-log Failed to apply label juju-application=kubernetes-worker. Will retry.

**Comment by snooksy** [comment]
I resolved this issue. For anyone is interested I followed the instructions at:
https://github.com/charmed-kubernetes/bundle/wiki/Deploying-on-LXD

Specifically, the LXC profile created by conjure-up doesn't include the dev kmsg configuration:
  aadisable2:
    path: /dev/kmsg
    source: /dev/kmsg
    type: unix-char

Once I added this I was able to get host -> container port forwarding working and all my containers up and running successfully.

**Comment by vandorjw** [comment]
I want to clarify for anyone following along what needs to be done to solve this.
Once conjure-up gets stuck,  open a new shell and try the following:

`$ juju whoami`

> Controller:  conjure-up-localhost-2f0
> Model:       **conjure-charmed-kubernet-d97**
> User:        admin

Notice the model in use. (I bolded it.)

`$ lxc profile list`

> ```
> +---------------------------------------------------------+---------+
> |                          NAME                           | USED BY |
> +---------------------------------------------------------+---------+
> | default                                                 | 7       |
> +---------------------------------------------------------+---------+
> | juju-conjure-charmed-kubernet-d97                       | 6       |
> +---------------------------------------------------------+---------+
> | juju-conjure-charmed-kubernet-d97-kubernetes-master-747 | 1       |
> +---------------------------------------------------------+---------+
> | juju-controller                                         | 1       |
> +---------------------------------------------------------+---------+
> ```

There is a profile that matches the current model that juju is working with.
We want to edit this.

`$ lxc profile show juju-conjure-charmed-kubernet-d97`

You should see something like [this](https://github.com/charmed-kubernetes/bundle/wiki/Deploying-on-LXD#the-profile), but missing **aadisable2**

`$ lxc profile edit juju-conjure-charmed-kubernet-d97`
Hopefully you are familiar with Vi.

One you have made the change, just keep waiting.
This worked for me. Thank you @snooksy for posting your investigation!
