### ISSUE TITLE
Juju controller installation fails - SSH connection fails

### ISSUE THREAD

**Issue by skarux** [conjure-up/conjure-up#1650]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [X] Is conjure-up running inside a virtual machine?
- [X] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
$> which juju
/snap/bin/juju
$> juju version
2.7.6-focal-amd64

$> which conjure-up
/snap/bin/conjure-up
$> conjure-up --version
conjure-up 2.6.12

$> which lxc
snap/bin/lxc
$> /snap/bin/lxc config show
config:
  core.https_address: '[::]'
  core.trust_password: true
$> /snap/bin/lxc version
Client version: 4.0.1
Server version: 4.0.1
$> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/4570455/conjure-up.tar.gz)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
```
kubernetes
```
## What provider (aws, maas, localhost, etc)?
```
localhost
```

## Commands ran

Please outline what commands were run to install and execute conjure-up:
```
sudo snap install conjure-up --classic --edge
conjure-up kubernetes
```

## Additional Information
With or without --edge it's the same.
The commands have been performed on a clean ubuntu server 20.04 installation.

The main error provided by conjure-up log is this one:
```
'Installing Juju agent on bootstrap instance', 'Fetching Juju GUI 2.15.3', 'Waiting for address', 'Attempting to connect to 10.145.67.22:22', 'ERROR failed to bootstrap model: waited for 20m0s without being able to connect: ssh: symbol lookup error: /snap/core18/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE']
```

**Comment by ficcaglia** [comment]
I also see this same issue on AWS EC2 Ubuntu 20.04 AMI
ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423 (ami-09dd2e08d601bff67)
