### ISSUE TITLE
The installation does not start . I am with ppa:conjure-up/daily-git

### ISSUE THREAD

**Issue by moula** [conjure-up/conjure-up#252]
moula@maas:~$ MAAS Version 2.0.0 (rc2+bzr5156)^C
moula@maas:~$ juju --version
2.0-beta12-xenial-amd64
moula@maas:~$ openstack --version
openstack 2.3.0
moula@maas:~$ conjure-up --version
conjure-up 2.0.0
moula@maas:~$ conjure-up openstack
[info] Loading current openstack spells from Juju Charmstore, please wait.
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 225, in main
    extra_info = bundle['Meta']['extra-info/conjure']
KeyError: 'extra-info/conjure'

**Comment by battlemidget** [comment]
whats the output of

```
dpkg -l conjure-up
```

**Comment by moula** [comment]
dpkg -l conjure-up
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
|
État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version      Architecture Description
+++-==============-============-============-=================================
ii  conjure-up     2.0.0.5-0~46 all          Package runtime for
apt-installab

2016-07-17 14:59 GMT+02:00 Adam Stokes <notifications@github.com>:

**Comment by battlemidget** [comment]
You aren't using the daily-git package, you need to do:

```
sudo apt remove conjure-up
```

Then remove the existing conjure up repos in `/etc/apt/sources.list.d`

Then add the daily-git ppa:

```
sudo apt-add-repository ppa:conjure-up/daily-git
sudo apt update
sudo apt install conjure-up
conjure-up openstack
```

**Comment by moula** [comment]
Merci Adam, 
it works, 
![capture du 2016-07-17 16-12-37](https://cloud.githubusercontent.com/assets/1804815/16901118/f94a77ae-4c39-11e6-8c84-2921de933d19.png)
![machines_maas_maas_-_2016-07-17_16 16 39](https://cloud.githubusercontent.com/assets/1804815/16901127/1c0600c4-4c3a-11e6-922b-b36770895983.png)

I'll keep my testes

**Comment by moula** [comment]
Sorry Adam, Installation fails a gain :-) 
![capture du 2016-07-17 19-04-09](https://cloud.githubusercontent.com/assets/1804815/16901954/ce1d2bc2-4c51-11e6-968c-e672a1c68f82.png)
![capture du 2016-07-17 19-04-32](https://cloud.githubusercontent.com/assets/1804815/16901956/d3f37394-4c51-11e6-9ceb-92f6279fed43.png)

**Comment by battlemidget** [comment]
It is saying connection timed out trying to access the charm store. It could be an issue on their end, can you try again and see if the problem persists?

**Comment by moula** [comment]
Bonjour Adam, 
The problem persists. 
Jul 18 07:49:28 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 400, in _deploy_async#012    params={"url": service.csid.as_str()})#012  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'cannot retrieve charm "cs:xenial/ceph-mon-1": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/xenial/ceph-mon-1/archive: dial tcp 162.213.33.122:443: getsockopt: connection timed out')
![capture du 2016-07-18 07-49-08](https://cloud.githubusercontent.com/assets/1804815/16906725/b51421ce-4cbc-11e6-9ff3-c1bb728358f7.png)

**Comment by battlemidget** [comment]
I can only assume that you aren't able to reach the internet from that system. Is this a MAAS node or MAAS itself?

**Comment by moula** [comment]
I try to déploy a cluster bare-métal with 7 servers. ( like autopilot)
1 - server maas

and 6 like nodes from the cluster.

I can ping the web from the maas server. The IPMI it's working fine.The
nodes are deployed!!!!!

i don't hnow where is the problem!!!!

Merci.


2016-07-18 15:00 GMT+02:00 Adam Stokes <notifications@github.com>:

**Comment by battlemidget** [comment]
Do you have IP Forwarding enabled on your maas server? And iptables setup for NAT?

**Comment by moula** [comment]
yes,


moula@maas:~$ sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)

target     prot opt source               destination
MASQUERADE  all  --  10.99.0.0/24        !10.99.0.0/24


and :

sudo ufw status
[sudo] Mot de passe de admin :
État : actif

Vers                       Action      De
----                       ------      --
80                         ALLOW       Anywhere
22                         ALLOW       Anywhere
443                        ALLOW       Anywhere
80 (v6)                    ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)


2016-07-18 15:48 GMT+02:00 Adam Stokes <notifications@github.com>:

**Comment by battlemidget** [comment]
So from one of your deployed nodes can you `wget  https://api.jujucharms.com/charmstore/v5/xenial/ceph-mon-1/archive`? Are you behind a proxy?

**Comment by moula** [comment]
with up-to - date this morning, my plant has advanced, but I have other bugs
![capture du 2016-07-19 12-11-02](https://cloud.githubusercontent.com/assets/1804815/16946742/60aaa4ce-4dab-11e6-871b-5807a719b12a.png)
![capture du 2016-07-19 12-09-41](https://cloud.githubusercontent.com/assets/1804815/16946745/648c5772-4dab-11e6-83b2-5313b88d4a03.png)

**Comment by battlemidget** [comment]
Can you attach your /var/log/conjure-up/openstack?

**Comment by moula** [comment]
Bonjour Adam, 
Sorry but my problem is still there and I think there has been regression with new versions , like the passage of OpenStack version 2 to version 1.0.7 ...
I do not see why I can not  wget the  packages !! I'm not not behind a proxy and my network and firewall seem okay.

moula@maas:~$ dpkg -l maas
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                      Version           Architecture      Description
+++-========================-=================-=================-======================================================
ii  maas                     2.0.0~rc2+bzr5156 all               "Metal as a Service" is a physical cloud and IPAM
moula@maas:~$ dpkg -l juju
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                      Version           Architecture      Description
+++-========================-=================-=================-======================================================
ii  juju                     2.0-beta12~201607 all               next generation service orchestration system
moula@maas:~$ dpkg -l conjure-up
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                      Version           Architecture      Description
+++-========================-=================-=================-======================================================
ii  conjure-up               2.0.0.7-0~2016071 all               Package runtime for apt-installable juju bundles
moula@maas:~$ dpkg -l openstack
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                      Version           Architecture      Description
+++-========================-=================-=================-======================================================
ii  openstack                1.0.7.16.04.1     all               Ubuntu OpenStack Installer

moula@maas:~$ sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  10.99.0.0/24        !10.99.0.0/24        

moula@maas:~$ sudo tail -f /var/log/conjure-up/openstack.log 
Jul 21 09:46:24 maas conjure-up/openstack: [DEBUG] juju.py:137 - bootstrap cmd: juju bootstrap lucila maas/10.1.1.10 --upload-tools --config image-stream=daily --config enable-os-upgrade=false --bootstrap-series=xenial --credential lucila
Jul 21 09:46:24 maas conjure-up/openstack: [DEBUG] gui.py:59 - Rendering GUI controller for Variant
Jul 21 09:46:26 maas conjure-up/openstack: [DEBUG] gui.py:29 - Chosen spell: openstack
Jul 21 09:46:26 maas conjure-up/openstack: [DEBUG] download.py:82 - Extracting spell: bsdtar -xf /tmp/tmpmxwoz_rr/temp.zip -C /home/moula/.cache/conjure-up/openstack
Jul 21 09:46:43 maas conjure-up/openstack: [DEBUG] gui.py:25 - Rendering bootstrap wait
Jul 21 10:03:13 maas conjure-up/openstack: [DEBUG] gui.py:28 - handle bootstrap
Jul 21 10:03:15 maas conjure-up/openstack: [DEBUG] gui.py:76 - Checking for post bootstrap task: /home/moula/.cache/conjure-up/openstack/conjure/steps/00_post-bootstrap
Jul 21 10:03:16 maas conjure-up/openstack: [DEBUG] gui.py:44 - Running pre-deployment tasks.
Jul 21 10:03:16 maas conjure-up/openstack: [DEBUG] gui.py:67 - pre_deploy_done: {'isComplete': True, 'message': 'Successful pre-deploy.', 'returnCode': 0}
Jul 21 10:07:31 maas conjure-up/openstack: [ERROR] __init__.py:28 - Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 400, in _deploy_async#012    params={"url": service.csid.as_str()})#012  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'cannot retrieve charm "cs:xenial/ceph-mon-1": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/xenial/ceph-mon-1/archive: dial tcp 162.213.33.121:443: getsockopt: connection timed out')
Jul 21 10:11:45 maas conjure-up/openstack: [ERROR] __init__.py:28 - Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 400, in _deploy_async#012    params={"url": service.csid.as_str()})#012  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'cannot retrieve charm "cs:xenial/ceph-osd-2": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/xenial/ceph-osd-2/archive: dial tcp 162.213.33.121:443: getsockopt: connection timed out')
Jul 21 10:16:00 maas conjure-up/openstack: [ERROR] __init__.py:28 - Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 400, in _deploy_async#012    params={"url": service.csid.as_str()})#012  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'cannot retrieve charm "cs:xenial/ceph-radosgw-3": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/xenial/ceph-radosgw-3/archive: dial tcp 162.213.33.122:443: getsockopt: connection timed out')
![networks_maas_maas_-_2016-07-21_10 07 05](https://cloud.githubusercontent.com/assets/1804815/17015826/8086f66c-4f2c-11e6-82f2-bcc210ae11cd.png)
![capture du 2016-07-21 10-17-45](https://cloud.githubusercontent.com/assets/1804815/17015857/a49cea66-4f2c-11e6-8ac8-76a0a8afe327.png)

**Comment by battlemidget** [comment]
This is clearly a network issue on your side,  you may want to seek support from http://askubuntu.com on making sure your MAAS is configured correctly.

**Comment by moula** [comment]
Merci Adam,
I will review that and will continue testing.


2016-07-21 13:15 GMT+02:00 Adam Stokes <notifications@github.com>:
