### ISSUE TITLE
conjure-up doesn't appear to work in charmbox

### ISSUE THREAD

**Issue by chuckbutler** [conjure-up/conjure-up#279]
x-ref with https://github.com/juju-solutions/charmbox/issues/41

conjure-up doesn't complete successfully in charmbox flavors (:latest, and :devel) This bug is linked to track across both projects for steps required to address.

For reference, charmbox is: [on the docker hub](https://hub.docker.com/r/jujusolutions/charmbox/)

**Comment by kwmonroe** [comment]
fyi, failure in _connect_unixsocket: http://paste.ubuntu.com/20331200/

**Comment by battlemidget** [comment]
Fixed upstream
