### ISSUE TITLE
Support logging to flatfile

### ISSUE THREAD

**Issue by chuckbutler** [conjure-up/conjure-up#282]
Started in #279 

It would be nice to support skipping syslog logging all together. Specifically when conjure is being used in the context of automation. 

We can work around #279 by mapping in a syslog dev device: /dev/log into the container. This works primarily in boot2docker, and other linux host scenarios. Skipping the socket and going to flat file has benefits of not requiring the end user to have a syslog service running, and directional output for archival purposes (if required). 

This can be by flag to override any configuration stemming from packaging or env var?

I'm fine with either, and feel that it should be a tuneable option.

**Comment by battlemidget** [comment]
This actually helps 2 cases, using docker and the recent snap building since we won't have access to /var/log

**Comment by chuckbutler** [comment]
Awesome, thanks for the fix @battlemidget 

I'll try to get some testing in this week with charmbox so we can close those issues out as well
