### ISSUE TITLE
look better on white backgrounds

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#283]
The contrast and/or color choice for conjure-up aren't well suited for white terminal backgrounds.  Here's what it looks like:

http://imgur.com/14EaKkB

The summary panel is even harder to make out.  Can we find something else that looks good in both light and dark terminals?

**Comment by battlemidget** [comment]
Yea that is pretty hard to see, I'll mess with the color palette and see what we can do
