### ISSUE TITLE
conjure-up bigdata:  wget failure

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#285]
I ran `conjure-up bigdata` and selected the apache processing mapreduce bundle.  This failed with:

```
Exception: Unable to download https://api.jujucharms.com/charmstore/v5/bundle/apache-processing-mapreduce-3/archive: Command 'wget -qO /tmp/tmp8qpa6npk/temp.zip https://api.jujucharms.com/charmstore/v5/bundle/apache-processing-mapreduce-3/archive' returned non-zero exit status 127
```

Seems the url that specifies a revno doesn't work.

Bad:
```
https://api.jujucharms.com/charmstore/v5/bundle/apache-processing-mapreduce-3/archive
```

Good:
```
https://api.jujucharms.com/charmstore/v5/bundle/apache-processing-mapreduce/archive
```

**Comment by mikemccracken** [comment]
I was able to pull the link with the revno just now.

error 127 suggests that the shell couldn't find wget. where were you running this?

**Comment by battlemidget** [comment]
Worse case we should check for this and give a decent error on how to resolve it

**Comment by kwmonroe** [comment]
Yup yup, you were right.. I was running this from within charmbox (which is a docker container that does not install wget by default).  Perhaps add `wget` to the dep list for apt installing conjure-up?

And you're right -- the rev in the link in my initial comment was not the problem.  I had just pushed rev3 of that bundle and it seems there is a small lag between 'charm publish' and that api link being available.  I am now able to wget the previously mentioned bad link.

**Comment by battlemidget** [comment]
Thanks we'll get that package dep added

**Comment by battlemidget** [comment]
Fixed in next release.
