### ISSUE TITLE
Traceback error if a spell has no steps

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#286]
a spell with no steps gets a 'deque index out of range' error

**Comment by battlemidget** [comment]
Was afraid of that

**Comment by battlemidget** [comment]
Should we always require at least 1 step? Even if it's something simple like "go to this address to see your new app"

**Comment by mikemccracken** [comment]
wouldn't that fit in the summary screen? I think it ought to be fine to
have no steps.
