### ISSUE TITLE
neutron API error using 1.0 needs 2.0

### ISSUE THREAD

**Issue by gorblimey** [conjure-up/conjure-up#288]
using 'conjure-up -d openstack' with default settings on 4 node bundle.
- conjure-up               2.0.0.7-0~201607222212
- juju                           2.0-beta13-0ubuntu1~16.04.1
- maas                       2.0.0~rc2+bzr5156-0ubuntu2~16.04.3
here's the message in the conjuring up window. attached combined.log
[combined-log.txt](https://github.com/ubuntu/conjure-up/files/380098/combined-log.txt)
----------------------------------------------------------------------------------------------------------------------------------------
neutron-api/0                                      error                                           
                   cannot add a new machine: ServerError: 410 GONE (The 1.0 API is no longer available. Please use  
                   API version 2.0.)
----------------------------------------------------------------------------------------------------------------------------------------

**Comment by battlemidget** [comment]
This will be fixed over in https://github.com/battlemidget/openstack-bundles/tree/patch-conjurfied/stable/openstack-base, ill leave it open here so you can track when i get that spell updated.

thanks for the report

**Comment by mikemccracken** [comment]
@battlemidget is this done now?
