### ISSUE TITLE
display a list of current controllers or option to deploy new

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#294]
We start off with a list of spells to deploy, the next view should contain either a list of known controllers or ability to create a new controller

**Comment by mikemccracken** [comment]
Need clarification here, should this view be shown if there are not any controllers at all yet? In that case we will have to show the 'newcloud' view anyway, so we might as well skip to that, right?

**Comment by battlemidget** [comment]
@mikemccracken yea skip to that if nothing previously exist
