### ISSUE TITLE
Conjure-up - Unable to get juju version

### ISSUE THREAD

**Issue by JoeDoe00** [conjure-up/conjure-up#296]
Hoping this is easy;

When I try a conjure-up openstack; I get an Unable to get juju version message, whether the environment is bootstrapped or not. 

If I just run juju version I get and access denied. If I run sudo conjure-up openstack, I get an error that tells me its a nono.

What to do?

Dee vee

**Comment by battlemidget** [comment]
So `juju version` fails for you?

**Comment by JoeDoe00** [comment]
juju version
    Welcome to Juju 2.0-beta13. If you meant to use Juju 1.x you can continue using it
    with the command juju-1 e.g. 'juju-1 switch'.
    See https://jujucharms.com/docs/stable/introducing-2 for more details.
error: cannot load ssh client keys: mkdir /home/user/.local/share: permission denied

sudo juju version
[sudo] password for user: 
2.0-beta13-xenial-amd64


If I run conjure-up openstack; I get Unable to get juju version. I can't run sudo conjure-up openstack.

Should I just change permissions on the directory?

**Comment by battlemidget** [comment]
No dont change the permissions, I'll try and reproduce this and see whats going on.

**Comment by DBassel** [comment]
+1. same issue

**Comment by battlemidget** [comment]
This is addressed upstream as we will be packaging this as a snap

**Comment by DBassel** [comment]
could you please provide the upstream issue number?

**Comment by battlemidget** [comment]
You can just run:

```
sudo apt-get remove conjure-up
sudo snap install conjure-up
/snap/bin/conjure-up
```

Keep in mind we're still working to get the OpenStack spells working inside snaps. All other spells do work though.
