### ISSUE TITLE
No available machine matches constraints: zone=default`

### ISSUE THREAD

**Issue by impfrost** [conjure-up/conjure-up#331]
`Aug  5 19:01:07 maas conjure-up/openstack: [ERROR] Failure in deploy done: Machine creation errors:#0124: cannot run instances: cannot run instance: No available machine matches constraints: zone=default`
`Aug  5 19:01:07 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjureup/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Machine creation errors:#0124: cannot run instances: cannot run instance: No available machine matches constraints: zone=default`

is this a bug or configuration error?

**Comment by impfrost** [comment]
`Aug  6 07:46:44 maas conjure-up/openstack: [ERROR] Failure in deploy done: Machine creation errors:#0123: cannot run instances: cannot run instance: No available machine matches constraints: zone=default`
`Aug  6 07:46:44 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjureup/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Machine creation errors:#0123: cannot run instances: cannot run instance: No available machine matches constraints: zone=default`


had this again now when trying to setup nova lxd

it seems like he wants even more then 6 VM's to deploy to.

**Comment by impfrost** [comment]
`Aug  7 16:50:28 maas conjure-up/openstack: [ERROR] Failure in deploy done: Deployment errors:#012neutron-gateway/0: hook failed: "config-changed"
Aug  7 16:50:28 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjureup/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Deployment errors:#012neutron-gateway/0: hook failed: "config-changed"`

another error today. has anyone ever successfully deployed openstack? i have a manual install running on other systems but this is just a nightmare

**Comment by impfrost** [comment]
first of all the list of packages 

`
root@maas:/var/log/quagga# dpkg -l | grep -E -i "conjure|lxd|juju|maas"
ii  charm                              2.1.1-0ubuntu1                       amd64        Tool for publishing and maintaining Juju charms
ii  charm-tools                        2.1.2-0ubuntu4                       all          Tools for maintaining Juju charms
ii  conjure-up                         2.0.0.7-0~201607261916~ubuntu16.04.1 all          Package runtime for apt-installable juju bundles
ii  juju                               2.0-beta14-0ubuntu1~16.04.2~juju1    all          next generation service orchestration system
ii  juju-2.0                           2.0-beta14-0ubuntu1~16.04.2~juju1    amd64        Juju is devops distilled - client
ii  lxd                                2.0.3-0ubuntu2~ubuntu16.04.1~ppa1    amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                         2.0.3-0ubuntu2~ubuntu16.04.1~ppa1    amd64        Container hypervisor based on LXC - client
ii  maas                               2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          "Metal as a Service" is a physical cloud and IPAM
ii  maas-cli                           2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS client and command-line interface
ii  maas-common                        2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS server common files
ii  maas-dhcp                          2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS DHCP server
ii  maas-dns                           2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS DNS server
ii  maas-proxy                         2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS Caching Proxy
ii  maas-rack-controller               2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          Rack Controller for MAAS
ii  maas-region-api                    2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          Region controller API service for MAAS
ii  maas-region-controller             2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          Region Controller for MAAS
ii  python-jujubundlelib               0.4.1-0ubuntu1                       all          Python 2 library for working with Juju bundles
ii  python-libcharmstore               0.0.3-0ubuntu1                       all          Python library to access Juju charmstore data
ii  python-theblues                    0.2.0-0ubuntu1                       all          Python library for using the Juju charm store API
ii  python3-django-maas                2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS server Django web framework (Python 3)
ii  python3-maas-client                2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS python API client (Python 3)
ii  python3-maas-provisioningserver    2.0.0~rc3+bzr5180-0ubuntu2~16.04.1   all          MAAS server provisioning libraries (Python 3)
`

my setup is 

ubuntu 16.0.4.1 running vmware workstation 12 which runs esxi6 and is connected to a vcenter 6.
i have 5 boxes setup like this. all are connected to cisco switches. storage comes with iscsi qnap.

i want to setup either one novalxd or/and just openstack.

**Comment by battlemidget** [comment]
If you run the novalxd one then it'll take up at least 15 machines as it is really meant for a single machine install utilizing all containers. The plain 'openstack' one requires less machines but uses the KVM virt-type for the nova compute instances. You will also need to have 2 network device associated with your VM so that your neutron-gateway can be configured properly. It uses the default 'eth1' as the management network.

**Comment by impfrost** [comment]
ok so i setup 16 vm's this time and it deployed 13 but then failed again with that:

`
Aug  8 22:24:03 maas conjure-up/openstack: [ERROR] Failure in deploy done: Deployment errors:#012keystone/0: hook failed: "shared-db-relation-changed" for mysql:shared-db
`
`
Aug  8 22:24:03 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjureup/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Deployment errors:#012keystone/0: hook failed: "shared-db-relation-changed" for mysql:shared-db
`

**Comment by battlemidget** [comment]
can you get me the output of:

```
juju status --format yaml
```

And also

```
juju ssh mysql/0
sudo pastebinit /var/log/juju/unit-mysql-0.log
```

**Comment by impfrost** [comment]
http://paste.ubuntu.com/22770731/

**Comment by impfrost** [comment]
another error

`
Aug  9 06:28:49 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjureup/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Deployment errors:#012neutron-gateway/0: hook failed: "config-changed"
`

**Comment by impfrost** [comment]
i figured that the deployment goes on in the background and this is the final state.

http://paste.ubuntu.com/22798947/

**Comment by battlemidget** [comment]
Try:

```
juju resolved --retry keystone/0
```

And see if keystone corrects itself. I'll try and reproduce this issue here locally as well

**Comment by impfrost** [comment]
tried that already. didnt help. i tried also without --retry to see if this gets me anywhere but it doesnt

**Comment by battlemidget** [comment]
k. ill try to reproduce in my maas lab.

**Comment by impfrost** [comment]
anything you could find out so far. im stuck.

**Comment by battlemidget** [comment]
I haven't been able to reproduce this yet, still investigating

**Comment by impfrost** [comment]
![1](https://cloud.githubusercontent.com/assets/20782882/17620383/43021314-608c-11e6-83cd-ec69f859a322.png)

check that out. juju status says 16 nodes are deployed but maas says 17. im not sure if that has anything to do with it but its strange. i havent deployed as a single node.

**Comment by mikemccracken** [comment]
juju uses a separate node as an infrastructure server - they deploy it under a different juju 'model', so if you want to see it in the juju status output you will need to `juju switch` to that model.

To see the list of models, run `juju models`. One of them will be named `controller` (Yes a model named 'controller', inside a controller that was created by `juju bootstrap` - the terminology is a little confusing). The one you are using is probably named `default`, it's created for you when you bootstrap.

If you do `juju switch controller`, that switches to the model named 'controller', and then `juju status` should show the machine you are curious about.

**Comment by impfrost** [comment]
mike thanks for explaining that.

**Comment by mikemccracken** [comment]
It's been over a month so I'm going to close this now. Please feel free to file a new issue if you have further problems.
