### ISSUE TITLE
non standard bridge juju failure

### ISSUE THREAD

**Issue by niccolox** [conjure-up/conjure-up#37]
I am running lxd on br0 and not lxdbr0 - so I can ssh and connect via lan to my lab servers lxd containers

I can work with lxd containers from lxc command line and also the new Ansible cloud provisioner lxd containers (a PR I think still in 2.2)

`conjure-up bigdata`

fails

`conjure.juju.JujuNotFoundException: Unable to list models: ['ERROR cannot find network interface "lxdbr0": route ip+net: no such network interface', 'ERROR cannot list models: constructing environ: invalid config: route ip+net: no such network interface']
`

when I run juju 2 lxd provider separately to conjure up I get similar errors

https://github.com/juju/juju/issues/5439#issuecomment-220808972

**Comment by battlemidget** [comment]
Thanks for the report, I'll be tracking this fix at https://bugs.launchpad.net/juju-core/+bug/1575676 since we use Juju under the hood. I'll update this bug once that gets fixed.

**Comment by niccolox** [comment]
just cranked it up with default bridge in a vmware vm xenial desktop and it worked great

**Comment by battlemidget** [comment]
Awesome! I'll make sure to keep bringing this issue up for the Juju guys to address

**Comment by BlueT** [comment]
I'm facing similar problem.

I followed this HowTo https://bayton.org/2016/05/lxd-zfs-and-bridged-networking-on-ubuntu-16-04-lts/ and changed the br0 name to **lxdbr0**.
LXD runs perfectly with br0 (with external DHCP server), so containers can get an IP in my network and we can connect into it.

With `conjure-up openstack` and the option "OpenStack with Nova-LXD", Clouds choose "localhost", after a short bootstraping screen then it says my lxdbr0 is not enabled...

![2016-06-04 07 24 14](https://cloud.githubusercontent.com/assets/51141/15795599/9f5cab58-2a25-11e6-824b-d101e3ae1355.png)

**Comment by niccolox** [comment]
Its been a limitation for quite a while and it would be great to get an
idea of when it will be fixed

I'm facing similar problem.

I followed this HowTo
https://bayton.org/2016/05/lxd-zfs-and-bridged-networking-on-ubuntu-16-04-lts/
and changed the br0 name to *lxdbr0*.
LXD runs perfectly with br0 (with external DHCP server), so containers can
get an IP in my network and we can connect into it.

With conjure-up openstack and the option "OpenStack with Nova-LXD", Clouds
choose "localhost", after a short bootstraping screen then it says my
lxdbr0 is not enabled...

[image: 2016-06-04 07 24 14]
<https://cloud.githubusercontent.com/assets/51141/15795599/9f5cab58-2a25-11e6-824b-d101e3ae1355.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/conjure-up/issues/37#issuecomment-223717858>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAbspsK_ZlQQNzWcmRkBnYwLTdyJK1wuks5qILgtgaJpZM4Il5Zz>
.

**Comment by battlemidget** [comment]
Ive pinged the Juju team again to see if we can get this addressed in Juju 2.0.0

**Comment by battlemidget** [comment]
We're seeing movement on the launchpad bug now with someone actively working it.  I'll post updates here when i know more.

**Comment by BlueT** [comment]
Seems fixed? Anyone can confirm?
https://bugs.launchpad.net/juju/+bug/1575676
https://github.com/juju/juju/pull/5871

**Comment by battlemidget** [comment]
I need to follow up with Juju team

**Comment by battlemidget** [comment]
This seems fixed now after doing the steps in https://github.com/juju/juju/pull/5871, @niccolox can you try this out now?
