### ISSUE TITLE
snap install issue -- snap.conjure-up.bridge.service failed

### ISSUE THREAD

**Issue by JoeDoe00** [conjure-up/conjure-up#376]
Follow up to #296 
When trying to install the snap, get the following:
(have br0 on system)

sudo snap install conjure-up

error: cannot perform the following tasks:
- Make snap "conjure-up" (25) available to the system ([start snap.conjure-up.bridge.service] failed with exit status 1: Job for snap.conjure-up.bridge.service failed because the control process exited with error code. See "systemctl status snap.conjure-up.bridge.service" and "journalctl -xe" for details.

**Comment by JoeDoe00** [comment]
systemctl output

 snap.conjure-up.bridge.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Tue 2016-08-30 10:32:29 EDT; 5min ago
 Main PID: 7357 (code=exited, status=126)

Aug 30 10:32:29 sys1 ubuntu-core-launcher[7357]: /snap/conjure-up/25/bridge.start: 15: /snap/conjure-up/25/bridge.start: iptables: Permission denied
Aug 30 10:32:29 sys1 ubuntu-core-launcher[7357]: + iptables -I INPUT -i conjureup0 -p tcp -m tcp --dport 67 -j ACCEPT
Aug 30 10:32:29 sys1 ubuntu-core-launcher[7357]: /snap/conjure-up/25/bridge.start: 16: /snap/conjure-up/25/bridge.start: iptables: Permission denied
Aug 30 10:32:29 sys1 ubuntu-core-launcher[7357]: + iptables -I INPUT -i conjureup0 -p udp -m udp --dport 67 -j ACCEPT
Aug 30 10:32:29 sys1 ubuntu-core-launcher[7357]: /snap/conjure-up/25/bridge.start: 17: /snap/conjure-up/25/bridge.start: iptables: Permission denied
Aug 30 10:32:29 sys1 systemd[1]: snap.conjure-up.bridge.service: Main process exited, code=exited, status=126/n/a
Aug 30 10:32:29 sys1 systemd[1]: Failed to start Service for snap application conjure-up.bridge.
Aug 30 10:32:29 sys1 systemd[1]: snap.conjure-up.bridge.service: Unit entered failed state.
Aug 30 10:32:29 sys1 systemd[1]: snap.conjure-up.bridge.service: Failed with result 'exit-code'.
Aug 30 10:32:29 sys1 systemd[1]: Stopped Service for snap application conjure-up.bridge.

**Comment by battlemidget** [comment]
Ah, you need to do

```
snap install conjure-up --devmode
```

The `--devmode` is required for now.

**Comment by JoeDoe00** [comment]
Thanks, that took care of it!

**Comment by battlemidget** [comment]
Just FYI we are still having issues getting an openstack deployment inside a snap but the other public clouds and spells should work. It's just the combination of LXD, Juju, and conjure-up that is failing

**Comment by JoeDoe00** [comment]
Is there a bug I can track for this issue?

**Comment by battlemidget** [comment]
Not at this time, it's recommended to stick with the debian packaging
