### ISSUE TITLE
can't edit unit count

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#418]
The num_units in application list view is currently not editable.

Note: it might be nice to have the ability to show a message about appropriate values of scale for the user.

Up for discussion: should we edit it inline, or make it part of the configure screen?
If it's part of the configure screen, we have room to show an info message.
However, if we put it there, we always have to show the configure button, and the configure screen will often be just the num_units edit widget by itself, since many charms don't have whitelisted options (yet). 

If we think most charms will have at least one option whitelisted eventually, it might make sense to just put it in the config screen.

**Comment by mikemccracken** [comment]
@battlemidget see question above, what do you think

**Comment by battlemidget** [comment]
Should at least have num units editable in the separate configure screen and leave it read only in the application list (we already discussed just putting here for reference)

**Comment by battlemidget** [comment]
This was fixed with #430
