### ISSUE TITLE
Exception: Unable to determine current controller (from juju.py; line 103)

### ISSUE THREAD

**Issue by mnama** [conjure-up/conjure-up#436]
~$ conjure-up openstack
Throwing an error saying "" when I select "OpenStack with NovaLXD" & selecting "localhost" from the next screen; from the GUI/wizard menu option.

What controller should I install before conjuring-up openstack?
I've no controllers installed yet.  I'm just trying to setup the entire stack on a laptop for the first time.  Appreciate your help!

~$ juju controllers
CONTROLLER  MODEL  USER  CLOUD/REGION

~$ 

---------------------Console output---------------
~$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3/dist-packages/ubuntui/views/error.py", line 42, in cancel
    raise SystemExit("Install exited because of error.")
SystemExit: Install exited because of error.
Install exited because of error.
~$ 
---------------------END: Console output---------------

**Comment by battlemidget** [comment]
Which version of juju and conjure-up are you running?

**Comment by mnama** [comment]
juju: 2.0-beta15-xenial-i386
conjure-up: 2.0.1~beta1

**Comment by battlemidget** [comment]
ah right, you need to add `ppa:juju/devel` and update juju. I need to fix the instructions on the webpage

**Comment by mnama** [comment]
Tnx, will check it tonight and update here...

**Comment by mnama** [comment]
went through my command history, I had done that.  Looks like I read it somewhere...

~$ sudo apt-add-repository ppa:juju/devel
~$ sudo apt update

Did it again, just to make sure.  It did some downloads and made some updates, but when I try to conjure-up openstack, it throws the same error.  Still no juju controllers...

**Comment by mikemccracken** [comment]
Hi @mnama, my apologies if you did this but just didn't mention it, but just in case:
did you also do `sudo apt install juju` again after the `sudo apt update` ?
`update` will only update the package index, it doesn't install any new package versions.
you can check what version you have installed compared to what the latest version that apt-get knows about by using the command `sudo apt-cache policy juju`.

You will see output something like this. The list is ordered with the newest releases at the top, and the one you have currently installed is marked with `***`. In this case, there are two newer versions available in the various PPAs I have installed on this system, 2.0-rc1 (from juju/devel) and 2.0-rc2 (from juju/daily).

```
juju:
  Installed: 2.0-beta16-0ubuntu1~16.04.1~juju1
  Candidate: 2.0-rc2~20160921~4415~bad2931b-20160921+4415+bad2931b~16.04
  Version table:
     2.0-rc2~20160921~4415~bad2931b-20160921+4415+bad2931b~16.04 500
        500 http://ppa.launchpad.net/juju/daily/ubuntu xenial/main amd64 Packages
     2.0-rc1-0ubuntu1~16.04.1~juju1 500
        500 http://ppa.launchpad.net/juju/devel/ubuntu xenial/main amd64 Packages
 *** 2.0-beta16-0ubuntu1~16.04.1~juju1 100
        100 /var/lib/dpkg/status
     2.0-beta15-0ubuntu1~16.04.1~juju1 500
        500 http://ppa.launchpad.net/juju/devel/ubuntu xenial/main amd64 Packages
     2.0-beta8~20160603~4022~141b9c4-20160603+4022+141b9c4~16.04 500
        500 http://ppa.launchpad.net/juju/daily/ubuntu xenial/main amd64 Packages
     2.0~beta15-0ubuntu2.16.04.1 500
        500 http://archive.ubuntu.com//ubuntu xenial-updates/main amd64 Packages
     2.0~beta4-0ubuntu2 500
        500 http://archive.ubuntu.com//ubuntu xenial/main amd64 Packages
```

If you try this and see a newer version, 'sudo apt install juju' will upgrade the package for you.

**Comment by mnama** [comment]
**@mikemccracken - Awesome! You are right!  My system has older JuJu 2.0-beta15...**

---
~$ sudo apt-cache policy juju
[sudo] password for madhu: 
juju:
  Installed: 2.0~beta15-0ubuntu2.16.04.1
  Candidate: 2.0-rc1-0ubuntu1~16.04.1~juju1
  Version table:
     2.0-rc1-0ubuntu1~16.04.1~juju1 500
        500 http://ppa.launchpad.net/juju/devel/ubuntu xenial/main i386 Packages
     2.0-beta15-0ubuntu1~16.04.1~juju1 500
        500 http://ppa.launchpad.net/juju/devel/ubuntu xenial/main i386 Packages
 *** 2.0~beta15-0ubuntu2.16.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages
        100 /var/lib/dpkg/status
     2.0~beta4-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main i386 Packages
~$ 
---

**Looks like the issue is with my ppa - configuration.  I perhaps didn't pay attention to the output, when I added the repository.  It is complaining about configuring agent-stream.**

---
~$ sudo apt-add-repository ppa:juju/devel
 The devel packages in this archive use the devel simple-streams. You must configure the agent stream to use the matching tools.

    agent-stream: devel
 More info: https://launchpad.net/~juju/+archive/ubuntu/devel
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp1rgjtw7l/secring.gpg' created
gpg: keyring `/tmp/tmp1rgjtw7l/pubring.gpg' created
gpg: requesting key C8068B11 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp1rgjtw7l/trustdb.gpg: trustdb created
gpg: key C8068B11: public key "Launchpad Ensemble PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
~$
----

** When I try to reinstall juju, it is clearly telling me I need to update the dependencies.  I'm new to this ppa feature, didn't find anything specific to help myself on launchpad website as well.  Appreciate your help :-) **

--
~$ sudo apt install juju
[sudo] password for madhu: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 juju : Depends: juju-2.0 (>= 2.0-rc1-0ubuntu1~16.04.1~juju1) but 2.0~beta15-0ubuntu2.16.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
~$
--

** found some online help with adding ppa source to ubuntu, but didn't find the actual ppa-string myself.  Added the string that was in the documentation (I know sounds dangerous, but did it anyways)**

--Documentation--
 Step 1: On the PPA's overview page, look for the heading that reads Adding this PPA to your system. Make a note of the PPA's location, which looks like:

ppa:gwibber-daily/ppa

Step 2: Open a terminal and enter:

sudo add-apt-repository ppa:user/ppa-name 
--

--
~$ sudo add-apt-repository ppa:gwibber-daily/ppa
[sudo] password for madhu: 
 Daily builds of Gwibber trunk
 More info: https://launchpad.net/~gwibber-daily/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpltd2_ec6/secring.gpg' created
gpg: keyring `/tmp/tmpltd2_ec6/pubring.gpg' created
gpg: requesting key 72D340A3 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpltd2_ec6/trustdb.gpg: trustdb created
gpg: key 72D340A3: public key "Launchpad PPA for gwibber-daily" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
~$ 
--

**Looks like that is not a good repo.  Have a bunch of omissions... here is what I got when I ran the update**

--
~$ sudo apt-get update
,,,,a bunch of logs and then this...
Ign:14 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main i386 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Err:10 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main i386 Packages
  404  Not Found
Ign:11 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main i386 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 190 kB in 12s (15.5 kB/s)                                              
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

** And again adding juju-devel - still didn't work either**

~$ sudo apt-add-repository ppa:juju/devel
 The devel packages in this archive use the devel simple-streams. You must configure the agent stream to use the matching tools.

    agent-stream: devel
 More info: https://launchpad.net/~juju/+archive/ubuntu/devel
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpz41xwfa4/secring.gpg' created
gpg: keyring `/tmp/tmpz41xwfa4/pubring.gpg' created
gpg: requesting key C8068B11 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpz41xwfa4/trustdb.gpg: trustdb created
gpg: key C8068B11: public key "Launchpad Ensemble PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
~$

--

** Guess my config is a mess now? 
Sorry for the long message...**

**Comment by battlemidget** [comment]
Looks like some of the additional ppa's you have are failing. Maybe try disabling them all except the juju one?
