### ISSUE TITLE
neutron-gateway/0: hook failed: "config-changed"

### ISSUE THREAD

**Issue by cjones-virt** [conjure-up/conjure-up#450]
Unable to proceed with conjure-up openstack MAAS option. 

conjure-up/openstack: [ERROR] conjure-up/openstack: Failure in deploy done: Deployment errors:
neutron-gateway/0: hook failed: "config-changed"
conjure-up/openstack: [ERROR] conjure-up/openstack: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploystatus/common.py", line 40, in wait_for_applications
    raise Exception(result['message'])
Exception: Deployment errors:
neutron-gateway/0: hook failed: "config-changed"

juju-2.0                           2.0~beta15-0ubuntu2.16.04.1
conjure-up                         2.0.1~beta2-0~201609281246~ubuntu16.04.1 all

Cheers

**Comment by battlemidget** [comment]
So we default the bridge to eth1 in the gateway config. If you've interface is named different or is not available during deployment this error will occur. I am unable to reproduce this in my lab.

Keep in mind that usually it's best that all machines registered in your maas have 2 NICS as conjure-up doesn't have the ability to selectively pick a machine to install neutron on.

**Comment by cjones-virt** [comment]
Seeing as Ubuntu no longer names NICs eth0 and eth1, but rather for the PCI slot that they live in this seems problematic. Is there a work around I am missing. Thanks.

**Comment by battlemidget** [comment]
In your MAAS webui goto Settings and find the Global Kernel Parameters section. In there put `net.ifaces=0` that should give you the expected behavior of having eth0, eth1, etc. You may want to re-commission your nodes just to be sure that kernel parameter gets applied.

**Comment by qgriffith** [comment]
I am having this issue as well and I have tried the kernel flag net.ifaces=0. However the build fails with the same error as indicated on this ticket. It appears my interfaces are all enoX where X is a number and not enth0

**Comment by battlemidget** [comment]
See ^; I've exposed those configuration options so that you can easily change them via conjure-up ui prior to deploying the application

**Comment by qgriffith** [comment]
Oh nice! I ended up changing the interfaces in MAAS to match eth0/eth1 and I think that worked. Re-building now

**Comment by cjones-virt** [comment]
Nice fix. For anyone running without the update you can do the following

1) Update /etc/defaults/grub with GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
2) sudo update-grub
3) sudo vi /etc/udev/rules.d/70-persistent-net.rules and update with your mac addresses:
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="e4:11:5b:9b:55:4c", ATTR{dev_id}=="0x0", ATTR{type}=="1",
 KERNEL=="p*", NAME="eth0"
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="e4:11:5b:9b:55:4d", ATTR{dev_id}=="0x0", ATTR{type}=="1",
 KERNEL=="p*", NAME="eth1"
4) vi /etc/network/interfaces and update to eth0/eth1
5) reboot

**Comment by Gemstone123** [comment]
i'm trying to deploy vanilla charm as i'm beginner in writing charm, i'm facing following issues in this regard;
i run this "charm proof . " and i got following output;
I: `display-name` not provided, add for custom naming in the UI
W: no copyright file
I: missing recommended hook config-changed


secondly, when i try to run "juju debug-log"
i get this error;
unit-mysql-1: 16:07:04 ERROR juju.worker.uniter.operation hook "db-relation-joined" failed: exit status 1

can anyone help me in resolving these issues?

**Comment by battlemidget** [comment]
Hey @Gemstone123 your question is better asked over at https://askubuntu.com or join #juju on irc.freenode.net
