### ISSUE TITLE
Document setting locale for UTF8

### ISSUE THREAD

**Issue by leetal** [conjure-up/conjure-up#478]
So tried to install conjure-up today on fresh Xenial and get this error:

`maasclustercontroller:~$ conjure-up
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.1b2', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 211, in main
    app.spells_index = yaml.safe_load(fp.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2201: ordinal not in range(128)`

Seems the encoding gets messed up somewhere.. Locale is set to english on the machine.

Version of conjure-up: 2.0.1b2

**Comment by battlemidget** [comment]
what the output of `locale` on that machine?

**Comment by leetal** [comment]
Jees, you are fast :) Well in the same time it took four you to answer, i found out the same thing and want to push that IF a user have set a Locale on the machine that differs from `LC_ALL=C.UTF-8`, then it will fail. My locale was set to `C` only. Setting it to C.UTF-8 fixes the problem!

Thanks for a quick reply!

**Comment by battlemidget** [comment]
Thanks, Im going to add this to the documentation as well
