### ISSUE TITLE
PPA Package not found when trying to install

### ISSUE THREAD

**Issue by btro** [conjure-up/conjure-up#483]
This may sound trivial, but I'm failing at installing conjure on ubuntu-14.04.5-server-amd64. 
What I do is:
sudo apt-add-repository ppa:conjure-up/next
sudo apt update
sudo apt install conjure-up, which fails with a "could not locate package"-error. All the other commands work finde (key import and such). Any idea what the problem is?

**Comment by battlemidget** [comment]
conjure-up only supports Xenial and above (16.04)
