### ISSUE TITLE
conjure-up openstack fails deployment missing spell

### ISSUE THREAD

**Issue by baldpope** [conjure-up/conjure-up#484]
$ more .cache/conjure-up/conjure-up.log
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Failure in deploy done: Deployment errors:
neutron-gateway/0: hook failed: "config-changed"
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploystatus/common.py", line 40, in wait_for_applicatio
ns
    raise Exception(result['message'])
Exception: Deployment errors:
neutron-gateway/0: hook failed: "config-changed"

**Comment by battlemidget** [comment]
This is due to not having neutron-gateway configured with the appropriate bridge_mappings for the system it's installed on. This is not an issue with the installer itself.
