### ISSUE TITLE
openstack instances not getting ip's

### ISSUE THREAD

**Issue by qgriffith** [conjure-up/conjure-up#494]
This may not be the proper project to post this in. After creating an openstack on MAAS with conjure-up when I create new instances inside of openstack, horizon shows an ip associated with it however when I login through the web console to the machine there is not an IP. The interface is configured as DHCP on the instance.

I ran juju config neutron-openvswitch enable-local-dhcp-and-metadata=true to enable the dhcp server but that didn't seem to work

**Comment by qgriffith** [comment]
It looks like the conjurup0 bridge isn't attached to an interface

brctl show
bridge name	bridge id		STP enabled	interfaces
conjureup0		8000.000000000000	no

And that has the IP of the ext-net 10.99.0.1

**Comment by battlemidget** [comment]
Moved issue: https://github.com/conjure-up/spells/issues/16
