### ISSUE TITLE
How to recover openstack install after reboot?

### ISSUE THREAD

**Issue by moozzer** [conjure-up/conjure-up#501]
Hi all,

I have installed openstack on ubuntu 16.04 with conjure-up. The intallment worked and I could get into the horizon gui. I needed to restart the system. After the reboot I could not get into horizon. I checked "lxc list" but did not work. After pressing enter with this command it went to the next line but did not gave me an error or anything the cursor was just stuck there  (I let it do that for 2 hours no change).

juju status does the same thing (endless waiting, like "lxc list").

The logs of both JUJU and LXD seems fine to me. When issuing top the services like nova, neutron and horizon were present, what gave me the idea the services are running. 

How can I solve this issue? And how am I suppose to restart the system in the future?

**Comment by battlemidget** [comment]
This is an underlying juju or lxd problem, you'll want to start first by reporting this issue with the juju project https://bugs.launchpad.net/juju/+filebug. Containers and their services should survive a reboot, however, conjure-up has no control over that.

**Comment by kedaio** [comment]
I encountered exactly the same issue, and have been searching around but didn't have any luck. I understand this is more of an juju or lxd issue. Will try to mimic the same openstacck setup manually using lxd and see if the same thing happens. if yes, that indicates an lxd issue; if not, then it's juju.

**Comment by battlemidget** [comment]
Yea I'm also trying to track down the culprit.
