### ISSUE TITLE
document:  vsphere network configuration must be loosened to allow Promiscuous mode in the OpenStack management vlan

### ISSUE THREAD

**Issue by geewerx** [conjure-up/conjure-up#504]
I'm attempting to deploy open stack on 4 ESXi 6.0 based VM's using MAAS 2.0 with:

`conjure-up -d openstack`

and then selecting the "OpenStack Base for MAAS" spell. It gets part way through the installation and then appears to hang. Any insights here would be appreciated. I have tried to provide as much detail as possible below, but please let me know if there is any further information that I can provide.

-----------------------------------
Versions:

ubuntu@openstack-4:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

server@openstack-server:~$ conjure-up --version
conjure-up 2.0.2

The only configuration change I make to the spell is to the neutron-gateway data-port option, where I change the interface from eth1 to ens192 to match the ubuntu 16 naming convention. I have confirmed the naming of the interface is correct using **juju ssh <machine-no>**

At this stage MAAS is configured and the 4 VMs are in a Ready state. The installation starts promisingly enough, and conjure-up starts up the VMs and gets underway installing the various applications. There is lots of activity on the CPU's/Network/Disk etc. and then after about 10-15 minutes it appears to just hang. I have attached a screen shot showing the final state of the installation conjure-up-installation.png

![image](https://cloud.githubusercontent.com/assets/1993841/20249627/582c1ba6-a9f5-11e6-85f5-d85ac90a9a0a.png)

I've checked disk usage, this is fine and provisioned around 8gb per VM, so plenty of headroom.

There does still appear to be a fair bit of CPU activity, but not any network activity. Looking at top on the server performing the conjure-up, the conjure-up process is consistenly running at between 37-42%.

**The log file /var/log/conjure-up/openstack.log look like this:**

Nov 13 22:55:10 openstack-server conjure-up/openstack: Refreshing spell registry
Nov 13 22:57:27 openstack-server conjure-up/openstack: Path is local filesystem, copying /home/server/.cache/conjure-up-spells/openstack-base to /home/server/.cache/conjure-up/openstack-base
Nov 13 22:57:29 openstack-server conjure-up/openstack: pre_deploy_done: {'message': 'No pre deploy necessary', 'isComplete': True, 'returnCode': 0}
Nov 13 22:57:29 openstack-server conjure-up/openstack: AddMachines: [{'constraints': {'arch': 'amd64'}, 'jobs': ['JobHostUnits'], 'series': 'xenial'}, {'constraints': {'arch': 'amd64'}, 'jobs': ['JobHostUnits'], 'series': 'xenial'}, {'constraints': {'arch': 'amd64'}, 'jobs': ['JobHostUnits'], 'series': 'xenial'}, {'constraints': {'arch': 'amd64'}, 'jobs': ['JobHostUnits'], 'series': 'xenial'}]
Nov 13 22:57:32 openstack-server conjure-up/openstack: AddMachines returned {'machines': [{'machine': '0'}, {'machine': '1'}, {'machine': '2'}, {'machine': '3'}]}
Nov 13 22:57:38 openstack-server conjure-up/openstack: Adding Charm cs:xenial/neutron-gateway-232
Nov 13 22:57:39 openstack-server conjure-up/openstack: AddCharm returned {}
Nov 13 22:57:39 openstack-server conjure-up/openstack: Resources for charm id 'cs:xenial/neutron-gateway-232': []
Nov 13 22:57:39 openstack-server conjure-up/openstack: Deploying <Service neutron-gateway>: {'applications': [{'placement': [{'directive': '0', 'scope': '#'}], 'charm-url': 'cs:xenial/neutron-gateway-232', 'config-yaml': 'neutron-gateway:\n  bridge-mappings: physnet1:br-ex\n  data-port: br-ex:eth1\n  openstack-origin: cloud:xenial-newton\n', 'num-units': 1, 'constraints': {}, 'application': 'neutron-gateway', 'series': 'xenial'}]}
Nov 13 22:57:39 openstack-server conjure-up/openstack: Deploy returned {'results': [{}]}
Nov 13 22:57:50 openstack-server conjure-up/openstack: Refreshing spell registry
Nov 13 22:57:52 openstack-server conjure-up/openstack: Path is local filesystem, copying /home/server/.cache/conjure-up-spells/openstack-base to /home/server/.cache/conjure-up/openstack-base
Nov 13 22:57:54 openstack-server conjure-up/openstack: pre_deploy_done: {'isComplete': True, 'message': 'No pre deploy necessary', 'returnCode': 0}
Nov 13 22:57:54 openstack-server conjure-up/openstack: AddMachines: [{'series': 'xenial', 'jobs': ['JobHostUnits'], 'constraints': {'arch': 'amd64'}}, {'series': 'xenial', 'jobs': ['JobHostUnits'], 'constraints': {'arch': 'amd64'}}, {'series': 'xenial', 'jobs': ['JobHostUnits'], 'constraints': {'arch': 'amd64'}}, {'series': 'xenial', 'jobs': ['JobHostUnits'], 'constraints': {'arch': 'amd64'}}]
Nov 13 22:57:55 openstack-server conjure-up/openstack: AddMachines returned {'machines': [{'machine': '0'}, {'machine': '1'}, {'machine': '2'}, {'machine': '3'}]}

**And the openstack-base.log like this:**

Nov 13 22:55:09 openstack-server conjure-up/openstack-base: message repeated 68 times: [ Running deploy-done for OpenStack installation.]
Nov 13 22:55:15 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:22 openstack-server conjure-up/openstack-base: message repeated 22 times: [ Running deploy-done for OpenStack installation.]
Nov 13 22:57:28 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:33 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:39 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:45 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:51 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.
Nov 13 22:57:57 openstack-server conjure-up/openstack-base: Running deploy-done for OpenStack installation.

**I'm not entirely sure how to read the juju status, but the error in the lxd state at the end suggests something isn't right there:**

server@openstack-server:~$ juju status
MODEL  CONTROLLER       CLOUD/REGION     VERSION
alien  maas-controller  maas-controller  2.0-beta15

APP                    VERSION  STATUS   EXPOSED  ORIGIN      CHARM                  REV  OS
ceph-mon                        unknown  false    jujucharms  ceph-mon               6    ubuntu
ceph-osd               10.2.2   waiting  false    jujucharms  ceph-osd               238  ubuntu
ceph-radosgw                    unknown  false    jujucharms  ceph-radosgw           245  ubuntu
cinder                          unknown  false    jujucharms  cinder                 257  ubuntu
cinder-ceph                              false    jujucharms  cinder-ceph            221  ubuntu
glance                          unknown  false    jujucharms  glance                 253  ubuntu
keystone                        unknown  false    jujucharms  keystone               258  ubuntu
mysql                           unknown  false    jujucharms  percona-cluster        246  ubuntu
neutron-api                     unknown  false    jujucharms  neutron-api            246  ubuntu
neutron-gateway        9.0.0    waiting  false    jujucharms  neutron-gateway        232  ubuntu
neutron-openvswitch    9.0.0             false    jujucharms  neutron-openvswitch    238  ubuntu
nova-cloud-controller           unknown  false    jujucharms  nova-cloud-controller  292  ubuntu
nova-compute           14.0.1   waiting  false    jujucharms  nova-compute           259  ubuntu
ntp                                      false    jujucharms  ntp                    0    ubuntu
openstack-dashboard             unknown  false    jujucharms  openstack-dashboard    243  ubuntu
rabbitmq-server                 unknown  false    jujucharms  rabbitmq-server        54   ubuntu

RELATION                 PROVIDES               CONSUMES               TYPE
mon                      ceph-mon               ceph-mon               peer
mon                      ceph-mon               ceph-osd               regular
mon                      ceph-mon               ceph-radosgw           regular
ceph                     ceph-mon               cinder-ceph            regular
ceph                     ceph-mon               glance                 regular
ceph                     ceph-mon               nova-compute           regular
cluster                  ceph-radosgw           ceph-radosgw           peer
identity-service         ceph-radosgw           keystone               regular
cluster                  cinder                 cinder                 peer
storage-backend          cinder                 cinder-ceph            subordinate
image-service            cinder                 glance                 regular
identity-service         cinder                 keystone               regular
shared-db                cinder                 mysql                  regular
cinder-volume-service    cinder                 nova-cloud-controller  regular
amqp                     cinder                 rabbitmq-server        regular
cluster                  glance                 glance                 peer
identity-service         glance                 keystone               regular
shared-db                glance                 mysql                  regular
image-service            glance                 nova-cloud-controller  regular
image-service            glance                 nova-compute           regular
amqp                     glance                 rabbitmq-server        regular
cluster                  keystone               keystone               peer
shared-db                keystone               mysql                  regular
identity-service         keystone               neutron-api            regular
identity-service         keystone               nova-cloud-controller  regular
identity-service         keystone               openstack-dashboard    regular
cluster                  mysql                  mysql                  peer
shared-db                mysql                  neutron-api            regular
shared-db                mysql                  nova-cloud-controller  regular
cluster                  neutron-api            neutron-api            peer
neutron-plugin-api       neutron-api            neutron-gateway        regular
neutron-plugin-api       neutron-api            neutron-openvswitch    regular
neutron-api              neutron-api            nova-cloud-controller  regular
amqp                     neutron-api            rabbitmq-server        regular
cluster                  neutron-gateway        neutron-gateway        peer
quantum-network-service  neutron-gateway        nova-cloud-controller  regular
juju-info                neutron-gateway        ntp                    subordinate
amqp                     neutron-gateway        rabbitmq-server        regular
neutron-plugin           neutron-openvswitch    nova-compute           regular
amqp                     neutron-openvswitch    rabbitmq-server        regular
cluster                  nova-cloud-controller  nova-cloud-controller  peer
cloud-compute            nova-cloud-controller  nova-compute           regular
amqp                     nova-cloud-controller  rabbitmq-server        regular
neutron-plugin           nova-compute           neutron-openvswitch    subordinate
compute-peer             nova-compute           nova-compute           peer
juju-info                nova-compute           ntp                    subordinate
amqp                     nova-compute           rabbitmq-server        regular
ntp-peers                ntp                    ntp                    peer
cluster                  openstack-dashboard    openstack-dashboard    peer
cluster                  rabbitmq-server        rabbitmq-server        peer

UNIT                     WORKLOAD  AGENT       MACHINE  PUBLIC-ADDRESS  PORTS  MESSAGE
ceph-mon/0               unknown   allocating  1/lxd/0                         Waiting for agent initialization to finish
ceph-mon/1               unknown   allocating  2/lxd/0                         Waiting for agent initialization to finish
ceph-mon/2               unknown   allocating  3/lxd/0                         Waiting for agent initialization to finish
ceph-osd/0               waiting   idle        1        192.168.2.6            Incomplete relation: monitor
ceph-osd/1               waiting   idle        2        192.168.2.3            Incomplete relation: monitor
ceph-osd/2               waiting   idle        3        192.168.2.4            Incomplete relation: monitor
ceph-radosgw/0           unknown   allocating  0/lxd/0                         Waiting for agent initialization to finish
cinder/0                 unknown   allocating  1/lxd/1                         Waiting for agent initialization to finish
glance/0                 unknown   allocating  2/lxd/1                         Waiting for agent initialization to finish
keystone/0               unknown   allocating  3/lxd/1                         Waiting for agent initialization to finish
mysql/0                  unknown   allocating  0/lxd/1                         Waiting for agent initialization to finish
neutron-api/0            unknown   allocating  1/lxd/2                         Waiting for agent initialization to finish
neutron-gateway/0        waiting   idle        0        192.168.2.5            Incomplete relations: messaging
  ntp/3                  unknown   idle                 192.168.2.5            
nova-cloud-controller/0  unknown   allocating  2/lxd/2                         Waiting for agent initialization to finish
nova-compute/0           waiting   idle        1        192.168.2.6            Incomplete relations: messaging, image, storage-backend
  neutron-openvswitch/2  waiting   idle                 192.168.2.6            Incomplete relations: messaging
  ntp/2                  unknown   idle                 192.168.2.6            
nova-compute/1           waiting   idle        2        192.168.2.3            Incomplete relations: messaging, image, storage-backend
  neutron-openvswitch/1  waiting   idle                 192.168.2.3            Incomplete relations: messaging
  ntp/1                  unknown   idle                 192.168.2.3            
nova-compute/2           waiting   idle        3        192.168.2.4            Incomplete relations: messaging, image, storage-backend
  neutron-openvswitch/0  waiting   idle                 192.168.2.4            Incomplete relations: messaging
  ntp/0                  unknown   idle                 192.168.2.4            
openstack-dashboard/0    unknown   allocating  3/lxd/2                         Waiting for agent initialization to finish
rabbitmq-server/0        unknown   allocating  0/lxd/2                         Waiting for agent initialization to finish

MACHINE    STATE    DNS          INS-ID   SERIES  AZ
0          started  192.168.2.5  4y3hkk   xenial  default
  0/lxd/0  error                 pending  xenial  
  0/lxd/1  error                 pending  xenial  
  0/lxd/2  error                 pending  xenial  
1          started  192.168.2.6  4y3hkm   xenial  default
  1/lxd/0  error                 pending  xenial  
  1/lxd/1  error                 pending  xenial  
  1/lxd/2  error                 pending  xenial  
2          started  192.168.2.3  4y3hkg   xenial  default
  2/lxd/0  error                 pending  xenial  
  2/lxd/1  error                 pending  xenial  
  2/lxd/2  error                 pending  xenial  
3          started  192.168.2.4  4y3hkh   xenial  default
  3/lxd/0  error                 pending  xenial  
  3/lxd/1  error                 pending  xenial  
  3/lxd/2  error                 pending  xenial 

I'm at a bit of dead end here, I hope this helps

**Comment by battlemidget** [comment]
Ill take a look in the morning, seems like an update to the LXD charm has broken something

**Comment by geewerx** [comment]
Is there a previous stable version I can try?

**Comment by battlemidget** [comment]
Are you able to do the installation outside of ESX? I don't currently have that environment to try and reproduce.

**Comment by jsenecal** [comment]
It appears that I have the same issue as @geewerx reported... Anything we could do to help resolve this?

**Comment by jsenecal** [comment]
Further investigation showed that the individual nodes seem to have issues connecting to the outside world. The get an IP address, but no traffic is flowing:
```
root@juju-35c0bc-3-lxd-0:~# tail -f /var/log/cloud-init-output.log
+ sleep 15
+ n=121
+ true
+ printf Attempt 121 to download tools from %s...\n https://172.31.255.238:17070/model/1398f1bd-9f93-42e9-8505-66b171                                                                                                                        35c0bc/tools/2.0.2-xenial-amd64
Attempt 121 to download tools from https://172.31.255.238:17070/model/1398f1bd-9f93-42e9-8505-66b17135c0bc/tools/2.0.                                                                                                                        2-xenial-amd64...
+ curl -sSfw tools from %{url_effective} downloaded: HTTP %{http_code}; time %{time_total}s; size %{size_download} by                                                                                                                        tes; speed %{speed_download} bytes/s  --noproxy * --insecure -o /var/lib/juju/tools/2.0.2-xenial-amd64/tools.tar.gz h                                                                                                                        ttps://172.31.255.238:17070/model/1398f1bd-9f93-42e9-8505-66b17135c0bc/tools/2.0.2-xenial-amd64
curl: (7) Failed to connect to 172.31.255.238 port 17070: No route to host
tools from https://172.31.255.238:17070/model/1398f1bd-9f93-42e9-8505-66b17135c0bc/tools/2.0.2-xenial-amd64 downloade                                                                                                                        d: HTTP 000; time 2.203s; size 0 bytes; speed 0.000 bytes/s + echo Download failed, retrying in 15s
Download failed, retrying in 15s
+ sleep 15
^C
root@juju-35c0bc-3-lxd-0:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
11: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:c8:22:f2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.31.255.245/24 brd 172.31.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fec8:22f2/64 scope link
       valid_lft forever preferred_lft forever
root@juju-35c0bc-3-lxd-0:~# ping google.ca
^C
root@juju-35c0bc-3-lxd-0:~#
```

**Comment by jsenecal** [comment]
It appears that the vsphere network configuration must be loosened to allow Promiscuous mode in the OpenStack management vlan. That did it for me.

**Comment by battlemidget** [comment]
Thanks Jonathan, I do believe both the issues are related to some additional network configuration for the environment used to host openstack

**Comment by geewerx** [comment]
Setting the sphere configuration to Promiscuous mode worked for me as suggested by @jsenecal

**Comment by battlemidget** [comment]
Great! I'm going to document this in our documentation, could one of you provide me with some screenshots or a quick step by step so I can make sure to get it up quickly?

**Comment by battlemidget** [comment]
Will mark this document tag when I get home ina few

**Comment by battlemidget** [comment]
@jsenecal @geewerx Can you guys provide me with some screenshots of the vsphere configuration screens and/or a quick step by step so I can get those added to the documentation?

Thanks!

**Comment by battlemidget** [comment]
Documented here: http://conjure-up.io/docs/en/users/#_deployment_gets_part_way_through_and_seems_to_hang_under_vsphere

Thanks all
