### ISSUE TITLE
Please support deploying kubernetes-core

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#506]
Feature Request:

It'd be nice if conjure-up supported both sets of kubernetes deployments we support for people who want pure Kubes without the elastic stack, etc.: 

https://jujucharms.com/kubernetes-core/
https://jujucharms.com/canonical-kubernetess/

And then have `conjure-up kubernetes` default to canonical-kubernetes?

**Comment by battlemidget** [comment]
Thanks this is on the to-do list for early next week
