### ISSUE TITLE
make a decision on supporting root level modifications

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#507]
In some cases such as kubernetes on localhost provider we need to make certain modifications to kernel parameters to allow for a successful deploy. We need to make a decision on if we want to prompt the user for a sudo password to make these modifications on their behalf, or have conjure-up wait for those particular actions to be completed in a separate terminal. The latter will leave the modifications up to the user.

Right now the spells readmes contain any necessary modifications needed to make the deployment work.

**Comment by mikemccracken** [comment]
I'd rather not prompt the user to type in a root password into conjure-up. What about shipping a separate script that conjure-up tells you to run as sudo - it'd echo each command and let you OK it, then write a flag file somewhere that would tell conjure-up that the task was done OK or had an error. Then when you're done you go back to conjure-up and it does the right thing to continue, based on that flag file?

**Comment by battlemidget** [comment]
Yea that would be the latter portion where we wait for that setup to be done by the user manually. I prefer that approach as well
