### ISSUE TITLE
error: flag provided but not defined: --upload-tools

### ISSUE THREAD

**Issue by Fooobar23** [conjure-up/conjure-up#518]
Hi,
I just want to test openstack with conjure-up. I use ubuntu lts 16.04.01 with latest updates in a virtual machine (proxmox). 
If I use the command conjure-up openstack and after setup the lxc network, I got the Error in the title:

 error: flag provided but not defined: --upload-tools

How can I fix this problem?

Thx 

Stefan

**Comment by battlemidget** [comment]
Follow the instructions on http://conjure-up.io, you are probably running an older version.

**Comment by Fooobar23** [comment]
Hi,
thx, I have updated my version:
root@pluto:~# dpkg -l |grep conjure
ii  conjure-up                         2.0.2-0~201612011930~ubuntu16.04.1 all          Package runtime for conjure-up spells
root@pluto:~# 

I got a new error:

Exception: Unable to find: /home/testuser/.local/share/juju/accounts.yaml
conjure-up/openstack: [ERROR] conjure-up/openstack: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 32, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 102, in login
    account = get_account(app.current_controller)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 525, in get_account
    return get_accounts().get(controller, {})
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 537, in get_accounts
    "Unable to find: {}".format(env))
Exception: Unable to find: /home/testuser/.local/share/juju/accounts.yaml

**Comment by battlemidget** [comment]
What version of Juju are you running?

**Comment by Fooobar23** [comment]
`
root@pluto:~# dpkg -l |grep juju
ii  juju                               1:2.0.2-0ubuntu1~16.04.1~juju1     all          next generation service orchestration system
ii  juju-2.0                           1:2.0.2-0ubuntu1~16.04.1~juju1     amd64        Juju is devops distilled - client
root@pluto:~# `

**Comment by battlemidget** [comment]
Ok, can you remove `~/.local/share/juju` and try again?

**Comment by Fooobar23** [comment]
Yes, that's it.

Thx
