### ISSUE TITLE
Conjure-up for hangs for a long time and eventually throws error

### ISSUE THREAD

**Issue by ashish235** [conjure-up/conjure-up#523]
![conjure-waiting](https://cloud.githubusercontent.com/assets/11647730/21253081/d3193470-c381-11e6-958d-ee3b3a70aeba.png)
I 'm using conjure-up openstack LXD on Ubuntu 16.04.

I tried 5-6 different times installing openstack using conjure-up each time it ends with a different error. But 3 out of 5 times it was a similar situation. 

3-4 machines everytime remains in "waiting for machine" state for a long long time. 

When I see the status of the LXC containers, I see those containers running but without an IP. Nothing in the LXC error logs. 

And eventually conjure-up exists with the below error. 

openstack@ubuntu:~$ vi ~/.cache/conjure-up/conjure-up.log
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Failure in deploy done: Deployment errors:
neutron-api/0: hook failed: "update-status"
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploystatus/common.py", line 40, in wait_for_applications
    raise Exception(result['message'])
Exception: Deployment errors:
neutron-api/0: hook failed: "update-status"

can anyone help?

**Comment by battlemidget** [comment]
Looks like a problem with LXD and not the installer itself. You'll probably want to make sure your system is allowing enough resources for those containers: https://github.com/lxc/lxd/blob/master/doc/production-setup.md
