### ISSUE TITLE
placement: querying maas machines show empty list

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#528]
When editing a node to pick a maas machine to pin the machines list is empty. The only thing I noticed is that there is a filter already set for trying to match machines of amd64

**Comment by mikemccracken** [comment]
which spell is this? maas lists your nodes as having arch='amd64/generic'
so that's why it doesn't match.
maybe we should do more custom matching for architectures

**Comment by battlemidget** [comment]
This is for the openstack base one, ill try to get a SS

**Comment by battlemidget** [comment]
![screenshot_2016-12-19_11-09-03](https://cloud.githubusercontent.com/assets/51892/21319531/9ae8ec7e-c5db-11e6-8fff-2c9f14f189ca.png)

**Comment by mikemccracken** [comment]
yeah it's got constraints that say just amd64. I'll do some custom parsing on that field
