### ISSUE TITLE
error creating snapshots

### ISSUE THREAD

**Issue by rgauny** [conjure-up/conjure-up#537]
Install and everything works great except when I try to create a snapshot it fails silently and in the nova log I see:

Dec 23 06:04:08 juju-549580-13 nova-compute[993]: 2016-12-23 06:04:08.546 993 ERROR oslo_messaging.rpc.dispatcher ImageBadRequest: Request of image 892ba2aa-5bc4-46c3-87c1-0b83b2184fa4 got BadRequest response: 400 Bad Request: Container format is not specified. (HTTP 400)

Not sure what to do about this.....this also happens externally using packer to create an image from a source.

**Comment by battlemidget** [comment]
Hi,

I'm not sure this is a bug with our installer.  You'll probably want to seek support for snapshots over at https://ask.openstack.org/en/questions/
