### ISSUE TITLE
Multiple conjure-up's fail to deploy because of unknown controller/cloud

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#544]
Doing `conjure-up canonical-kubernetes` on AWS I got a dialog with an error that told me to look in conjure-up.log, which mentions this: 

```
[conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Failure in deploy done: Error in one of the applications deployment
conjure-up/_unspecified_spell: [ERROR] conjure-up/_unspecified_spell: Showing dialog for exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploystatus/common.py", line 40, in wait_for_applications
    raise Exception(result['message'])
Exception: Error in one of the applications deployment](url)
```

However the applications were still pending in juju status! This is with using the conjure-up/next ppa.

**Comment by battlemidget** [comment]
Thanks, I'll try and reproduce now. What version of juju are you running?

**Comment by battlemidget** [comment]
The problem stemmed from running multiple conjure-up's for two different controllers. That portion works but it falls apart when both deployment go into the "waiting for applications" part of the process and gets confused about which model/controller to be checking.

**Comment by mikemccracken** [comment]
@battlemidget are you sure that it's getting confused? jorge was seeing the same error from individual deploys - this might have been just issues with deploy-done.

**Comment by battlemidget** [comment]
Yea i wasn't sure about this but i remember doing the work to allow multiple deploys to occur by not relying on juju switch. I was thinking this may be a similar issue, Ill need to investigate more

**Comment by battlemidget** [comment]
I couldn't reproduce this problem as multiple conjure-up deploys on same system were being successfully deployed
