### ISSUE TITLE
Name of the kubernetes spell is wrong

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#546]
When you launch conjure-up and it shows a list of big software the title is "Canonical Kubernetes"; that should be "The Canonical Distribution of Kubernetes". 

Using "canonical-kubernetes" as a cli argument is fine, but when describing it as a product we should use the full name.

**Comment by mikemccracken** [comment]
This is a spells bug, moving to https://github.com/conjure-up/spells/issues/25
