### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#549]
Proxy request from some canonical-kubernetes users, it would be nice to support OSX (for public cloud deployments, obviously not LXD).

**Comment by mikemccracken** [comment]
@castrojo to clarify, this means running conjure-up locally on OS X?

**Comment by mikemccracken** [comment]
@castrojo We don't have any plans to do this, but it's probably possible. I've worked on OS X in the past and could help anyone who wanted to submit patches.

Since we don't have a good idea how many people would like this, please point anyone who asks to this issue to add their voice, either with a comment or just a 👍  on the issue. Thanks!

**Comment by battlemidget** [comment]
Talked with some of the eco guys about how we can do this. Going to look into brew and what it takes to get things like urwid with ncurses installed.

**Comment by rimusz** [comment]
really would love to use conjure-up locally on OS X

**Comment by battlemidget** [comment]
My Mac mini showed up yesterday so it won't be long!

**Comment by caio1982** [comment]
Hey there @battlemidget have you had any success with your Mini yet? :-)

**Comment by battlemidget** [comment]
@caio1982 I'm actually running it right now, I've got conjure-up working and now im just testing the spells to make sure they are all macOS compatible. I have the brew recipe written so now im just polishing and i'll submit a PR to brew hopefully before today is over :D

**Comment by battlemidget** [comment]
Tracking progress,
https://github.com/Homebrew/homebrew-core/pull/11472

**Comment by battlemidget** [comment]
This is now in brew

**Comment by rimusz** [comment]
awesome
