### ISSUE TITLE
conjure-up ssh connection fails to remote host

### ISSUE THREAD

**Issue by coriolnus** [conjure-up/conjure-up#550]
Hello,

i'm having trouble deploying openstack with conjure-up, the deployment phase completes successfully but when the client opens up and conjure-up tries to connect via ssh im receiving the following error,
i thought it might be a ssh issue so i have generated a new key and tried with the following way,
it still can not connect

anyone has experienced the same issue?

`SSHPUBLICKEY=/home/administrator/.ssh/id_rsa.pub conjure-up -d`

![juju](https://cloud.githubusercontent.com/assets/25040314/21821501/7eb4cb92-d77c-11e6-8126-4b0e871377ef.JPG)

**Comment by mikemccracken** [comment]
Hi, first, what cloud type are you using? Is this connecting to a MAAS or using the localhost/lxd cloud type?

Then, for some background - conjure-up uses [juju](https://jujucharms.com/) in the background to provision your cluster and deploy the software you've chosen. Juju needs to bootstrap by bringing up a controller node or instance that will coordinate the other nodes' installation.

What you're seeing there is that the bootstrap is not succeeding. Conjure-up tries to avoid having you wait for bootstrap by doing it in the background while you're looking at and configuring the applications, but if it isn't done by the time you've finished that step, (or if it's timing out like in your case), then you see this screen.

If you're comfortable using Juju from the command line, one way to debug this would be to try bootstrapping directly, using `juju bootstrap --debug` (see its help for the appropriate arguments for your cloud type). the --debug flag will print out even more info about what it's trying to do.

**Comment by coriolnus** [comment]
Hello again,

i'm currently using maas as cloud base and have been able to commission and deploy nodes successfully
juju bootstrap is working fine i have tried to bootstrap on local host and it finished completely, i have discovered the connection error after adding -d for conjure-up, i believe it can not reach the deployed machine through ssh so that it can deploy the required packages, i dont know if that was caused by a configuration error on maas or conjure up.

**Comment by mikemccracken** [comment]
@coriolnus if you can bootstrap a MAAS controller successfully outside of conjure-up, you shouldn't be seeing any bootstrap problems in using conjure-up.

Is it possible that this is just taking a long time? Some juju logging just shows transient errors. I'm not familiar with that part of juju's code, but it may just be trying to connect before the machine is up.

**Comment by coriolnus** [comment]
@mikemccracken 

after the timeout i'm receiving the following error, i wanted to see whats causing the error and opened the debug option, the maas successfully deploys the host and i can see it booted up.

> exception calling callback for <Future at 0x7fe0bd974438 state=finished raised LookupError>
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 69, in _pre_deploy_done
    future.result())))
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 61, in _pre_deploy_done
    result = json.loads(future.result().stdout.decode())
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/conjureup/controllers/deploy/gui.py", line 38, in _pre_deploy_exec
    app.current_model)['provider-type']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 36, in _decorator
    login(force=True)
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 127, in login
    uuid = get_model(app.current_controller, app.current_model)['model-uuid']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 592, in get_model
    models = get_models(controller)['models']
  File "/usr/lib/python3/dist-packages/conjureup/juju.py", line 626, in get_models
    "Unable to list models: {}".format(sh.stderr.decode('utf8')))
LookupError: Unable to list models: error: No selected controller.
Please use "juju switch" to select a controller.

>

**Comment by mikemccracken** [comment]
OK, it looks like the controller was not successfully bootstrapped, and we're not dealing well with showing a good error message in the case where it times out.

It sounds like juju can contact the MAAS server and start a node, but then can't contact the actual controller node.
It's possible that the SSH key that is set up for your user in MAAS is not the same one that juju is trying to use to contact the node. 

Have you been able to bootstrap successfully using your current SSH key?

I'd check the SSH key configuration in your MAAS account - http://your.maas/MAAS/account/prefs/

**Comment by coriolnus** [comment]
Ok, i have only one user on maas and i have created a keypair for this user and imported to the maas account, before the deployment i can ssh to the host but when the deployment finishes i can no longer login to the host and receive the following error, im really confused

> administrator@os-maas-cntrl:~$ ssh 172.16.103.12
ssh: connect to host 172.16.103.12 port 22: Connection refused

The hosts are working on a vm enviroment and i can access to the host directly through esxi console.

**Comment by mikemccracken** [comment]
Hi, can you share what version of MAAS you're using? I'm told that if it's 2.1.x, you definitely want to upgrade to 2.1.2 or 2.1.3.

To double-check your MAAS setup, are you able to deploy using just MAAS - no juju or conjure-up - an ubuntu system and SSH to it?

**Comment by coriolnus** [comment]
I'm currently using the below version, and i have tried to deploy a machine using only maas and tried to ssh but it was also unable to connect after deployment,

`maas                                  2.1.2+bzr5555-0ubuntu1~16.04.1`  
`conjure-up                         2.1.0-0~201701041302~ubuntu16.04.1`  

so it's an issue with the maas, i have checked the ssh configuration again and the ssh key is correct abd imported to the current user, the problem is remote machine doesnt respond to the ssh requests

**Comment by battlemidget** [comment]
hmm, yea you may want to head over to askubuntu.com or join #maas on freenode and see if you can get some help there.

**Comment by battlemidget** [comment]
@coriolnus Please let me know once you've posted your MAAS question to askubuntu.com and I can get the right people to look at it. Once we get passed that issue the rest of conjure-up installation should proceed as normal.

**Comment by coriolnus** [comment]
@battlemidget Hello,

i have posted the question to the askubuntu, 
http://askubuntu.com/questions/870634/maas-cant-ssh-to-remote-host

**Comment by battlemidget** [comment]
Thanks, you'll want to provide more detail about your environment (networks, maas versions, maas logs)
