### ISSUE TITLE
Conjure-up uses double the deployed hardware when deploying openstack-base and kubernetes-core

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#553]
cs:kubernetes-core uses 2 physical machines to deploy the services for kubernetes. Conjure-up bootstraps one node for juju, then 4 more for the services. Not sure why this is the case

**Comment by battlemidget** [comment]
Thanks will look into this

**Comment by simonklb** [comment]
I think this could be the issue I'm facing as well, but with OpenStack base for MAAS. Rather than deploying all of the charms onto LXD machines, conjure up spins up one machine per charm. Ended up with ~20 servers running instead of 4... :)

**Comment by battlemidget** [comment]
@simonklb thanks we'll get this sorted

**Comment by mikemccracken** [comment]
@canonical-cgregan are you seeing this on a MAAS controller or something else? Curious if it's limited to MAAS - the add-machine handling path is different for MAAS vs. the rest.

**Comment by canonical-cgregan** [comment]
When using the Maas option in conjure-up is when I see this behavior.


On Jan 12, 2017 21:34, "Michael McCracken" <notifications@github.com> wrote:

@canonical-cgregan <https://github.com/canonical-cgregan> are you seeing
this on a MAAS controller or something else? Curious if it's limited to
MAAS - the add-machine handling path is different for MAAS vs. the rest.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conjure-up/conjure-up/issues/553#issuecomment-272259414>,
or mute the thread

**Comment by mikemccracken** [comment]
@canonical-cgregan thanks. I have a fix in progress, it should be committed today and will be available in our daily-git ppa for testing.
