### ISSUE TITLE
2.1.0-0~201701041302~ubuntu16.04.1 fails to pull down spells and fails without --notrack

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#554]
It seems conjure-up should gracefully ignore the tracking option if the URL is not available behind a firewall without --notrack, but this is not the case. conjure-up openstack with a firewall blocking google analytics URL will cause conjure-up to crash without the --notrack passed at launch

**Comment by battlemidget** [comment]
Ok, thought we fixed this one ill look into this one

**Comment by mikemccracken** [comment]
this is #516 again.

**Comment by mikemccracken** [comment]
Confirmed by black-holing GA on my local system and running `conjure-up` without the `-d` option, which has the same effect as `--notrack`
```
sudo iptables -A OUTPUT -p tcp -d www.google-analytics.com -j DROP
```

**Comment by battlemidget** [comment]
adding test-track label here so we can make sure to include this into our testing
