### ISSUE TITLE
Add support for channels

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#556]
It would be nice if I could do something like `conjure-up canonical-kubernetes --edge` or something so I can test edge versions of bundles.

**Comment by battlemidget** [comment]
We had talked about this, but for the time being it's best to just:

```
cp ~/.cache/conjure-up-spells/canonical-kubernetes $HOME/work/canonical-kubernetes
```

Do your spell edits, or copy a bundle.yaml into that directory. Then

```
conjure-up -d $HOME/work/canonical-kubernetes
```

**Comment by battlemidget** [comment]
Oh I see, the charmstore channels, yea that is a good idea

**Comment by marcoceppi** [comment]
@battlemidget can we have this priority bumped?

We want people to try the 1.6.0 release of kubernetes a week before we release. Having the ability to point `conjure-up kubernetes --candidate` would be strong in pulling the candidate channel of the bundle.

**Comment by battlemidget** [comment]
Can you guys push a bundle to another channel so that I can test this feature work?

**Comment by wwwtyro** [comment]
@battlemidget There's a 1.6 bundle available in the candidate channel of canonical-kubernetes and kubernetes-core, now.

**Comment by battlemidget** [comment]
@wwwtyro thanks will give it a try!
