### ISSUE TITLE
using localhost with lxd init has confusing instructions

### ISSUE THREAD

**Issue by sergiusens** [conjure-up/conjure-up#565]
I went throught the `conjure-up` and didn't have `lxd` setup it says it drops me to a shell before telling me to run a couple of instructions.

It would be nice to see those instructions on the shell and it would be better to not say *drop* but mention that it is exiting and we need to restart the process (rerun `conjure-up`) since as it is I get the impression I need to exit the shell when done which is not the case.

**Comment by elsonrodriguez** [comment]
In addition, the terminal mode prevents copying of the lxd setup instructions, at least in Terminal.app

Really though this should be automated as part of the setup.

**Comment by battlemidget** [comment]
@elsonrodriguez Hi, so for new users this is being addressed in our upcoming release (2.1) where it'll automatically configure lxd networking and default storage prior to starting conjure-up.

For users that have lxd already setup and may have something like ipv6 we will also detect that and point them to our documentation on how to disable ipv6 which would have your copy and paste abilities there.

**Comment by battlemidget** [comment]
This has been addressed with our latest snap release
