### ISSUE TITLE
It's not clear whether I should use the mouse or keyboard

### ISSUE THREAD

**Issue by Meai1** [conjure-up/conjure-up#583]
Apparently both is possible but there is little indication of what happens when. 
Sometimes the installer appears to be stuck but when i click inside, suddenly it appears i have activated some hidden option and it continues.

**Comment by battlemidget** [comment]
Thanks for the report, I've been debating disabling mouse support all together as it's not heavily tested.

**Comment by mikemccracken** [comment]
@Meai1 is it possible that you used the middle button and pasted some text into the window? The terminal UI is unable to distinguish text entered that way from keys pressed, and so if you paste text that includes a letter that causes the UI to do something, it'll do that thing.

Unfortunately, that's not even something we can disable, AFAICT.

**Comment by battlemidget** [comment]
The UI supports both mouse and keyboard and anything editable or any buttons can be pressed with a key or a mouse click.

Not sure there is an actual bug here to fix.
