### ISSUE TITLE
Nonsensical keyboard navigation

### ISSUE THREAD

**Issue by Meai1** [conjure-up/conjure-up#584]
On this screen 1, I only press UP and DOWN arrow keys. NOTHING SHOULD HAPPEN(!) right? Because I'm not pressing ENTER.
Not to mention that the screen itself is quite nonsensical. 6 applications? What 6 applications? I see two nondescript [configure] lines, then it says "flannel units: 0", no idea what that means either.

![1](https://cloud.githubusercontent.com/assets/1112157/22030516/227b6eaa-dcde-11e6-9065-d3ae4b0fa09e.PNG)

Yet suddenly I land on this screen:

![2](https://cloud.githubusercontent.com/assets/1112157/22030531/2937b302-dcde-11e6-8669-f5a38acb38fb.PNG)

EDIT: Just to add something, then I click with the mouse leftclick one time in the middle of the description somewhere and this screen appears: (top right options disappear for no discernable reason)

![3](https://cloud.githubusercontent.com/assets/1112157/22030622/76bdbf0e-dcde-11e6-8d96-f820e1a249c0.PNG)

**Comment by battlemidget** [comment]
So we designed the UI around a 130x43 terminal as you can see it is difficult to get the entire UI in a 80x30 terminal.

Pressing up or down doesn't cause anything to be deployed so not sure where you're seeing that at.

We'll see what we can do about further optimizing the UI got smaller screens.

**Comment by mikemccracken** [comment]
Hi @Meai1 I'm sorry you've had a frustrating experience here. Thanks very much for filing the bug with screenshots, that was really helpful.

As @battlemidget mentioned, we designed it for a significantly larger terminal. I'd be very annoyed myself if I had to use it at the size you're showing.

There are screenshots at our docs page here: http://conjure-up.io/docs/en/users/#getting-started which show what it should look like - hopefully you'd agree it's more understandable at that size.
If you can make your terminal window bigger or font size smaller to use it, I think that might go a long way.

As for the unexpected change you noticed when using the arrow keys, that's also from being the small size - you haven't caused any action. On that screen, the top part of the screen shows a list of applications to configure or deploy, and the bottom part of the screen shows a description of the currently selected application. Etcd has a large description, so it moved the rest of the screen out of the way. On a larger screen, this would be less disruptive. This is what that screen looks like here:

![image](https://cloud.githubusercontent.com/assets/1768106/22032105/e7b7bf8a-dc97-11e6-8795-8f731c289323.png)

**Comment by mikemccracken** [comment]
@Meai1 I've filed issue #585 about this problem - I'd be very interested to hear if there's some reason why using a larger terminal window won't work for you. I understand that the default size of a terminal in Unity is smaller than the 130x43 size we've targeted, but as you can see it's difficult to fit a useful UI in such a small space. If you have a use case that requires a small terminal, we can look harder at how to re-design the screen for smaller terminals.

Thanks again for the detailed bug report!

**Comment by Meai1** [comment]
No, I can use a bigger terminal. But if you're only adding a warning then it should be a gigantic warning because it makes the terminal completely unusable in unpredictable ways. It's not just a minor inconvenience, for me the entire thing was simply a broken product.

**Comment by battlemidget** [comment]
A warning has been added
