### ISSUE TITLE
If lxc is used, conjure-up needs to deal with lxc problems too

### ISSUE THREAD

**Issue by Meai1** [conjure-up/conjure-up#587]
If there are lxc containers left over from interrupted installations, conjure-up should allow me to view and delete them. 
If lxc networking isnt setup, conjure-up should allow me to execute it from within the installer. 
If lxc needs a zfs pool then that should be created by conjure-up, possibly showing me my current disk layout and letting me partition something for that use.

The same thing applies to every usecase that juju fulfills.. it really isnt useful for me to use conjure-up to install "something" and then end up realizing that some tiny config isnt quite right and I have to learn juju and lxc and lxd extensively after all.

https://www.stgraber.org/ has posted a guide on how to setup kubernetes locally with conjure-up.
Why does such a guide need to exist at all if this is supposedly a supported option in the installer? 
Something doesnt seem quite right here.

I know what you will say "well, we just provide a wrapper over juju, it's not our problem if something fails because juju/lxc/[...] is failing". Well then this will never be truly userfriendly because the problem ends up at my doorstep where I, as a user who *originally does not want to deal with juju or anything really* now has to deal with these other tools because conjure-up doesn't handle everything.

**Comment by battlemidget** [comment]
> I know what you will say "well, we just provide a wrapper over juju, it's not our problem if something fails because juju/lxc/[...] is failing". Well then this will never be truly userfriendly because the problem ends up at my doorstep where I, as a user who originally does not want to deal with juju or anything really now has to deal with these other tools because conjure-up doesn't handle everything.

This is incorrect, we will fix the issues to make conjure-up more user friendly including guiding you through setting up LXC networking, ZFS, etc. 

This is still a young project and we haven't covered every single use case so bugs like this will help us narrow our focus.

Aside from that paragraph thank you for taking the time to file the bug and we'll make sure to get those items addressed.
