### ISSUE TITLE
Registered DNS names don't reflect same names specified in configuration Edit

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#593]
Ran through conjure-up almost successfully (failed one machine due a typo on a cidr notation). When I go to log into the openstack dashboard I get an error saying can't contact keystone. Looking at the configuration it is pointed at the correct dns name but this hasn't been registered in MAAS. Therefore no name resolution. The container instance is registered but this is no good as it is dynamic. Not sure if I have missed a setting so sorry if I have.

**Comment by mikemccracken** [comment]
I don't really follow what's going on here. It sounds like a DNS issue? @battlemidget do you remember who this was from?

**Comment by battlemidget** [comment]
https://bugs.launchpad.net/conjure-up/+bug/1633446
