### ISSUE TITLE
spells need to be able to specify what hw architecture they support

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#594]
After successfully upconjuring kubernetes core on a ppc64el system, conjure-up reports that

  The Kubernetes client utility is now available at '~/kubectl'

This is a lie, there is nothing there.

'juju status' also reports no machines on the local lxd, but conjure-up had no complaints.

$ juju status
Model Controller Cloud/Region Version
conjure-up mayfly localhost/localhost 2.0.2

App Version Status Scale Charm Store Rev OS Notes

Unit Workload Agent Machine Public address Ports Message

Machine State DNS Inst id Series AZ

$ juju list-models
Controller: mayfly

Model Cloud/Region Status Machines Cores Access Last connection
controller localhost/localhost available 1 - admin just now
conjure-up* localhost/localhost available 0 - admin 9 seconds ago

$

**Comment by mikemccracken** [comment]
@battlemidget do you remember who this was?

**Comment by battlemidget** [comment]
https://bugs.launchpad.net/conjure-up/+bug/1656263

**Comment by mikemccracken** [comment]
OK, so this won't work on ppc64el: the kubernetes-core spell gets kubectl from the kubernetes-master charm, which only packages x86-64 binaries. 
Our kubernetes guys are telling us this is from upstream - there are no current kubernetes builds for ppc64 or s390x.

**Comment by bpradipt** [comment]
Kubernetes builds for ppc64 and s390x are now available from upstream - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#downloads-for-v161

**Comment by battlemidget** [comment]
Thanks will get this added to our spells
