### ISSUE TITLE
conjure-up uses petname for model name

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#595]
conjure-up apparently uses single-word petnames for Juju models it
creates, e.g.:
```
| james@malefic:~$ juju models
| Controller: lxd
|
| Model Cloud/Region Status Machines Cores Access Last connection
| controller localhost/localhost available 1 - admin just now
| default localhost/localhost available 0 - admin 2017-01-02
| dane* localhost/localhost available 4 - admin 6 minutes ago
|
| james@malefic:~$
```
A bare pet name is pretty confusing and would only get more so if you
conjured up multiple spells. At a minimum, I think the spell should
be indicated in some way in the model name (perhaps combined with a
petname, if you need to avoid clashes). It might also be useful to
indicate in some way that this is a conjure-up model?

**Comment by mikemccracken** [comment]
I like this idea. Honestly I'd prefer `$spellname-$UUID`
where `UUID=uuidgen -t | cut -d '-' -f 1` instead of using petnames at all
