### ISSUE TITLE
provide way to de-conjure-up a spell

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#596]
It would be nice to provide a way to de-conjure-up a spell. While 'juju destroy-model' works, it a) exposes Juju unnecessarily, and b) doesn't cover other things the spell might do to the host (e.g. the kubernetes-core spell adds a lxd profile)

**Comment by battlemidget** [comment]
> b) doesn't cover other things the spell might do to the host (e.g. the kubernetes-core spell adds a lxd profile)

This may actually be something we want to provide in the spell for cleaning up?

**Comment by mikemccracken** [comment]
Yeah, the spell will have to provide a cleanup script - e.g. not every
spell adds a lxd profile, or the kubernetes spell might want to remove the
kubectl it installed.

Also, just a note that this ties in with the problem of how we should store
state about a deployed model, and a good solution there will help us solve
this.

Specifically, if we can store conjure-up state in juju storage for a dummy
charm, or just on the controller node in a directory somewhere,
then we can always point 'conjure-down' at any model and it will know how
to clean up.

Perhaps the thing to do would be to store a zip of the specific version of
the spell that we used to do the deploy.
