### ISSUE TITLE
Spell selection doesn't highlight requirements (or any other spell+bundle details)

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#599]
When I fire up conjure-up kubernetes I see two options:

  Kubernetes Core
  The Canonical Distribution of Kubernetes

There is actually a difference between them in terms of system requirements, but the description for either of them doesn't make it clear. Could we expose those so we know which option is suitable to select? We might want to surface more details (number of services, etc?) if that helps the choice.

(For bonus points, maybe group the spells from the unfiltered list, i.e. `conjure-up`, into groups, so you get the OpenStack options together, the K8s versions together, etc.)

**Comment by mikemccracken** [comment]
Note about the bonus points - this was done in #548 and is in the current daily-git PPA version

**Comment by mikemccracken** [comment]
wrt the descriptions, agreed. But those strings are defined in the spells repo in https://github.com/conjure-up/spells/blob/master/spells-index.yaml -- I'm moving this bug there.
