### ISSUE TITLE
Architecture view lets you add machines without making it clear there won't be any units assigned.

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#604]
The architecture view lets you add machines in advance of units being added. It knows how many units are available, as it only lets you assign them, but if you go there first you have no clue that adding machines won't do anything useful until you increase the number of units.

The number of units is incidentally displayed in the header but I missed it a few times until I took a fresh look and scanned for it.

PS: I was puzzled when I hit the architecture view and noticed that it didn't actually mean I could choose ARM or x86. After thinking about it the view made sense, but perhaps there is a better word to use there; "Architect", "Layout" or "Design" might work and match the fact that the other actions there are verbs.

**Comment by mikemccracken** [comment]
@battlemidget I'd like to ask some followups here, do you remember who filed this on LP?

**Comment by battlemidget** [comment]
https://bugs.launchpad.net/conjure-up/+bug/1656210
