### ISSUE TITLE
conjure-up ui does not work on 80x24 terminal

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#605]
When running conjure-up in a "standard" 80x24 character terminal, the interface is unusable. Text paragraphs in the detailed description are written assuming a wider terminal, and have hard newlines, which leads to word wrapping and badly flowing text. This wastes nearly all the available vertical screen space, which in turn crowds out the other widgets, making it impossible to navigate.

**Comment by mikemccracken** [comment]
current solution is #585. I'm going to close this bug but if we hear that lots of people want to use it at the small size we can reopen it and use it to track that design work.
