### ISSUE TITLE
conjure-up quits if a charm hook error happens

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#609]
During deployment of the Canonical Deployment of Kubernetes, one of the etcd units had a hook error. The hook was retried and the unit stabilized. Despite this, a few moments later, the conjure-up deployment exited because of the transient hook failure.

**Comment by mikemccracken** [comment]
IMO this is correct behavior. 'error' should mean error, and it's a charm bug if the charm sends an 'error' status that really just means it needs to wait.

In discussions with eco folks last week, Chuck agreed and fixed this in the etcd charm:

https://github.com/juju-solutions/layer-etcd/issues/72

 and in the k8s bundle here:

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/153#issuecomment-271647600
