### ISSUE TITLE
Adding machines with kvm causes conjure-up Oops (localhost controller)

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#610]
I deployed a k8s core with one kvm machine added in the worker architecture page. The deployment ran through most of the steps, but the kvm machine ended up stuck in down/pending state, and the conjure-up UI ended up with an Oops "Error in one of the applications deployment" (that error message deserves a rewrite, btw).

Log: http://paste.ubuntu.com/23791234/
Status: http://paste.ubuntu.com/23791235/

**Comment by mikemccracken** [comment]
@battlemidget not sure if kvm inside lxd machines is well tested but I think it should work. have you tried this? Do you have the contact info for the original bug filer?

**Comment by battlemidget** [comment]
kiko is the original bug filer I think I remember how he reproduced it I will test some more
