### ISSUE TITLE
Oops when running false for required in a step

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#611]
I am working on a step in the hadoop-processing spell so users may optionally run a Terasort benchmark.

My step.yaml looks like:
title: Terasort Benchmark
description: |
  Runs teragen to generate sample data, and then runs terasort to sort that data.
viewable: True
required: False

Code at https://github.com/arosales/spells/tree/master/hadoop-processing

When I run this spell I get an error:
"Could not read output from step . . . step-04_run-terasort

**Comment by mikemccracken** [comment]
I removed the traceback in the issue text because it's just the stack from him pressing the OK button on the error dialog.

**Comment by mikemccracken** [comment]
@battlemidget - From what I can tell this is because his step script is writing plain text and not yaml. I don't think we need this bug here. Feel free to reopen if you disagree

**Comment by arosales** [comment]
I see this bug is closed. Just wanted to say thanks for the reply, and I'll try @mikemccracken suggestion to output in yaml and dropping the OpenStack boiler plate scripts.
