### ISSUE TITLE
Unable to conjure-up kubernetes with OpenStack

### ISSUE THREAD

**Issue by jleavers** [conjure-up/conjure-up#617]
Status gets stuck forever on "Applications not ready yet, please wait."

All machines are "waiting":

```
kubernetes-worker/2	waiting
	waiting for machine
```

On checking Horizon no instances have been created. The controller was created successfully with `juju bootstrap` and if `juju deploy canonical-kubernetes` is used instead of `conjure-up`, it does start creating instances.

**Comment by battlemidget** [comment]
did you use conjure-up to deploy openstack or is this a custom cloud?

**Comment by jleavers** [comment]
Unfortunately I never managed to get conjure-up to deploy openstack :-)

So yes, it was deployed without it I'm afraid.

**Comment by battlemidget** [comment]
This should be addressed with latest conjure-up, if you ever get a chance to retry with the instructions from http://conjure-up.io
