### ISSUE TITLE
conjure-up continue operations

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#624]
For things like kubernetes we could re-run conjure-up against it and present the user with a list of actions to perform against the cluster.

**Comment by battlemidget** [comment]
We can utilize the model-config api for storing a string of yaml/json metadata within an 'extra-info' key in order to give us the ability to perform different tasks based on what data is available for conjure-up.

**Comment by mikemccracken** [comment]
I'd like to add a reminder here that once this is done, the conjure-down destroy controller should only show you models that have the extra-info key - so you can only conjure-down models that were conjured-up.

**Comment by mc0e** [comment]
See also https://github.com/conjure-up/conjure-up/issues/641#issuecomment-276345562

**Comment by battlemidget** [comment]
This should also include providing the ability to run additional actions against an existing deploy.

**Comment by battlemidget** [comment]
https://github.com/conjure-up/conjure-up/issues/648
