### ISSUE TITLE
Support modifying instance size

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#628]
From IRC: 

02:02          ⤷ ╡ i am using conjure-up to deploy Kubernetes on aws
02:03          ⤷ ╡ could you tell me how to modify aws instance default size as well change aws region
02:04          ⤷ ╡ it took while deploying m3. medium and us-east-1
02:04          ⤷ ╡ but i want to change that

**Comment by psyhomb** [comment]
I there anything new on this?

Thx

**Comment by battlemidget** [comment]
So for a headless install you can define the region to deploy too but we are still working on doing that via the console UI. We'll try to tackle this after our 2.2 release

**Comment by psyhomb** [comment]
My question was mainly about AWS instance types, I think you should definitely make an option for that, so we (consumer) can specify the exact size of instances while deploying a K8S cluster. IMHO it's very inconvenient to not have this option already implemented, especially for cases when I want to create a K8S cluster for testing purposes ony, cause in that case I definitely want to use AWS free tier instance types.

**Comment by battlemidget** [comment]
Cleanup, this was addressed with recent additions to our bundle fragments where you could provide different constraints on a charm deploy like `instance-type` and they would be honored when deploying to aws.
