### ISSUE TITLE
Support deploying to other regions in a cloud

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#630]
From IRC (the one for instance size I filed separately):

02:02 ⤷ ╡ i am using conjure-up to deploy Kubernetes on aws
02:03 ⤷ ╡ could you tell me how to modify aws instance default size as well change aws region
02:04 ⤷ ╡ it took while deploying m3. medium and us-east-1
02:04 ⤷ ╡ but i want to change that

Not sure how we would expose this, I think a separate screen after they choose the cloud might be too much? Not sure how well we support inheriting the cloud credentials and preferences from the standard cloud tools and environment variables, but if we do it might just be a matter of explaining that?

**Comment by battlemidget** [comment]
Dup https://github.com/conjure-up/conjure-up/issues/511
