### ISSUE TITLE
Add support for DreamCloud

### ISSUE THREAD

**Issue by castrojo** [conjure-up/conjure-up#631]
Tracking bug as this is a work-in-progress. Marco's got us working on DreamCloud but we need to work with them on getting the right metadata in their cloud:

- https://github.com/dreamhost/dreamcloud-docs/issues/67
- https://asciinema.org/a/7ba3snjdkxybmgisbm8430c34

**Comment by battlemidget** [comment]
Looks like we may want to expand on the add cloud experience in conjure-up
