### ISSUE TITLE
should spell steps have conditions based on cloud provider

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#633]
An example would be a step that would install additional storage options like ceph if on localhost for kubernetes.  This step would only be available on whatever cloud-whitelist we set in this case localhost.

@mikemccracken thoughts?

**Comment by mikemccracken** [comment]
I think there are two ideas here:
1. steps could have a whitelist, so some steps are only shown for e.g.
localhost. This seems like it's probably useful and not too hard to add.
Maybe setting up a local dir as an NFS-based kubernetes storage provider
would be something you'd only do on localhost.

2. the add-on bundles we discussed earlier as part of the 'next-deploy'
idea should also have a whitelist, so e.g. you could have an add-on bundle
with 3 ceph nodes that's only for a cloud or maas target, and a separate
add-on that has just one ceph node for localhost.

The difference between #1 and #2 here is whether or not you're adding units
and relations as part of the thing you want to optionally do.

**Comment by battlemidget** [comment]
ref #648 , going to close this out but link to our operations management bug for future reference
