### ISSUE TITLE
Allow specifying model name in headless

### ISSUE THREAD

**Issue by marcoceppi** [conjure-up/conjure-up#635]
We're using something like the following in headless:

```
conjure-up kubernetes-core localhost my-controller
conjure-up kubernetes-core localhost my-controller
```

But this creates model names that don't represent what the deployment is. Suggestion to allow a third positional argument to set model name:

```
conjure-up kubernetes-core localhost my-controller prod-test
conjure-up kubernetes-core localhost my-controller qa-cluster
```

Alternatively, it might be interesting to implicitly set the model name in the UI above the deploy screen as a prefilled but editable "Deployment name" to expose this functionality in the UI. I'm hesitant to put it there, choice fatigue, etc.

**Comment by mikemccracken** [comment]
I think the main concern here might have already been addressed by the changes in https://github.com/conjure-up/conjure-up/pull/619 , right?

The problem @marcoceppi pointed out was "model names that don't represent what the deployment is", and while allowing the user to set them is one way to fix that, isn't automatically generating meaningful names solving the same problem without requiring the user to do more?

**Comment by battlemidget** [comment]
I think @marcoceppi was more concerned with providing his own names for the models to represent the different phases of the application(s) deployed.

**Comment by battlemidget** [comment]
We decided to stick with the recent changes that name the controllers/models relevant to whats being deployed.

**Comment by marcoceppi** [comment]
Doesn't resolve this bug.

**Comment by mikemccracken** [comment]
@marcoceppi can you elaborate? I thought it solved your problem.

**Comment by marcoceppi** [comment]
I would like to name my models in headless. Repeating 2 kubernetes core
deployments, let alone 5, mean I have models that are names
conjure-up-kubernetes-core-xxxx which is meaningless for me.

**Comment by mikemccracken** [comment]
ok, thanks for clarifying

**Comment by marcoceppi** [comment]
Documentation would need to be updated, but thank you!
