### ISSUE TITLE
add ability to customize model name in UI

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#637]
> Alternatively, it might be interesting to implicitly set the model name in the UI above the deploy screen as a prefilled but editable "Deployment name" to expose this functionality in the UI. I'm hesitant to put it there, choice fatigue, etc.

From https://github.com/conjure-up/conjure-up/issues/635

**Comment by mikemccracken** [comment]
See my comment on #635, I think a reasonable automatic name is best. All it
needs to do is help the user identify the model later, and the names we're
now generating should do that. I think @marcoceppi is right to be concerned
about adding one more thing for users to figure out what to do with.

(and our UI options for showing something that is mostly a label but subtly
shows that it can be edited without being distracting are not great in
urwid)

**Comment by battlemidget** [comment]
I leave this open for another day to get @marcoceppi feedback (if any) otherwise it'll be closed.
