### ISSUE TITLE
Spells-dir expects git repo and public internet access

### ISSUE THREAD

**Issue by marcoceppi** [conjure-up/conjure-up#645]
It should try, but not fail on spell querying

```
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.1.0', 'console_scripts', 'conjure-up')()
  File "/usr/lib/python3/dist-packages/conjureup/app.py", line 227, in main
    spells_dir, update=True, branch=spells_registry_branch)
  File "/usr/lib/python3/dist-packages/conjureup/download.py", line 183, in download_or_sync_registry
    shell=True, check=True)
  File "/usr/lib/python3/dist-packages/conjureup/utils.py", line 32, in run
    return _run(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd spells && git pull -q' returned non-zero exit status 128
```

**Comment by mikemccracken** [comment]
@marcoceppi what version of conjure-up is this?
Also, is it the first time using it on that system, or is it failing to just update the spell registry?

@battlemidget IIRC this should have been fixed in https://github.com/conjure-up/conjure-up/pull/548 - I'm not sure what version that change went out…

**Comment by marcoceppi** [comment]
I'm using conjure-up from the ppa, ppa:conjure-up/next

**Comment by battlemidget** [comment]
I don't believe this is on the next ppa. The latest snap does have this fix if you're willing to try that out

**Comment by battlemidget** [comment]
@marcoceppi lemme know if the deploy still fails with the latest package from the daily-git ppa
