### ISSUE TITLE
use juju-wait deprecate 00-deploy_done script

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#651]
I've been using `juju-wait` python module for most of my testing scripts to wait for all units to become ready. This does so by waiting for all hooks to complete firing for a given amount of time.

I think we should utilize this because we can use it for both initial deployments and when we do our 'deploy next' strategy.

https://code.launchpad.net/juju-wait

**Comment by battlemidget** [comment]
@mikemccracken

**Comment by battlemidget** [comment]
The question here is do we want to remove deploy_done and just utilize `juju wait` within conjure-up for post deployments or allow spell authors to decide on if they wish to use that or not.

Currently, the spells make use of the latter.

**Comment by mikemccracken** [comment]
Looked at that module, it looks very comprehensive.
I think it'd be great to maybe ship it with the conjure-up spell library,
but I think we should also make sure that spell authors can still do
something custom if they need to. So don't completely replace the
deploy_done script, but let people use juju-wait in their scripts if they
want to.

**Comment by mikemccracken** [comment]
Just saw the PR you merged using it. I think that approach works fine. +1
