### ISSUE TITLE
Fresh install of conjure-up fails

### ISSUE THREAD

**Issue by AdamIsrael** [conjure-up/conjure-up#652]
I just installed conjure-up for the first time on Ubuntu 16.04:

$ sudo snap install conjure-up --classic --beta

When I try to run it, I get this:
$ conjure-up
Traceback (most recent call last):
  File "/snap/conjure-up/54/bin/conjure-up", line 7, in <module>
    from conjureup.app import main
ImportError: No module named 'conjureup'

**Comment by battlemidget** [comment]
After getting Adam upgraded to the `core` (vs `ubuntu-core`) and cleaning up some symlinks he was able to install and run the conjure-up snap without issue.

**Comment by luislobo** [comment]
@battlemidget @AdamIsrael 

I'm having the same issue, what do you mean by upgraded to the `core`? and what symlinks did you clean up?

**Comment by battlemidget** [comment]
You'll want to upgrade `snapd` in order for `ubuntu-core` to be migrated to `core` as seen in your `snap list`
