### ISSUE TITLE
Documentation: need to install snapd manually

### ISSUE THREAD

**Issue by sabaini** [conjure-up/conjure-up#658]
Small buglet, http://conjure-up.io/docs/en/users/#installing-conjure-up instructs to use snap for xenial. My xenial machine (upgraded from trusty, fwiw) doesn't have snapd by default, needed to install manually.

**Comment by sabaini** [comment]
Also, docs say to run 

$ conjure-up

This probably should be $ snap run conjure-up ?

**Comment by battlemidget** [comment]
Thanks for the report, I'll get the documentation updated. Also once you have snapd installed and you `sudo snap install conjure-up --classic --beta` you only need to run `conjure-up` and not `snap run conjure-up`
