### ISSUE TITLE
headless conjure-up kubernetes-core fails, while GUI does work

### ISSUE THREAD

**Issue by mikemccracken** [conjure-up/conjure-up#676]
root cause appears to be nested lxd containers,
but the GUI version does not nest the containers.

likely a difference in the paths used wrt the placement code

**Comment by jameinel** [comment]
https://bugs.launchpad.net/juju/+bug/1664409

should be addressed in the next Juju 2.1rc2 release.

**Comment by battlemidget** [comment]
\o/
