### ISSUE TITLE
LXD openstack: installation failure

### ISSUE THREAD

**Issue by gaetanquentin** [conjure-up/conjure-up#688]
Host: Ubuntu 16.10 updated
lxd 2.8 / 2.0.6

Using this procedure: https://stgraber.org/2016/10/26/lxd-2-0-lxd-and-openstack-1112/

 lxd containers are deployed immediatly (less than 2 seconds each …) in fact not depoyed at all as you can imagine: it shows immediatly the ‘additional application configuration’ screen.

I think i have something rotten on my host but i can’t find what it is.

in openstack container i have these errors: (/var/log/syslog)
Feb 15 21:37:09 openstack systemd-remount-fs[47]: /bin/mount for / exited with exit status 1.
Feb 15 21:37:09 openstack systemd-remount-fs[47]: mount: can’t find LABEL=cloudimg-rootfs
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting Load/Save Random Seed…
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/cloud-init-local.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting Initial cloud-init job (pre-networking)…
Feb 15 21:37:09 openstack systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting Flush Journal to Persistent Storage…
Feb 15 21:37:09 openstack systemd[1]: Started Load/Save Random Seed.
Feb 15 21:37:09 openstack systemd[1]: Started Flush Journal to Persistent Storage.
Feb 15 21:37:09 openstack systemd[1]: lvm2-lvmetad.socket: Trigger limit hit, refusing further activation.
Feb 15 21:37:09 openstack systemd[1]: lvm2-lvmetad.socket: Unit entered failed state.
Feb 15 21:37:09 openstack lvm[48]: Daemon lvmetad returned error 104
Feb 15 21:37:09 openstack lvm[48]: WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
Feb 15 21:37:09 openstack systemd[1]: Started Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Feb 15 21:37:09 openstack systemd[1]: Reached target Local File Systems (Pre).
Feb 15 21:37:09 openstack systemd[1]: Reached target Local File Systems.
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/plymouth-read-write.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting Tell Plymouth To Write Out Runtime Data…
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/apparmor.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting LSB: AppArmor initialization…
Feb 15 21:37:09 openstack systemd[1]: Failed to reset devices.list on /system.slice/systemd-tmpfiles-setup.service: Operation not permitted
Feb 15 21:37:09 openstack systemd[1]: Starting Create Volatile Files and Directories…
…

Feb 15 21:37:09 openstack apparmor[71]: /etc/init.d/apparmor: 256: /etc/init.d/apparmor: cannot open /sys/kernel/security/apparmor/.ns_stacked: Permission denied
Feb 15 21:37:09 openstack apparmor[71]: * Not starting AppArmor in container

[ …·]
Feb 15 21:38:36 openstack systemd[1]: Failed to reset devices.list on /system.slice/dev-.lxd\x2dmounts.mount: Operation not permitted
Feb 15 21:38:36 openstack systemd[1]: Failed to reset devices.list on /system.slice/networking.service: Operation not permitted
Feb 15 21:38:36 openstack systemd[1]: Failed to reset devices.list on /system.slice/proc-diskstats.mount: Operation not permitted

[…]
Feb 15 22:05:15 openstack lxc-apparmor-load[487]: /lib/apparmor/profile-load: 256: /lib/apparmor/profile-load: cannot open /sys/kernel/security/apparmor/.ns_stacked: Permission denied
Feb 15 22:05:15 openstack lxc-apparmor-load[487]: /lib/apparmor/profile-load: 256: /lib/apparmor/profile-load: cannot open /sys/kernel/security/apparmor/.ns_stacked: Permission denied
Feb 15 22:05:15 openstack lxd[492]: lvl=warn msg=”Per-container AppArmor profiles are disabled because the mac_admin capability is missing.” t=2017-02-15T22:05:15+0000
Feb 15 22:05:15 openstack lxd[492]: lvl=warn msg=”Per-container AppArmor profiles are disabled because LXD is already protected by AppArmor.” t=2017-02-15T22:05:15+0000
Feb 15 22:05:15 openstack lxd[492]: lvl=warn msg=”CGroup memory swap accounting is disabled, swap limits will be ignored.” t=2017-02-15T22:05:15+0000

in lxd.log:
creation date=2017-02-15T22:15:37+0000 ephemeral=false lvl=info msg=”Deleting container” name=juju-4820c9-14 t=2017-02-15T22:15:37+0000
creation date=2017-02-15T22:15:37+0000 ephemeral=false lvl=info msg=”Deleted container” name=juju-4820c9-14 t=2017-02-15T22:15:37+0000
ephemeral=false lvl=info msg=”Creating container” name=juju-4820c9-14 t=2017-02-15T22:15:48+0000
ephemeral=false lvl=info msg=”Created container” name=juju-4820c9-14 t=2017-02-15T22:15:48+0000

on the first juju container created , there is only this log:

root@openstack:/var/log/lxd# cat ./juju-f55c5e-0/lxc.log
lxc 20160215220533.450 WARN lxc_start – start.c:signal_handler:322 – Invalid pid for SIGCHLD. Received pid 593, expected pid 594.

Regards.

**Comment by battlemidget** [comment]
This is inside a container as well?

**Comment by gaetanquentin** [comment]
yes. as indicated in this blog: https://stgraber.org/2016/10/26/lxd-2-0-lxd-and-openstack-1112/

**Comment by battlemidget** [comment]
Try installing `squashfuse` and see if that helps. If it does we can close out your other bug as well.

**Comment by gaetanquentin** [comment]
in the first container "openstack"?

**Comment by battlemidget** [comment]
yea in the initial container you created to run conjure-up insside

**Comment by gaetanquentin** [comment]
lxc exec openstack bash
root@openstack:~# apt install squashfuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  squashfuse
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 17.4 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 squashfuse amd64 0.1.100-0ubuntu1~ubuntu16.04.1 [17.4 kB]
Fetched 17.4 kB in 0s (371 kB/s)      
Selecting previously unselected package squashfuse.
(Reading database ... 25469 files and directories currently installed.)
Preparing to unpack .../squashfuse_0.1.100-0ubuntu1~ubuntu16.04.1_amd64.deb ...
Unpacking squashfuse (0.1.100-0ubuntu1~ubuntu16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up squashfuse (0.1.100-0ubuntu1~ubuntu16.04.1) ...
root@openstack:~# snap install conjure-up --classic --stable
error: cannot perform the following tasks:
- Setup snap "core" (1079) security profiles (cannot setup udev for snap "core": cannot reload udev rules: exit status 2
udev output:
)
- Setup snap "core" (1079) security profiles (cannot reload udev rules: exit status 2
udev output:
)

**Comment by battlemidget** [comment]
Hmm yea that is a problem, my best advice at this point in time is to either switch to a VM or do this directly on the host machine (they deploy to all containers). Also I would open a bug over at https://github.com/lxc/lxd/issues/new and get those guys to weigh in on our possibilities for this to work with snaps inside containers

**Comment by battlemidget** [comment]
This is superseded by #694
