### ISSUE TITLE
Snap based installation fails

### ISSUE THREAD

**Issue by raesene** [conjure-up/conjure-up#691]
Trying to use the new snap based installation method to install conjure-up and I'm running into a problem with the install process

**output of uname -a**
`Linux xFoxy 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Snap version**
`snap    2.22.2
snapd   2.22.3
series  16
ubuntu  16.04
`

**command run (I've tried this with and without `--beta`)**
`sudo snap install conjure-up --classic`

**output**

```
error: cannot perform the following tasks:
- Run configure hook of "conjure-up" snap if present (
-----
+ lxd_bin=/usr/bin/lxd
+ lxc_bin=/usr/bin/lxc
++ which lxd
+ '[' '' = '' ']'
+ snap install lxd
+ lxd_bin=/snap/bin/lxd
+ lxc_bin=/snap/bin/lxc
++ /snap/bin/lxd --version
cat: /proc/self/attr/current: Permission denied
/snap/lxd/976/wrappers/lxd: 5: exec: aa-exec: Permission denied
+ VERSION=
-----)
```

I've checked that aa-exec is present and runs ok, which is does. Also looks like at least one other person is hitting [this error](https://askubuntu.com/questions/884568/ubuntu-16-04-1-snap-install-conjure-up-error)

**Comment by battlemidget** [comment]
Thank you for the bug report. Can you do the following for me:

```
sudo snap remove lxd
sudo apt-get install lxd lxd-client
```

This looks like an issue with the actual snap version of LXD and I need to get with those guys and see what may be going on.

If this works for you I'll update the askubuntu question as well.

**Comment by raesene** [comment]
Yep that worked fine for me, so that looks to be the problem. Thanks!

**Comment by battlemidget** [comment]
Glad to hear, I updated that question as well and will sync up with the LXD guys on Monday.
