### ISSUE TITLE
Kubectl exec/attach don't work on localhost deploy of the Canonical Distribution of Kubernetes

### ISSUE THREAD

**Issue by raesene** [conjure-up/conjure-up#692]
After completing a `conjure-up` for the canonical distribution of Kubernetes with a localhost target, running `kubectl exec [POD] -c [CONTAINER] [COMMAND]` or trying to use `kubectl attach` to get an interactive shell on a running container return an error

`Error from server (BadRequest): Upgrade request required`

A bit of googling seems to suggest a problem either with the client or if there's an nginx proxy involved in getting the request to the apiserver.  I tried getting the latest kubectl from google's site but that didn't seem to resolve it...

**Comment by battlemidget** [comment]
So we automatically download kubectl to your host system for you in `$HOME/bin/kubectl`. It is probably suffixed with what is called a **juju model**. You can see your deployed models by typing `juju models` or viewing the `result.txt` file inside `~/.cache/conjure-up/canonical-kubernetes/results.txt`

**Comment by raesene** [comment]
yep I've got `kubectl` with the suffix working just fine for commands like `get pods` and the like but `exec` and `attach` don't work.

**Comment by battlemidget** [comment]
OK thanks most people are off today in the US but I'll see if we can get one of the kubernetes guys on here.

**Comment by battlemidget** [comment]
@chuckbutler have you seen this before?

**Comment by chuckbutler** [comment]
I have, the upgrade-request is with regard to the Nginx proxy. I'm cycling either this week or next on getting a haproxy layer4 based router to replace the layer7 nginx router. I'm sorry you hit this, it's a known issue, and will be a problem until the replacement is completed.

A potential workaround until such time is to either update the kubectl with the IP address of a master and expose it directly, allowing kubectl to connect directly to a master without the use of the api-loadbalancer. 

https://kubernetes.io/docs/getting-started-guides/ubuntu/troubleshooting/#common-problems


If you're doing HA kubernetes control plane - look here: https://github.com/kubernetes/kubernetes/issues/41019 - there is a fix in flight for this scenario as well

**Comment by battlemidget** [comment]
thanks @chuckbutler , @raesene we're working on it thanks for reporting this!

**Comment by raesene** [comment]
@chuckbutler cool, thanks for the workarounds.

**Comment by battlemidget** [comment]
circling around, is this stlil an issue?
