### ISSUE TITLE
Error deploying to AWS when default region changed - conjure-up does not form correct bootstrap command when juju default aws region set

### ISSUE THREAD

**Issue by eric-sonchaiwanich** [conjure-up/conjure-up#693]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [N] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on:  Thinkpad X1 carbon, Ubuntu 16.10

Please outline what commands were run to install and execute conjure-up:

sudo snap install conjure-up
juju add-credential aws
juju set-default-region aws us-east-2

$ cat ~/.local/share/juju/credentials.yaml 
credentials:
  aws:
    default-region: us-east-2
    aws:
      auth-type: access-key
      access-key: (REDACTED)
      secret-key: (REDACTED)

 - Run conjure up
conjure-up
(Choose Canonical distribution of Kubernetes)
(Choose AWS as the cloud)
(encounter error, see log)

 - error from ~/.cache/conjure-up/conjure-up.log:
2017-02-21 14:56:10,425 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: Bootstrap error: 14:56:08 INFO  juju.cmd supercommand.go:63 running juju [2.1.0 gc go1.6.2]

14:56:08 DEBUG juju.cmd supercommand.go:64   args: []string{"juju", "bootstrap", "aws", "conjure-up-aws-dd5", "--config", "image-stream=daily", "--config", "enable-os-upgrade=false", "--default-model", "conjure-up-canonical-kubernetes-634", "--bootstrap-series=xenial", "--credential", "default-region", "--debug"}

14:56:08 ERROR cmd supercommand.go:458 "default-region" credential for cloud "aws" not found

14:56:08 DEBUG cmd supercommand.go:459 (error details: [{github.com/juju/juju/cmd/juju/commands/bootstrap.go:379: } {github.com/juju/juju/cmd/juju/commands/bootstrap.go:775: } {github.com/juju/juju/cmd/modelcmd/credentials.go:54: } {github.com/juju/juju/cmd/modelcmd/credentials.go:152: "default-region" credential for cloud "aws" not found}])

$ which conjure-up
/snap/bin/conjure-up
$ which juju
/snap/bin/juju
$ conjure-up --version
conjure-up 2.1.0
$ juju --version
2.1.0-yakkety-amd64

Please post **~/.cache/conjure-up/conjure-up.log**

**Comment by battlemidget** [comment]
Thank you we will get this fixed asap

**Comment by battlemidget** [comment]
So I attempted to reproduce this but was unable to:

```
juju add-credential aws
juju set-default-region aws us-east-2
```

My credentials file:

```
credentials:
  aws:
    default-region: us-east-2
    aws:
      auth-type: access-key
      access-key: abc
      secret-key: abc
```

And my bootstrap line:

```
19:53:16 DEBUG juju.cmd supercommand.go:64   args: []string{"/snap/conjure-up/86/bin/juju", "bootstrap", "aws", "conjure-up-aws-465", "--config", "image-stream=daily", "--config", "enable-os-upgrade=false", "--default-
model", "conjure-up-canonical-kubernetes-334", "--bootstrap-series=xenial", "--credential", "aws", "--debug"}
```

I feel like I may be missing a step though so please help me out to try and reproduce this as I want to make sure this works ootb for you.

**Comment by eric-sonchaiwanich** [comment]
$ sudo snap remove conjure-up
...
$ sudo snap install conjure-up --classic
conjure-up 2.1.0 from 'canonical' installed
$ which conjure-up
/snap/bin/conjure-up
$ which juju
/snap/bin/juju
$ juju --version
Since Juju 2 is being run for the first time, downloading latest cloud information.
Fetching latest public cloud list...
Your list of public clouds is up to date, see `juju clouds`.
2.1.0-yakkety-amd64
$ conjure-up --version
conjure-up 2.1.0



![image](https://cloud.githubusercontent.com/assets/2236055/23183149/d30ec104-f859-11e6-8927-4a8dbe1ac694.png)

**Comment by eric-sonchaiwanich** [comment]
I don't see a missing step.  How can we verify we're running the same version of software? 

Here are the steps I took to clean up my environment:

```
$ rm -r ~/.cache/conjure-up ~/.local/share/juju
$ sudo snap remove conjure-up
```

Here are the steps I took to re-install conjure-up

```
$ sudo snap install conjure-up --classic
conjure-up 2.1.0 from 'canonical' installed
```

More details about my environment:
```
$ which conjure-up
/snap/bin/conjure-up
$ which juju
/snap/bin/juju
$ juju --version
Since Juju 2 is being run for the first time, downloading latest cloud information.
Fetching latest public cloud list...
Your list of public clouds is up to date, see `juju clouds`.
2.1.0-yakkety-amd64
$ conjure-up --version
conjure-up 2.1.0

$ uname -a
Linux Eric-Thinkpad 4.8.0-38-generic #41-Ubuntu SMP Wed Feb 8 14:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ sudo snap info conjure-up
name:      conjure-up
summary:   "Package runtime for conjure-up spells"
publisher: canonical
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
  
commands:
  - conjure-up.conjure-down (conjure-down)
  - conjure-up
  - conjure-up.juju (juju)
tracking:    stable
installed:   2.1.0 (86) 78MB classic
refreshed:   2017-02-17 15:09:46 -0200 BRST
channels:               
  stable:    2.1.0 (86) 78MB classic
  candidate: 2.1.0 (86) 78MB classic
  beta:      2.1.0 (86) 78MB classic
  edge:      2.1.0 (86) 78MB classic
```

Steps to configure juju with credentials and default region
```
$ juju add-credential aws
Enter credential name: aws
Using auth-type "access-key".
Enter access-key: XXXXXXXXXXXXX
Enter secret-key: 
Credentials added for cloud aws.

$ juju set-default-region aws us-east-2
Default region in aws set to "us-east-2".
```
Note that if I list the clouds, the default region shows us-east-1 (not us-east-2, like I specified).  I'm not sure if that is intended or not.
```
$ juju clouds
Cloud        Regions  Default        Type        Description
aws               14  us-east-1      ec2         Amazon Web Services
aws-china          1  cn-north-1     ec2         Amazon China
aws-gov            1  us-gov-west-1  ec2         Amazon (USA Government)
azure             24  centralus      azure       Microsoft Azure
azure-china        2  chinaeast      azure       Microsoft Azure China
cloudsigma         5  hnl            cloudsigma  CloudSigma Cloud
google             6  us-east1       gce         Google Cloud Platform
joyent             6  eu-ams-1       joyent      Joyent Cloud
rackspace          6  dfw            rackspace   Rackspace Cloud
localhost          1  localhost      lxd         LXD Container Hypervisor

Try 'list-regions <cloud>' to see available regions.
'show-cloud <cloud>' or 'regions --format yaml <cloud>' can be used to see region endpoints.
'add-cloud' can add private clouds or private infrastructure.
Update the known public clouds with 'update-clouds'.
```

Resulting credentials file:
```
$ cat ~/.local/share/juju/credentials.yaml 
credentials:
  aws:
    default-region: us-east-2
    aws:
      auth-type: access-key
      access-key: xxxxxxxxxxxxxxxxxxxx
      secret-key: xxxxxxxxxxxxxxxxxxxxxx

$ conjure-up

```

And a screenshot of the error

![image](https://cloud.githubusercontent.com/assets/2236055/23183149/d30ec104-f859-11e6-8927-4a8dbe1ac694.png)
