### ISSUE TITLE
Setting lxd profile fails

### ISSUE THREAD

**Issue by marcoceppi** [conjure-up/conjure-up#695]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [X] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [X] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

2cpu, 4gb ram, 25GB disk

What spell was selected?:

canonical-kubernetes

What cloud provider was selected (this includes both MAAS and localhost)?:

localhost

Please outline what commands were run to install and execute conjure-up:

conjure-up kubernetes

Please post **~/.cache/conjure-up/conjure-up.log**

http://paste.ubuntu.com/24048334/

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd version
cat /etc/lsb-release
```

- /snap/bin/juju
- /snap/bin/conjure-up
- /usr/bin/lxd
- 2.1.0
- 2.1.0
- 2.8.2
- 16.04

VirtualBox machine on Windows

**Comment by battlemidget** [comment]
One of the latest coming out of LXD 2.9 (may be 2.8 as well) is we need to set the pool property in our configs: https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/steps/lxd-profile.yaml#L22

This is done with the latest --edge release of conjure-up and is still going through testing with positive results.

If they want, feel free to try the one from the edge channel to see if that gives better results.

The original error seems to be Juju was expecting a certain subnet on lxdbr0 but had a different address already assigned to it.

**Comment by battlemidget** [comment]
I believe this is resolved now with the latest conjure-up having the additional storage pool setting in its lxd profile updates.
