### ISSUE TITLE
Kubernetes Default Credentials

### ISSUE THREAD

**Issue by ztroop** [conjure-up/conjure-up#699]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [N] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [Y] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

2 Core, 8 GB RAM, Ubuntu 16.04

What spell was selected?:

Kubernetes Core

What cloud provider was selected (this includes both MAAS and localhost)?:

Localhost

Please outline what commands were run to install and execute conjure-up:

$ sudo snap install conjure-up --classic
$ conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

Sorry. Removed VM.

Summary:

I was not able to access the Kubernetes UI, I would be prompted for a Username and Password. Tried several combinations, with no avail, nothing mentioned in the documentation. Tried using:
juju change-user-password

Which changed did not work as expected, and wasn't able to run conjure-down afterwards. Will start from scratch later, anything I am missing?

**Comment by ztroop** [comment]
I should also mention, I tried accessing this local instance from another host in the network. Using NGINX on the host as a proxy.

**Comment by battlemidget** [comment]
You should only need to do:

```
kubectl proxy
xdg-open http://localhost:8001/ui
```

Also if you ssh into a system to run conjure-up you'll want to look at http://conjure-up.io/docs/en/users/#running-conjure-up-remotely as well.

**Comment by ztroop** [comment]
Okay, after running `kubctl.conjure-up-kubernetes-core-XXX proxy`.
I ran `sshuttle -r xxx@X.X.X.X 10.0.8.1/24` on my localhost and connected to the remote host without issue.

So, confirming the information with the cluster info:
```
XXX@XXX:~$ kubectl.conjure-up-kubernetes-core-XXX cluster-info
Kubernetes master is running at https://10.0.8.240:6443
Heapster is running at https://10.0.8.240:6443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.0.8.240:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.0.8.240:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://10.0.8.240:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.0.8.240:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

So with my local host, connected to the remote server running the kubernetes instance. I went to browse to any of the URLs mentioned above. I am prompted for a username and password - Unable to login.

**Comment by battlemidget** [comment]
Thanks, @chuckbutler any idea about this?

**Comment by ztroop** [comment]
Any update on this? If there's anything you would like me to try, I'll do my best to deliver.

**Comment by battlemidget** [comment]
I'm meeting with those developers next week and I'll talk to them about this particular issue.

Sorry for the delay

**Comment by battlemidget** [comment]
Also 1.5.3 was just released yesterday, not sure if you want to give that a try while you wait

**Comment by ztroop** [comment]
I gave it another try, ended up with the same result. Let me know how the meeting goes, and if there's anything else you or your team would like me to try. Thanks!

**Comment by battlemidget** [comment]
I've talked with the team and there doesn't seem to be any reason why you are prompted for a username/password for your deployment. One thing they asked to look at is to grab a https://github.com/juju/juju-crashdump from your running deployment so we can investigate and see if any differences stand out.

Additionally, could you provide us with additional information about how your infrastructure is configured? Is it possible to get a live session to that environment?

Lets start with the crashdump first and then go from there.

**Comment by battlemidget** [comment]
Does this problem persist? There is a 1.6.1 release coming out today or tomorrow if you're willing to try that.

**Comment by chuckbutler** [comment]
I've given this a redeploy and validated that the proxy step is still required to reach the endpoints. Those api endpoint listings for the services require a client key to be present on the connection in order to authenticate. It's the only auth mechanism we support *today*, and there will be additional support for more authentication mechanisms in a future release of CDK. 

The fact you were able to reach in with sshuttle doesn't make sense to me as it was not using that TLS key. That sounds to me like there's something else at play here and we need to unwind the complexity to discover where the disconnect is.

If ztroop does come back with additional info i'm happy to lend a hand in debugging. Just lmk.

**Comment by trunet** [comment]
Just installed on my local machine, and same problem as everybody. Connecting to any service, asks username/password. I understand that you only support certificate mechanism at this time, but why close the ticket if this is an issue affecting multiple users? at least a workaround should be provided, the `kubectl proxy` per example, doesn't provide access to grafana and influxdb services:

`$ kubectl.conjure-kubernetes-core-9bd cluster-info
Kubernetes master is running at https://10.0.8.215:6443
Heapster is running at https://10.0.8.215:6443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.0.8.215:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.0.8.215:6443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://10.0.8.215:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.0.8.215:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb`

**Comment by chuckbutler** [comment]
Hi, i think its important to note that there's a few things going on here that are probably more related to the https://github.com/juju-solutions/bundle-canonical-kubernetes/issues  issue tracker than the conjure-up issue at hand here, and one that looks more in tune with information than a product bug.

1) kubectl proxy will give you access to anything that's accessable by the API. The k8s dashboard includes graphs that are powered by grafana and fluentd. I'm uncertain what specifics you are looking for here that are not available to you through the proxy to the UI that will negate any need for username/password. You will however, have to change the first segment of the url to `http://localhost:8001`, then just tack on the `/api/v1/...` forward to reach those endpoints via the API. 

Rest assured, with the RBAC work we have in flight, there will be basic user/password combinations available for you to use on those links.

2) that output you've posted is coming from `kubectl cluster-info` which is a status output. We dont expose the master by default on `canonical-kubernetes` bundle, but do in the case of `kubernetes-core` as its not hosted behind a load-balancer. So its entirely possible that a user could click on one of those links and be taken to a non-responding endpoint.

**Comment by chuckbutler** [comment]
@trunet  This feedback prompted me to dig a little deeper at your ask and I discovered that our grafana and influx db addons are indeed not functioning as expected. I've filed an issue referenced above and pinged you explicitly for visiblity.  Thanks for tipping us off to this, we'll get a fix and a test to verify we don't break these addons moving forward.
