### ISSUE TITLE
lxd openstack - is there a way to  have custom names or more related names for containers?

### ISSUE THREAD

**Issue by gaetanquentin** [conjure-up/conjure-up#701]
I have installed openstack with lxd/nova.

Works fine but : lxd containers names are like juju-xxx which is not easy to recognize . 

Could them be more functional  name like ' neutron-xx" etc?

Can we rename containers?

**Comment by battlemidget** [comment]
Juju controls the naming of those containers and there isn't a way to customize that naming scheme. My suggestion would be to file a bug at https://bugs.launchpad.net/juju.

Thanks
