### ISSUE TITLE
Error deploying: cannot add application "ceph-osd": DB is locked | conjure-up setup

### ISSUE THREAD

**Issue by kkinkouu** [conjure-up/conjure-up#704]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure
up.io/docs/en/users/#_common_spell_problems <it may be associated to the following bug: https://bugs.launchpad.net/fuel/+bug/1474510>
- [ ] Is conjure-up running inside a virtual machine? <yes - VBox - 5.0.32_Gentoo r112930>

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

<$ sudo lspci -k
00:00.0 Host bridge: Intel Corporation Core Processor DMI (rev 11)
	Subsystem: Lenovo Core Processor DMI
00:03.0 PCI bridge: Intel Corporation Core Processor PCI Express Root Port 1 (rev 11)
	Kernel driver in use: pcieport
00:08.0 System peripheral: Intel Corporation Core Processor System Management Registers (rev 11)
00:08.1 System peripheral: Intel Corporation Core Processor Semaphore and Scratchpad Registers (rev 11)
00:08.2 System peripheral: Intel Corporation Core Processor System Control and Status Registers (rev 11)
00:08.3 System peripheral: Intel Corporation Core Processor Miscellaneous Registers (rev 11)
00:10.0 System peripheral: Intel Corporation Core Processor QPI Link (rev 11)
00:10.1 System peripheral: Intel Corporation Core Processor QPI Routing and Protocol Registers (rev 11)
00:16.0 Communication controller: Intel Corporation 5 Series/3400 Series Chipset HECI Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset HECI Controller
00:16.3 Serial controller: Intel Corporation 5 Series/3400 Series Chipset KT Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset KT Controller
	Kernel driver in use: serial
00:19.0 Ethernet controller: Intel Corporation 82577LM Gigabit Network Connection (rev 06)
	Subsystem: Lenovo 82577LM Gigabit Network Connection
	Kernel driver in use: e1000e
	Kernel modules: e1000e
00:1a.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset USB2 Enhanced Host Controller
	Kernel driver in use: ehci-pci
00:1b.0 Audio device: Intel Corporation 5 Series/3400 Series Chipset High Definition Audio (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset High Definition Audio
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
00:1c.0 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 1 (rev 06)
	Kernel driver in use: pcieport
00:1c.1 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 2 (rev 06)
	Kernel driver in use: pcieport
00:1c.3 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 4 (rev 06)
	Kernel driver in use: pcieport
00:1c.4 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 5 (rev 06)
	Kernel driver in use: pcieport
00:1c.6 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 7 (rev 06)
	Kernel driver in use: pcieport
00:1c.7 PCI bridge: Intel Corporation 5 Series/3400 Series Chipset PCI Express Root Port 8 (rev 06)
	Kernel driver in use: pcieport
00:1d.0 USB controller: Intel Corporation 5 Series/3400 Series Chipset USB2 Enhanced Host Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset USB2 Enhanced Host Controller
	Kernel driver in use: ehci-pci
00:1e.0 PCI bridge: Intel Corporation 82801 Mobile PCI Bridge (rev a6)
00:1f.0 ISA bridge: Intel Corporation Mobile 5 Series Chipset LPC Interface Controller (rev 06)
	Subsystem: Lenovo Mobile 5 Series Chipset LPC Interface Controller
	Kernel driver in use: lpc_ich
	Kernel modules: lpc_ich
00:1f.2 SATA controller: Intel Corporation 5 Series/3400 Series Chipset 6 port SATA AHCI Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset 6 port SATA AHCI Controller
	Kernel driver in use: ahci
	Kernel modules: ahci
00:1f.3 SMBus: Intel Corporation 5 Series/3400 Series Chipset SMBus Controller (rev 06)
	Subsystem: Lenovo 5 Series/3400 Series Chipset SMBus Controller
	Kernel driver in use: i801_smbus
	Kernel modules: i2c_i801
01:00.0 VGA compatible controller: NVIDIA Corporation GT216GLM [Quadro FX 880M] (rev a2)
	Subsystem: Lenovo GT216GLM [Quadro FX 880M]
	Kernel driver in use: nouveau
	Kernel modules: nvidiafb, nouveau
01:00.1 Audio device: NVIDIA Corporation GT216 HDMI Audio Controller (rev a1)
	Subsystem: Lenovo GT216 HDMI Audio Controller
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6200 (rev 35)
	Subsystem: Intel Corporation Centrino Advanced-N 6200 2x2 AGN
	Kernel driver in use: iwlwifi
	Kernel modules: iwlwifi
0d:00.0 SD Host controller: Ricoh Co Ltd MMC/SD Host Controller (rev 01)
	Subsystem: Lenovo MMC/SD Host Controller
	Kernel driver in use: sdhci-pci
	Kernel modules: sdhci_pci
0d:00.1 System peripheral: Ricoh Co Ltd R5U2xx (R5U230 / R5U231 / R5U241) [Memory Stick Host Controller] (rev 01)
	Subsystem: Lenovo R5U2xx (R5U230 / R5U231 / R5U241) [Memory Stick Host Controller]
0f:00.0 USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 03)
	Subsystem: Lenovo uPD720200 USB 3.0 Host Controller
	Kernel driver in use: xhci_hcd
	Kernel modules: xhci_pci
17:00.0 SD Host controller: Ricoh Co Ltd MMC/SD Host Controller (rev 01)
	Subsystem: Lenovo MMC/SD Host Controller
	Kernel driver in use: sdhci-pci
	Kernel modules: sdhci_pci
17:00.3 FireWire (IEEE 1394): Ricoh Co Ltd R5C832 PCIe IEEE 1394 Controller (rev 01)
	Subsystem: Lenovo R5C832 PCIe IEEE 1394 Controller
	Kernel driver in use: firewire_ohci
	Kernel modules: firewire_ohci
ff:00.0 Host bridge: Intel Corporation Core Processor QuickPath Architecture Generic Non-Core Registers (rev 04)
	Subsystem: Lenovo Core Processor QuickPath Architecture Generic Non-Core Registers
ff:00.1 Host bridge: Intel Corporation Core Processor QuickPath Architecture System Address Decoder (rev 04)
	Subsystem: Lenovo Core Processor QuickPath Architecture System Address Decoder
ff:02.0 Host bridge: Intel Corporation Core Processor QPI Link 0 (rev 04)
	Subsystem: Lenovo Core Processor QPI Link 0
	Kernel modules: i7core_edac
ff:02.1 Host bridge: Intel Corporation Core Processor QPI Physical 0 (rev 04)
	Subsystem: Lenovo Core Processor QPI Physical 0
ff:03.0 Host bridge: Intel Corporation Core Processor Integrated Memory Controller (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller
ff:03.1 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Target Address Decoder (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Target Address Decoder
ff:03.4 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Test Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Test Registers
ff:04.0 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 0 Control Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 0 Control Registers
ff:04.1 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 0 Address Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 0 Address Registers
ff:04.2 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 0 Rank Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 0 Rank Registers
ff:04.3 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 0 Thermal Control Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 0 Thermal Control Registers
ff:05.0 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 1 Control Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 1 Control Registers
ff:05.1 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 1 Address Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 1 Address Registers
ff:05.2 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 1 Rank Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 1 Rank Registers
ff:05.3 Host bridge: Intel Corporation Core Processor Integrated Memory Controller Channel 1 Thermal Control Registers (rev 04)
	Subsystem: Lenovo Core Processor Integrated Memory Controller Channel 1 Thermal Control Registers>

<~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:          15957         587       14708          15         661       15296
Swap:          8191           0        8191>

<~ $ sudo df -h
Password: 
Filesystem            Size  Used Avail Use% Mounted on
udev                   10M  4.0K   10M   1% /dev
/dev/mapper/vg0-root  227G   44G  172G  21% /
tmpfs                 1.6G  932K  1.6G   1% /run
shm                   7.8G  8.2M  7.8G   1% /dev/shm
cgroup_root            10M     0   10M   0% /sys/fs/cgroup
none                  7.8G   12K  7.8G   1% /run/user/1000
/dev/mapper/vg1-data  458G  164G  271G  38% /mnt/data>

<~ $ lsblk 
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda              8:0    0 238.5G  0 disk  
|-sda1           8:1    0     2M  0 part  
|-sda2           8:2    0   477M  0 part  
`-sda3           8:3    0   238G  0 part  
  `-root       253:0    0   238G  0 crypt 
    |-vg0-swap 253:1    0     8G  0 lvm   [SWAP]
    `-vg0-root 253:2    0   230G  0 lvm   /
sdb              8:16   0 465.8G  0 disk  
`-sdb1           8:17   0 465.8G  0 part  
  `-data       253:3    0 465.8G  0 crypt 
    `-vg1-data 253:4    0 465.8G  0 lvm   /mnt/data>

What spell was selected?:<sorry, unsure as to what this means>

What cloud provider was selected (this includes both MAAS and localhost)?:<ubuntu.16.04.2>

Please outline what commands were run to install and execute conjure-up:<snap install congure-up --classic | conjure-up> <NovaLXD>

Please post **~/.cache/conjure-up/conjure-up.log**

- <http://paste.ubuntu.com/24086556/>

Provide the output of the following commands:

```
which juju <Juju version: 2.1.0-xenial-amd64>
which conjure-up <conjure-up 2.1.0>
which lxd <2.9.3>
cat /etc/lsb-release <stack@vm-ubuntu-openstack:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS">
```

Summary of problem:
VM seems to have halted due to the following error  <Error deploying: cannot add application "ceph-osd": DB is locked>

**Comment by kkinkouu** [comment]
Apologies VM Specs:
< ~ $ ssh -p 2424 stack@127.0.0.1
stack@127.0.0.1's password: 
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-64-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

4 packages can be updated.
0 updates are security updates.


Last login: Tue Feb 28 21:47:39 2017 from 10.10.0.2
stack@vm-ubuntu-openstack:~$ sudo df -h
[sudo] password for stack: 
Filesystem                                  Size  Used Avail Use% Mounted on
udev                                        3.9G     0  3.9G   0% /dev
tmpfs                                       799M  9.2M  790M   2% /run
/dev/mapper/vm--ubuntu--openstack--vg-root   89G   12G   73G  14% /
tmpfs                                       3.9G     0  3.9G   0% /dev/shm
tmpfs                                       5.0M     0  5.0M   0% /run/lock
tmpfs                                       3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0                                   76M   76M     0 100% /snap/core/1337
/dev/loop1                                   82M   82M     0 100% /snap/conjure-up/103
/dev/sda1                                   472M  105M  343M  24% /boot
tmpfs                                       100K     0  100K   0% /var/lib/lxd/shmounts
tmpfs                                       100K     0  100K   0% /var/lib/lxd/devlxd
tmpfs                                       799M     0  799M   0% /run/user/1000
stack@vm-ubuntu-openstack:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7983         359        6544          69        1079        7243
Swap:         10231           0       10231
stack@vm-ubuntu-openstack:~$ lsblk 
NAME                                   MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                                      8:0    0 100.4G  0 disk  
|-sda1                                   8:1    0   487M  0 part  /boot
|-sda2                                   8:2    0     1K  0 part  
|-sda5                                   8:5    0   100G  0 part  
  |-sda5_crypt                         252:0    0   100G  0 crypt 
    |-vm--ubuntu--openstack--vg-root   252:1    0    90G  0 lvm   /
    |-vm--ubuntu--openstack--vg-swap_1 252:2    0    10G  0 lvm   [SWAP]
sr0                                     11:0    1  1024M  0 rom   
loop0                                    7:0    0  75.2M  0 loop  /snap/core/1337
loop1                                    7:1    0  81.2M  0 loop  /snap/conjure-up/103
stack@vm-ubuntu-openstack:~$ >

<~$ lspci -k
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
	Kernel driver in use: ata_piix
	Kernel modules: pata_acpi
00:02.0 VGA compatible controller: InnoTek Systemberatung GmbH VirtualBox Graphics Adapter
	Kernel driver in use: vboxvideo
	Kernel modules: vboxvideo
00:03.0 Ethernet controller: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
	Subsystem: Intel Corporation PRO/1000 MT Desktop Adapter
	Kernel driver in use: e1000
	Kernel modules: e1000
00:04.0 System peripheral: InnoTek Systemberatung GmbH VirtualBox Guest Service
	Kernel driver in use: vboxguest
	Kernel modules: vboxguest
00:05.0 Multimedia audio controller: Intel Corporation 82801AA AC'97 Audio Controller (rev 01)
	Subsystem: Dell 82801AA AC'97 Audio Controller
	Kernel driver in use: snd_intel8x0
	Kernel modules: snd_intel8x0
00:07.0 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 08)
	Kernel modules: i2c_piix4
00:0c.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller
	Kernel driver in use: xhci_hcd
00:0d.0 SATA controller: Intel Corporation 82801HM/HEM (ICH8M/ICH8M-E) SATA Controller [AHCI mode] (rev 02)
	Kernel driver in use: ahci
	Kernel modules: ahci>

**Comment by kkinkouu** [comment]
please ignore this post, this is clearly a resource problem

**Comment by battlemidget** [comment]
@kkinkouu thank you for trying conjure-up, feel free to re-open if you find that the problem persists even after allocating additional resources

**Comment by kkinkouu** [comment]
@battlemidget - Your welcome, will post any problems i run into while testing conjure-up. looks like i need get the w530/w540 (32GB RAM) for testing. looks like the w510 cannot cut it :-)

**Comment by battlemidget** [comment]
Yea I have a w520 and it can't handle a full deploy either. I find the Intel NUCS with at least 16G ram work very well for testing
