### ISSUE TITLE
Typo in Manual Docs

### ISSUE THREAD

**Issue by keithkk** [conjure-up/conjure-up#705]
http://conjure-up.io/docs/en/users/#advanced-usage

The 2 is missing for the IP address 172.16.0.5 in this section on the $ line:

The subnet of localhost is going to be what conjure-up configured the network bridge for. By default this is set to 10.0.8.1/24. Lets also say the remote host’s ip is 172.16.0.5 so you’ll want to do the following

$ sshuttle -r 17.16.0.5 10.0.8.1/24
[local sudo] Password:
client: Connected.

**Comment by battlemidget** [comment]
@keithkk Thanks! I'll get this doc push asap

**Comment by battlemidget** [comment]
Docs sync up every hour and this is in the queue, thanks again!
