### ISSUE TITLE
Support juju login for JAAS support

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#708]
In order to connect to upcoming JAAS we need to investigate integrating macaroon support in conjure-up and/or libjuju.

**Comment by jamesbeedy** [comment]
there is an issue started [here](https://github.com/juju/python-libjuju/issues/50)

**Comment by battlemidget** [comment]
@jamesbeedy perfect thanks james, we've got a sprint next week and I hope to have this sorted then.

**Comment by battlemidget** [comment]
We'll be utilizing `juju login` and some UI view flows to guide a user through authenticating to JAAS. This will be done via subprocess call to juju login as the python version of macaroons does not support the httpbakery spec or enough of it to utilize the juju api for logging in.

**Comment by battlemidget** [comment]
https://github.com/conjure-up/conjure-up/commit/2686cecc8037d8b0a5c9256455d2bac3bb5e36ed
