### ISSUE TITLE
Exception calling callback for <Future at 0x7f4fd00db080 state=finished returned NoneType>

### ISSUE THREAD

**Issue by mbruzek** [conjure-up/conjure-up#712]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:
4 CPU, 16GB RAM, ~400GB available space

What spell was selected?: canonical-kubernetes

What cloud provider was selected (this includes both MAAS and localhost)?: localhost

Please outline what commands were run to install and execute conjure-up: snap install conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

[conjure-up.log.zip](https://github.com/conjure-up/conjure-up/files/821869/conjure-up.log.zip)

Provide the output of the following commands:

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which lxd
/snap/bin/lxd
$ juju version
2.1.1-yakkety-amd64
$ conjure-up --version
conjure-up 2.2-dev
$ lxd version
Usage: lxd [command] [options]
...
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Summary of problem:

I tried to conjure-up kubernetes on localhost today and encountered a python stack trace.  It looks like I have one xenial image running in lxd but it failed somewhere after that.

See the screenshot for the error message:
![screenshot from 2017-03-06 10-27-59](https://cloud.githubusercontent.com/assets/6385185/23619877/b8ffda72-025a-11e7-8364-862e53a019a1.png)

The conjure-up process failed, and left the user with out a clear error message. We should fix this.

**Comment by battlemidget** [comment]
I believe this is an issue with running lxd 2.8 which doesn't support a new storage pool option in lxd 2.9 and above. So probably better to do a better job at making sure the user is on the proper lxd and a better error message directing that user.
