### ISSUE TITLE
conjure-up shared libraries leaking out to system ldconfig

### ISSUE THREAD

**Issue by jay-vosburgh** [conjure-up/conjure-up#717]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems

No

- [ ] Is conjure-up running inside a virtual machine?

No

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

Intel i7-4790 workstation (4 core Haswell), 16 GB memory, free disk space couple hundred GB

What spell was selected?:

openstack (LXD)

What cloud provider was selected (this includes both MAAS and localhost)?:

localhost

Please outline what commands were run to install and execute conjure-up:

snap refresh conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

2017-03-07 20:23:21,246 [DEBUG] log.py:14 - conjure-up/help: LXD version: 2.10.1, Juju version: 2.1.2-xenial-amd64
2017-03-07 20:23:23,686 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: LXD version: 2.10.1, Juju version: 2.1.2-xenial-amd64

Provide the output of the following commands:

$ which juju
juju is /snap/bin/juju
$ which conjure-up
conjure-up is /snap/bin/conjure-up
$ which lxd
lxd is /usr/bin/lxd
lxd is /usr/bin/X11/lxd
$ juju version
2.1.2-xenial-amd64
$ conjure-up --version
conjure-up 2.1.2
$ lxd --version
2.10.1
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Issue has been observed with conjure-up snap versions 107 and 115.

Summary of problem:

Shared libraries provided with conjure-up are leaking out to the standard system.  It provides an /etc/ld.so.conf.d file, /etc/ld.so.conf.d/conjure-up.conf, that adds snap libraries to the standard ldconfig cache:

$ ldconfig -p | grep snap
        libxml2.so.2 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libxml2.so.2
        libsqlite3.so.0 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libsqlite3.so.0
        libsnapd-glib.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsnapd-glib.so.1
        libonig.so.2 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libonig.so.2
        libnettle.so.6 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libnettle.so.6
        libmpdec.so.2 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libmpdec.so.2
        libicuuc.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicuuc.so.55
        libicutu.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicutu.so.55
        libicutest.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicutest.so.55
        libiculx.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libiculx.so.55
        libicule.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicule.so.55
        libicui18n.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicui18n.so.55
        libicuio.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicuio.so.55
        libicudata.so.55 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicudata.so.55
        libexpatw.so.1 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libexpatw.so.1
        libdb-5.3.so (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libdb-5.3.so
        libarchive.so.13 (libc6,x86-64) => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libarchive.so.13

Examples of system programs now acquiring libraries from the conjure-up libraries:

$ ldd /usr/bin/totem /bin/ping6 /usr/bin/gedit /usr/bin/nslookup | grep -e ^/' -e snap 
/usr/bin/totem:
        libxml2.so.2 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f7d1d87c000)
        libarchive.so.13 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libarchive.so.13 (0x00007f7d1ce8a000)
        libicuuc.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f7d19090000)
        libsqlite3.so.0 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f7d18b98000)
        libnettle.so.6 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f7d18285000)
        libicudata.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f7d14a63000)
/bin/ping6:
        libnettle.so.6 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f3726ee2000)
/usr/bin/gedit:
        libxml2.so.2 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f14adc2c000)
        libicuuc.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007f14aa73c000)
        libicudata.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007f14a4b74000)
/usr/bin/nslookup:
        libxml2.so.2 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fcf46ee8000)
        libicuuc.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fcf45cb1000)
        libicudata.so.55 => /snap/conjure-up/115/usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fcf43ab3000)

I suspect this is not a desired result of installing conjure-up or any snap; I'm unsure whether this is an issue with conjure-up specifically or with snaps in general.

**Comment by battlemidget** [comment]
It's not an issue with snaps, it is with conjure-up. It was a quick fix to address some of the issues I am seeing with snapped conjure-up failing to load correct libraries because of the way pure python3 applications are snapped in a classic environment.

I need to find a better alternative to this, thanks for reporting

**Comment by battlemidget** [comment]
I think I'll need to just edit my wrappers to update it's LD_LIBRARY_PATH at runtime.
