### ISSUE TITLE
Snap install conjure-up doesn't work if juju is installed

### ISSUE THREAD

**Issue by dpb1** [conjure-up/conjure-up#719]
```
dpb@helo:~[0]$ snap install juju --classic
juju 2.1.1 from 'canonical' installed
dpb@helo:~[0]$ snap install conjure-up --classic
error: cannot perform the following tasks:
- Set automatic aliases for snap "conjure-up" (cannot enable alias "juju" for "conjure-up", it conflicts with the command namespace of installed snap "juju")
dpb@helo:~[0]$ 
```

**Comment by battlemidget** [comment]
This is expected as we own the juju alias and that command will conflict with the juju snap. Since you get juju when installing conjure-up this was decided as the best course.

**Comment by freyes** [comment]
Why not rename the `juju` command embedded in conjure-up to something hat doesn't collide with the juju snap?, like `conjure-juju`, `conjure-up-juju`, etc

**Comment by battlemidget** [comment]
I guess it really depends on what way we take conjure-up. If we take it down the path for day 2 type operations (operations management) then we could effectively not own the top level juju name. This would be because we'd document running conjure-up against existing deployments to perform additoinal operations rather than juju directly.

feedback from @johnsca @mikemccracken @nskaggs welcomed on this

**Comment by johnsca** [comment]
Alias collision handling is going to have to be handled by the snap system at some point regardless.

**Comment by nskaggs** [comment]
Yes, you should be using the alias commands. I've installed both on my box, but only one can own juju. That is by intent as it were. https://snapcraft.io/docs/reference/snap-command#alias

**Comment by nskaggs** [comment]
To be clear, you don't need both, as indeed conjure-up has all the juju you need.

**Comment by johnsca** [comment]
Actually, from the error message above, it sounds like the alias conflict is being handled appropriately in that snap is warning you that it can't enable the alias automatically but it doesn't block the install.  (That is different than what I had seen in the past.)

**Comment by battlemidget** [comment]
Ok, so we're good here then? If users want to use juju snap itself they will have to remove the existing alias conjure-up sets

**Comment by freyes** [comment]
On Wed, May 31, 2017, at 19:36, Cory Johns wrote:
> Actually, from the error message above, it sounds like the alias conflict is being handled appropriately in that snap is warning you that it can't enable the alias automatically but it doesn't block the install.  (That is different than what I had seen in the past.)

It does block the installation

 ~  $  snap info conjure-up 
name:      conjure-up
summary:   "Package runtime for conjure-up spells"
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
description: |
  This package provides conjure-up, an interface to installing spells
  that
  provide the user with an end to end walkthrough experience for
  installing and
  using big software.
  
channels:                                       
  latest/stable:    2.1.5                 (352) 97MB classic
  latest/candidate: 2.1.5                 (352) 97MB classic
  latest/beta:      2.2-beta4             (316) 92MB classic
  latest/edge:      2.2-rc1-20170525.1405 (346) 88MB classic
 ~  $  which conjure-up
 ~  $  sudo snap install --classic conjure-up
[sudo] password for freyes: 
error: cannot perform the following tasks:
- Set automatic aliases for snap "conjure-up" (cannot enable alias
"juju" for "conjure-up", it conflicts with the command namespace of
installed snap "juju")
 ~  $  which conjure-up
 ~  $  ls /snap/bin/
bundletester  bundletester.bundlewatcher  jenkins-cli-python.jenkins 
juju  snapcraft
 ~  $  dpkg -l snapd
Desired=Unknown/Install/Remove/Purge/Hold
|
Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version             
        Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  snapd                                           2.25+17.04          
        amd64                        Tool to interact with Ubuntu Core
Snappy.
 ~  $  snap list
Name                Version    Rev   Developer  Notes
bundletester        0.10.3-1   x1               classic
core                16-2       1689  canonical  -
jenkins-cli-python  0.1.2+git  x1               -
juju                2.2-beta4  1837  canonical  classic
snapcraft           2.29.1     99    canonical  classic

**Comment by SaMnCo** [comment]
From a pure user perspective, having the error message for conjure-up doesn't help the user understand that he/she should first remove the juju snap, then install conjure-up again. 
A clearer debug message with a recommendation on next steps would be welcome in my opinion

**Comment by battlemidget** [comment]
Would you mind opening a bug with https://launchpad.net/snappy? There is not much we can do from a conjure-up point of view.
