### ISSUE TITLE
conjure-up kubernetes gives stacktrace 

### ISSUE THREAD

**Issue by mbruzek** [conjure-up/conjure-up#727]
Provide the output of the following commands:

```
$ conjure-up kubernetes
$ which juju
/snap/bin/juju
$ which -a juju
/snap/bin/juju
$ which -a conjure-up
/snap/bin/conjure-up
$ which -a lxd
/usr/bin/lxd
$ juju version
2.1.2-yakkety-amd64
$ conjure-up --version
conjure-up 2.1.2
$ lxd --version
2.11
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

```

Summary of problem:

I got a Python stack trace when I tried to `conjure-up kubernetes` today.

![screenshot from 2017-03-13 10-12-49](https://cloud.githubusercontent.com/assets/6385185/23860675/a635090a-07d5-11e7-9e06-bbec3396ca80.png)

**Comment by battlemidget** [comment]
This was an issue with jujucharms.com api, it should now be fixed
