### ISSUE TITLE
Conjure-down does not allow me to mark the previous installation

### ISSUE THREAD

**Issue by btro** [conjure-up/conjure-up#730]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ ] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:
i5 (4cores)
16G
500G SSD

What spell was selected?:
openstack

What cloud provider was selected (this includes both MAAS and localhost)?:
localhost

Please outline what commands were run to install and execute conjure-up:
conjure-up
localhost install LXD

Please post **~/.cache/conjure-up/conjure-up.log**

Provide the output of the following commands:

```
user@openstack-host:~$ which juju
/snap/bin/juju
user@openstack-host:~$ which conjure-up
/snap/bin/conjure-up
user@openstack-host:~$ which lxd
/usr/bin/lxd
user@openstack-host:~$ juju version
2.1.1-yakkety-amd64
user@openstack-host:~$ conjure-up --version
conjure-up 2.1.1
user@openstack-host:~$ lxd --version
2.11
user@openstack-host:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Summary of problem:
I want to conjure-down, but I can't select the localhost environment. Tabbing only switches to "QUIT". Cursor-Keys don't seem to select anything and hammering ENTER to accept uninstallation of the environment won't work either. I don't want to install a new distro everytime I have to reinstall.  Is there some headless mode that I can use to uninstall the environment?

edit: This happens via SSH and on the machine itself

**Comment by btro** [comment]
Ok, I figured out the headless mode: 
just enter "juju models" and then uninstall via: "conjure-down [CONTROLLERNAME] [MODEL]" where CONTROLLERNAME was sth. like "conjure-up...." and MODEL was "controller". The bug still persists though ;)

**Comment by llwp** [comment]
Had the same UI issue and your comment @btro saved me the search... thanks!
