### ISSUE TITLE
"architecture" option to select maas node didn't work

### ISSUE THREAD

**Issue by panlinux** [conjure-up/conjure-up#755]
I'm using the landscape-spell and while conjure-up was bootstrapping, I selected the "architecture" option to try some machine placement options:

![image](https://cloud.githubusercontent.com/assets/5117210/24222513/2ac8b36c-0f31-11e7-938f-bf34ace86aba.png)

I then clicked on the "ID" field, which brought up a list of maas nodes:
![image](https://cloud.githubusercontent.com/assets/5117210/24222542/3c8f9b2e-0f31-11e7-9f33-bd4eaf8f70c6.png)
 
In this list, I selected "avalugg", and then continued the deployment.

After bootstrap was done, though, avalugg never left the "ready" state in MAAS. Checking the process listing, I can see that conjure-up issued a juju wait call, and has been waiting since:

```
27913 pts/2    Sl+    6:18          |   |   \_ python3 /snap/conjure-up/140/bin/conjure-up -c /snap/conjure-up/140/etc/conjure-up.conf --spells-dir /snap/conjure-up/140/
29929 pts/2    S+     0:00          |   |       \_ /bin/sh -c /home/andreas/.cache/conjure-up/landscape-spell/steps/00_deploy-done
29930 pts/2    S+     0:00          |   |           \_ /bin/bash /home/andreas/.cache/conjure-up/landscape-spell/steps/00_deploy-done
29933 pts/2    Sl+    0:00          |   |               \_ juju wait -wm conjure-up-maas-9b6:conjure-up-landscape-spell-69d
29939 pts/2    S+     0:01          |   |                   \_ python3 /snap/conjure-up/140/bin/juju-wait -wm conjure-up-maas-9b6:conjure-up-landscape-spell-69d
```

The conjure-up log (attached, but mind you it contains several attempts: just focus on the last one) shows that some AddMachine call was made, and the node id matches the "avalugg" machine I selected:

```
2017-03-22 18:37:38,869 [DEBUG] log.py:14 - conjure-up/landscape-spell: AddMachines: [{'series': 'trusty', 'constraints': {'tags': ['node-0ced1566-1b79-11e5-846c-2c59e54
ace74']}, 'jobs': ['JobHostUnits']}]
2017-03-22 18:37:49,702 [DEBUG] log.py:14 - conjure-up/landscape-spell: AddMachines returned {'machines': [{'machine': '0'}]}
2017-03-22 18:37:49,704 [DEBUG] log.py:14 - conjure-up/landscape-spell: Adding Charm cs:trusty/haproxy-16
2017-03-22 18:37:51,812 [DEBUG] log.py:14 - conjure-up/landscape-spell: AddCharm returned {}
```

But the node is still in a "ready" state in MAAS.

My conjure-up snap:
conjure-up           2.1.2    140   canonical  classic

juju version is 2.1.2

**Comment by panlinux** [comment]
[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/863048/conjure-up.txt)

**Comment by panlinux** [comment]
juju status as of now, while it's still waiting

`Model                           Controller           Cloud/Region  Version
conjure-up-landscape-spell-69d  conjure-up-maas-9b6  maas          2.1.2

App               Version  Status   Scale  Charm             Store       Rev  OS      Notes
haproxy                    waiting    0/1  haproxy           jujucharms   16  ubuntu  exposed
landscape-server           waiting    0/1  landscape-server  jujucharms   15  ubuntu  
postgresql                 waiting    0/1  postgresql        jujucharms   40  ubuntu  
rabbitmq-server            waiting    0/1  rabbitmq-server   jujucharms   43  ubuntu  

Unit                Workload  Agent       Machine  Public address  Ports  Message
haproxy/0           waiting   allocating  0/lxd/0                         waiting for machine
landscape-server/0  waiting   allocating  0/lxd/1                         waiting for machine
postgresql/0        waiting   allocating  0/lxd/2                         waiting for machine
rabbitmq-server/0   waiting   allocating  0/lxd/3                         waiting for machine

Machine  State    DNS  Inst id  Series  AZ
0        down          pending  trusty  
0/lxd/0  pending       pending  trusty  
0/lxd/1  pending       pending  trusty  
0/lxd/2  pending       pending  trusty  
0/lxd/3  pending       pending  trusty  

Relation     Provides          Consumes          Type
peer         haproxy           haproxy           peer
website      haproxy           landscape-server  regular
db-admin     landscape-server  postgresql        regular
amqp         landscape-server  rabbitmq-server   regular
replication  postgresql        postgresql        peer
cluster      rabbitmq-server   rabbitmq-server   peer
`

**Comment by battlemidget** [comment]
@mikemccracken can you comment on this?

**Comment by mikemccracken** [comment]
@panlinux I'll try to reproduce this. what MAAS version was it?

**Comment by panlinux** [comment]
2.1.3

**Comment by mikemccracken** [comment]
Unfortunately I can't reproduce this on our test maas, v 2.1.4.
@panlinux is this reproducible regularly for you? Is avalugg a flaky node?
Looking at the logs, conjure-up is getting the API results it's expecting, no errors or strange things there.

**Comment by panlinux** [comment]
On Thu, Mar 23, 2017 at 2:52 PM, Michael McCracken <notifications@github.com
> wrote:

> Unfortunately I can't reproduce this on our test maas, v 2.1.4.
> @panlinux <https://github.com/panlinux> is this reproducible regularly
> for you? Is avalugg a flaky node?
> Looking at the logs, conjure-up is getting the API results it's expecting,
> no errors or strange things there.
>
I'll try this pinning again next time. The node is fine.

**Comment by panlinux** [comment]
On Thu, Mar 23, 2017 at 3:02 PM, Andreas Hasenack <panlinux@gmail.com>
wrote:

> On Thu, Mar 23, 2017 at 2:52 PM, Michael McCracken <
> notifications@github.com> wrote:
>
>> Unfortunately I can't reproduce this on our test maas, v 2.1.4.
>> @panlinux <https://github.com/panlinux> is this reproducible regularly
>> for you? Is avalugg a flaky node?
>> Looking at the logs, conjure-up is getting the API results it's
>> expecting, no errors or strange things there.
>>
> I'll try this pinning again next time. The node is fine.
>

I tried it again, with a different 2.1.3 MAAS server, and it worked just
fine. I pinned the deploy to different nodes and the right one was always
selected and deployed correctly.

Please mark this issue as invalid. If it happens again, I'll try to gather
more information. Thanks.

**Comment by mikemccracken** [comment]
ok, thanks!
