### ISSUE TITLE
Unable to install via: brew install conjure-up --HEAD

### ISSUE THREAD

**Issue by arosales** [conjure-up/conjure-up#762]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
  - No

- [ ] Is conjure-up running inside a virtual machine?
  - No

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

```
  OSX: 10.11.5 (15F34)
  Model Identifier:	iMac14,2
  Processor Name:	Intel Core i7
  Processor Speed: 3.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  Memory:	32 GB
  Storage: 450GB Free
```

What spell was selected?:
- N/A, install issue

What cloud provider was selected (this includes both MAAS and localhost)?:
- N/A, install issue

Please outline what commands were run to install and execute conjure-up:

```
$ brew install conjure-up --HEAD
Error: No available formula with the name "conjure-up" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

Please post **~/.cache/conjure-up/conjure-up.log**
- N/A, install issue

Provide the output of the following commands:
- N/A, install issue

Summary of problem:
Unable to install via Brew on OSX.

**Comment by battlemidget** [comment]
It hasn't been merged yet, https://github.com/Homebrew/homebrew-core/pull/11488, what you can do though is copy this file https://github.com/battlemidget/homebrew-core/blob/add-conjure-up/Formula/conjure-up.rb into your `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula` and cd into that dir and do `brew install conjure-up --HEAD`

**Comment by arosales** [comment]
@battlemidget thanks for the info I had a suspicion this may have been pilot error, thanks for the info. I'll be patient for this landing in Brew.

Thanks again for the work on this.

-Antonio

**Comment by battlemidget** [comment]
Np, I'm hoping they'll move on it today im also getting anxious :D

**Comment by battlemidget** [comment]
This is now in brew
