### ISSUE TITLE
conjure-up doesn't set terminal title

### ISSUE THREAD

**Issue by mitechie** [conjure-up/conjure-up#775]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ ] Is conjure-up running inside a virtual machine?
no

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

Mac Air with 8GB of ram

What spell was selected?:

canonical-kubernetes

What cloud provider was selected (this includes both MAAS and localhost)?:

MAAS

Please outline what commands were run to install and execute conjure-up:

conjure-up canonical-kubernetes

Please post **~/.cache/conjure-up/conjure-up.log**

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
cat /etc/lsb-release
```
    
    % which juju                                                                                
    /usr/local/bin/juju
    % which conjure-up
    /usr/local/bin/conjure-up
    % juju --version
    2.2-beta1-elcapitan-amd64
    % conjure-up --version
    conjure-up 2.1.2

Summary of problem:
The title in the terminal could be set to brand what's going on in that tab as conjure-up. 
During bootstrap you see Juju here:
![titlebar-during-bootstrap](https://cloud.githubusercontent.com/assets/75915/24404500/b9bb96a4-138f-11e7-97ca-12e8c9108e02.jpg)
And during deploy it shoes Python 3.6 vs anything conjure-up related. 
![titlebar-during-deploy](https://cloud.githubusercontent.com/assets/75915/24404501/b9c33d00-138f-11e7-87ed-10fcde8efa08.jpg)

It looks like this might be able to be set manually and branded as to what's going on.

**Comment by battlemidget** [comment]
Possible fix, just needs implemented:

```
