### ISSUE TITLE
need the ability to optionally specify the controller name and model name 

### ISSUE THREAD

**Issue by mitechie** [conjure-up/conjure-up#777]
If folks are going to leverage conjure-up for many things and keep models running beyond testing and demo I think that we need a method of specifying the controller/model names during bootstrap or deploys. I believe meaningful names are vital for long term maintainability of the models.

**Comment by johnsca** [comment]
This overlaps some with #753 which is being worked on in the [gui-model-prompt](https://github.com/conjure-up/conjure-up/tree/feature/gui-model-prompt) branch.

**Comment by battlemidget** [comment]
This is achieved through our Conjurefile support in addition to passing those models into the cli
