### ISSUE TITLE
OS X "Unable to find model"

### ISSUE THREAD

**Issue by jamesbeedy** [conjure-up/conjure-up#778]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [no ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
- [ no] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

![screen shot 2017-03-28 at 6 46 10 am](https://cloud.githubusercontent.com/assets/5590546/24408230/e951011e-1381-11e7-8e43-ac1a30d1a24c.png)

What spell was selected?:

canonical-kubernetes

What cloud provider was selected (this includes both MAAS and localhost)?:

AWS

Please outline what commands were run to install and execute conjure-up:
```bash
$ brew update 

$ brew upgrade

$ brew install conjure-up
```

Please post **~/.cache/conjure-up/conjure-up.log**

http://paste.ubuntu.com/24269626/

Provide the output of the following commands:

```
which juju
/usr/local/bin/juju

which conjure-up
/usr/local/bin/conjure-up

which lxd - N/A

juju version
2.1.2-sierra-amd64

conjure-up --version
conjure-up 2.1.2

lxd --version - N/A

cat /etc/lsb-release - N/A
```

Summary of problem:
```bash
$ conjure-up canonical-kubernetes
```
![screen shot 2017-03-28 at 6 51 14 am](https://cloud.githubusercontent.com/assets/5590546/24408490/b1dc4558-1382-11e7-89a6-4e12219b9a03.png)

(Select 'jujucharms.com' for hosted controller)
![screen shot 2017-03-28 at 6 51 34 am](https://cloud.githubusercontent.com/assets/5590546/24408504/c1d4095a-1382-11e7-84fe-4e9d75d5607f.png)

Select "Deploy all 6 remaining applications", then errors out with: http://paste.ubuntu.com/24267940/

**Comment by jamesbeedy** [comment]
```bash
$ conjure-up kubernetes 
```

Errors with the same "LookupError" http://paste.ubuntu.com/24267960/

**Comment by battlemidget** [comment]
Thanks! Will get this looked at today

**Comment by jamesbeedy** [comment]
@battlemidget I'm guessing this is happening due to the fact my controller is JAAS.

**Comment by battlemidget** [comment]
Yea it's possible, I'm testing that in a few minutes

**Comment by battlemidget** [comment]
@jamesbeedy can you re-try this with

```
brew reinstall conjure-up --HEAD
```

I think this has been addressed, there was also some JAAS authentication problems on the backend a couple days ago

**Comment by jamesbeedy** [comment]
cat ~/.cache/conjure-up/conjure-up.log -> http://paste.ubuntu.com/24282254/

Getting past that now, to the next traceback, this occurs immediately after selecting either distribution of kubernetes via conjure-up http://paste.ubuntu.com/24282269/

**Comment by battlemidget** [comment]
@jamesbeedy , `rm -rf ~/.cache/conjure-up*` and retry. We're working on a spell specification change and your cache is out of date

**Comment by jamesbeedy** [comment]
@battlemidget that did it! seems to be working now. Does conjure-up use libjuju here?

**Comment by battlemidget** [comment]
no yet, @johnsca is working on that for our 2.2 release though

**Comment by battlemidget** [comment]
libjuju will be in the 2.2 GA release, please re-open this bug if you find more issues during the beta phase so we can make sure they are addressed in either conjure-up, libjuju, or juju
