### ISSUE TITLE
Deploying with Juju 2.2 beta1 and vsphere provider - Conjure-up errors with: Application did not start successfully

### ISSUE THREAD

**Issue by larrymi** [conjure-up/conjure-up#785]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems
No
- [ ] Is conjure-up running inside a virtual machine?
No

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:
$ cat /proc/cpuinfo | grep processor | wc -l
4
$ cat /proc/meminfo |grep Mem
MemTotal:       20425236 kB
MemFree:         3128572 kB
MemAvailable:    7994216 kB

What spell was selected?:
kubernetes-core

What cloud provider was selected (this includes both MAAS and localhost)?:
vsphere

Please outline what commands were run to install and execute conjure-up:
sudo snap install conjure-up --classic --candidate
then,
conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

[conjure-up.log.gz](https://github.com/conjure-up/conjure-up/files/880592/conjure-up.log.gz)

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
cat /etc/lsb-release
```

$ which juju
/usr/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which lxd
/usr/bin/lxd
$ juju version
2.2-beta1-xenial-amd64
$ conjure-up --version
conjure-up 2.1.2
$ lxd --version
2.12
$  cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Summary of problem:
I tried to deploy kubernetes-core with juju 2.2-beta1-xenial-amd64 and soon after hitting deploy remaining applications, I got this screen:
![screenshot from 2017-03-29 18-05-08](https://cloud.githubusercontent.com/assets/13599808/24480494/4f9d0fca-14aa-11e7-9f43-f357edf8c3b0.png)

The deployment itself worked as per juju status:
![screenshot from 2017-03-29 18-07-17](https://cloud.githubusercontent.com/assets/13599808/24480551/9ce5beda-14aa-11e7-813a-d1c15bc0ac40.png)

**Comment by battlemidget** [comment]
Can you attach a tarball of `~/.cache/conjure-up/`?

**Comment by larrymi** [comment]
Adding tarball: 
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/882566/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
Thanks, unfortunately, I didnt see anything obvious here. Could you try with the latest edge version? It has an updated Juju and updated spells as well:

```
sudo snap refresh conjure-up --edge
```

**Comment by larrymi** [comment]
I re-tried with the edge version, and it worked.

![screenshot from 2017-03-30 12-38-12](https://cloud.githubusercontent.com/assets/13599808/24517964/ded32e04-1545-11e7-9b57-14553f531308.png)

![screenshot from 2017-03-30 12-39-48](https://cloud.githubusercontent.com/assets/13599808/24518011/0143b8f0-1546-11e7-967d-a871f46b393a.png)

**Comment by battlemidget** [comment]
Thanks Larry, we're doing a 2.2 beta2 today which is on its way to GA expected April 20th. Going to close this out as resolved.
