### ISSUE TITLE
bundlewriter should place generated bundles inside their cached spell dir

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#787]
currently the generated bundle is written to `~/.cache/conjure-up/kubernetes-core-<date>.yaml`. we should place that inside `~/.cache/conjure-up/kubernetes-core/bundle-<date>.yaml` so that people can easily `cp -a ~/.cache/conjure-up/kubernetes-core` and customize their spell further.

**Comment by battlemidget** [comment]
@mikemccracken what do you think?

**Comment by mikemccracken** [comment]
isn't ~/.cache/conjure-up/spellname overwritten with each download? I think
that's why I put it in the top level directory.
Maybe that's changed recently?

**Comment by battlemidget** [comment]
Ah.. I dont remember actually i need to look again

**Comment by battlemidget** [comment]
Yea looks like we remove that dir each time:

https://github.com/conjure-up/conjure-up/blob/master/conjureup/download.py#L58

**Comment by battlemidget** [comment]
Ill just document the bundle as it
