### ISSUE TITLE
Error while conjuring up kubernetes-core "Applications did not start successfully"

### ISSUE THREAD

**Issue by mbruzek** [conjure-up/conjure-up#802]
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available: 4 core i7, 450GB of disk available 

What spell was selected?: kubernetes-core

What cloud provider was selected (this includes both MAAS and localhost)?: localhost

Please outline what commands were run to install and execute conjure-up: `snap install conjure-up --channel beta`

Please post **~/.cache/conjure-up/conjure-up.log** 
[error.zip](https://github.com/conjure-up/conjure-up/files/891525/error.zip)

Provide the output of the following commands:

```
mbruzek@pandora:~$ which juju
/snap/bin/juju
mbruzek@pandora:~$ which conjure-up
/snap/bin/conjure-up
mbruzek@pandora:~$ which lxd
/usr/bin/lxd
mbruzek@pandora:~$ juju version
2.2-beta2-yakkety-amd64
mbruzek@pandora:~$ conjure-up --version
conjure-up 2.2-beta2
mbruzek@pandora:~$ lxd --version
2.12
mbruzek@pandora:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Summary of problem: I tried to conjure-up the kubernetes-core from the candidate channel and it ended in error "Application did not start successfully"

Here is the command that I ran:
```
conjure-up --channel candidate kubernetes-core
```

**Comment by mbruzek** [comment]
Here is what the `juju status` looks like on my pc: 
```
$ juju status 
Model                           Controller                Cloud/Region         Version
conjure-up-kubernetes-core-b4e  conjure-up-localhost-0fd  localhost/localhost  2.2-beta2

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            jujucharms    7  ubuntu  
etcd                        blocked      1  etcd               jujucharms   26  ubuntu  
flannel                     waiting      0  flannel            jujucharms   12  ubuntu  
kubernetes-master           error        1  kubernetes-master  jujucharms   14  ubuntu  exposed
kubernetes-worker           error        1  kubernetes-worker  jujucharms   16  ubuntu  exposed

Unit                  Workload  Agent      Machine  Public address  Ports  Message
easyrsa/0*            active    idle       0        10.33.190.190          Certificate Authority ready.
etcd/0*               blocked   executing  1        10.33.190.97           (install) Missing relation to certificate authority.
kubernetes-master/0*  error     idle       2        10.33.190.101          hook failed: "install"
kubernetes-worker/0*  error     idle       3        10.33.190.17           hook failed: "install"

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.33.190.190  juju-4a6628-0  xenial      Running
1        started  10.33.190.97   juju-4a6628-1  xenial      Running
2        started  10.33.190.101  juju-4a6628-2  xenial      Running
3        started  10.33.190.17   juju-4a6628-3  xenial      Running

Relation      Provides           Consumes           Type
certificates  easyrsa            etcd               regular
certificates  easyrsa            kubernetes-master  regular
certificates  easyrsa            kubernetes-worker  regular
cluster       etcd               etcd               peer
etcd          etcd               flannel            regular
etcd          etcd               kubernetes-master  regular
cni           flannel            kubernetes-master  regular
cni           flannel            kubernetes-worker  regular
cni           kubernetes-master  flannel            subordinate
kube-control  kubernetes-master  kubernetes-worker  regular
cni           kubernetes-worker  flannel            subordinate
```

**Comment by battlemidget** [comment]
So why did those units error out?

**Comment by mbruzek** [comment]
I looked into the failing units and they all seem to fail with loading profiles for the snaps

```
error: cannot perform the following tasks:
2017-04-04 14:23:57 INFO install - Setup snap "core" (1441) security profiles (cannot setup apparmor for snap "core": cannot load apparmor profile "snap.core.hook.configure": cannot load apparmor profile: exit status 243
2017-04-04 14:23:57 INFO install apparmor_parser output:
2017-04-04 14:23:57 INFO install apparmor_parser: Unable to replace "snap.core.hook.configure".  Permission denied; attempted to load a profile while confined?
2017-04-04 14:23:57 INFO install )
2017-04-04 14:23:57 INFO install - Setup snap "core" (1441) security profiles (cannot load apparmor profile "snap.core.hook.configure": cannot load apparmor profile: exit status 243
2017-04-04 14:23:57 INFO install apparmor_parser output:
2017-04-04 14:23:57 INFO install apparmor_parser: Unable to replace "snap.core.hook.configure".  Permission denied; attempted to load a profile while confined?
2017-04-04 14:23:57 INFO install )
```

**Comment by chuckbutler** [comment]
This seems related to the profile we are applying to lxd containers deployed via conjure-up. I'm not certain why that is the case, as it explicitly disables app armor. However if you launch a fresh container you can successfully install the components via snap.

```
lxc launch ubuntu:x tester
lxc exec tester /bin/bash
apt update && apt install -y snapd squashfuse
snap install etcd --channel=3.1/stable
```

However when I attempt the same in a conjure-up deployed lxd unit, it fails with the error pasted above.

**Comment by mbruzek** [comment]
@chuckbutler and I did some digging on this issue. We ended up with a discussion in #snappy.
I believe this is a problem loading the apparmor profile in a privileged container.

(11:11:55 AM) tyhicks: mbruzek: this is an intentional decision by lxd to not allow apparmor profile loads inside of privileged containers: https://github.com/lxc/lxd/blob/master/lxd/apparmor.go#L321
(11:13:02 AM) tyhicks: mbruzek: we're not seeing a denial message in the syslog because the rule on line 326 denies without auditing those filesystem accesses
(11:13:33 AM) tyhicks: mbruzek: you should use an unpriv container if you need to run snaps inside the container today
...
(11:15:39 AM) tyhicks: mbruzek: they're still confined and there attempts made at trying to keep them from affecting the system
(11:15:50 AM) tyhicks: s/there attempts/there are attempts/
(11:18:03 AM) tyhicks: mbruzek: you could file a bug against lxd and subscribe the security team so that we can discuss if it is safe to enable profile loads inside of a privileged container using apparmor namespaces
(11:18:18 AM) tyhicks: mbruzek: I don't know the answer to that off the top of my head and we'd need broader discussion

**Comment by battlemidget** [comment]
https://github.com/conjure-up/spells/commit/fc6e672bd501f1304cefe5a855ad4a33470a47f2
