### ISSUE TITLE
Expired timestamp

### ISSUE THREAD

**Issue by richardsith** [conjure-up/conjure-up#803]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems? 
- [x] Is conjure-up running inside a virtual machine? 

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

All environment Lab has been realised on Ubuntu 16.04 LTS:

1 VM for MAAS + conjure-up (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for JUJU (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for LANDSCAPE (memory: 8GB, CPU: 1, HDD: 500TB);
5 VM for OPENSTACK (memory: 16GB, CPU: 1, HDD: 1TB)x5;

What spell was selected?:
**Landscape**

What cloud provider was selected (this includes both MAAS and localhost)?:
**MAAS**

Please outline what commands were run to install and execute conjure-up:

**conjure-up --bootstrap-to nodeJuju**

Please post **~/.cache/conjure-up/conjure-up.log**
**[here](https://paste.ubuntu.com/24328008/)**

Provide the output of the following commands:

```
which juju
/snap/bin/juju
which conjure-up: 
/snap/bin/conjure-up
which lxd
/usr/bin/lxd
juju version
2.1.2-xenial-amd64
conjure-up --version
conjure-up 2.1.2
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
Summary of problem:

After that the vm is deployed receive the following error:
![screen shot 2017-04-06 at 16 49 07](https://cloud.githubusercontent.com/assets/9977215/24761559/0c9f382c-1aec-11e7-9a39-9e404202f0f1.png). I've open also a post [here](http://askubuntu.com/questions/900827/install-ubuntu-openstack-autopilot-on-ubuntu-16-04-2-lts-via-conjure-up)

_458 new environ: Authorization Error: 'Expired timestamp: given 1491489833 and now 1491497374 has a greater difference than threshold 300'_

**Comment by battlemidget** [comment]
Make sure you're running ntp and that your clock is synced correctly

**Comment by richardsith** [comment]
it's configurated by default on MAAS

![screen shot 2017-04-06 at 23 22 02](https://cloud.githubusercontent.com/assets/9977215/24776209/21dba890-1b20-11e7-8f3b-1e0e1d8a13ba.png)

**Comment by battlemidget** [comment]
This is strictly a time skew issue, could be a number of things but make sure your VM's are configured properly for time. It could be the vm's making the requests are setup with incorrect clocks as well. When you deploy your nodes manually via MAAS please verify that all of those clocks are set correctly as well.

**Comment by richardsith** [comment]
I've check that and it results that the date reports on MAAS was different from my clock.  I've seen that MAAS replaces the ntp of Ubuntu ((https://paste.ubuntu.com/24332640/) with its own. How do I can to set the ntp right with that?

**Comment by richardsith** [comment]
now it's fine, I've changed the ntp on VMware vSpere Client setting as ntp server ntp.ubuntu.com and the right time. The MAAS Server has the right date. thanks
