### ISSUE TITLE
deploy of Landscape in Openstack Autopilot is in permanent pending status

### ISSUE THREAD

**Issue by richardsith** [conjure-up/conjure-up#805]
Thank you for trying conjure-up! Before reporting a bug please make sure you've gone through this checklist:

 Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems?
 Is conjure-up running inside a virtual machine?
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

All environment Lab has been realised on Ubuntu 16.04 LTS:

1 VM for MAAS + conjure-up (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for JUJU (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for LANDSCAPE (memory: 8GB, CPU: 1, HDD: 500TB);
5 VM for OPENSTACK (memory: 16GB, CPU: 1, HDD: 1TB)x5;

What spell was selected?:
Landscape

What cloud provider was selected (this includes both MAAS and localhost)?:
MAAS

Please outline what commands were run to install and execute conjure-up:

conjure-up --bootstrap-to nodeJuju

Please post ~/.cache/conjure-up/conjure-up.log
here

Provide the output of the following commands:

which juju
/snap/bin/juju
which conjure-up: 
/snap/bin/conjure-up
which lxd
/usr/bin/lxd
juju version
2.1.2-xenial-amd64
conjure-up --version
conjure-up 2.1.2
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Summary of problem:
After to have deployed JUJU, during the task to deploy LANDSCAPE, the task rest in permanent pending without a feedback, it's in this situation from 1hr. 

![screen shot 2017-04-07 at 11 50 28](https://cloud.githubusercontent.com/assets/9977215/24795524/e4fd3262-1b89-11e7-89a2-1c6f66b1cbbc.png)

![screen shot 2017-04-07 at 00 09 53](https://cloud.githubusercontent.com/assets/9977215/24795492/d0d2018c-1b89-11e7-8607-9d9c116ff941.png)

the command juju status reports [that](https://paste.ubuntu.com/24333146/) and the nslookup is correct:
```
$: nslookup nodelandscape.maas
Server:		10.20.81.11
Address:	10.20.81.11#53

Name:	nodeLandscape.maas
Address: 10.20.81.101
```

**Comment by battlemidget** [comment]
Make sure you've set the promiscuous mode in vsphere

**Comment by richardsith** [comment]
promiscuous mode has to be set as Reject or Accept?

**Comment by battlemidget** [comment]
I believe Accept

**Comment by richardsith** [comment]
I'm testing that with your suggest, I'll inform you soon which is its situation.

**Comment by richardsith** [comment]
now the situation is different, have a look to the screen below:

![screen shot 2017-04-07 at 15 27 01](https://cloud.githubusercontent.com/assets/9977215/24802048/c9d75b4e-1ba6-11e7-81e1-3a0b4de55e73.png)
![screen shot 2017-04-07 at 15 27 08](https://cloud.githubusercontent.com/assets/9977215/24802049/c9e614a4-1ba6-11e7-9d58-ce5b01f88f5e.png)
![screen shot 2017-04-07 at 15 32 10](https://cloud.githubusercontent.com/assets/9977215/24802222/69d54fca-1ba7-11e7-9e04-7fa6c72ba781.png)


I'm waiting its finished to close the issue

**Comment by battlemidget** [comment]
Looking good!

**Comment by richardsith** [comment]
also the final result is good

![screen shot 2017-04-07 at 15 44 19](https://cloud.githubusercontent.com/assets/9977215/24802706/31f2282e-1ba9-11e7-98bc-3405f6c5e397.png)

 next last step is Openstack, thanks a lot for your support
