### ISSUE TITLE
Deployment of kubernetes-core crashes on 2.2-beta3

### ISSUE THREAD

**Issue by ktsakalozos** [conjure-up/conjure-up#806]
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available: This is on my local machine i7 8 Gb ram 22b free disk space. 

What spell was selected?:

kubernetes-core channel=candidate

What cloud provider was selected (this includes both MAAS and localhost)?: Localhost

Please outline what commands were run to install and execute conjure-up:

Here is what I am running:
/snap/bin/conjure-up --channel=candidate kubernetes-core

Version is 2.2-beta3 from edge deployed through snap refresh --edge conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

http://paste.ubuntu.com/24334662/

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
cat /etc/lsb-release
```
http://pastebin.ubuntu.com/24334680/

Summary of problem:
Crashes with https://imagebin.ca/v/3IGTNvLZ8eyp

**Comment by battlemidget** [comment]
@ktsakalozos is this part of the problem https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/250?

**Comment by ktsakalozos** [comment]
@battlemidget no, it does not.

**Comment by ktsakalozos** [comment]
I realised I pasted the wrong url pointing to the error. Here is the error: https://imagebin.ca/v/3IGTNvLZ8eyp

**Comment by battlemidget** [comment]
What revision of conjure-up do you have? `snap info conjure-up`

**Comment by ktsakalozos** [comment]
There you go: http://pastebin.ubuntu.com/24336115/

**Comment by battlemidget** [comment]
Thanks, I haven't been able to reproduce this particular error yet. The error you are seeing is the websocket code misbehaving so if you try a new deployment it'll probably work.

**Comment by battlemidget** [comment]
This looks to be some sort of websocket error when talking to the juju api server. Can you re-deploy and see if it's consistently failing?

**Comment by battlemidget** [comment]
Were you able to re-deploy?

**Comment by ktsakalozos** [comment]
Sorry for the delay @battlemidget  it was a crazy week (release, and... more). Just cleaned up my setup  and redeployed everything and did not get this error. Closing this ticket since it was against edge and I cannot repro anymore. Thank you.
