### ISSUE TITLE
error to build Openstack Cloud 

### ISSUE THREAD

**Issue by richardsith** [conjure-up/conjure-up#812]
Thank you for trying conjure-up! Before reporting a bug please make sure you've gone through this checklist:

Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems?
Is conjure-up running inside a virtual machine?
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

All environment Lab has been realised on Ubuntu 16.04 LTS:

1 VM for MAAS + conjure-up (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for JUJU (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for LANDSCAPE (memory: 8GB, CPU: 1, HDD: 500TB);
6 VM for OPENSTACK (memory: 16GB, CPU: 1, HDD: 1TB) for HA; 

What spell was selected?:
Landscape

What cloud provider was selected (this includes both MAAS and localhost)?:
MAAS

Please outline what commands were run to install and execute conjure-up:

conjure-up --bootstrap-to nodeJuju

Please post ~/.cache/conjure-up/conjure-up.log
here

Provide the output of the following commands:

which juju
/snap/bin/juju
which conjure-up:
/snap/bin/conjure-up
which lxd
/usr/bin/lxd
juju version
2.1.2-xenial-amd64
conjure-up --version
conjure-up 2.1.2
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Summary of problem:
After to have deployed JUJU, andLANDSCAPE, the last step is to deploy Openstack. 

![screen-shot-2017-04-07-at-16-11-49](https://cloud.githubusercontent.com/assets/9977215/24855568/48b4a448-1de2-11e7-9228-0e6299dbc977.png)

![screen shot 2017-04-10 at 10 09 52](https://cloud.githubusercontent.com/assets/9977215/24855407/d7c22aa8-1de1-11e7-87b6-0a5575d7ab7c.png)
![screen shot 2017-04-10 at 11 12 58](https://cloud.githubusercontent.com/assets/9977215/24855409/d81e7524-1de1-11e7-9161-407109803543.png)

After run all the task requested on LANDSCAPE during the deploy, 

![screen-shot-2017-04-07-at-16-38-21](https://cloud.githubusercontent.com/assets/9977215/24858081/fa6c34b4-1dea-11e7-8aca-079ff144d008.png)

about 50%, received that error:

![screen shot 2017-04-10 at 11 30 20](https://cloud.githubusercontent.com/assets/9977215/24855408/d8138d30-1de1-11e7-8161-75e541cbeb9e.png)

**Comment by battlemidget** [comment]
You'll need to post this particular question on http://askubuntu.com/questions/tagged/landscape as this isn't a conjure-up issue.

**Comment by richardsith** [comment]
ok thanks

**Comment by panlinux** [comment]
Richard, please click on that "Report a bug" link that you get in the landscape failed openstack install, that will file a bug with the logs we need to diagnose this issue.

**Comment by richardsith** [comment]
Panlinux, the vswitches are in promiscuous mode. I've attached the logs downloaded from Landscape.
 
[landscape-openstack-autopilot-logs-2017-04-10T15-14-08Z.tar.gz](https://github.com/conjure-up/conjure-up/files/910521/landscape-openstack-autopilot-logs-2017-04-10T15-14-08Z.tar.gz)

**Comment by panlinux** [comment]
launchpad bug: https://bugs.launchpad.net/landscape/+bug/1681483

Let's continue over there since the issue here in github is closed.

**Comment by floriankleewald** [comment]
Hi! 

on the VMs on ESXi i get no RAM displayed for my nodes etc after commissioning. Did you have a idea ?
