### ISSUE TITLE
syncing spell repository: handle git related conflicts better

### ISSUE THREAD

**Issue by mitechie** [conjure-up/conjure-up#813]
Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

What spell was selected?:

conjure-up landscape

Please outline what commands were run to install and execute conjure-up:

brew unlink conjure-up
brew install --devel conjure-up

Please post **~/.cache/conjure-up/conjure-up.log**

    2017-04-10 10:57:40,122 [DEBUG] log.py:14 - conjure-up/landscape: Could not sync spells from github: Command 'cd /Users/rharding/.cache/conjure-up-spells && git pull' returned non-zero exit status 128.

Provide the output of the following commands:

```
which juju
which conjure-up
which lxd
juju version = 2.2-beta1
conjure-up --version = 2.2.beta2
lxd --version
cat /etc/lsb-release
```

Summary of problem:

I updated conjure-up by going from the brew install conjure-up to brew install --devel conjure-up to get to 2.2-beta2. I then tried to do the conjure-up landscape and received the warning 

    fatal: refusing to merge unrelated histories
    [error] Can't find a spell matching 'landscape'

**Comment by mitechie** [comment]
I removed the cache and things are now reloading and working.

**Comment by battlemidget** [comment]
Thanks for the report, we need to handle this better
