### ISSUE TITLE
Error during the deploy of Landscape

### ISSUE THREAD

**Issue by richardsith** [conjure-up/conjure-up#820]
Thank you for trying conjure-up! Before reporting a bug please make sure you've gone through this checklist:

Is this problem already documented at http://conjure-up.io/docs/en/users/#_common_spell_problems?
Is conjure-up running inside a virtual machine?
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

All environment Lab has been realised on Ubuntu 16.04 LTS:

1 VM for MAAS + conjure-up (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for JUJU (memory: 8GB, CPU: 1, HDD: 500TB);
1 VM for LANDSCAPE (memory: 8GB, CPU: 1, HDD: 500TB);
5 VM for OPENSTACK (memory: 16GB, CPU: 1, HDD: 1TB)x5;

What spell was selected?:
Landscape

What cloud provider was selected (this includes both MAAS and localhost)?:
MAAS

Please outline what commands were run to install and execute conjure-up:

conjure-up --bootstrap-to nodeJuju

Please post ~/.cache/conjure-up/conjure-up.log
[here](http://paste.ubuntu.com/24374659/)

Provide the output of the following commands:

which juju
/snap/bin/juju
which conjure-up:
/snap/bin/conjure-up
which lxd
/usr/bin/lxd
juju version
2.1.2-xenial-amd64
conjure-up --version
conjure-up 2.1.2
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
Summary of problem:
After to have deployed JUJU, during the task of LANDSCAPE, the task gave me an error and not complete the task.

**Comment by richardsith** [comment]
this is the yaml before the deploy [here](https://paste.ubuntu.com/24378946/)
that one is after the error above [here](https://paste.ubuntu.com/24378948/)


![screen shot 2017-04-14 at 10 11 33](https://cloud.githubusercontent.com/assets/9977215/25037681/c7fbc338-20fa-11e7-8138-4d2b9716dfd6.png)

**Comment by battlemidget** [comment]
Ah, you're hitting https://github.com/conjure-up/conjure-up/issues/821, I'll get this fixed today and pushed out
