### ISSUE TITLE
[X86] build snap for x86 (i386/i686)

### ISSUE THREAD

**Issue by amrbaraka** [conjure-up/conjure-up#823]
Hi
I tried to the following command on newly installed ubuntu 16.04 but it fails:

```
$ sudo snap install conjure-up --classic
error: cannot install "conjure-up": snap not found

$ snap find
Name    Version   Developer   Notes  Summary
docker  1.11.2-9  docker-inc  -      The docker app deployment mechanism
lxd     2.12      canonical   -      System container manager and API

$ snap find name
Name           Version  Developer    Notes  Summary
petname        2.5      kirkland     -      generate pronouncable, perhaps even memorable, pet names
ab             1.0      snappy-test  -      Test snap with shortest name
neverbore      5        mterry       -      A picture logic puzzle game
mdns-hostname  0.0.1    welike       -      mDNS mini-daemon to published hostname.local
overlay        0.1      kyrofa       -      Tools for assisting with debugging read-only squashfs snaps via overlayfs
gucharmap-udt  9.0.git  canonical    -      Unicode character picker and font browser

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Any ideas?
Thanks!
Amr

**Comment by battlemidget** [comment]
I just tried on a fresh 16.04 system:

```
ubuntu@zohan:~$ snap list
No snaps are installed yet. Try "snap install hello-world".
ubuntu@zohan:~$ sudo snap install conjure-up --classic
conjure-up 2.1.4 from 'canonical' installed
ubuntu@zohan:~$ snap info conjure-up
name:      conjure-up
summary:   "Package runtime for conjure-up spells"
publisher: canonical
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
  
commands:
  - conjure-up.conjure-down (conjure-down)
  - conjure-up
  - conjure-up.juju (juju)
tracking:    stable
installed:   2.1.4 (196) 96MB classic
refreshed:   2017-04-14 15:07:33 +0000 UTC
channels:                    
  stable:    2.1.4     (196) 96MB classic
  candidate: 2.1.4     (196) 96MB classic
  beta:      2.2-beta2 (160) 97MB classic
  edge:      2.2-beta3 (195) 98MB classic
```

I didn't run into your issue, can you try again? Make sure you've done:

```
sudo apt-get update
sudo apt-get dist-upgrade
```

To make sure the system is fully updated.

**Comment by amrbaraka** [comment]
Hi!
Thanks for your feedback.

As you recommended I executed those two commands,and it updated it.
sudo apt-get update
sudo apt-get dist-upgrade

had to reboot,, but same output occurs:

$ sudo snap install conjure-up --classic
[sudo] password for amr: 
error: cannot install "conjure-up": snap not found
amr@amr-HP-ProBook-6460b:~$ 


$ snap list
Name  Version  Rev   Developer  Notes
core  16-2     1578  canonical  -
lxd   2.12     1745  canonical  -
amr@amr-HP-ProBook-6460b:~$

**Comment by battlemidget** [comment]
Very strange, could you try:

```
sudo snap install conjure-up --classic --edge
```

I wonder if it's an issue with the channels themselves

**Comment by amrbaraka** [comment]
Unfortunately the same..
sudo snap install conjure-up --classic --edge
[sudo] password for amr: 
error: cannot install "conjure-up": snap not found

**Comment by battlemidget** [comment]
What architecture are you running? Paste the output of `uname -a`

**Comment by amrbaraka** [comment]
$ uname -a
Linux amr-HP-ProBook-6460b 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:50:48 UTC 2017 i686 i686 i686 GNU/Linux

**Comment by battlemidget** [comment]
Yea that's why, we don't have a build for i686 just amd64.

**Comment by battlemidget** [comment]
Got a request for arm64, going to get these built as well

**Comment by battlemidget** [comment]
At this time we are unable to build an x86 version of conjure-up (which includes juju - the failure to build)

**Comment by amrbaraka** [comment]
Many Thanks for your support.
