### ISSUE TITLE
Usage on system with only root account

### ISSUE THREAD

**Issue by SystemZ** [conjure-up/conjure-up#827]
Hello, I'm just trying to install one node kubernetes on Digital Ocean droplet 8GB RAM just for 1-2h sandbox play with it.
Unfortunately I can't do anything on root even display some help.

I'm using Ubuntu 16.04 then installed via snap: `snap install conjure-up --classic`

I know dangers of root but standard procedure seems doesn't apply here like in other apps:
```
conjure-up --version
conjure-up --help
[info] 
[info] This should _not_ be run as root or with sudo.
[info]
```
I added new user for this `adduser someuser` and logged as it `su someuser` but then
```
conjure-up
The program 'conjure-up' is currently not installed. To run 'conjure-up' please ask your administrator to install the package 'conjure-up'
```

So I need to add this user to sudo group? But why to bother with it and just not launch it from root account? Am I missing something here?

**Comment by battlemidget** [comment]
You'll want to add /snap/bin to your $PATH for the `someuser`
