### ISSUE TITLE
[ARM64] Need conjure-up snap in snap store

### ISSUE THREAD

**Issue by manjo-git** [conjure-up/conjure-up#828]
## Report
Could we have conjure-up snap for ARM64 in the snap store? I was able to build the snap on arm64 system and install.. So I think it is a matter of building an ARM64 version and making it available in the snap store.

**Comment by battlemidget** [comment]
yea we can set that up

**Comment by battlemidget** [comment]
Done, install with:

```
sudo snap install conjure-up --classic --edge
```

It'll make it's way down to stable when applicable

**Comment by manjo-git** [comment]
Install worked on ARM64

$ sudo snap install conjure-up --classic --edge
conjure-up (edge) 2.2-beta3+8c775ab from 'canonical' installed
