### ISSUE TITLE
enable oracle provider

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#833]
enable oracle provider

**Comment by drewwells** [comment]
Does any of this work? I work for Oracle Cloud so could possibly provide help in implementing this feature. We typically follow the following convention for logging in.

1. TenancyID
2. Region (uscom-central-1 is not a valid region that I am aware of) working ones could be us-ashburn-1, us-phoenix-1 
3. Username (email)
4. API key, Oracle API requires request signing which is likely not available in conjure directly
