### ISSUE TITLE
conjure-up crashes on macos

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#839]
Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

    2015 Macbook Pro

What spell was selected?:

    multiple spells tried, all failing

What cloud provider was selected (this includes both MAAS and localhost)?:

     multiple clouds tried, all failing

Please outline what commands were run to install and execute conjure-up:

    I tried both:
    $ brew install conjure-up
    $ brew upgrade conjure-up --devel

Please post **~/.cache/conjure-up/conjure-up.log**

```
2017-04-21 14:06:26,985 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: LXD version: N/A, Juju version: 2.1.2-sierra-amd64
2017-04-21 14:06:30,606 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Path is local filesystem, copying /Users/kwmonroe/.cache/conjure-up-spells/hadoop-processing to /Users/kwmonroe/.cache/conjure-up/hadoop-processing
2017-04-21 14:06:30,614 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Pulling bundle for hadoop-processing from channel: stable
2017-04-21 14:06:51,017 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: sequence item 0: expected str instance, int found
```

## Please provide the output of the following commands

```
$ which juju
/usr/local/bin/juju

$ which conjure-up
/usr/local/bin/conjure-up

$ juju version
2.1.2-sierra-amd64

$ conjure-up --version
conjure-up 2.2-beta2
```

## Summary of problem

Run `conjure-up`, select a spell, select a cloud, wait for 5 seconds.  Conjure-up will Oops:

![screen shot 2017-04-21 at 2 36 58 pm](https://cloud.githubusercontent.com/assets/4576822/25293341/110202fe-26a0-11e7-9b21-fcf6e293431b.png)

**Comment by kwmonroe** [comment]
This is now working after I did `brew upgrade --HEAD conjure-up`, which gave me:

```
[DEBUG] conjure-up/_unspecified_spell - app.py:221 - LXD version: N/A, Juju version: 2.1.2-sierra-amd64, conjure-up version: 2.2-beta3+996471d
```

However, I had to manually `pip3 install juju` in conjure-up's venv.  I can either leave this open and re-verify once 2.2 has been officially released for brew, or I can close it out and open a new issue outlining the pip3 workaround.  @battlemidget which do you prefer?

**Comment by battlemidget** [comment]
@kwmonroe yea we need juju beta3 to be released to brew, working with nskaggs this week to get that done

**Comment by kwmonroe** [comment]
Closing this out.. brew install from --HEAD is working when reqs are manually pip3 installed into the venv.  I'll re/open if other issues crop up in the next release.
