### ISSUE TITLE
conjure-up initial user issues (16.04 + snap)

### ISSUE THREAD

**Issue by rothgar** [conjure-up/conjure-up#842]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [x] Is conjure-up running inside a virtual machine?

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:
unknown

    - What spell was selected?: kubernetes
    - What cloud provider was selected (this includes both MAAS and localhost)?: none
      - If MAAS which version are you running?

Please outline what commands were run to install and execute conjure-up:
clean install of ubuntu 16.04
```
apt install snapd
snap install conjure-up --classic
```

Please post **~/.cache/conjure-up/conjure-up.log**
NA

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
/usr/bin/lxd
juju version
The program 'juju' can be found in the following packages:
 * juju-2.0
 * juju-1-default
Try: apt install <selected package>
conjure-up --version
The program 'conjure-up' is currently not installed. You can install it by typing:
apt install conjure-up
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

## Summary of problem
Installing conjure-up via snap package doesn't make command available
```
snap list
Name        Version  Rev   Developer  Notes
conjure-up  2.1.5    197   canonical  classic
core        16-2     1577  canonical  -
```
I know this is a `snap` problem as @chuckbutler was able to help me out in the kubernetes slack channel. Using `export PATH=$PATH:/snap/bin` lets me run the command.

**Comment by chuckbutler** [comment]
@battlemidget relevant information:  Justin is using the root user, as this was the only user available when using the cncf provided cluster. I suspect this is in relation to default profile bits loading for `$PATH` and snaps not being part of that `$PATH`

**Comment by rothgar** [comment]
A few more issues.
I created a new user `useradd -m ubuntu`
switched to that user and was able to run `conjure-up kubernetes` but got an error about terminal size (this caused other errors later).
I zoomed out my terminal and was able to get a terminal size of 151x45 (actual screen resolution is 1366x768). I don't get the errors but I still get the tui drawing issues.
![selection_061](https://cloud.githubusercontent.com/assets/371796/25360648/dacc15d8-28fe-11e7-94c1-1248e8a9a4a9.png)
I upgraded to the beta but got the same problem
```
$ conjure-up --version
conjure-up 2.2-beta3+41e97d5
```
After working through the first few steps to run kubernetes on localhost I got an error about lxd group not existing. It said to logout/login and the problem would be solved but it didn't work (lxd group still didn't exist). As the root user I created the lxd group and added the ubuntu user to it.
```
newgrp lxd
usermod -G lxd ubuntu
```
after re-launching `conjure-up kubernetes` I got to the actual deployment steps.

**Comment by battlemidget** [comment]
What type of install was this? @chuckbutler mentioned something about a `cncf provided cluster` is that a standard Ubuntu cloud image? If I could get a reproducible environment I'll get these issues fixed. We should also be thinking about Fedora users as well now that snap is on that OS.

**Comment by rothgar** [comment]
I was provided ubuntu bare metal systems provisioned via cobbler from cncf/cluster#32
I'm not sure how they were configured but I would assume snap and conjure-up to not make assumptions about a cloud image and instead work from a base Ubuntu installation.

**Comment by battlemidget** [comment]
> I was provided ubuntu bare metal systems provisioned via cobbler from cncf/cluster#32
> I'm not sure how they were configured but I would assume snap and conjure-up to not make assumptions about a cloud image and instead work from a base Ubuntu installation.

It was made to work from a base Ubuntu installation like you would download from ubuntu.com. Which most people would have a new non root user in additon to the proper paths added. We also test via MAAS which deploys nodes using the cloud images so we make sure they work there as well.

Is there a way for me to get a reproducible environment so I can take a look and see what the differences are between a standard desktop/server iso versus what you're using?

**Comment by rothgar** [comment]
ping @cncfclusterteam

**Comment by battlemidget** [comment]
Thanks, we'll need to do more environment checking and update our instructions to make sure a non-root user is created.

**Comment by mattwhi** [comment]
Hi, I have just done a clean install 16gb Ram SSD 6 Core AMD Processor, When I attempt to conjure-up I get 'Unable to Bootstrap (cloud type: localhost)' any ideas?

Ubuntu Openstack with NovaLXD

**Comment by battlemidget** [comment]
Can you open a new bug on this? Also providing what is asked for in the issue template?

**Comment by battlemidget** [comment]
I believe we've taken care of the majority of these concerns. If there are some that still exist please file a new bug and we'll get those addressed.
