### ISSUE TITLE
MAAS is not completing a successful node deployment

### ISSUE THREAD

**Issue by ampena** [conjure-up/conjure-up#843]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?

No

Please outline the hardware you're running conjure-up on, including number of cpus, amount of memory, amount of storage space available:

This is the hardware of the machine selected as juju controller role.
Number of cpus: 16
Amount of Memory: 32GiB
Storage space available: 278.9GiB

    - What spell was selected?:
          Landscape
    - What cloud provider was selected (this includes both MAAS and localhost)?:
          MAAS
      - If MAAS which version are you running?
          MAAS version 2.1.3

Please outline what commands were run to install and execute conjure-up:

I executed these commands in MAAS server:
snap install conjure-up --classic
conjure-up --bootstrap-to (the hostname of the machine selected as juju controller role)

Please post **~/.cache/conjure-up/conjure-up.log**

[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/956499/conjure-up.txt)

## Please provide the output of the following commands

```
which juju
/snap/bin/juju
which conjure-up
/snap/bin/conjure-up
which lxd
/usr/bin/lxd

juju version
2.1.2-xenial-amd64
conjure-up --version
conjure-up 2.1.5
lxd --version
2.12
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

## Summary of problem
Can not install landscape using the command conjure-up --bootstrap-to <hostname>.

**Comment by battlemidget** [comment]
We're ramping up to a 2.2 release do you mind trying:

```
sudo snap refresh conjure-up --edge
```

And retrying the deployment? If the problem still exists we can get it fixed quicker there.

**Comment by ampena** [comment]
Ok, I executed the command in the MAAS server and tried again to deploy Landscape using congure-up --bootstrap-to, but I got the same error.

![image](https://cloud.githubusercontent.com/assets/28022473/25409045/5e22fbb0-29de-11e7-9602-c1599352d47f.png)

**Comment by battlemidget** [comment]
Can you now attach latest ~/.cache/conjure-up/conjure-up.log?

**Comment by ampena** [comment]
Here are the files. I removed the apikeys.

[credentials.txt](https://github.com/conjure-up/conjure-up/files/958372/credentials.txt)
[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/958373/conjure-up.txt)

**Comment by battlemidget** [comment]
`2017-04-25 17:37:10,938 [ERROR] conjure-up/landscape - common.py:200 - Error bootstrapping controller: ERROR Authorization Error: Invalid API key.`

Make sure you are using the correct api key for MAAS:

http://maas.domain/MAAS/account/prefs/ the key is listed under:

Keys
MAAS Keys

You need to make sure you copy the whole api key that should have 3 sections seperated by `:`. Can you double check to make sure you've entered the correct key?

**Comment by ampena** [comment]
I was using that key, but now I tried selecting it by triple clicking on it and it seems to be correct now, but few second later the same problem appears. I copied the conjure-up.log file:

[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/958458/conjure-up.txt)

**Comment by battlemidget** [comment]
This is showing an error finding a MAAS machine to bootstrap too:

```
ERROR failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=10.232.213.45
```
Please double check your MAAS configuration as machine with `10.232.213.23` doesn't seem to be working correctly.

**Comment by ampena** [comment]
Hello, 
Thank you for your suggestions.
I reinstalled MAAS using the solution from: https://www.ubuntu.com/download/cloud/autopilot. I'm still having problems when I run "conjure-up --bootstrap-to <hostname>", now the deployment starts but few minutes later it stops the process showing an error. I copied the conjure-up.log file:
[conjure-up.txt](https://github.com/conjure-up/conjure-up/files/962652/conjure-up.txt)

**Comment by battlemidget** [comment]
Your maas is still incorrectly configured:

```
15:10:08 ERROR cmd supercommand.go:458 failed to bootstrap model: bootstrap instance started but did not change to Deployed state: instance "cd3rmw" failed to deploy
```

This is saying that conjure-up was unable to start an instance via MAAS and have it come up to a deployed state so we could continue the installation.

**Comment by battlemidget** [comment]
Please obtain further support for MAAS via https://askubuntu.com/questions/tagged/maas
