### ISSUE TITLE
Unable to install OpenStack on single node with conjure-up

### ISSUE THREAD

**Issue by petrovicaleksandar** [conjure-up/conjure-up#858]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

I was following instructions on https://www.ubuntu.com/download/cloud/conjure-up and installation failed. 
![image](https://cloud.githubusercontent.com/assets/28317525/25639510/2040c47c-2f5a-11e7-8976-92482730e070.png)

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
Not as far as I know.
- [ ] Is conjure-up running inside a virtual machine?
No.
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
I did not try this option.

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
lxc config show
cat /etc/lsb-release
```
:~# which juju
/snap/bin/juju
:~# which conjure-up
/snap/bin/conjure-up
:~# which lxd
/usr/bin/lxd
:~# juju version
Since Juju 2 is being run for the first time, downloading latest cloud information.
Fetching latest public cloud list...
Updated your list of public clouds with 1 cloud and 1 cloud region added:

    added cloud:
        - oracle-compute
    added cloud region:
        - google/asia-southeast1
2.1.2-xenial-amd64
:~# 
:~/.cache/conjure-up$ conjure-up --version
conjure-up 2.1.5
:~/.cache/conjure-up$ lxd --version
2.13
:~/.cache/conjure-up$ lxc config show
config:
  core.https_address: '[::]'
:~/.cache/conjure-up$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/971960/conjure-up.tar.gz)

## Sosreport

In order to better get an overall idea of your system setup please also attach a **sosreport**

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

## What Spell was Selected?

[sosreport.tar.gz](https://github.com/conjure-up/conjure-up/files/971999/sosreport.tar.gz)

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

Just those ones on listed web site.

**Comment by petrovicaleksandar** [comment]
Please find below printout of 'juju status' if needed:
`:~$ juju status
Model                         Controller                Cloud/Region         Version
conjure-openstack-novalx-b55  conjure-up-localhost-252  localhost/localhost  2.1.2

App                    Version  Status       Scale  Charm                  Store       Rev  OS      Notes
ceph-mon               10.2.6   active           3  ceph-mon               jujucharms    9  ubuntu
ceph-osd               10.2.6   active           3  ceph-osd               jujucharms  241  ubuntu
ceph-radosgw           10.2.6   waiting          1  ceph-radosgw           jujucharms  247  ubuntu
glance                 12.0.0   waiting          1  glance                 jujucharms  256  ubuntu
keystone               9.2.0    waiting          1  keystone               jujucharms  265  ubuntu
lxd                    2.0.9    active           1  lxd                    jujucharms   10  ubuntu
mysql                           maintenance      1  percona-cluster        jujucharms  250  ubuntu
neutron-api            8.4.0    waiting          1  neutron-api            jujucharms  250  ubuntu
neutron-gateway        8.4.0    waiting          1  neutron-gateway        jujucharms  234  ubuntu
neutron-openvswitch    8.4.0    active           1  neutron-openvswitch    jujucharms  240  ubuntu
nova-cloud-controller  13.1.3   waiting          1  nova-cloud-controller  jujucharms  294  ubuntu
nova-compute           13.1.3   active           1  nova-compute           jujucharms  266  ubuntu
ntp                             waiting          0  ntp                    jujucharms   17  ubuntu
openstack-dashboard    9.1.1    waiting          1  openstack-dashboard    jujucharms  245  ubuntu  exposed
rabbitmq-server        3.5.7    active           1  rabbitmq-server        jujucharms   61  ubuntu

Unit                      Workload     Agent      Machine  Public address  Ports           Message
ceph-mon/0                active       idle       0        10.0.8.220                      Unit is ready and clustered
ceph-mon/1*               active       idle       1        10.0.8.226                      Unit is ready and clustered
ceph-mon/2                active       idle       2        10.0.8.67                       Unit is ready and clustered
ceph-osd/0*               active       idle       3        10.0.8.144                      Unit is ready (1 OSD)
ceph-osd/1                active       idle       4        10.0.8.126                      Unit is ready (1 OSD)
ceph-osd/2                active       idle       5        10.0.8.228                      Unit is ready (1 OSD)
ceph-radosgw/0*           waiting      idle       6        10.0.8.39       80/tcp          Incomplete relations: identity
glance/0*                 waiting      idle       7        10.0.8.16       9292/tcp        Incomplete relations: identity, database
keystone/0*               waiting      idle       8        10.0.8.158      5000/tcp        Incomplete relations: database
mysql/0*                  maintenance  executing  9        10.0.8.146                      (install) installing charm software
neutron-api/0*            waiting      idle       10       10.0.8.111      9696/tcp        Incomplete relations: identity, database
neutron-gateway/0*        waiting      idle       11       10.0.8.128                      Incomplete relations: network-service
nova-cloud-controller/0*  waiting      idle       12       10.0.8.20       8774/tcp        Incomplete relations: identity, database
nova-compute/0*           active       idle       13       10.0.8.191                      Unit is ready
  lxd/0*                  active       idle                10.0.8.191                      Unit is ready
  neutron-openvswitch/0*  active       idle                10.0.8.191                      Unit is ready
openstack-dashboard/0*    waiting      executing  14       10.0.8.168      80/tcp,443/tcp  (update-status) Incomplete relations: identity
rabbitmq-server/0*        active       idle       15       10.0.8.110      5672/tcp        Unit is ready

Machine  State    DNS         Inst id         Series  AZ
0        started  10.0.8.220  juju-4deb0e-0   xenial
1        started  10.0.8.226  juju-4deb0e-1   xenial
2        started  10.0.8.67   juju-4deb0e-2   xenial
3        started  10.0.8.144  juju-4deb0e-3   xenial
4        started  10.0.8.126  juju-4deb0e-4   xenial
5        started  10.0.8.228  juju-4deb0e-5   xenial
6        started  10.0.8.39   juju-4deb0e-6   xenial
7        started  10.0.8.16   juju-4deb0e-7   xenial
8        started  10.0.8.158  juju-4deb0e-8   xenial
9        started  10.0.8.146  juju-4deb0e-9   xenial
10       started  10.0.8.111  juju-4deb0e-10  xenial
11       started  10.0.8.128  juju-4deb0e-11  xenial
12       started  10.0.8.20   juju-4deb0e-12  xenial
13       started  10.0.8.191  juju-4deb0e-13  xenial
14       started  10.0.8.168  juju-4deb0e-14  xenial
15       started  10.0.8.110  juju-4deb0e-15  xenial

Relation                 Provides               Consumes               Type
mon                      ceph-mon               ceph-mon               peer
mon                      ceph-mon               ceph-osd               regular
mon                      ceph-mon               ceph-radosgw           regular
ceph                     ceph-mon               glance                 regular
ceph                     ceph-mon               nova-compute           regular
cluster                  ceph-radosgw           ceph-radosgw           peer
identity-service         ceph-radosgw           keystone               regular
cluster                  glance                 glance                 peer
identity-service         glance                 keystone               regular
shared-db                glance                 mysql                  regular
image-service            glance                 nova-cloud-controller  regular
image-service            glance                 nova-compute           regular
amqp                     glance                 rabbitmq-server        regular
cluster                  keystone               keystone               peer
shared-db                keystone               mysql                  regular
identity-service         keystone               neutron-api            regular
identity-service         keystone               nova-cloud-controller  regular
identity-service         keystone               openstack-dashboard    regular
lxd-migration            lxd                    lxd                    peer
lxd                      lxd                    nova-compute           regular
cluster                  mysql                  mysql                  peer
shared-db                mysql                  neutron-api            regular
shared-db                mysql                  nova-cloud-controller  regular
cluster                  neutron-api            neutron-api            peer
neutron-plugin-api       neutron-api            neutron-gateway        regular
neutron-plugin-api       neutron-api            neutron-openvswitch    regular
neutron-api              neutron-api            nova-cloud-controller  regular
amqp                     neutron-api            rabbitmq-server        regular
cluster                  neutron-gateway        neutron-gateway        peer
quantum-network-service  neutron-gateway        nova-cloud-controller  regular
amqp                     neutron-gateway        rabbitmq-server        regular
neutron-plugin           neutron-openvswitch    nova-compute           regular
amqp                     neutron-openvswitch    rabbitmq-server        regular
cluster                  nova-cloud-controller  nova-cloud-controller  peer
cloud-compute            nova-cloud-controller  nova-compute           regular
amqp                     nova-cloud-controller  rabbitmq-server        regular
lxd                      nova-compute           lxd                    subordinate
neutron-plugin           nova-compute           neutron-openvswitch    subordinate
compute-peer             nova-compute           nova-compute           peer
amqp                     nova-compute           rabbitmq-server        regular
ntp-peers                ntp                    ntp                    peer
cluster                  openstack-dashboard    openstack-dashboard    peer
cluster                  rabbitmq-server        rabbitmq-server        peer

:~$
`

**Comment by battlemidget** [comment]
Hey @petrovicaleksandar,

Thank you for gathering that data, this is a known problem and has improved with our `beta` release of conjure-up. However, we are also finding that we need to still do some more work with how we are detecting units to become ready before prompting for post processing.

You'll have better luck with `beta` but you may run into the other issue that we are actively addressing as I write this comment.

To use the beta you can do 

`sudo snap refresh conjure-up --beta`

**Comment by battlemidget** [comment]
@johnsca This is what we were talking about `juju wait` happening to quickly where the units are still in that state of not being ready.

**Comment by petrovicaleksandar** [comment]
Hi @battlemidget and @johnsca 

As you predicted, I could not finish installation
![image](https://cloud.githubusercontent.com/assets/28317525/25676875/c38bb6c0-3011-11e7-8518-fdefc7bc935b.png)
I even restarted node and I could not finish installation. 
However, if you bottom of attached picture, I get notifications that some processes/deployments were still executing.
Do you have any hints that can help me?
When are you going to deliver full revision, if that is public information?
Thank you

**Comment by battlemidget** [comment]
We are working on getting this addressed this week. Can you attach a new tarball of `~/.cache/conjure-up` so we can get the exact log from that issue above? Also can you post a new `juju status --format yaml` as well?

Thank you

**Comment by petrovicaleksandar** [comment]
Here they are:

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/974622/conjure-up.tar.gz)
[juju_status.yaml.txt](https://github.com/conjure-up/conjure-up/files/974636/juju_status.yaml.txt)

**Comment by battlemidget** [comment]
We've made several updates in our `edge` snap, please give it a try and open a new bug if you run into any other problems
