### ISSUE TITLE
ubuntui version in requirements.txt

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/conjure-up#868]
## Report

```
$ which juju
/usr/local/bin/juju
$ which conjure-up
/usr/local/Cellar/conjure-up/HEAD-e2b67b3/libexec/bin/conjure-up
$ juju version
2.1.2-sierra-amd64
$ conjure-up --version
conjure-up 2.2-beta3+996471d
```

Please attach tarball of **~/.cache/conjure-up**:

```
$ tail -f .cache/conjure-up/conjure-up.log
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/Cellar/conjure-up/HEAD-e2b67b3/libexec/lib/python3.6/site-packages/conjureup/controllers/newcloud/gui.py", line 5, in <module>
    from conjureup.ui.views.newcloud import NewCloudView
  File "/usr/local/Cellar/conjure-up/HEAD-e2b67b3/libexec/lib/python3.6/site-packages/conjureup/ui/views/newcloud.py", line 4, in <module>
    from ubuntui.widgets.input import SelectorHorizontal
ImportError: cannot import name 'SelectorHorizontal'
```
## Commands ran

- ```conjure-up```
- select a bundle and JAAS controller
- hit above stack trace

## Additional Information

This is happening because i had an old `ubuntui` pip package.  Fixed by upgrading to >= 0.1.5.  Suggest to include this as a minimum version in `requirements.txt`.

**Comment by battlemidget** [comment]
Are you seeing crashes like in https://github.com/conjure-up/conjure-up/issues/839 still? I can close that one out if not, I need to push a new release to brew that has the additional requirements like libjuju etc. working on that this week

**Comment by kwmonroe** [comment]
@battlemidget negative on crashes like #839.  brew install conjure-up --HEAD is working nicely after getting juju/ubuntui at the right levels.  I left 839 open on purpose to test an official release, but I'll close it out now and reopen if other issues come up post-release.

For this one though, I would like to see versioned reqs in requirements.txt.

**Comment by battlemidget** [comment]
Does building from --HEAD pull the version from the requirements.txt or from the dependencies that are defined in the formulae?

**Comment by kwmonroe** [comment]
@battlemidget, looks like brew does indeed install the deps from:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/conjure-up.rb#L30

For macOS, i'm guessing including a version in reqs.txt would have no effect.  Still may be useful for other platforms, but i think you'll need to update the above for brew.

**Comment by battlemidget** [comment]
Thanks, I'll work to get those added
