### ISSUE TITLE
snap configure hook could just run `lxc version` to determine if installation needed

### ISSUE THREAD

**Issue by OddBloke** [conjure-up/conjure-up#873]
## Report

When doing `snap install --classic --edge conjure-up`, the configure hook attempts to work out if lxc is installed, and will install it if it isn't. At the moment, only the snap being installed will skip installation. I think that lxd being installed from any source should be sufficient (and will make the snap easier to use on non-Ubuntu distros).

**Comment by battlemidget** [comment]
I think we're going to go with a pure snap install for both conjure-up and lxd

**Comment by OddBloke** [comment]
On Tue, May 09, 2017 at 12:49:23PM -0700, Adam Stokes wrote:
> I think we're going to go with a pure snap install for both conjure-up and lxd

So lxd would be bundled with conjure-up?

**Comment by battlemidget** [comment]
That's a discussion we're having, the two options are:

1. Bundle lxd with conjure-up, this gives us the control over the version that we know works with conjure-up/juju

2. `snap install lxd` and just update our `LXD_DIR` to point there

**Comment by OddBloke** [comment]
On Tue, May 09, 2017 at 01:02:27PM -0700, Adam Stokes wrote:
> 1. Bundle lxd with conjure-up, this gives us the control over the version that we know works with conjure-up/juju
>
> 2. `snap install lxd` and just update our `LXD_DIR` to point there

Fair enough.  At the moment the installation experience if you already
have lxd installed is pretty rocky, so however we can address that would
be good. :)
