### ISSUE TITLE
Cannot retrieve charm "cs:haproxy-41" 

### ISSUE THREAD

**Issue by InfoQB** [conjure-up/conjure-up#874]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
lxc config show
cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

In order to better get an overall idea of your system setup please also attach a **sosreport**

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?
MAAS Version 2.1.3+bzr5573-0ubuntu1 (16.04.1)

## Commands ran
conjure-up --bootstrap-to <hostname>
Please outline what commands were run to install and execute conjure-up:
snap install conjure-up --classic
sudo snap refresh conjure-up --edge
conjure-up --bootstrap-to <hostname>

## Additional Information

When following this installation guide: https://www.ubuntu.com/download/cloud/autopilot
using conjure-up --bootstrap-to <hostname> chosing to install landscape (for openstack installation) we receive error message "Cannot retrieve charm "cs:haproxy-41"" and I don't know how to fix this issue.

juju status:
Model                  Controller           Cloud/Region            Version      SLA
conjure-landscape-fbd  conjure-up-maas-67c  conjure-cloud-maas-2af  2.2-beta4.1  unsupported

App  Version  Status  Scale  Charm  Store  Rev  OS  Notes

Unit  Workload  Agent  Machine  Public address  Ports  Message

Machine  State    DNS            Inst id  Series  AZ       Message
0        started  172.19.254.86  7maedw   xenial  default  Deployed

juju version:
2.2-beta4-xenial-amd64

conjure-up --version:
conjure-up 2.2-beta4+4aefb70

lxd --version:
2.13

**Comment by InfoQB** [comment]
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/986901/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
@johnsca similar to what we were seeing last week about not being able to find a charm even though the path is correct. it could still be an issue with the charmstore again, but, maybe we should handle this better like we discussed, if it's seen in the charmstore but not the controller retry. Thoughts?

**Comment by johnsca** [comment]
@InfoQB Do you still have this controller available?  The logs from machine 0 on the `controller` model would be very helpful in debugging this.

**Comment by InfoQB** [comment]
Yes we do have that. Just let me know what you need and how to get it :)

 



Oskar Paulsson

 <mailto:omp@infoqb.com> omp@infoqb.com

 <http://www.infoqb.com/> www.infoqb.com

Granbergsvägen 1

912 32 Vilhelmina

Support/Sales:0770-350340

 

Från: Cory Johns [mailto:notifications@github.com] 
Skickat: den 9 maj 2017 16:34
Till: conjure-up/conjure-up <conjure-up@noreply.github.com>
Kopia: InfoQB <omp@infoqb.com>; Mention <mention@noreply.github.com>
Ämne: Re: [conjure-up/conjure-up] Cannot retrieve charm "cs:haproxy-41" (#874)

 

@InfoQB <https://github.com/InfoQB>  Do you still have this controller available? The logs from machine 0 on the controller model would be very helpful in debugging this.

**Comment by InfoQB** [comment]
If it would make things easier for you, we can give you access to the servers instead?

**Comment by johnsca** [comment]
Access to the server is fine, if that's easiest for you (my public key is available via GitHub at https://github.com/johnsca.keys), but I really only need the controller log (`/var/log/juju/machine-0.log` from machine `0` on the `controller` model) (and really only the timeframe from between +/1, say, an hour from when the failure occurred).  I don't think it contains any sensitive data, but of course you should do a spot review, particularly near the start of the file.  You could send it to `cory.johns@canonical.com` or attach it here if you're comfortable with that.  You can also encrypt it using my [gpg key](http://keyserver.ubuntu.com:11371/pks/lookup?fingerprint=on&op=index&search=0x5762CA76ABD635A79185394EDB6E071B449C78B1) if you like.

Again, whatever's easiest or you feel most comfortable with.  I am fine with ssh if that's simpler and you're comfortable with it.

**Comment by InfoQB** [comment]
I've sent you an email from omp@infoqb.com with the log and i apologize for my late reply

**Comment by InfoQB** [comment]
I have another question, when bootstraping to a node and we chose to install landscape(We are retrying the installation) it's bootstraping to other node that the one we specified. 

Is it possible to either install landscape to only 1 node(all in one) and then use the rest of the nodes for openstack deployment (that's how we did in 14.04).
Or can we specify to only install landscape to a node called 05?

**Comment by battlemidget** [comment]
Unfortunately, the way Juju 2 works is that a node is always used for the controller (juju bootstrap) and then the actual deployments of applications start an additional node and so on. There has been some discussion that would allow conjure-up to handle this particular use case, however, at this time it is not on our roadmap for the near future.

**Comment by InfoQB** [comment]
Ok thank you for the information, it's helping us newbies a lot. 
So one node will be used for juju bootstrap, how will maas decide wich node that will be? Can we chose wich one to use? 
And a second node will be used for landscape?

**Comment by battlemidget** [comment]
You can predefine the bootstrap node, what I usually do is create a KVM instance on the MAAS server and register that into MAAS (with the virsh power type). Then you can run the following:

```
conjure-up --bootstrap-to <vmname>.maas
```

That way you can make a really small VM and keep your bare metal for the landscape/autopilot deployment. I would first start here for help with adding a VM to MAAS (https://docs.ubuntu.com/maas/2.1/en/installconfig-nodes-power-types) then visit (https://docs.ubuntu.com/maas/2.1/en/installconfig-add-nodes#kvm-guest-nodes) for additional information on configuring the VM.

**Comment by InfoQB** [comment]
Oh ok, I will look into that and se if the CPU for the servers used can utilize that.
I thank you for the help and information!
I will close the issue since we got Landscape installation to work and if something else comes up we'll be in touch again.
