### ISSUE TITLE
conjure-up unable to obtain a node from MAAS

### ISSUE THREAD

**Issue by haashah** [conjure-up/conjure-up#876]
## Report

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems. 

No this is not documented

- [x] Is conjure-up running inside a virtual machine?

Yes conjure-up is running inside a vm setup with maas.

- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

Yes hit the same issue with conjure-up (edge) 2.2-beta4+4aefb70 

## Please provide the output of the following commands

```
which juju
/snap/bin/juju

which conjure-up
/snap/bin/conjure-up

which lxd
/usr/bin/lxd

juju version
2.1.2-xenial-amd64

conjure-up --version
conjure-up 2.1.5

lxd --version
2.13

lxc config show
If this is your first time using LXD, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

config: {}

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"


Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/988802/conjure-up.tar.gz)

```

## Sosreport

In order to better get an overall idea of your system setup please also attach a **sosreport**

```
sudo apt install sosreport
sosreport
[sosreport-ubuntu-20170510110043.zip](https://github.com/conjure-up/conjure-up/files/988814/sosreport-ubuntu-20170510110043.zip)
```



The resulting output file can be attached to this issue.


I am trying to deploy openstack using the guide:
https://www.ubuntu.com/download/cloud/autopilot


When running the following command to bootrap a node:

$ conjure-up --bootstrap-to juju

juju is the hostname of the VM to be bootrap. MAAS is the provider.

I see the following error when running the landscape spell:

Juju failed to bootrap: maas. 

in the logs I see:

_Launching controller instance(s) on maas...

10:43:25 INFO  juju.provider.common destroy.go:20 destroying model "controller"

10:43:25 INFO  juju.provider.common destroy.go:31 destroying instances

10:43:25 INFO  juju.provider.common destroy.go:51 destroying storage

10:43:25 ERROR cmd supercommand.go:458 failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=juju

10:43:25 DEBUG cmd supercommand.go:459 (error details: [{github.com/juju/juju/cmd/juju/commands/bootstrap.go:574: failed to bootstrap model} {github.com/juju/juju/provider/common/bootstrap.go:179: cannot start bootstrap instance} {github.com/juju/juju/provider/maas/environ.go:950: cannot run instances} {github.com/juju/juju/provider/maas/environ.go:1310: cannot run instance} {github.com/juju/juju/provider/maas/environ.go:751: } {github.com/juju/gomaasapi/controller.go:511: } {github.com/juju/gomaasapi/controller.go:708: } {github.com/juju/gomaasapi/controller.go:739: } {github.com/juju/gomaasapi/client.go:123: } {ServerError: 409 CONFLICT (No available machine matches constraints: mem=3584.0 name=juju)}])

2017-05-10 10:43:26,727 [DEBUG] log.py:14 - conjure-up/_unspecified_spell: Showing dialog for exception: Juju failed to bootstrap: maas_


## What Spell was Selected?
bootstrap-to

## What provider (aws, maas, localhost, etc)?
maas

### MAAS Users
Which version of MAAS?
MAAS version is  2.1.3

**Comment by battlemidget** [comment]
`10:43:25 ERROR cmd supercommand.go:458 failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=juju
`

This is a MAAS error where conjure-up can't find a hostname of `juju` to start the node.  This usually indicates a failure in your MAAS configuration.  Please verify that you can deploy a node via MAAS and that you can resolve `juju` hostname to that deployed node IP.

**Comment by haashah** [comment]
I tried deploying a node on MAAS. that completed successfully. can you clarify the hostname resolution? do you mean the maas node being able to ping with hostname only?

**Comment by battlemidget** [comment]
Wherever you ran conjure-up from tried to contact a MAAS change via `juju` hostname but was not resolvable.

**Comment by haashah** [comment]
That would be the maas node itself. I added the resolvconf entry and it can resolve from fqdn to ip i.e juju.maas
should I be entering this value when running conjure up?

**Comment by battlemidget** [comment]
Yes use `juju.maas`

**Comment by haashah** [comment]
FYI I tried running conjure-up --bootstrap-to juju.maas and that also failed even though ping to juju.maas works. Can you clarify to bootstrap a node do we need it in deployed state or ready state and on what version of ubuntu in the deployed state? since the guide doesnt mention

**Comment by battlemidget** [comment]
The node has to be in a 'Ready' state and also can be powered on/off automatically. Ubuntu 16.04 is the version of Ubuntu that is recommended

**Comment by haashah** [comment]
ok so checked the node can be bootstrap and resolved using fqdn from maas node. Automatic power off/on is also working. The node is in Ready state and powered off when conjure-up is run. I still hit the error below.One thing i noticed is the contraint value for mem is also wrong and not 3584 on the actual node. 

`ERROR failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=juju.maas

2017-05-11 10:39:21,479 [DEBUG] conjure-up/landscape - events.py:50 - Setting Error at conjureup/events.py:133
2017-05-11 10:39:21,480 [ERROR] conjure-up/landscape - events.py:141 - Unhandled exception
Traceback (most recent call last):
  File "/snap/conjure-up/291/lib/python3.6/site-packages/conjureup/events.py", line 139, in handle_exception
    raise exc
  File "/snap/conjure-up/291/lib/python3.6/site-packages/conjureup/controllers/newcloud/common.py", line 206, in do_bootstrap
    cloud_type))
Exception: Unable to bootstrap (cloud type: maas)
`

**Comment by haashah** [comment]
I verified memory value of machine from MAAS UI as well maas $PROFILE nodes read from the CLI. memory for the node in maas in 2048 not 3584.

**Comment by battlemidget** [comment]
@haashah What about just running a `juju bootstrap maas/<maasserverip> --to juju.maas --debug`

Does that work? If not, then this is still an issue with Juju trying to request a machine from your maas.

**Comment by haashah** [comment]
@battlemidget I ran the above command. Got the following logs:


12:55:14 INFO  juju.cmd supercommand.go:63 running juju [2.2-rc1 gc go1.8]
12:55:14 DEBUG juju.cmd supercommand.go:64   args: []string{"/snap/conjure-up/319/bin/juju", "bootstrap", "maas", "--to", "juju.maas", "--debug", "--credential", "admin"}
12:55:14 DEBUG juju.cmd.juju.commands bootstrap.go:803 authenticating with region "" and credential "admin" ()
12:55:14 DEBUG juju.cmd.juju.commands bootstrap.go:915 provider attrs: map[]
12:55:14 INFO  cmd authkeys.go:114 Adding contents of "/home/ubuntu/.local/share/juju/ssh/juju_id_rsa.pub" to authorized-keys
12:55:14 INFO  cmd authkeys.go:114 Adding contents of "/home/ubuntu/.ssh/id_rsa.pub" to authorized-keys
12:55:14 DEBUG juju.cmd.juju.commands bootstrap.go:971 preparing controller with config: map[apt-mirror: type:maas development:false proxy-ssh:false logforward-enabled:false enable-os-refresh-update:true provisioner-harvest-mode:destroyed no-proxy:127.0.0.1,localhost,::1 authorized-keys:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA4NIMAw256vXPC5GR8PGTfhk1VfuACjOoWTNLGmEPgYp+aHbpPBuBTfWNGb7vDHEmyYsPGWmW+U6vOc9Lm9Rk+YNJPtScFU2wu7vaEazoZKLelLAsbqIP8SVUTfUUIV9lW/tdn9qGuAnI9ZNCU0t+k6ChoQu5Je+L90oACvhq7ZwDfAfCFyRem0EZEZoARjcmcocXpA3OkNr+Aq1dopE5VfZU+C5x4q+j3yEYnH0XjNYHWDWArJve47fbnglpVrt0V8WkSg/3/jRfr+pUCj/wHjbdl43W+wTQRZ+MRZhsUrjEZKHZp9V3IEwjAivdlxKdLRSzOfzHwSNJQKMaCjRV juju-client-key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRoMFj2f8WJs4vjYeeKHdAeNYdXCEyIQK3PV3T7PrwF/YDVJWvwYbAcB78/tgUvprn0n8HRti5IUSSZLvfOwNWor+49CT2aXNiG+3i3bcNZRAYdeZoZX1CrDd1Zi50Rt3U5DleEvm0U/2vlvD397SoiF6FCxs5ND2esJjaY7TklWIxpFxo3fUBS6pStMdTkeaA+bV6lqA9x/3xBryQd8NTBUJhlhkwxvSh4k3TAWtJKSvxy0tQozm9jnlr8DBAcYXmFSFLXHKbm2TKauqOQxaUaGXD986rJeZIdWLzggImb50H/umbzXuUWLCYJJzv7XmYVwIJzNIAgFDBg11b5kDr ubuntu@ubuntu
 uuid:970b7bd4-3928-427c-8ee7-70855ebeb276 net-bond-reconfigure-delay:17 https-proxy: max-status-history-age:336h transmit-vendor-metrics:true logging-config: apt-http-proxy: ssl-hostname-verification:true ftp-proxy: http-proxy: resource-tags: disable-network-management:false max-status-history-size:5G image-stream:released ignore-machine-addresses:false apt-no-proxy: image-metadata-url: agent-stream:released name:controller apt-https-proxy: test-mode:false agent-metadata-url: enable-os-upgrade:true firewall-mode:instance apt-ftp-proxy: automatically-retry-hooks:true default-series:xenial]
12:55:14 DEBUG juju.provider.maas environprovider.go:56 opening model "controller".
12:55:14 INFO  cmd bootstrap.go:481 Creating Juju controller "maas" on maas
12:55:15 INFO  juju.cmd.juju.commands bootstrap.go:536 combined bootstrap constraints:
12:55:15 DEBUG juju.environs.bootstrap bootstrap.go:199 model "controller" supports service/machine networks: true
12:55:15 DEBUG juju.environs.bootstrap bootstrap.go:201 network management by juju enabled: true
12:55:15 INFO  cmd bootstrap.go:233 Loading image metadata
12:55:15 INFO  cmd bootstrap.go:296 Looking for packaged Juju agent version 2.2-rc1 for amd64
12:55:15 INFO  juju.environs.bootstrap tools.go:72 looking for bootstrap agent binaries: version=2.2-rc1
12:55:15 INFO  juju.environs.tools tools.go:101 finding agent binaries in stream "devel"
12:55:15 INFO  juju.environs.tools tools.go:103 reading agent binaries with major.minor version 2.2
12:55:15 INFO  juju.environs.tools tools.go:111 filtering agent binaries by version: 2.2-rc1
12:55:15 INFO  juju.environs.tools tools.go:117 filtering agent binaries by architecture: amd64
12:55:15 DEBUG juju.environs.tools urls.go:109 trying datasource "keystone catalog"
12:55:18 DEBUG juju.environs.simplestreams simplestreams.go:683 using default candidate for content id "com.ubuntu.juju:devel:tools" are {20161007 mirrors:1.0 content-download streams/v1/cpc-mirrors.sjson []}
12:55:33 INFO  juju.environs.bootstrap tools.go:74 found 0 packaged agent binaries
12:55:33 INFO  cmd bootstrap.go:315 No packaged binary found, preparing local Juju agent binary
12:55:33 DEBUG juju.environs.sync sync.go:302 Making agent binary tarball
12:55:33 DEBUG juju.environs.tools build.go:115 looking for: /snap/conjure-up/319/bin/juju
12:55:33 DEBUG juju.environs.tools build.go:154 checking: /snap/conjure-up/319/bin/jujud
12:55:33 INFO  juju.environs.tools build.go:160 Found agent binary to upload (/snap/conjure-up/319/bin/jujud)
12:55:33 INFO  juju.environs.tools build.go:170 target: /tmp/juju-tools031568215/jujud
12:55:36 DEBUG juju.environs.tools build.go:243 forcing version to 2.2-rc1.1
12:55:36 DEBUG juju.environs.tools build.go:42 adding entry: &tar.Header{Name:"FORCE-VERSION", Mode:436, Uid:0, Gid:0, Size:9, ModTime:time.Time{sec:63631036536, nsec:912921479, loc:(*time.Location)(0x3084460)}, Typeflag:0x30, Linkname:"", Uname:"ubuntu", Gname:"ubuntu", Devmajor:0, Devminor:0, AccessTime:time.Time{sec:63631036536, nsec:912921479, loc:(*time.Location)(0x3084460)}, ChangeTime:time.Time{sec:63631036536, nsec:912921479, loc:(*time.Location)(0x3084460)}, Xattrs:map[string]string(nil)}
12:55:36 DEBUG juju.environs.tools build.go:42 adding entry: &tar.Header{Name:"jujud", Mode:493, Uid:0, Gid:0, Size:91583840, ModTime:time.Time{sec:63631036536, nsec:784919989, loc:(*time.Location)(0x3084460)}, Typeflag:0x30, Linkname:"", Uname:"ubuntu", Gname:"ubuntu", Devmajor:0, Devminor:0, AccessTime:time.Time{sec:63631036536, nsec:784919989, loc:(*time.Location)(0x3084460)}, ChangeTime:time.Time{sec:63631036536, nsec:784919989, loc:(*time.Location)(0x3084460)}, Xattrs:map[string]string(nil)}
12:55:44 INFO  juju.environs.sync sync.go:333 using agent binary 2.2-rc1-xenial-amd64 aliased to 2.2-rc1.1-xenial-amd64 (21549kB)
12:55:45 INFO  cmd bootstrap.go:357 Starting new instance for initial controller
Launching controller instance(s) on maas...
12:55:46 ERROR juju.cmd.juju.commands bootstrap.go:492 failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=juju.maas
12:55:46 DEBUG juju.cmd.juju.commands bootstrap.go:493 (error details: [{github.com/juju/juju/cmd/juju/commands/bootstrap.go:584: failed to bootstrap model} {github.com/juju/juju/provider/common/bootstrap.go:185: cannot start bootstrap instance} {github.com/juju/juju/provider/maas/environ.go:967: cannot run instances} {github.com/juju/juju/provider/maas/environ.go:1327: cannot run instance} {github.com/juju/juju/provider/maas/environ.go:768: } {github.com/juju/gomaasapi/controller.go:546: } {github.com/juju/gomaasapi/controller.go:743: } {github.com/juju/gomaasapi/controller.go:774: } {github.com/juju/gomaasapi/client.go:124: } {ServerError: 409 CONFLICT (No available machine matches constraints: mem=3584.0 name=juju.maas)}])
12:55:46 DEBUG juju.cmd.juju.commands bootstrap.go:1078 cleaning up after failed bootstrap
12:55:46 INFO  juju.provider.common destroy.go:20 destroying model "controller"
12:55:46 INFO  juju.provider.common destroy.go:31 destroying instances
12:55:46 INFO  juju.provider.common destroy.go:51 destroying storage
12:55:46 INFO  cmd supercommand.go:465 command finished

**Comment by battlemidget** [comment]
You are still getting errors from maas:

```
failed to bootstrap model: cannot start bootstrap instance: cannot run instances: cannot run instance: No available machine matches constraints: mem=3584.0 name=juju.maas
12:55:46 DEBUG juju.cmd.juju.commands bootstrap.go:493 (error details: [{github.com/juju/juju/cmd/juju/commands/bootstrap.go:584: failed to bootstrap model} {github.com/juju/juju/provider/common/bootstrap.go:185: cannot start bootstrap instance} {github.com/juju/juju/provider/maas/environ.go:967: cannot run instances} {github.com/juju/juju/provider/maas/environ.go:1327: cannot run instance} {github.com/juju/juju/provider/maas/environ.go:768: } {github.com/juju/gomaasapi/controller.go:546: } {github.com/juju/gomaasapi/controller.go:743: } {github.com/juju/gomaasapi/controller.go:774: } {github.com/juju/gomaasapi/client.go:124: } {ServerError: 409 CONFLICT (No available machine matches constraints: mem=3584.0 name=juju.maas)}])
12:55:46 DEBUG juju.cmd.juju.commands bootstrap.go:1078 cleaning up after failed bootstrap
```

Have you tried recommissioning your nodes to see if that helps?

**Comment by battlemidget** [comment]
This error message also indicates that you have no available nodes in MAAS that can be used by Juju. You need to make sure any machines you want to use are in a "Ready" state and can be powered on/off via BMC, that is the only way Juju will be able to utilize these resources.

**Comment by haashah** [comment]
The machines are in ready state and power control works. They are however virtual and not bare metal. Not sure if that should effect in any way?

**Comment by battlemidget** [comment]
As long as MAAS can power them on/off then that should work. Can you do it without setting `juju.maas` in bootstrap-to?

**Comment by haashah** [comment]
without any argument in bootstrap-to? will that work?

**Comment by battlemidget** [comment]
Yea just drop the `--bootstrap-to` all together

**Comment by deepsidhu1313** [comment]
Same issue. How did you guys solved it ?? My juju VM is saying it is deployed, but as soon the status turn to `deployed` for my juju vm in the MAAS control panel, i get the error in conjure-up command.

**Comment by battlemidget** [comment]
@deepsidhu1313 can you open a new issue with the required data asked in the template?

**Comment by deepsidhu1313** [comment]
Sure. Thanks !!
