### ISSUE TITLE
Conjure-up openstack deployment stuck at last step "additional-application-tasks" 

### ISSUE THREAD

**Issue by shobhit-shrivastava** [conjure-up/conjure-up#885]
Hi 

My deployment is stuck at the last step -> https://docs.ubuntu.com/conjure-up/en/walkthrough#additional-application-tasks
It was stuck at 1st addition task 'importing glance images'. 
 I had to ctrl-c to get out.

**Is there a way to trigger/kick-off the "additional application tasks" manually somehow after deployment ?** 

I have completed the report as best as i could. 

## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [Not sure ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ No] Is conjure-up running inside a virtual machine?
- [ Not sure] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
$ which juju
/snap/bin/juju
$ which conjure-up
/snap/bin/conjure-up
$ which lxd
/usr/bin/lxd
$ juju version
2.2-beta4-xenial-amd64
$ conjure-up --version
conjure-up 2.2-beta4
$ lxd --version
2.13
$ lxc config show
config:
  core.https_address: '[::]'
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:
Attached
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/998046/conjure-up.tar.gz)

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:
[sosreport-sshri.conjureup-20170512150948.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/998068/sosreport-sshri.conjureup-20170512150948.tar.xz.zip)

```
sudo apt install sosreport
sosreport


```

The resulting output file can be attached to this issue.

## What Spell was Selected?

openstack novalxd
## What provider (aws, maas, localhost, etc)?
localhost
### MAAS Users
Which version of MAAS?
NA
## Commands ran

Please outline what commands were run to install and execute conjure-up:

**Comment by battlemidget** [comment]
We are working on better step processing support and also ability to reconnect to existing deploys to continue.

Please track https://github.com/conjure-up/conjure-up/issues/648 and I'll close this one out
