### ISSUE TITLE
Stuck in "waiting for applications to start"

### ISSUE THREAD

**Issue by italomaia** [conjure-up/conjure-up#890]
## Report

- [ no ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ no ] Is conjure-up running inside a virtual machine?
- [ no ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju  # /usr/bin/juju
which conjure-up  # /snap/bin/conjure-up
which lxd  # /usr/bin/lxd
juju version  # 2.0.2-yakkety-amd64
conjure-up --version  # conjure-up 2.2-rc1+ca4e878
lxd --version  # 2.13
lxc config show
# config:
#  core.https_address: '[::]'
cat /etc/lsb-release
# DISTRIB_ID=Ubuntu
# DISTRIB_RELEASE=16.10
# DISTRIB_CODENAME=yakkety
# DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1012580/conjure-up.tar.gz)
![profile](https://cloud.githubusercontent.com/assets/14670/26225765/3f25219c-3bff-11e7-9a1a-c2829705fb53.png)

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport  # no valid plugins were enabled ??
```

The resulting output file can be attached to this issue.

## What Spell was Selected?
NovaLXD

## What provider (aws, maas, localhost, etc)?
localhost

### MAAS Users
Which version of MAAS?
??

## Commands ran

Please outline what commands were run to install and execute conjure-up:
conjure-up

**Comment by battlemidget** [comment]
Can you `apt-get remove juju`? We provide our own version of Juju and it doesn't seem to be used in this issue. `/snap/bin/juju` is the one that should be accessed

**Comment by italomaia** [comment]
I believe **sudo snap install conjure-up --classic** installed juju on its own. Should I 
"sudo snap install conjure-up --jailmode --edge"?

**Comment by battlemidget** [comment]
installing conjure-up does install juju, however, according to the previous output when you do `which juju` it points to `/usr/bin/juju` which is installed through the debian package juju.

**Comment by italomaia** [comment]
```
which juju
/snap/bin/juju
```

Juju is now from snap, yet, the error persists. 
![pre_deploy](https://cloud.githubusercontent.com/assets/14670/26248781/188771d6-3c7a-11e7-932d-b84ca8601fe5.png)

**Comment by battlemidget** [comment]
Can you attach a new `~/. cache/conjure-up`

**Comment by battlemidget** [comment]
We've made several improvements to our localhost deployment, can you try to reproduce with the latest in `sudo snap refresh conjure-up --stable`?

**Comment by battlemidget** [comment]
Please re-open if problem persists with the latest conjure-up.
