### ISSUE TITLE
Installing OpenStack from Landscape not working

### ISSUE THREAD

**Issue by InfoQB** [conjure-up/conjure-up#893]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
lxc config show
cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?
MAAS Version 2.1.3+bzr5573-0ubuntu1 (16.04.1)

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information

Hi again,

We have successfully installed landscape since last time. Now we are stuck when installing OpenStack from Landscape.
The error message we receive when landscape has started the OpenStack installation:

"juju ended with exit code 1 (out='', err='Adding contents of "/var/lib/landscape/juju-homes/8/ssh/juju_id_rsa.pub" to au
ERROR Get http://http:/x.x.x.x:5240/MAAS/api/1.0/version/: dial tcp: lookup http on x.x.x.x:53: no such host')"

We can deploy this node from our maas but it's not working from Landscape. We have one landscape and one juju controller auto deployed already.

juju status:
Model                  Controller           Cloud/Region            Version    SLA
conjure-landscape-30c  conjure-up-maas-e3f  conjure-cloud-maas-2bd  2.2-rc1.1  unsupported

juju version:
2.2-rc1-xenial-amd64

conjure-up --version:
conjure-up 2.2-rc1

lxd --version:
2.13

**Comment by battlemidget** [comment]
I've pinged the Autopilot team to have a look.

**Comment by battlemidget** [comment]
Also this is incorrect " http://http:/x.x.x.x:5240/MAAS/api/1.0/version/" Why are there 2 `http:`?

**Comment by InfoQB** [comment]
That's what the error message says ..

**Comment by battlemidget** [comment]
Np! Glad it worked out

**Comment by InfoQB** [comment]
Default installation adds multiple http:/ on some settings. Thank you for pointing that out since my head’s not working today..

 



Oskar Paulsson

 <mailto:omp@infoqb.com> omp@infoqb.com

 <http://www.infoqb.com/> www.infoqb.com

Granbergsvägen 1

912 32 Vilhelmina

Support/Sales:0770-350340

 

Från: Adam Stokes [mailto:notifications@github.com] 
Skickat: den 23 maj 2017 16:29
Till: conjure-up/conjure-up <conjure-up@noreply.github.com>
Kopia: InfoQB <omp@infoqb.com>; State change <state_change@noreply.github.com>
Ämne: Re: [conjure-up/conjure-up] Installing OpenStack from Landscape not working (#893)

 

Np! Glad it worked out
