### ISSUE TITLE
Unable to deploy kubernetes-core using --edge and MAAS Version 2.1.5+bzr5596-0ubuntu1 (16.04.1)

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#894]
Juju 2.2 rc1
Conjure-up 2.2-rc1-20170522.2105
lxd 2.0.9-0ubuntu1~16.04.2

[conjure-up.tar.gz](https://github.com/conjure-up/conjure-up/files/1023347/conjure-up.tar.gz)

**Comment by battlemidget** [comment]
Could be related https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/270

**Comment by battlemidget** [comment]
Was the proxy setting for snaps the issue here?

**Comment by battlemidget** [comment]
Needed snap proxy settings applied to allow snap install to work behind firewall
