### ISSUE TITLE
cloud native support

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#895]
Support cloud native services such as AWS Load Balancers

**Comment by tvansteenburgh** [comment]
1. Bundle AWS cli with conjure-up
2. Create IAM roles for cluster nodes (pre-deploy)
3. Set --cloud-provider on master and worker and restart snap services
4. Do aws-specific stuff in spell - create StorageClass, PVCs, etc

See https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/346
