### ISSUE TITLE
Error Deploying Openstack: Could not find a suitable network interface... with NovaLXD in a nested LXD 

### ISSUE THREAD

**Issue by ladams00** [conjure-up/conjure-up#916]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [x] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
_It is not_
- [x] Is conjure-up running inside a virtual machine?
_Yes it is, per Stephane Graber's instructions: https://stgraber.org/2016/10/26/lxd-2-0-lxd-and-openstack-1112/_
- [x] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?
_This only occurs under --edge and --beta snap channels (not under --stable)_

## Please provide te output of the following commands

```
which juju
/snap/bin/juju
which conjure-up
/snap/bin/conjure-up
which lxd
/usr/bin/lxd
juju version
2.2-rc1-xenial-amd64
conjure-up --version
conjure-up 2.2-rc1
lxd --version
2.0.9
lxc config show
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```
_See attached at bottom_
## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```
_See attached at bottom_
The resulting output file can be attached to this issue.

## What Spell was Selected?
_OpenStack with NovaLXD_
## What provider (aws, maas, localhost, etc)?
_localhost_
### MAAS Users
Which version of MAAS?
_n/a_
## Commands ran
_Those found in Stephane Graber's tutorial: https://stgraber.org/2016/10/26/lxd-2-0-lxd-and-openstack-1112/_
```
lxc init ubuntu:16.04 openstack -c security.privileged=true -c security.nesting=true -c "linux.kernel_modules=iptable_nat, ip6table_nat, ebtables, openvswitch, nbd"
printf "lxc.cap.drop=\nlxc.aa_profile=unconfined\n" | lxc config set openstack raw.lxc -
lxc config device add openstack mem unix-char path=/dev/mem
lxc start openstack

lxc exec openstack -- apt update
lxc exec openstack -- apt dist-upgrade -y
lxc exec openstack -- apt install squashfuse -y
lxc exec openstack -- ln -s /bin/true /usr/local/bin/udevadm
lxc exec openstack -- snap install conjure-up --classic --edge (also happens in --beta channel)

lxc exec openstack -- lxd init

lxc exec openstack -- sudo -u ubuntu -i conjure-up
```
Please outline what commands were run to install and execute conjure-up:

## Additional Information
Tried creating LXD bridge via 'lxd init' before conjure-up, and omitted setting up LXD bridge in second trial to see if that made a difference.  Same result.

[conjure-up.tgz.zip](https://github.com/conjure-up/conjure-up/files/1059024/conjure-up.tgz.zip)
[sosreport-ladams00-20170607185306.tar.xz.zip](https://github.com/conjure-up/conjure-up/files/1059025/sosreport-ladams00-20170607185306.tar.xz.zip)

**Comment by ladams00** [comment]
It might help if I included the full error encountered:
```
Oops, there was a problem with your install:                          
Reason:                                                                                                                                   
                Could not find a suitable physical network interface to create a LXD bridge on. Please check your network configuration.                                                                                                                                       
                Review log messages at ~/.cache/conjure-up/conjure-up.log If appropriate, please submit a bug here:                               
                https://github.com/conjure-up/conjure-up/issues/new                                                                       
```

**Comment by falfaro** [comment]
Actually, I can reproduce exactly this problem with --stable, --beta and --edge. The underlying problem seems how conjure-up enumerates network devices:

    sys_class_net = Path('/sys/class/net')
    devices = []
    for device in sys_class_net.glob("*"):
        if "virtual" in str(device.resolve()):
            continue
        try:
            if not get_physical_network_ipaddr(device.name):
                continue
        except Exception:
            continue
        devices.append(device.name)
    if len(devices) == 0:
        raise Exception(
            "Could not find a suitable physical network interface "
            "to create a LXD bridge on. Please check your network "
            "configuration.")
    return sorted(devices)

The problem is that when conjure-up is running inside an LXD container (as per Stephane Graber's post), all network interfaces as seen inside the container are "virtual". That is:

$ ls -l /sys/class/net
total 0
lrwxrwxrwx 1 root root 0 Jun 15 21:34 eth0 -> ../../devices/virtual/net/eth0
lrwxrwxrwx 1 root root 0 Jun 15 21:34 lo -> ../../devices/virtual/net/lo

As you can see, the result of expanding the "symlink" contains the "virtual" in it. This causes conjure-up to find zero network interfaces and bail out with the exception mentioned above.

**Comment by battlemidget** [comment]
@falfaro thank you for the detailed analysis! we'll take a look at getting this addressed.

**Comment by falfaro** [comment]
It is very lame, but what I did in the end to work this around temporarily (while a proper fix is implemented) is this:

<div><pre>
$ git diff
diff --git a/conjureup/utils.py b/conjureup/utils.py
index ce32b4c..5f6d582 100644
--- a/conjureup/utils.py
+++ b/conjureup/utils.py
@@ -535,8 +535,6 @@ def get_physical_network_interfaces():
     sys_class_net = Path('/sys/class/net')
     devices = []
     for device in sys_class_net.glob("*"):
-        if "virtual" in str(device.resolve()):
-            continue
         try:
             if not get_physical_network_ipaddr(device.name):
                 continue
</pre></div>

Then built the snap from source code (yields conjure-up_2.3-alpha1-20170615.2206_amd64.snap), installed the resulting snap and it works. When deploying something via this custom version of conjure-up it asks me which network interface I want to use (eth0 or lo), which is fine.

**Comment by battlemidget** [comment]
@falfaro Thank you for that, we'll look to see what else can be done. I'll speak with the LXD guys and see if there are other properties we can look for.

**Comment by battlemidget** [comment]
@ladams00 @falfaro So i spoke with LXD guys and there isn't a good way to detect those non virtual interfaces within a container. It is suggested to whitelist eth* so this is what I think we'll do.
