### ISSUE TITLE
decide on top level juju alias

### ISSUE THREAD

**Issue by tvansteenburgh** [conjure-up/conjure-up#917]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ x ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
tvansteenburgh@xenial-vm:~⟫ snap install conjure-up --classic --beta
error: cannot perform the following tasks:
- Set automatic aliases for snap "conjure-up" (cannot enable alias "juju" for "conjure-up", it conflicts with the command namespace of installed snap "juju")
1 tvansteenburgh@xenial-vm:~⟫ which conjure-up
1 tvansteenburgh@xenial-vm:~⟫ which juju
/snap/bin/juju
tvansteenburgh@xenial-vm:~⟫ which lxd
/usr/bin/lxd
tvansteenburgh@xenial-vm:~⟫ juju version
2.2-rc1-xenial-amd64
tvansteenburgh@xenial-vm:~⟫ lxd --version
2.14
tvansteenburgh@xenial-vm:~⟫ lxc config show
config:
  core.https_address: '[::]'
tvansteenburgh@xenial-vm:~⟫ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

## Commands ran
```
tvansteenburgh@xenial-vm:~⟫ snap install conjure-up --classic --beta
error: cannot perform the following tasks:
- Set automatic aliases for snap "conjure-up" (cannot enable alias "juju" for "conjure-up", it conflicts with the command namespace of installed snap "juju")
## Additional Information
```

**Comment by canonical-cgregan** [comment]
snap remove juju
snap install conjure-up --classic --beta

Juju snap and conjure up snap are not able to co-exist because conjure-up attempt to install juju and a conflict arises. The conflict perhaps is a snap bug, but not sure this is a conjure-up issue

**Comment by tvansteenburgh** [comment]
I discussed this with @johnsca earlier today, but I'm summarizing my thoughts here so we can have a group discussion about it.

Quoting directly from the latest Juju release announcement:

"The best way to get your hands on this release of Juju and conjure-up is to install them via snap packages (see https://snapcraft.io/ for more info on snaps).
 
         snap install juju --classic --beta
         snap install conjure-up --classic --beta
"

If a new user follows those instructions, they will:

1. install juju
2. try to install conjure-up and have it fail
3. probably not know how to fix it, but if they do happen to figure it out...
4. uninstall the juju that they just installed
5. install conjure-up

Maybe this can/will be fixed in snapd at some point (I'm aware of https://bugs.launchpad.net/snappy/+bug/1693016), but in the mean time it's a pretty rough user experience. We could fix it in one of two ways:

1. conjure-up includes juju but doesn't alias it - the user can do that if they want to. Or,
2. conjure-up doesn't include juju, but checks it at runtime and prompts the user to take a corrective action if juju is either not installed, or is an incompatible version.

I think the first is better, as it's more in keeping with the snap way of doing things (including everything you need in the snap itself), it's an easier fix, and I'm not convinced that conjure-up should be aliasing juju in the first place.

**Comment by battlemidget** [comment]
I'm ok entertaining this idea of removing the alias for juju, however, I'd like to not do it until we finish this cycle's work with conjure-up's operational management capabilities.

Also want to note that all of our marketing material (aside from this juju mailing list) describe conjure-up's usage as 2 lines (snap install conjure-up, conjure-up). Adding in more commands to type before getting to use conjure-up, I think, is a poor user experience. We need to keep in mind that our target audience probably has no idea about juju to begin with and requiring them to snap install both conjure-up and juju then running snap alias to get where we were initially is also a poor user experience.

Again, I'm not totally against the idea of removing the top level juju alias, however, I'd like to discuss this again once we've gotten our operational management capabilities completed.
