### ISSUE TITLE
Hadoop-spark bundle calls a charm version not available (hadoop-plugin-21)

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#918]
Conjure-up --classic --candidate

Attempted to use the maas cloud to deploy hadoop-spark but the process failed because the hadoop-plugin charm requested did not exist.

**Comment by battlemidget** [comment]
This supposedly was fixed by the charm author?

**Comment by kwmonroe** [comment]
This was my bad -- I have a terrible workflow in which I leave charms in the candidate channel until upstream PRs are closed.  There's a period of time where the charm is g2g (and I update the stable bundles), yet housekeeping on the PRs hasn't occurred, so the charm revs haven't moved to the stable channel.

Conjuring a stable bundle with non-stable charm revs is what's breaking here.

I have fixed the issue by closing out relevant PRs and moving charms to stable.  @canonical-cgregan, I'll fix my flow for the future.  Sorry about the breakage.

**Comment by canonical-cgregan** [comment]
Confirmed fixed
