### ISSUE TITLE
Openstack with LXD; slow APIs and Horizon interface

### ISSUE THREAD

**Issue by NicolaiSchmid** [conjure-up/conjure-up#919]
## Nova with LXD
I've successfully deployed a local OpenStack installation with LXD.
But the horizon interface, as well as all the APIs are having an extremely high latency. Up to 20s. The download of the assets is pretty fast (3 to 5 ms for a horizon view)
My machine has plenty of power (8 cores) and around 16GB of RAM from which only 8GB are allocated. Do you have an idea, where the latency comes from? Or do you know how I can debug the issue?

**Comment by battlemidget** [comment]
Not really sure aside from following this production information for lxd https://github.com/lxc/lxd/blob/master/doc/production-setup.md#network-bandwidth-tweaking

See if that helps
