### ISSUE TITLE
lxdbr0 set as default for localhost cloud

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/conjure-up#921]
conjure-up  2.2-rc2-20170612.1306
NovaLXD spell using localhost

+------------+----------+---------+---------+
|    NAME    |   TYPE   | MANAGED | USED BY |
+------------+----------+---------+---------+
| conjureup0 | bridge   | NO      | 0       |
+------------+----------+---------+---------+
| conjureup1 | bridge   | NO      | 0       |
+------------+----------+---------+---------+
| eno1       | physical | NO      | 0       |
+------------+----------+---------+---------+
| eno2       | physical | NO      | 0       |
+------------+----------+---------+---------+
| lxdbr0     | bridge   | YES     | 0       |
+------------+----------+---------+---------+

conjure-up.lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []

**Comment by battlemidget** [comment]
@canonical-cgregan this is a blocker for our 2.2 release, will work on this tonight/tomorrow to get addressed

**Comment by battlemidget** [comment]
Notes, in order for the upcoming fix to work you will either need to edit `~/.local/share/juju/bootstrap-config.yaml` and update the endpoint to `10.100.0.1:12001` or do a new bootstrap so that it'll pick up the correct bridge to use.
