### ISSUE TITLE
latest conjure-up brought me to error when I deployed openstack

### ISSUE THREAD

**Issue by ekalaya2015** [conjure-up/conjure-up#940]
## Report

Thank you for trying **conjure-up**! Before reporting a bug please make sure you've gone through this checklist:

- [ ] Is this problem already documented at https://docs.ubuntu.com/conjure-up/en/troubleshoot#common-spell-problems
- [ ] Is conjure-up running inside a virtual machine?
- [ ] Is this problem reproducible with `sudo snap refresh conjure-up --edge`?

## Please provide the output of the following commands

```
which juju
which conjure-up
which lxd
juju version
conjure-up --version
lxd --version
lxc config show
cat /etc/lsb-release
```

Please attach tarball of **~/.cache/conjure-up**:

```
tar cvzf conjure-up.tar.gz ~/.cache/conjure-up
```

## Sosreport

Please attach a sosreport:

```
sudo apt install sosreport
sosreport
```

The resulting output file can be attached to this issue.

### MAAS Users
Which version of MAAS?

## Commands ran

Please outline what commands were run to install and execute conjure-up:

## Additional Information
I managed to deploy Openstack using conjure-up version 2.1.5, but failed when used latest version.
Is there any chance for me to use previous conjure-up version?

**Comment by battlemidget** [comment]
Whats the actual error? Can you provide what the issue template asked for?

**Comment by ekalaya2015** [comment]
here is the error
![whatsapp image 2017-06-16 at 2 44 31 pm](https://user-images.githubusercontent.com/27433888/27227247-e414110c-52cc-11e7-9a0f-e73cd8781f0c.jpeg)

Never encountered error like that before

**Comment by battlemidget** [comment]
Ok this is an Autopilot issue, I'll ping the landscape guys. On the main dashboard page there is a button to collect log information, can you grab that for us so they can take a look?

**Comment by ekalaya2015** [comment]
@battlemidget, as I said before, I managed to deploy Openstack using conjure-up version 2.1.5. I did not touch anything except snap did automatic update and when I need to redeploy Openstack, anything went wrong. That's why I ask you whether any chance to go back to previous version.

**Comment by battlemidget** [comment]
there is `snap revert` that lets you go back

**Comment by ekalaya2015** [comment]
I think I can not do that because I already removed conjure-up :(

**Comment by ekalaya2015** [comment]
I am trying reproduce the error, be back to you soon

**Comment by battlemidget** [comment]
Just want to let you know also that Autopilot is no longer one of our supported products. They'll be no new updates/fixes to it going forward as well. You may want to look into using our OpenStack with NovaKVM instead.

**Comment by ekalaya2015** [comment]
arrgh... you should remove Landscape from spell then

**Comment by battlemidget** [comment]
Yea, Im talking with the management now, I think we may want to keep landscape as it's still use for systems managemet but remove Autopilot part. I'll let you know what I find out

**Comment by ekalaya2015** [comment]
@battlemidget I already cloned version 2.1.5 and built it manually.  Any suggestions how can i use it to deploy Openstack using Landscape? Really need your help to get my Openstack back

**Comment by battlemidget** [comment]
Ok, so I've been informed that only support can be facilitated through Canonical as Landscape/Autopilot is a commercial offering.

You'll want to contact Canonical for support, https://www.canonical.com/services/contact-us

**Comment by ekalaya2015** [comment]
ok. thank you @battlemidget

**Comment by battlemidget** [comment]
Thanks and sorry for the confusion, if you have issues with anything outside of landscape feel free to post on askubuntu.com or post here if a bug
