### ISSUE TITLE
add --verify for running tests after a deployment/post process complete

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#96]
Would be nice to allow someone to do a full end to end deployment/post process/testing with their big software.

Thinking along the lines of 

```
conjure-up openstack --verify
```

This will deploy openstack, do all necessary configuration via post processing (steps) scripts, and run whatever is in the `tests` directory for validating the deployment.

**Comment by mikemccracken** [comment]
In the initial design session, there was some discussion of optional 'extra steps', like benchmarks that could be added to the results/summary screen - that could be a good place to put this in the GUI.

The way I imagine it working is much like the required postproc steps, where they're shown as description + button, but they're just strictly optional.
