### ISSUE TITLE
Provide up-to-date version of conjure-up through PPA

### ISSUE THREAD

**Issue by iatrou** [conjure-up/conjure-up#977]
Currently the latest stable version of conjure-up is:
- From snaps (stable) is 2.2.1
- From ppa:conjure-up/ppa is 2.0.2-0~201610141215
- From ppa:conjure-up/next is 2.1.0-0~201702170427

In some environments, using snaps is not an option (see https://forum.snapcraft.io/t/certificate-substitution-and-snaps/1077)
Having an up to date PPA can make a huge difference, as snap evolves to accommodate more "idiosyncratic" environments.

**Comment by battlemidget** [comment]
Unfortunately, we are a snap only distribution. We should spend our time in making that experience workable in your situation by interfacing with the snap developers (the forum is the best place to start that conversation)
