### ISSUE TITLE
permission denied accessing ~/.local/share/juju

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/conjure-up#991]
https://sentry.io/canonical-pj/conjure-up/issues/296651535/

```
LookupError: Unable to list controllers: ERROR failed to list controllers: open /home/ubuntu/.local/share/juju/controllers.yaml: permission denied

(15 additional frame(s) were not displayed)
...
  File "conjureup/ui/views/base.py", line 142, in submit
    self.submit_cb(self.schema)
  File "conjureup/controllers/credentials/gui.py", line 101, in save_credential
    self.finish(cred_name)
  File "conjureup/controllers/credentials/common.py", line 23, in finish
    controllers.use('controllerpicker').render()
  File "conjureup/controllers/controllerpicker/gui.py", line 11, in render
    existing_controllers = juju.get_controllers()['controllers']
  File "conjureup/juju.py", line 698, in get_controllers
    "Unable to list controllers: {}".format(sh.stderr.decode('utf8')))

LookupError: Unable to list controllers: ERROR failed to list controllers: open /home/ubuntu/.local/share/juju/controllers.yaml: permission denied

```

**Comment by RouR** [comment]
Same issue

`lsb_release -a`

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

Steps:

1. apt-get update
2. apt-get upgrade
3. sudo apt install snapd
4. sudo snap install conjure-up --classic
5. // re-login 
6. adduser kkk
7. adduser kkk sudo
8. su kkk
9. PATH=/snap/bin:$PATH
10. conjure-up kubernetes

> Traceback (most recent call last):
>   File "/snap/conjure-up/924/bin/conjure-up", line 11, in <module>
>     load_entry_point('conjure-up==2.5.2', 'console_scripts', 'conjure-up')()
>   File "/snap/conjure-up/924/lib/python3.6/site-packages/conjureup/app.py", line 204, in main
>     if juju_dir.exists():
>   File "/snap/conjure-up/924/usr/lib/python3.6/pathlib.py", line 1314, in exists
>     self.stat()
>   File "/snap/conjure-up/924/usr/lib/python3.6/pathlib.py", line 1136, in stat
>     return self._accessor.stat(self)
>   File "/snap/conjure-up/924/usr/lib/python3.6/pathlib.py", line 387, in wrapped
>     return strfunc(str(pathobj), *args)
> PermissionError: [Errno 13] Permission denied: '/home/kkk/.local/share/juju'
> 

`sudo juju status`

> Model    Controller  Cloud/Region         Version  SLA
> default  juju-ctrl   localhost/localhost  2.3.1    unsupported
> 
> App  Version  Status  Scale  Charm  Store  Rev  OS  Notes
> 
> Unit  Workload  Agent  Machine  Public address  Ports  Message
> 
> Machine  State  DNS  Inst id  Series  AZ  Message
>

**Comment by battlemidget** [comment]
Please don't run `juju <cmd>` with `sudo`. Also what's the output of `ls -la ~/.local/share`. You want to make sure that directory is owned and writeable as your current user.

**Comment by RouR** [comment]
`juju status` say "permission denied"

Is it possible to install on clean system, without manual edit chmod flags?

**Comment by battlemidget** [comment]
You ran juju as `sudo` previously so the permissions are wrong. If you do another clean install only use `sudo` to `snap install conjure-up --classic` but run conjure-up and/or juju without using `sudo`. Or, just fix your current permissions.
